### ISSUE TITLE
Error on YGGTorrent

### ISSUE THREAD

**Issue by ulysserevient** [FlareSolverr/FlareSolverr#10]
Hi,
I'm trying to use FlareSolverr to connect to yggtorrent.si but  obtain an error !
`curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{
    "url":"https://www.yggtorrent.si/",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0",
    "maxTimeout": 10000
}'
`
Return this error :
`{"status":"error","message":"Maximum timeout reached. maxTimeout=10000 (ms)","startTimestamp":1607254565415,"endTimestamp":1607254576646,"version":"1.0.0"}`

Any idea to solve my problem ? Thx

**Comment by ngosang** [comment]
FlareSolverr 1.2.0 is out!
It's working for all sites protected by CloudFlare.
Installation => https://github.com/FlareSolverr/FlareSolverr#docker
