### ISSUE TITLE
Latest docker image is 3.3.6 and not 3.3.11

### ISSUE THREAD

**Issue by ethgrim** [FlareSolverr/FlareSolverr#1009]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:latest
- Operating system:docker
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hello
When I pull the flaresolverr l'attestation via docker-compose.
It grabs v3.3.6 and not 3.3.11.
Is it normal ?

### Logged Error Messages

```text
There is no error message
```

**Comment by ilike2burnthing** [comment]
https://www.baeldung.com/ops/docker-compose-latest-image
