### ISSUE TITLE
[hddolby] Adding site failed, tried multiple times but still persists

### ISSUE THREAD

**Issue by 240722795** [FlareSolverr/FlareSolverr#1024]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]no
- Are you using a Proxy: [yes/no]no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:https://www.hddolby.com/
```

### Description

Adding site failed, tried multiple times but still persists

### Logged Error Messages

```text
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: unknown error: cannot connect to chrome at 127.0.0.1:58455\nfrom chrome not reachable\nStacktrace:\n#0 0x55ca6d477d23 <unknown>\n#1 0x55ca6d1457ae <unknown>\n#2 0x55ca6d133871 <unknown>\n#3 0x55ca6d17db34 <unknown>\n#4 0x55ca6d1752d9 <unknown>\n#5 0x55ca6d1c0740 <unknown>\n#6 0x55ca6d1bfc70 <unknown>\n#7 0x55ca6d1b7a43 <unknown>\n#8 0x55ca6d181bc6 <unknown>\n#9 0x55ca6d182fb2 <unknown>\n#10 0x55ca6d44cda7 <unknown>\n#11 0x55ca6d44fe8d <unknown>\n#12 0x55ca6d44f938 <unknown>\n#13 0x55ca6d4503a5 <unknown>\n#14 0x55ca6d43f1df <unknown>\n#15 0x55ca6d450732 <unknown>\n#16 0x55ca6d429666 <unknown>\n#17 0x55ca6d468e95 <unknown>\n#18 0x55ca6d46907b <unknown>\n#19 0x55ca6d4772af <unknown>\n#20 0x7f5d586e7ea7 start_thread\n
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/31929493/28081b07-034a-48e9-9cd4-9bfcd3bd5e15)

**Comment by 240722795** [comment]
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Message: unknown error: cannot connect to chrome at 127.0.0.1:58455\nfrom chrome not reachable\nStacktrace:\n#0 0x55ca6d477d23 <unknown>\n#1 0x55ca6d1457ae <unknown>\n#2 0x55ca6d133871 <unknown>\n#3 0x55ca6d17db34 <unknown>\n#4 0x55ca6d1752d9 <unknown>\n#5 0x55ca6d1c0740 <unknown>\n#6 0x55ca6d1bfc70 <unknown>\n#7 0x55ca6d1b7a43 <unknown>\n#8 0x55ca6d181bc6 <unknown>\n#9 0x55ca6d182fb2 <unknown>\n#10 0x55ca6d44cda7 <unknown>\n#11 0x55ca6d44fe8d <unknown>\n#12 0x55ca6d44f938 <unknown>\n#13 0x55ca6d4503a5 <unknown>\n#14 0x55ca6d43f1df <unknown>\n#15 0x55ca6d450732 <unknown>\n#16 0x55ca6d429666 <unknown>\n#17 0x55ca6d468e95 <unknown>\n#18 0x55ca6d46907b <unknown>\n#19 0x55ca6d4772af <unknown>\n#20 0x7f5d586e7ea7 start_thread\n

**Comment by ilike2burnthing** [comment]
Provide the environment information requested in full and reopen.
