### ISSUE TITLE
Synology NAS support

### ISSUE THREAD

**Issue by neoOpus** [FlareSolverr/FlareSolverr#103]
Hi,

Please is it possible to install this on Synology NAS via package manager or some other ways? other than Docker!

Thank you,

**Comment by mkaaaf** [comment]
Would be really great, we can't have docker in ARM based synology NAS...

**Comment by ngosang** [comment]
I don't know much about Synology but it should be possible to run FlareSolverr without Docker in ARM. Take a look at https://github.com/FlareSolverr/FlareSolverr/issues/88#issuecomment-806227185
I can't work in this feature but I keep it is open for future references. PRs are welcome.

**Comment by anoril1979** [comment]
Hi! Very interrested in too!
No knowledge about how to do, anyway :/

**Comment by brianmowens** [comment]
Hello,

By installing Docker on your Synology device you should be capable of running this application as a docker container. A docker container is provided by the developers. I am currently able to run this on a DS920+ Synology (Intel based) device without issue.

**Comment by malinwa001** [comment]
any progress on this issue or is it put underneed a great stack?

**Comment by anoril1979** [comment]
Years pass by and I'm still greatly expecting this! :)

**Comment by ngosang** [comment]
We are not providing binaries for FlareSolverr v3. You can install from source code following the readme instructions.
Related #660
