### ISSUE TITLE
[cpasbien] (testing) Exception (cpasbien): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. string index out of range: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. string index out of range

### ISSUE THREAD

**Issue by p060477** [FlareSolverr/FlareSolverr#1031]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. string index out of range: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. string index out of range

### Logged Error Messages

```text
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. string index out of range: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. string index out of range
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/789
