### ISSUE TITLE
Use Cloudflare JS worker

### ISSUE THREAD

**Issue by Guisch** [FlareSolverr/FlareSolverr#104]
Hey 🖖

@jychp recently published an article on how to use a Cloudflare service to run JS from cloudflare server.

https://jychp.medium.com/how-to-bypass-cloudflare-bot-protection-1f2c6c0c36fb

It's a bit more complex than setting up a docker but since it's using less ressources than firing up an headless browser, It's worth a look 😄  (and it's free up to 100k request a day).

https://github.com/jychp/cloudflare-bypass

**Comment by ngosang** [comment]
It's interesting but the approach is really different and it's not guaranteed to work in the future.
* It's basically hosting a proxy in the Cloudflare cloud. I think it wont last.
* All the requests must past through the proxy. FlareSolverr is running in local and you only need to make 1 request to grab a valid cookie.

I have no interest in implementing this. If someone wants to open a PR to implement this it will be welcome, but the default behavior must be the headless browser.

**Comment by Guisch** [comment]
Hey I think we can close this issue or move it to the discussion tab.
