### ISSUE TITLE
Each request must be bypassed again.

### ISSUE THREAD

**Issue by Esteban795** [FlareSolverr/FlareSolverr#1042]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.13
- Last working FlareSolverr version: haven't used it previously
- Operating system: Linux Mint 
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:  /
- URL to test this issue: https://sushiscan.net/ and then 
https://sushiscan.net/wp-content/uploads45/JJKChap247-01.png
```

### Description

Hey all, 
I'm currently on my way to download mangas chapters before preparing a 12 hour flight, and so I was wondering if I could get to automate it using only CLI to perform the downloads. Cloudflare protecting the website, a friend told me to use this, but we're both unable to fix the issue : it seems I have to perform each request through Flaresolverr, instead of being able to reuse the cloudflare clearance cookies and make the next requests through  `requests.get`.
Here is a minimum reproducible code : 
```py
import requests
import json
url = "https://sushiscan.net/"
api_url = "http://localhost:8191/v1"
headers = {"Content-Type": "application/json"}
data = {
    "cmd": "request.get",
    "url": url,
    "maxTimeout": 60000
}
response = requests.post(api_url, headers=headers, json=data)
response_data = json.loads(response.content)
cookies = response_data["solution"]["cookies"]
cookies = {cookie["name"]: cookie["value"] for cookie in cookies}
user_agent = response_data["solution"]["userAgent"]
response = requests.get('https://sushiscan.net/wp-content/uploads45/JJKChap247-01.png', cookies=cookies, headers={"User-Agent": user_agent})
with open("test.png", "wb") as f:
    f.write(response.content)
```
This only returns the typical html :
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title> 

I checked the discussions, and found nothing really related to my issue. Same for issues, except for #953 but the issue was closed with no answers from OP.
Another solution I could agree on is by downloading *through* Flaresolverr, but again it seems like you currently can't.
Also, for the debug HTML, very sorry, but I'm not familiar with docker : I tried changing the docker-compose.yml files infos to 
```txt
---
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-true}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
```
but I'm sure it's not as it outputs nothing into the terminal.
Thanks for your time and answers !

### Logged Error Messages

```text
I get none, see description section.
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/58440121/489e2337-7907-440c-b53d-13779ad5c2a9)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/58440121/192696a6-3ace-4c01-b10e-6739cf20fe60)

**Comment by ilike2burnthing** [comment]
You'd need to create a session, so that all successive requests used that same session and the cookie remained vaild - https://github.com/FlareSolverr/FlareSolverr#-sessionscreate

But yes, currently you can't download through FlareSolverr.
