### ISSUE TITLE
How to set proxy?

### ISSUE THREAD

**Issue by holden321** [FlareSolverr/FlareSolverr#105]
Tried to use something like 
```
{
  "cmd": "request.get",
  "url": "some_web_address",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleW...",
  "maxTimeout": 60000,
  "headers": {
    "X-Test": "Testing 123..."
  },
  "proxy" : {
        "url": "proxy_address",
        //"username": "optional",
        //"password": "only_with_username"
    }
}
```

But without success.
I am using docker.

**Comment by holden321** [comment]
Found some solution.
Proxy can be set by sessions.create
`{"cmd":"sessions.create","proxy":{"url":"proxy_address"}}`
and then
`{"cmd":"request.get","session":"session_id"}`
But it is not a good solution if you do not need sessions.

**Comment by ngosang** [comment]
The proxy implementation is incomplete. We are tracking developments here #26
