### ISSUE TITLE
request.post command with  Content-Type set to application/x-www-form-urlencoded expect json from FlareSolverr server

### ISSUE THREAD

**Issue by janemba** [FlareSolverr/FlareSolverr#1055]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: I freshly `git pull`
- Last working FlareSolverr version: Only used the `git` version
- Operating system: GNU/Linux
- Are you using Docker: [yes/no] No
- FlareSolverr User-Agent (see log traces or / endpoint): User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] No
- Are you using a Proxy: [yes/no] No
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.qa/user/login
```

### Description

Hello,

I'm trying to perform a `POST` request using the `request.post` command. The parameters of my request is the following:
```
{'cmd': 'request.post', 'url': 'https://www3.yggtorrent.qa/user/login', 'postData': 'id=someuser&pass=somepassword&ci_csrf_token=', 'session': '1234', 'maxTimeout': 60000, 'returnOnlyCookies': False}
```
Before this request I created a session (so I'm using the same `session_id`) and get the challenge.

But while sending the `request.post` command above, I got the following error from FlareSolverr logs:
```
2024-02-03 21:21:00 ERROR    'NoneType' object is not iterable
2024-02-03 21:21:00 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

So looking at the souce code I discovered the following in `FlareSolverr.py` (from line 48):

```
@app.post('/v1')
def controller_v1():
    """
    Controller v1
    """
    req = V1RequestBase(request.json)
    res = flaresolverr_service.controller_v1_endpoint(req)
    if res.__error_500__:
        response.status = 500
    return utils.object_to_dict(res)
```

The issue is the following line:
```
    req = V1RequestBase(request.json)
```

So using `request.post` command with `application/x-www-form-urlencoded` does not seem to produce an expected `JSON`. As a result, `request.json` is empty and thus explain the error logs.

### Logged Error Messages

```text
2024-02-03 21:21:00 ERROR    'NoneType' object is not iterable
2024-02-03 21:21:00 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/discussions/1041
