### ISSUE TITLE
Error: Error solving the challenge. %d format: a real number is required, not NoneType

### ISSUE THREAD

**Issue by polyphia** [FlareSolverr/FlareSolverr#1062]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.13
- Last working FlareSolverr version: 3.3.13
- Operating system: Linux Ubuntu
- Are you using Docker: yes
- FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: yes
- Are you using Captcha Solver: no
- URL to test this issue:
  https://www.safeguard.run/captcha/dcjisyxh32
```

### Description

curl -L -X POST 'http://localhost:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url":"https://www.safeguard.run/captcha/dcjisyxh32",
  "proxy": {"url": "91.239.130.17:44443", "username": "username", "password": "mypassword},
  "maxTimeout": 60000
}'

### Logged Error Messages

```text
172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error
2024-02-09 20:21:39 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.safeguard.run/captcha/q57aswq1hh', 'proxy': {'url': '91.239.130.17:44443', 'username': 'username', 'password': 'mypassword'}, 'maxTimeout': 60000}
2024-02-09 20:21:39 ERROR    Error: Error solving the challenge. %d format: a real number is required, not NoneType
```

**Comment by polyphia** [comment]
Nailed down the issue to the proxy username, worked after setting my authentication to be based on ip address . 

There seems to be some issue parsing user data of proxies with similar format to this : 

`"proxy": {"url": "1.1.1.1:44443", "username": "myusername", "password": "MxASJUAIk_country-us_session-uxtakfxx_lifetime-2m"}`

**Comment by ilike2burnthing** [comment]
Underscores and hyphens shouldn't be considered special characters. Change the password to ~12 alphanumeric characters, see if that works. If so, try adding a single underscore. Whether that works or not, change the underscore to a hyphen. Report back what works and doesn't.
