### ISSUE TITLE
The Cloudflare 'Verify you are human' button not found on the page.

### ISSUE THREAD

**Issue by lsultana98** [FlareSolverr/FlareSolverr#1079]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
3.3.14-hotfix2
- Last working FlareSolverr version:
3.3.14
- Operating system:
Unraid 6.12.6
- Are you using Docker: [yes/no]
Yes
- FlareSolverr User-Agent (see log traces or / endpoint):
FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no]
Yes
- Are you using a Proxy: [yes/no]
No
- Are you using Captcha Solver: [yes/no]
No
- If using captcha solver, which one:
No
- URL to test this issue:
From within Jackett using:
https://1337x.to/
https://1337x.to/
https://1337x.st/
https://x1337x.ws/
https://x1337x.eu/
https://x1337x.se/
https://1337x.so/
https://1337x.unblockit.dad/
https://1337x.unblockninja.com/
https://1337x.ninjaproxy1.com/
https://1337x.proxyninja.org/
https://1337x.torrentbay.st/
```

### Description

This is the headless docker container version hosted within comunity applications. I have seen similar log errors in here, but the support threads seem to all finish with (update *** has fixed this issue). As far as I am aware I am using the latest version, and I reverted to the last version with no success. I am not too sure what is going on here. I have attached container start up + error logs, please let me know if anything else was needed. 
[flaresolverr.txt](https://github.com/FlareSolverr/FlareSolverr/files/14337594/flaresolverr.txt)

### Logged Error Messages

```text
2024-02-20 10:22:18 DEBUG    ReqId 22364533434112 Waiting for title (attempt 17): Just a moment...
2024-02-20 10:22:19 DEBUG    ReqId 22364533434112 Timeout waiting for selector
2024-02-20 10:22:19 DEBUG    ReqId 22364533434112 Try to find the Cloudflare verify checkbox...
2024-02-20 10:22:19 DEBUG    ReqId 22364533434112 Cloudflare verify checkbox not found on the page.
2024-02-20 10:22:19 DEBUG    ReqId 22364533434112 Try to find the Cloudflare 'Verify you are human' button...
2024-02-20 10:22:19 DEBUG    ReqId 22364533434112 The Cloudflare 'Verify you are human' button not found on the page.
2024-02-20 10:22:20 DEBUG    ReqId 22364541839104 A used instance of webdriver has been destroyed
```

**Comment by maligeez** [comment]
Exact same issue rn

**Comment by marshall409** [comment]
Same Cloudflare loop issue on my Windows setup.

**Comment by soapster** [comment]
Same issue, here.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1036

**Comment by tuyennn** [comment]
Same issue

**Comment by captmicr0** [comment]
Same issue. I tried changing the user agent used by modifying utils.py inside my docker container, that had no effect on it.

**Comment by captmicr0** [comment]
#1080

**Comment by lsultana98** [comment]
I know you closed, but thank you for getting this sorted!
