### ISSUE TITLE
yesterday not work with https://1337x.to/

### ISSUE THREAD

**Issue by Nikibasso94** [FlareSolverr/FlareSolverr#1080]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.14-hotfix2
- Last working FlareSolverr version: 3.3.14
- Operating system: linux ubuntu 22.04
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Portainer
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- URL to test this issue: https://1337x.to/
```

### Description

Yesterday stop work
i try increment time but not resolve

### Logged Error Messages

```text
2024-02-20 12:57:20 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://1337x.to/cat/Movies/time/desc/1/', 'proxy': {}}
version_main cannot be converted to an integer
2024-02-20 12:57:23 INFO     Challenge detected. Title found: Just a moment...
2024-02-20 12:58:52 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.
2024-02-20 12:58:52 INFO     Response in 91.703 s
2024-02-20 12:58:52 INFO     172.19.0.1 POST http://192.168.0.79:8191/v1 500 Internal Server Error
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/112549678/5fd9047d-4bd9-4fd8-ac30-06b04e6fbf8e)

**Comment by Nikibasso94** [comment]
![image](https://github.com/FlareSolverr/FlareSolverr/assets/112549678/59d0f366-97de-4812-8a01-79f4d0ad94b5)

**Comment by captmicr0** [comment]
I just made a terrible fix for this that has nothing to do with FlareSolverr...

You can use the 1337x onion domain which doesn't have cloudflare protection, making use of the [onion.ly](onion.ly) Tor2Web service.
In your prowlarr container (or wherever the app data is) create a custom definition and use this slightly modified yml I created: [1337x-onion.yml](https://gist.github.com/captmicr0/9cc2c331de9972197f716aa5981df65d)
Afterwards you can add 1337x-onion as a new indexer and disable your regular 1337x for the time being.

It should be placed in Definitions/Custom/1337x-onion.yml
I tried to just add the URL to a copy of the original 1337x.yml file, but that didn't work with the tor site.
I had to slightly modify the CSS selectors to work correctly with the onion website.

**Comment by souradeepDe225** [comment]
facing this issue with flaresolverr. Its not able to find the "Verify Human" button.
![image](https://github.com/FlareSolverr/FlareSolverr/assets/109722637/eddb1c1a-0cb6-4bda-8358-d5fb80b1baf4)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1036

**Comment by alexbraga** [comment]
> I just made a terrible fix for this that has nothing to do with FlareSolverr...
> 
> You can use the 1337x onion domain which doesn't have cloudflare protection, making use of the [onion.ly](onion.ly) Tor2Web service. In your prowlarr container (or wherever the app data is) create a custom definition and use this slightly modified yml I created: [1337x-onion.yml](https://gist.github.com/captmicr0/9cc2c331de9972197f716aa5981df65d) Afterwards you can add 1337x-onion as a new indexer and disable your regular 1337x indexer for the time being.
> 
> It should be placed in Definitions/Custom/1337x-onion.yml I tried to just add the URL to a copy of the original 1337x.yml file, but that didn't work with the tor site. I had to slightly modify the CSS selectors to work correctly with the onion website.
> 
> Just keep in mind that this will not be very fast, it add a lot of latency.

@captmicr0 is the custom yaml config still working for you? Because I've had no success with it yet.
