### ISSUE TITLE
TZ environment is not working

### ISSUE THREAD

**Issue by lukjod** [FlareSolverr/FlareSolverr#109]
no metter how i put -e TZ=CET or -e TZ=Europe/Warsaw i always get UTC time
flaresolverr 1.2.5

**Comment by ngosang** [comment]
This feature is not implemented yet but I will add it in the future.
By now you can enter in the docker container and change the date with Linux commands.

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 released.
