### ISSUE TITLE
Error: Error solving the challenge. Timeout after 60.0 seconds.

### ISSUE THREAD

**Issue by collin-bchkmr** [FlareSolverr/FlareSolverr#1090]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: Updated yesterday (newest version)
- Last working FlareSolverr version: -
- Operating system: Debian 12
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: yes
- Are you using Captcha Solver: no
- If using captcha solver, which one: -
- URL to test this issue: Any cloudflare protected site
```

### Description

If I scrape any site that is protected, I get "Error: Error solving the challenge. Timeout after 60.0 seconds."
Yesterday it worked for 1 request, then it stopped working.

### Logged Error Messages

```text
2|flaresolverr  | 2024-02-21 09:32:18 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2|flaresolverr  | 2024-02-21 09:32:18 INFO     Response in 60.69 s
2|flaresolverr  | 2024-02-21 09:32:18 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

**Comment by ukharley** [comment]
Same for me. Windows 11 and using Jackett.

2024-02-21 10:27:18 INFO     FlareSolverr 3.3.14-hotfix2
2024-02-21 10:27:18 INFO     Testing web browser installation...
2024-02-21 10:27:18 INFO     Platform: Windows-10-10.0.22631-SP0
2024-02-21 10:27:18 INFO     Chrome / Chromium path: C:\Program Files\Google\Chrome\Application\chrome.exe
2024-02-21 10:27:18 INFO     Chrome / Chromium major version: 121
2024-02-21 10:27:18 INFO     Launching web browser...
2024-02-21 10:27:25 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
2024-02-21 10:27:25 INFO     Test successful!
2024-02-21 10:27:25 INFO     Serving on http://0.0.0.0:8191
2024-02-21 10:27:52 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://extratorrent.st/'}
2024-02-21 10:27:57 INFO     Challenge detected. Title found: Just a moment...
2024-02-21 10:29:27 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.
2024-02-21 10:29:27 INFO     Response in 94.311 s
2024-02-21 10:29:27 INFO     192.168.6.2 POST http://192.168.6.2:8191/v1 500 Internal Server Error
2024-02-21 10:29:27 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://1337x.to/cat/Movies/time/desc/1/'}
2024-02-21 10:29:31 INFO     Challenge detected. Title found: Just a moment...
2024-02-21 10:30:58 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.
2024-02-21 10:30:58 INFO     Response in 91.514 s
2024-02-21 10:30:58 INFO     192.168.6.2 POST http://192.168.6.2:8191/v1 500 Internal Server Error

**Comment by Rumpelstilzli** [comment]
Also have this issue

**Comment by mvkalsbeek** [comment]
Same here, worked fine yesterday. Started acting up this morning.

**Comment by naeemsufian** [comment]
Also have this issue

**Comment by timekone** [comment]
Update to v3.3.15, that fixed this issue for me.

**Comment by mvkalsbeek** [comment]
I've updated the Docker container to version 3.3.15. Now the test for 1337x.to doesn't give a timeout but a stacktrace:

> An error occurred while testing this indexer
Exception (1337x): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (192.168.0.4:8191) ---> System.Net.Sockets.SocketException (111): Connection refused at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.N

**Comment by zjpleau** [comment]
> Update to v3.3.15, that fixed this issue for me.

working for me now too

**Comment by ilike2burnthing** [comment]
[v3.3.15](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.15)

In future, when asked for a version do not say 'latest/newest', it is meaningless.

@mvkalsbeek follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting. Also make sure that FlareSolverr is actually running and accessible in browser at `http://192.168.0.4:8191`. For Docker you can also try the container IP and port (e.g. `http://172.17.0.2:8191`) or name and port (`http://flaresolverr:8191`).

**Comment by mvkalsbeek** [comment]
@ilike2burnthing I've found the issue. I'm running FlareSolverr in a docker container on a Synology NAS. Sadly updating containers is quite the hassle on Synology. After downloading the latest image and copying the old container to force it to use the latest image (v3.3.15) the port assignments got messed up.

**Comment by ilike2burnthing** [comment]
Try using Watchtower to auto-update your containers - https://hub.docker.com/r/containrrr/watchtower

**Comment by bombz88** [comment]
> [v3.3.15](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.15)
> 
> In future, when asked for a version do not say 'latest/newest', it is meaningless.
> 
> @mvkalsbeek follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting. Also make sure that FlareSolverr is actually running and accessible in browser at `http://192.168.0.4:8191`. For Docker you can also try the container IP and port (e.g. `http://172.17.0.2:8191`) or name and port (`http://flaresolverr:8191`). If you still have problems, open a new issue and provide the information requested.

flare solver seems to have stopped working correctly over the past few weeks via jacket Version v0.22.315

```
FlareSolverr 3.3.21
INFO     Test successful!
INFO     Serving on http://0.0.0.0:8191
INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://ext.to/latest/'}
INFO     Challenge detected. Title found: Just a moment...
ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
INFO     Response in 58.073 s
INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

**Comment by whozur** [comment]
> 
> flare solver seems to have stopped working correctly over the past few weeks via jacket Version v0.22.315
> 
> ```
> FlareSolverr 3.3.21
> INFO     Test successful!
> INFO     Serving on http://0.0.0.0:8191
> INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://ext.to/latest/'}
> INFO     Challenge detected. Title found: Just a moment...
> ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
> INFO     Response in 58.073 s
> INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
> ```

I'm seeing the same... not sure what to do to troubleshoot/fix. Service is running fine in docker:

`{"msg": "FlareSolverr is ready!", "version": "3.3.21", ....`

**Comment by ilike2burnthing** [comment]
See open pinned issues, rather than this one closed months ago.
