### ISSUE TITLE
[yggcookie] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by Naurolapatisserie** [FlareSolverr/FlareSolverr#1091]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

FlareSolver est KO avec YggTorrent et YggCookie. Auriez vous une solution?

### Logged Error Messages

```text
[yggcookie] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
```

### Screenshots

![2024-02-21_18h22_46](https://github.com/FlareSolverr/FlareSolverr/assets/160769690/838d3024-8673-4bd1-bc0e-b5bccfb01aa1)

**Comment by ilike2burnthing** [comment]
[v3.3.15](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.15)

Failing that, increase the timeout.

If you still have issues, provide the information requested in the template and reopen.
