### ISSUE TITLE
The CPU and memory usage of Chromium

### ISSUE THREAD

**Issue by nanmuye** [FlareSolverr/FlareSolverr#1123]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.16
- Last working FlareSolverr version:
- Operating system: centos7
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): default config
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

When the runtime extends, the CPU and memory usage of Chromium become unusually high. This persists even when there is no website access at the moment.
Both CPU and memory are maxed out at 100%.
The high CPU and memory usage of Chromium cause server lag.

### Logged Error Messages

```text
The logs appear to be normal.
```

**Comment by nanmuye** [comment]
The longer the runtime, the higher the usage becomes, and it doesn't decrease over time.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues?q=is%3Aissue+zombie
