### ISSUE TITLE
[speedcd] (testing) Exception (speedcd): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by norbsmaq** [FlareSolverr/FlareSolverr#1124]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.12
- Last working FlareSolverr version: 3.3.12
- Operating system: Ubuntu
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: https://speed.cd/browse/
```

### Description

It looks like maybe speed.cd recently added Cloudflare protections?  I am unable to configure the cookie and user agent settings in Jackett for this indexer like I am for others.  Logging into the site directly, I did see the Cloudflare screen briefly while browsing.

Using the "Test" button in Jackett produces the error for the speed.cd tracker.  I tried removing the indexer, restarting the serivce, and re-adding it but still getting the same result.

### Logged Error Messages

```text
2024-03-18 13:36:27 INFO     Challenge detected. Title found: Just a moment...
2024-03-18 13:37:20 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-03-18 13:37:20 INFO     Response in 55.908 s
2024-03-18 13:37:20 INFO     XXX.XXX.XXX.XXX POST http://server_url:8191/v1 500 Internal Server Error
2024-03-18 13:37:22 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://speed.cd/browse/52/53/41/55/49/2/norar/q/'}
version_main cannot be converted to an integer
```

**Comment by ilike2burnthing** [comment]
Update FlareSolverr.
