### ISSUE TITLE
[speedcd] (testing) Exception (speedcd): FlareSolverr was unable to process the request

### ISSUE THREAD

**Issue by 7eptem** [FlareSolverr/FlareSolverr#1129]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system: Unraid
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: NO
- Are you using a Proxy: NO
- Are you using Captcha Solver: NO
- If using captcha solver, which one: -
- URL to test this issue: https://speed.cd
```

### Description

[speedcd] (testing) Exception (speedcd): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

this stop working yesterday on Jackett or prowlarr

### Logged Error Messages

```text
DEBG 'flaresolverr' stdout output:
INFO     Incoming request => POST /v1 body: {'postData': 'username=myuser', 'maxTimeout': 55000, 'cmd': 'request.post', 'url': 'https://speed.cd/login'}

DEBG 'flaresolverr' stdout output:
INFO     Challenge detected. Title found: Just a moment...
DEBG 'flaresolverr' stdout output:
ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
DEBG 'flaresolverr' stdout output:
INFO     Response in 55.758 s
172.17.0.1 POST http://10.10.10.6:8191/v1 500 Internal Server Error
```

**Comment by norbsmaq** [comment]
I am also having an issue with this tracker.  The cookie version was working yesterday but now it is failing.  I am getting a slightly different error than OP, however.

Error:
`Your cookie did not work: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.`

I am happy to enter a separate issue if needed.  Just let me know.

**Comment by ilike2burnthing** [comment]
Wasn't working yesterday, working again now. Cookie+UA version also now available,
