### ISSUE TITLE
[chdbits] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by PN62323424** [FlareSolverr/FlareSolverr#1131]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:v3.3.16
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [yes]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

[log.zip](https://github.com/FlareSolverr/FlareSolverr/files/14732971/log.zip)

### Logged Error Messages

```text
In the zip above
```

**Comment by andtoliom** [comment]
Facing same problem since 4-5 days ago

**Comment by ilike2burnthing** [comment]
Log file is just spaces.

If you've followed the troubleshooting steps [here](https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting) and you've tried increasing the timeout to 120s, then - https://github.com/FlareSolverr/FlareSolverr/issues/1036
