### ISSUE TITLE
[yggtorrent] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by daniwalter001** [FlareSolverr/FlareSolverr#1141]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.16
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] no 
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

This happens whenever i tried resolving a captcha on jackett

### Logged Error Messages

```text
An error occurred while updating this indexer
The cookies provided by FlareSolverr are not valid
```

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

**Comment by daniwalter001** [comment]
> FlareSolverr should be running on the same device and using the same IP as the app making the request

I was running it on another device so might be the ip
