### ISSUE TITLE
File Download: 405 Method not allowed

### ISSUE THREAD

**Issue by 0rsa** [FlareSolverr/FlareSolverr#1145]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.16
- Operating system: Debian 12
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
```

### Description

Hello,
I'm trying to download a torrent from yggtorrent using method.get with this kind of URL :
$source = 'https://www3.yggtorrent.qa/rss/download?id=xxxxxxxxx&passkey=xxxxxxxxxxxxxxxxxxxx';

Using a browser, the link works well with a GET request and the .torrent download starts immediately.

Using FlareSolverr with these parameters
`array( "cmd"=> "request.get", "url"=> $source, "maxTimeout"=> 60000, 'returnOnlyCookies'=>false )`

I get the following error response:
`{
    "status": "ok",
    "message": "Challenge not detected!",
    "solution": {
        "url": "http://localhost:8191/v1",
        "status": 200,
        "cookies": [],
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "headers": {},
        "response": "<html><head><meta name=\"color-scheme\" content=\"light dark\"></head><body><pre style=\"word-wrap: break-word; white-space: pre-wrap;\">{\"error\": \"Method not allowed.\", \"status_code\": 405}</pre></body></html>"
    },
    "startTimestamp": 1712508738067,
    "endTimestamp": 1712508738938,
    "version": "3.3.16"
}`

Is the file download supposed to work or is this something not working yet?
Thank you, have a nice day

### Logged Error Messages

```text
{"error": "Method not allowed.", "status_code": 405}
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/207
