### ISSUE TITLE
[chdbits] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by MasalaTalk** [FlareSolverr/FlareSolverr#1148]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:podman version: 4.9.4
- Last working FlareSolverr version:podman version: 4.9.4
- Operating system: linux
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint): 
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] dont know
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

it worked with hd-t 
but not working with chdb

### Logged Error Messages

```text
An error occurred while updating this indexer
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
```

**Comment by ilike2burnthing** [comment]
Increase the timeout, check the troubleshooting wiki, otherwise https://github.com/FlareSolverr/FlareSolverr/issues/1036.
