### ISSUE TITLE
Fix The cookies provided by FlareSolverr are not valid by using a proxy

### ISSUE THREAD

**Issue by olaxe** [FlareSolverr/FlareSolverr#115]
### Description
When I tried FlareSolverr the first time, I had the message:
The cookies provided by FlareSolverr are not valid
I disabled my proxy on Jackett and after that, everything works fine.

### Fix
Add the option to provide a proxy like Jackett does to ensure we contact the target website from the same apparent source.
I google what can be done because I don't know much about npm and I found this:
We can use the global-tunnel-ng package to initialize proxy and not pollute the http or https based code everywhere. So first install global-tunnel-ng package:

npm install global-tunnel-ng
Then change your implementations to initialize proxy if needed as:

const globalTunnel = require('global-tunnel-ng');

globalTunnel.initialize({
  host: 'proxy.host.name.or.ip',
  port: 8080
});

Maybe it is something you can consider and an environment variable in the Docker so we can use it if needed.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/26

**Comment by ngosang** [comment]
We already have an issue to implement the proxy support #26
The `global-tunnel-ng` library can't be used here because it only affects node modules. We have to configure the proxy in Chrome but it's easy anyway.
