### ISSUE TITLE
Problem with utils.get_flaresolverr_version() & package.json

### ISSUE THREAD

**Issue by stonfute** [FlareSolverr/FlareSolverr#1152]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.17 - Binary
- Last working FlareSolverr version:
- Operating system: Ubuntu 22.04
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Using binary versions doesn't work properly under Ubuntu because of the package.json location.

When placed in its default location (root level, same as the flaresolverr binary), it doesn't function correctly (see error message). The package.json file must be placed in the parent directory for it to work.

To resolve this error:
- Either update the Readme to clearly instruct users to place the package.json file in the parent directory.
- Or fix utils.get_flare_solver_version() and package_path.

### Logged Error Messages

```text
Traceback (most recent call last):
  File "flaresolverr.py", line 101, in <module>
  File "utils.py", line 38, in get_flaresolverr_version
KeyError: 'version'
```

**Comment by ilike2burnthing** [comment]
Working fine here so long as Xvfb is installed - https://app.any.run/tasks/3e0245ae-2f51-4aba-aeb1-3c1557104ca1 (excuse the sandbox freaking out at the end and registering multiple keystrokes for one).

Can you repeat the steps there to resolve your issue?

Can you give step-by-step instructions of what you're doing to cause your issue?

**Comment by stonfute** [comment]
This this not related to xvfb at all ... It's an headless server but xvfb was already installed.
I said it's related to the path of `package.json` and `package_path` in `utils.get_flaresolverr_version()` (Look at error message).
`package_path` is not working properly the get the path of package.json, package.json needs to be in the parent directory.

Could be related to : [660#issuecomment-1463769964](https://github.com/FlareSolverr/FlareSolverr/issues/660#issuecomment-1463769964)

**Comment by stonfute** [comment]
After further investigation, I can't reproduce. 
I just removed the package.json from parent directory and now it works like a charm !
