### ISSUE TITLE
Windows Defender detects flaresolverr.exe as Trojan:Win32/Bearfoos.Alml

### ISSUE THREAD

**Issue by StephenCYang** [FlareSolverr/FlareSolverr#1157]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.17
- Last working FlareSolverr version:3.3.16
- Operating system:Windows 11
- Are you using Docker: [yes/no] No
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] yes
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] yes
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Upon unzipping the file, flaresolverr_windows_x64.zip, Windows Defender triggers upon extracting flaresolverr.exe.

### Logged Error Messages

```text
Windows Defender reports: Trojan:Win32/Bearfoos.Alml
```

**Comment by ilike2burnthing** [comment]
Defender being a sack of shit as per. I suggest Kaspersky or Bitdefender's free AVs instead.
