### ISSUE TITLE
[NixOS x64] -bash: ./flaresolverr/flaresolverr: cannot execute: required file not found

### ISSUE THREAD

**Issue by aicynide** [FlareSolverr/FlareSolverr#1160]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:v3.3.17
- Last working FlareSolverr version:none
- Operating system:NixOS
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):N/A
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:N/A
- URL to test this issue: https://google.com
```

### Description

```
./flaresolverr/flaresolverr
-bash: ./flaresolverr/flaresolverr: cannot execute: required file not found
```

### Logged Error Messages

```text
-bash: ./flaresolverr/flaresolverr: cannot execute: required file not found
```

**Comment by ilike2burnthing** [comment]
Try installing Xvfb, see if that resolves the issue.

If not, is there no information beyond that error? Have you extracted the contents of the archived precompiled binaries in full and unedited?

**Comment by ilike2burnthing** [comment]
From my understanding, that's the prime example of where Xvfb would be used, "Xvfb is an X server that can run on machines with no display hardware and no physical input devices. It emulates a dumb framebuffer using virtual memory." - https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml

I previously found it was required for running on Ubuntu - https://github.com/FlareSolverr/FlareSolverr/issues/1152.
