### ISSUE TITLE
(YGGTORRENT) Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request

### ISSUE THREAD

**Issue by MozkaGit** [FlareSolverr/FlareSolverr#1178]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: Just updated from 3.3.12 to 3.3.17 because it didn't work anymore on 3.3.12
- Last working FlareSolverr version: 3.3.12
- Operating system: Debian 12
- Are you using Docker: yes
- FlareSolverr User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
- Are you using a VPN: no
- Are you using a Proxy: no
```

### Description

Hello, it was functioning until today. I haven't changed anything in my configuration. I was using version 3.3.12, and after it stopped working, I updated to 3.3.17, but this did not resolve the issue.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
```

### Screenshots

![Capture d'écran 2024-05-05 224451](https://github.com/FlareSolverr/FlareSolverr/assets/43102748/4288e9db-8d7b-4ab5-b70c-e952d638ec25)
![Capture d'écran 2024-05-05 224557](https://github.com/FlareSolverr/FlareSolverr/assets/43102748/e88143ce-7dbd-4a4a-ae8b-7ca15eb2b07a)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/1036
