### ISSUE TITLE
Cloudflare challenge now uses CHIPS for cf_clearance cookie

### ISSUE THREAD

**Issue by andtoliom** [FlareSolverr/FlareSolverr#1186]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.17
- Last working FlareSolverr version: 3.3.17
- Operating system: Windows 10
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: Any with latest cloudflare challenge (ex: https://www.goldbelly.com/)
```

### Description

From now on cloudlfare is using CHIPS (Cookies Having Independent Partitioned State) to store the cookie on the browser, what is causing the Flaresolverr could not be able to extract the cf_clearance cookies anymore. At the momment most of the sites i've tested are causing this issue, some not (but I guess is temporary till the new Cloudflare update reach all the sites)

### Logged Error Messages

```text
No log, just infinite loop
```

### Screenshots

![2024-05-09 235127](https://github.com/FlareSolverr/FlareSolverr/assets/5096957/d67ffe55-c3c5-4943-b4a4-c3a5a6807b7d)

Marked is the Partition Key, when you try to use a Cookie extension to inspect cookies (EditThisCookie) the cf_clearance cookie won't appear, only is visible when using the DevTools

**Comment by ilike2burnthing** [comment]
Hi, why was this closed?

**Comment by andtoliom** [comment]
I noticed my issue was caused because of the DevTools opened. If It's closed it will pass the challenge with no issues (Chrome v123)

**Comment by andtoliom** [comment]
> Hi, why was this closed?

I noticed my issue was caused because of the DevTools opened. If It's closed it will pass the challenge with no issues (Chrome v123)
