### ISSUE TITLE
Precompiled binaries missing chrome dependencies [libnss3.so]

### ISSUE THREAD

**Issue by MuhammadBayiz** [FlareSolverr/FlareSolverr#1189]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.17
- Last working FlareSolverr version:/
- Operating system: Linux-6.1.6 gentoo
- Are you using Docker: [no]
- FlareSolverr User-Agent (see log traces or / endpoint):/
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:/
- URL to test this issue:/
```

### Description

I'm executing the [precompiled binaries](https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.17/flaresolverr_linux_x64.tar.gz) with a non root user but I can't run flaresolverr because chrome has a missing dependency (libnss3.so), previously i was able to use flaresolverr in docker with no issue but now that I'm moving away from docker.

### Logged Error Messages

```text
~/flaresolverr $ ./flaresolverr
2024-05-13 07:39:33 INFO     FlareSolverr 3.3.17                  2024-05-13 07:39:33 INFO     Testing web browser installation...  2024-05-13 07:39:33 INFO     Platform: Linux-6.1.66-gentoo-***-x86_64-AMD_EPYC_7702P_64-Core_Processor-with-glibc2.38           2024-05-13 07:39:33 INFO     Chrome / Chromium path: /mnt/mpathad/hamashareef/flaresolverr/chrome/chrome                            /mnt/mpathad/hamashareef/flaresolverr/chrome/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory                                      2024-05-13 07:39:33 ERROR    Chrome / Chromium version not detected!
```

**Comment by ilike2burnthing** [comment]
Working fine here on Ubuntu 22.0.4.2, with libnss3.so already present as a system library file - https://app.any.run/tasks/851a36f6-dc7d-44a3-853c-7bef37b7d5c6

Looks like you need to install libnss3.

**Comment by ilike2burnthing** [comment]
OP stated they weren't using Docker.

**Comment by MuhammadBayiz** [comment]
The mentioned package seems to be missing in the system and as non-root user(as I'm on a seedbox) i can't install it without root privileges and compiling it myself requires third party software that are also missing so eventually I'm going back to using docker for the moment as it seems to be the only solution for me.

Sorry for replying late on the issue.
