### ISSUE TITLE
Documentation mentions sample systemd unit file but none is included

### ISSUE THREAD

**Issue by pessimism** [FlareSolverr/FlareSolverr#1204]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Systemd service
We provide an example Systemd unit file flaresolverr.service as reference. You have to modify the file to suit your needs: paths, user and environment variables.

### Logged Error Messages

```text
No sample systemd unit file is present
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/commit/805a34c9d621cf39c04ca799a5df26ac85dcfd56

**Comment by brad-charboneau** [comment]
Reopening because systemd service file is missing from repo.

**Comment by konjas** [comment]
it is still missing

**Comment by dbolser** [comment]
> it was deleted in [3830250#diff-a3e8f47ca0f3a280855b24105aa4dabd53bb6129838cdd000406e52e39925b20](https://github.com/FlareSolverr/FlareSolverr/commit/383025032b4939ffc62a42d011373e07cd617c47#diff-a3e8f47ca0f3a280855b24105aa4dabd53bb6129838cdd000406e52e39925b20) [@ilike2burnthing](https://github.com/ilike2burnthing)

Is it sufficient to just put that file back?

**Comment by RedSnt** [comment]
I thought I was taking crazy pills, because I couldn't find it in the new v3.3.22 package either.  

I don't know why this is closed when it's still nowhere to be found..

**Comment by konjas** [comment]
@ilike2burnthing, could you help here?

**Comment by ilike2burnthing** [comment]
Issue was closed because I linked to a copy of the file, and the original was removed by the repo owner. I was hoping they'd have gotten some free time between then and now, and decided whether to remove the reference to the file, or restore it, but no such luck.

If someone can confirm the file works with v3.3.22/24, I'll add it back.

**Comment by RedSnt** [comment]
I tested it and it almost works, Group and User values obviously doesn't work, so setting user as either root or ones own username and it runs fine, and I just commented out Group as that wasn't needed for me (and also failed to launch if set to "flaresolverr").

**Comment by ilike2burnthing** [comment]
Restored.

As per the readme:

> You have to modify the file to suit your needs: paths, user and environment variables.
