### ISSUE TITLE
error : unable to connect to indexer. Indexer's server is unavailable HTTP Request failed 500 internal error at (HTTP://Flaresolverr IP)

### ISSUE THREAD

**Issue by tifo71** [FlareSolverr/FlareSolverr#1209]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.19
- Last working FlareSolverr version:3.3.19
- Operating system: Windows 11
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no 
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

YGGTorrent has had a bug since yesterday. An error appears when testing
![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/44eda04a-ddcf-4e14-b428-962d4ff6a8fc)

When you test flaresolverr it works, but for YGGtorrent it gives this error.

When you look at the log, this is what it shows repeatedly![image]
![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/60ab5659-90c2-4748-a1d8-dfed369c4a50)

### Logged Error Messages

```text
error message in prowlarr when testing YGGtorrent : 
Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.1.26:8191/v1]

and in the flaresolverr log here's the message : 

172.17.0.1 POST http://192.168.1.26:8191/v1 200 OK
2024-06-03 09:57:58 INFO     Incoming request => POST /v1 body: {'maxTimeout': 20000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all', 'proxy': {}}
version_main cannot be converted to an integer
2024-06-03 09:57:59 INFO     Challenge detected. Title found: Just a moment...
2024-06-03 09:58:19 ERROR    Error: Error solving the challenge. Timeout after 20.0 seconds.
2024-06-03 09:58:19 INFO     Response in 20.787 s
2024-06-03 09:58:19 INFO     172.17.0.1 POST http://192.168.1.26:8191/v1 500 Internal Server Error
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/44eda04a-ddcf-4e14-b428-962d4ff6a8fc)

![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/60ab5659-90c2-4748-a1d8-dfed369c4a50)

**Comment by ilike2burnthing** [comment]
You've been using FlareSolverr long enough, I have no idea why you thought changing the timeout to 20s was a good idea.

**Comment by tifo71** [comment]
ok great you should have increased the timeout. It work again. Thanks
