### ISSUE TITLE
Destroy Session Error (disconnected: not connected to DevTools) and hung chrome.exe/chromedriver.exe processes

### ISSUE THREAD

**Issue by sunnyd24** [FlareSolverr/FlareSolverr#1216]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.19
- Last working FlareSolverr version: 3.3.17 (I think)
- Operating system: Windows
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- URL to test this issue: any
```

### Description

1. Start a session with any "url" using sessions.create, all works ok.
```
$data = @{
"cmd" = "sessions.create"
"session" = "session_REDACTED_container"
"url" = $url
"maxTimeout" = 60000
}

$jsonData = $data | ConvertTo-Json

$response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $jsonData
```
2. Use request.get to query webpage, all works ok.

```
$data = @{
"cmd" = "request.get"
"session" = "session_REDACTED_container"
"url" = $url
"maxTimeout" = 60000
}

$jsonData = $data | ConvertTo-Json

$response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $jsonData
```

3. Use sessions.destroy which throws up error message on Invoke-RestMethod command as per below.

```
$data = @{
"cmd" = "sessions.destroy"
"session" = "session_nextcloud_container"
"url" = $url
"maxTimeout" = 60000
}

$jsonData = $data | ConvertTo-Json

$response = Invoke-RestMethod -Uri $apiUrl -Method Post -Headers $headers -Body $jsonData
```

4. Lots of "hung" chrome.exe and chromedriver.exe at different ports processes left over in task manager.

### Logged Error Messages

```text
Invoke-RestMethod:
{
  "status": "error",
  "message": "Error: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=123.0.6300.0)\nStacktrace:\n\tGetHandleVerifier [0x00E14CA3\u002B225091]\n\t(No symbol) [0x00D44DF1]\n\t(No symbol) [0x00BE9A7A]\n\t(No symbol) [0x00BD94DC]\n\t(No symbol) [0x00BD9B3D]\n\t(No symbol) [0x00BE9ED7]\n\t(No symbol) [0x00BCE00D]\n\t(No symbol) [0x00C4ABA7]\n\t(No symbol) [0x00C4A7BB]\n\t(No symbol) [0x00C3F523]\n\t(No symbol) [0x00C179B9]\n\t(No symbol) [0x00C1879D]\n\tsqlite3_dbdata_init [0x01289A43\u002B4064547]\n\tsqlite3_dbdata_init [0x0129104A\u002B4094762]\n\tsqlite3_dbdata_init [0x0128B948\u002B4072488]\n\tsqlite3_dbdata_init [0x00F8C9A9\u002B930953]\n\t(No symbol) [0x00D507C4]\n\t(No symbol) [0x00D4ACE8]\n\t(No symbol) [0x00D4AE11]\n\t(No symbol) [0x00D3CA80]\n\tBaseThreadInitThunk [0x758C7BA9\u002B25]\n\tRtlInitializeExceptionChain [0x77BBBE7B\u002B107]\n\tRtlClearBits [0x77BBBDFF\u002B191]\n",
  "startTimestamp": 1718699732556,
  "endTimestamp": 1718699732628,
  "version": "3.3.19"
}
```

**Comment by ilike2burnthing** [comment]
`url` and `maxTimeout` aren't needed when creating and destroying sessions.

Using your format, I can reproduce the error. However, when using the format from our example, there's no error - https://github.com/FlareSolverr/FlareSolverr#usage

Removing `-UseBasicParsing` from our example results in the same error.

`-UseBasicParsing` has been deprecated in PS v6 onwards, as it's the default behaviour  (to not run script code when HTML is parsed). Either use PS v6/7 (v5 is default in Windows), or use `-UseBasicParsing`.

**Comment by sunnyd24** [comment]
@ilike2burnthing Thanks for your checks, and note your `url` and `maxTimeout` suggestions, I have amended this.

I am using PowerShell 7.4.2, but the error persists, whether I use `-UseBasicParsing` or not using my script.

Even using the powershell example below, I have the same error:
```
$body = @{
    cmd = "request.get"
    url = "http://www.google.com/"
    maxTimeout = 60000
} | ConvertTo-Json

irm -UseBasicParsing 'http://localhost:8191/v1' -Headers @{"Content-Type"="application/json"} -Method Post -Body $body
```

Error:
```
Invoke-RestMethod:
{
  "status": "error",
  "message": "Error: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=123.0.6300.0)\nStacktrace:\n\tGetHandleVerifier [0x00B64CA3\u002B225091]\n\t(No symbol) [0x00A94DF1]\n\t(No symbol) [0x00939A7A]\n\t(No symbol) [0x009294DC]\n\t(No symbol) [0x00929B3D]\n\t(No symbol) [0x00939ED7]\n\t(No symbol) [0x0091E00D]\n\t(No symbol) [0x0099ABA7]\n\t(No symbol) [0x0099A7BB]\n\t(No symbol) [0x0098F523]\n\t(No symbol) [0x009679B9]\n\t(No symbol) [0x0096879D]\n\tsqlite3_dbdata_init [0x00FD9A43\u002B4064547]\n\tsqlite3_dbdata_init [0x00FE104A\u002B4094762]\n\tsqlite3_dbdata_init [0x00FDB948\u002B4072488]\n\tsqlite3_dbdata_init [0x00CDC9A9\u002B930953]\n\t(No symbol) [0x00AA07C4]\n\t(No symbol) [0x00A9ACE8]\n\t(No symbol) [0x00A9AE11]\n\t(No symbol) [0x00A8CA80]\n\tBaseThreadInitThunk [0x77347BA9\u002B25]\n\tRtlInitializeExceptionChain [0x77E2C10B\u002B107]\n\tRtlClearBits [0x77E2C08F\u002B191]\n",
  "startTimestamp": 1719155635311,
  "endTimestamp": 1719155638583,
  "version": "3.3.19"
}
```

I will update to 3.3.20 meanwhile. 

Any ideas?

**Comment by sunnyd24** [comment]
Same issue with 3.3.20.

However, I have isolated this error to an environment variable "headless=false", and "headless=true" seems to work fine.

Likely to be something in the code that has affected this at some point?

**Comment by ilike2burnthing** [comment]
I'm unable to reproduce your issue.

Using a clean Windows Sandbox I download and extract FlareSolverr, run the example PS command, and I get normal output. Stopping FlareSolverr, setting `headless=false`, starting FlareSolverr again, and rerunning the script, I still get normal output.

Can you provide debug FS logs of the issue?
