### ISSUE TITLE
I am getting 'Attention Required' when running in docker. Running on windows in vscode seems to work (for now?)

### ISSUE THREAD

**Issue by leonidcan** [FlareSolverr/FlareSolverr#1217]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.19
- Last working FlareSolverr version: it seems older versions are also not working
- Operating system: ubuntu
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://drivetest.ca/dtbookingngapp/registration/signup (access from Canada only but US also might work)


```

### Description

I am getting 'Attention Required' when running in docker. Running on windows in vscode seems to work (for now?)

### Logged Error Messages

```text
N/A
```

**Comment by ilike2burnthing** [comment]
`latest` is meaningless, especially when it comes to Docker; please provide the actual version.

If the site is geo-restricted and you're not using a valid IP address, FlareSolverr can't do anything about it. If you are using a valid IP, provide the URL.

**Comment by leonidcan** [comment]
Update issue. I have being using flaresolverr for a while with this site. It was working until today it stopped working. I am sure it was CF update. I built my custom docker image with few modifications not related to handling chrome browser, mostly to handle errors and sessions as I needed.

**Comment by ilike2burnthing** [comment]
In browser it's working fine for me, with or without a VPN or proxy, even when emulating the UA of the Docker FlareSolverr and with devtools open. Not sure what is causing it.

**Comment by leonidcan** [comment]
For me In browser it also works, it does not work in docker :(.
So you saying that it does not block you in docker? 
"when emulating the UA of the Docker" what does it mean? How can I try it? Unfortunately I am away and can't do much at this time :(

**Comment by leonidcan** [comment]
I will close this for now, somehow it started working. Maybe it was temporary ban :\.

**Comment by leonidcan** [comment]
I will close this for now, somehow it started working. Maybe it was temporary ban :.

**Comment by leonidcan** [comment]
Closed as non confirmed

**Comment by leonidcan** [comment]
So sometimes it works but most of the time it's not. Looks like cloud flare update. Maybe more cases will come.
