### ISSUE TITLE
YGG Flaresolverr test Error: Error solving the challenge. Timeout after 60.0 seconds. 500 Internal Server Error

### ISSUE THREAD

**Issue by tifo71** [FlareSolverr/FlareSolverr#1221]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.19
- Last working FlareSolverr version: 3.3.19
- Operating system: windows 11 (OMV VM)
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date
```

### Description

flaresolverr error :  Error solving the challenge. Timeout after 60.0 seconds. 500 Internal Server Error

even with increased timing same error

![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/bfd864b9-0940-413c-a4a4-cc7d84804084)

### Logged Error Messages

```text
Flaresolverr problem with ygg. Flaresolverr test in prowlarr work but when I test YGG there's the flaresolverr error I have increased the timing but nothing works

 Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
version_main cannot be converted to an integer
2024-06-21 03:06:33 INFO     Challenge detected. Title found: Just a moment...
2024-06-21 03:07:32 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-06-21 03:07:32 INFO     Response in 60.746 s
2024-06-21 03:07:32 INFO     172.17.0.1 POST http://192.168.1.12:8191/v1 500 Internal Server Error
```

### Screenshots

![image_2024-06-21_031648780](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/c04d3e39-372c-4155-a524-d39c3875cbcf)

flaresolverr error in prowlarr log too : 

![image](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/18e51c3c-87b5-4d96-8ef5-81f010fb3b0e)

**Comment by tifo71** [comment]
this problem had already appeared once and I had increased the timing and it had worked but now it doesn't matter the timing set to 30 60 70 seconds; it doesn't work.

**Comment by trowmarrant** [comment]
I have the same problem ...

**Comment by dk-one** [comment]
Same problem here, every few month on ygg...

**Comment by EMeric1992** [comment]
Same problem for me since yesterday afternoon

**Comment by ilike2burnthing** [comment]
@tifo71 once again, this is the same issue - #1036

**Comment by tifo71** [comment]
@ilike2burnthing Yes but what do you do then?

**Comment by ilike2burnthing** [comment]
Read #1036 and the PR.

I stated clearly that trying to get around the issue lock to post more spam about this would result in a ban. This is your last warning.

**Comment by tifo71** [comment]
@ilike2burnthing ok i understand but do you know what's causing this recurring problem? Or do you just have to wait until it works again?

**Comment by ilike2burnthing** [comment]
CF is detecting FS, more specifically UC, in its current state.
