### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): FlareSolverr

### ISSUE THREAD

**Issue by sel13015** [FlareSolverr/FlareSolverr#1228]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version: 3.3.19
- Operating system:
- Are you using Docker: yes
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
```

### Description

Hello, 
When I do tests with prowlarr to indexer ygg, I get this error.

Can you help me please ?

Waiting for your return.

### Logged Error Messages

```text
Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.xxx.xxx:8191/v1]
```

### Screenshots

![Capture d'écran 2024-06-21 214531](https://github.com/FlareSolverr/FlareSolverr/assets/82291876/cdd693a9-426e-4c17-9340-5e3119ae5e1b)

**Comment by ilike2burnthing** [comment]
[v3.3.20](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.20)
