### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Token solver failed to return a token.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Token solver failed to return a token. (Test)

### ISSUE THREAD

**Issue by CyberPoison** [FlareSolverr/FlareSolverr#123]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: (tag set as Latest and pulled the image just today) 
* **Last working FlareSolverr version**:this one
* **Operating system**:Ubuntu 18.04
* **Are you using Docker**: yes
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** yes
* **If using captcha solver, which one:** hcaptcha-solver

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
1° add the flaresolverr to jackett and set up both 
2° try to check yggtorrent.li with your username and password 

[Make sure you attach the full logs with your personal information removed in case we need more information]
```
   
      
      maxHeadersCount: null,


      reusedSocket: false,


      host: 'assets.hcaptcha.com',


      protocol: 'https:',


      [Symbol(kCapture)]: false,


      [Symbol(kNeedDrain)]: false,


      [Symbol(corked)]: 0,


      [Symbol(kOutHeaders)]: [Object: null prototype]


    },


    request: Request {


      _events: [Object: null prototype],


      _eventsCount: 5,


      _maxListeners: undefined,


      uri: [Url],


      method: 'GET',


      readable: true,


      writable: true,


      explicitMethod: true,


      _qs: [Querystring],


      _auth: [Auth],


      _oauth: [OAuth],


      _multipart: [Multipart],


      _redirect: [Redirect],


      _tunnel: [Tunnel],


      _rp_resolve: [Function (anonymous)],


      _rp_reject: [Function (anonymous)],


      _rp_promise: [Promise],


      _rp_callbackOrig: undefined,


      callback: [Function (anonymous)],


      _rp_options: [Object],


      headers: {},


      setHeader: [Function (anonymous)],


      hasHeader: [Function (anonymous)],


      getHeader: [Function (anonymous)],


      removeHeader: [Function (anonymous)],


      localAddress: undefined,


      pool: {},


      dests: [],


      __isRequestRequest: true,


      _callback: [Function: RP$callback],


      proxy: null,


      tunnel: true,


      setHost: true,


      originalCookieHeader: undefined,


      _disableCookies: true,


      _jar: undefined,


      port: 443,


      host: 'assets.hcaptcha.com',


      path: '/c/500c658/hsl.js',


      httpModule: [Object],


      agentClass: [Function: Agent],


      agent: [Agent],


      _started: true,


      href: 'https://assets.hcaptcha.com/c/500c658/hsl.js',


      req: [ClientRequest],


      ntick: true,


      response: [Circular *1],


      originalHost: 'assets.hcaptcha.com',


      originalHostHeaderName: 'host',


      responseContent: [Circular *1],


      _destdata: true,


      _ended: true,


      _callbackCalled: true,


      [Symbol(kCapture)]: false


    },


    toJSON: [Function: responseToJSON],


    caseless: Caseless { dict: [Object] },


    body: 'nonsense\n',


    [Symbol(kCapture)]: false,


    [Symbol(kHeaders)]: {


      date: 'Sat, 08 May 2021 22:02:27 GMT',


      'content-type': 'text/html',


      'transfer-encoding': 'chunked',


      connection: 'close',


      'set-cookie': [Array],


      'x-amz-meta-md5': '0377438312a93cf85307e3fa0fe437cf',


      'x-amz-meta-privilege': '755',


      'last-modified': 'Mon, 20 Aug 2018 21:31:04 GMT',


      'x-amz-error-code': 'NoSuchKey',


      'x-amz-error-message': 'The specified key does not exist.',


      'x-amz-error-detail-key': 'c/500c658/hsl.js',


      'x-amz-request-id': '76S05JK51FG972KS',


      'x-amz-id-2': 'rY+gGa94s0NUxWwAgEss3mkGRMfng29Sle64W1pfFYACVzTVBb04xrVxV2QjK+QhDK6Nvilw+CA=',


      'cf-cache-status': 'EXPIRED',


      'cf-request-id': '09ef99eae80000c2f45c256000000001',


      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',


      'strict-transport-security': 'max-age=2592000; includeSubDomains; preload',


      'x-content-type-options': 'nosniff',


      server: 'cloudflare',


      'cf-ray': '64c5f8f16f19c2f4-FRA',


      'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'


    },


    [Symbol(kHeadersCount)]: 42,


    [Symbol(kTrailers)]: null,


    [Symbol(kTrailersCount)]: 0,


    [Symbol(RequestTimeout)]: undefined


  }


}


2021-05-08T22:02:27.747Z INFO REQ-1 Successful response in 4.938 s


2021-05-08T22:02:27.748Z INFO REQ-1 Cloudflare Error: Token solver failed to return a token.
```
### Screenshot 

[Place any screenshots of the issue here if needed]

![Screenshot_20210509_000747](https://user-images.githubusercontent.com/60718477/117554876-a4997e00-b05a-11eb-8329-627f0f760f9e.jpg)

**Comment by Killianbe** [comment]
anyway to add proxy or vpn only for jackett/flarsolver docker?

**Comment by CyberPoison** [comment]
> new cloudflare challenges, can't be solved :/
> only solution is have multiple servers on differents countries running jackett+flaresolverr :(

This isn't really a solution, it should have a solution to bypass this 🤔 maybe with a deeper look

**Comment by CyberPoison** [comment]
@ngosang what is the chances for a fix?

**Comment by Abbo44** [comment]
@ngosang Any updates on that issue ?

**Comment by Killianbe** [comment]
@Abbo44 Nope

**Comment by titatom** [comment]
> anyway to add proxy or vpn only for jackett/flarsolver docker?

https://jordanelver.co.uk/blog/2019/06/03/routing-docker-traffic-through-a-vpn-connection/

I will try this

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 will fix YGG. Will be released today.
About the hCaptcha solver, I'm going to add a clarification in the traces.

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 released.

**Comment by titatom** [comment]
> FlareSolverr v1.2.6 released.

@ngosang Unfortunately the problem seems to persist with the latest FlareSolverr release.

**Comment by titatom** [comment]
> FlareSolverr v1.2.6 released.

@ngosang Unfortunately the issues seem to persists with YGG after the latest release. Still getting this error :

Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured.

**Comment by Al4ndil** [comment]
@ngosang It's ok for me with the new release.

**Comment by xfouloux** [comment]
it's ok for me from scaleway, but not from USA or OVH, so i wonder if in the mean time their anti ddos went off on scaleway or it's the update :/
