### ISSUE TITLE
Chrome / Chromium version not detected!

### ISSUE THREAD

**Issue by Knocxx32** [FlareSolverr/FlareSolverr#1232]
### Have you checked our README?

- [x] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.19
- Last working FlareSolverr version: 3.3.19
- Operating system: RPI 4
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint): NA
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
```

### Description

Hello,

I installed Flaresolverr with Docker but when starting I got the following message: (see logs)

However, I installed Chromium, Chromium Browser, and I checked the path /usr/bin/chromium, there is Chromium installed.

Do you have a solution for this?
I'm desperately looking for a solution for the installation.

### Logged Error Messages

```text
FlareSolverr 3.3.19
Testing web browser installation...
Platform: Linux-6.6.28+rpt-rpi-v8-aarch64-with-glibc2.31
Chromium / Chromium path: /usr/bin/chromium
Segmentation fault (core dumped)
Chrome / Chromium version not detected!


chromium --version
Chromium 111.0.5563.110 built on Debian bookworm/sid, running on Debian 12.1
```

**Comment by ilike2burnthing** [comment]
If you're using Docker, there's no need to install Chrome or Chromium on the host; the whole point of containers is that they're contained.

You shouldn't be getting that error on 3.3.19, but we updated to 3.3.20 yesterday, so try updating to that.

**Comment by Knocxx32** [comment]
> If you're using Docker, there's no need to install Chrome or Chromium on the host; the whole point of containers is that they're contained.
> 
> You shouldn't be getting that error on 3.3.19, but we updated to 3.3.20 yesterday, so try updating to that.

Well thank you, I updated and I have no problems!
