### ISSUE TITLE
3.3.20 Not working with Yggtorrent

### ISSUE THREAD

**Issue by AkuroSoren** [FlareSolverr/FlareSolverr#1238]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.20
- Last working FlareSolverr version: 3.3.13
- Operating system: Linux Debian
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://ygg.re
```

### Description

I'm using FlareSolverr on a seedbox/VPS, in Prowlarr (same issue with Jackett)
It's been nearly 3 weeks since I can't get ygg working on Prowlarr/Jackett

### Logged Error Messages

```text
2024-06-25 14:27:48.6|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://172.17.0.1:18011/v1: 500.InternalServerError (182 bytes)
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 20.0 seconds.", "startTimestamp": 1719318447571, "endTimestamp": 1719318468648, "version": "3.3.20"}
2024-06-25 14:27:48.6|Warn|Cardigann|Request for YggTorrent failed with exception 'HTTP request failed: [500:InternalServerError] [POST] at [http://172.17.0.1:18011/v1]'. Retrying in 1.9066166s.
```

**Comment by ilike2burnthing** [comment]
Gonna need longer than 20s for the timeout, default is 60s, some people extend it. Otherwise, see troubleshooting and #1036.
