### ISSUE TITLE
Challenge solved but site reload cf challenge frame

### ISSUE THREAD

**Issue by nanmuye** [FlareSolverr/FlareSolverr#1239]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.20
- Last working FlareSolverr version:3.3.20
- Operating system:windows
- Are you using Docker: [yes/no]no
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]yes
- Are you using Captcha Solver: [yes/no]no
- If using captcha solver, which one:
- URL to test this issue:
https://extremereportbot.com/banned/?page=1E
```

### Description

Challenge solved but the site reload cf challenge frame,so FlareSolverr return the challenging frame h5 code to me.
I use headless=false to watch what happened,it seems that cf think I am bot so reload the challenge frame rather than into the true site

### Logged Error Messages

```text
2024-06-26 01:22:48 INFO     Challenge detected. Selector found: #turnstile-wrapper
2024-06-26 01:22:56 INFO     Challenge solved!
2024-06-26 01:23:00 INFO     Response in 18.736 s
2024-06-26 01:23:02 INFO     127.0.0.1 POST http://localhost:8191/v1 200 OK
```

**Comment by ilike2burnthing** [comment]
[v3.3.21](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.21)

**Comment by nanmuye** [comment]
> [v3.3.21](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.21)

but the challenge keeps looping

**Comment by ilike2burnthing** [comment]
#1036
