### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by spetitjean94** [FlareSolverr/FlareSolverr#1242]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.19
- Last working FlareSolverr version:3.3.19
- Operating system:TrueNas Scale
- Are you using Docker: no
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- URL to test this issue:www.ygg.re
```

### Description

when I test yggtorrent with jackett it gives me an error.
yggtorrent indexer not working

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/81688300/1535fc08-791c-49b2-ad48-b0738e67f371)

**Comment by ilike2burnthing** [comment]
Update to v3.3.21

If you still have issues, increase timeout, see troubleshooting wiki, and otherwise #1036.
