### ISSUE TITLE
Flaresolverr doesnt work 

### ISSUE THREAD

**Issue by ab220700** [FlareSolverr/FlareSolverr#1252]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.21
- Last working FlareSolverr version:
- Operating system: W11
- Are you using Docker: [no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I managed to get flaresolverr to work on python, but only when he command line is open. Is there anyway to get it to run as a service/ in the background.

### Logged Error Messages

```text
n/a
```

**Comment by ilike2burnthing** [comment]
Going to need a little more than 'doesnt work'. If you just mean https://github.com/FlareSolverr/FlareSolverr/issues/1253, then you can close your issue and just follow that. As for running FlareSolverr hidden - https://github.com/FlareSolverr/FlareSolverr/issues/70.

**Comment by tifo71** [comment]
if I may say so, yes, so flaresolverr doesn't work with cloudflare. It finds the challenge and puts error. Here are the log lines
Incoming request => POST /v1 body: {'maxTimeout': 35000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-14 23:42:58 INFO     Challenge detected. Title found: Just a moment...
2024-07-14 23:43:33 ERROR    Error: Error solving the challenge. Timeout after 35.0 seconds.
2024-07-14 23:43:33 INFO     Response in 35.725 s
2024-07-14 23:43:33 INFO     172.17.0.1 POST http://192.168.1.12:8191/v1 500 Internal Server Error

**Comment by tifo71** [comment]
@ilike2burnthing if I may say so, yes, so flaresolverr doesn't work with cloudflare. It finds the challenge and puts error. Here are the log lines
Incoming request => POST /v1 body: {'maxTimeout': 35000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-14 23:42:58 INFO     Challenge detected. Title found: Just a moment...
2024-07-14 23:43:33 ERROR    Error: Error solving the challenge. Timeout after 35.0 seconds.
2024-07-14 23:43:33 INFO     Response in 35.725 s
2024-07-14 23:43:33 INFO     172.17.0.1 POST http://192.168.1.12:8191/v1 500 Internal Server Error

**Comment by tifo71** [comment]
@

> Going to need a little more than 'doesnt work'. If you just mean #1253, then you can close your issue and just follow that. As for running FlareSolverr hidden - #70.

 @ilike2burnthing the fix proposed by @alexandervlk (#1253) doesn't work

**Comment by AARON8888** [comment]
[full log.txt](https://github.com/user-attachments/files/16309603/full.log.txt)

I have met this problem two weeks ago. I put idope, but I´m using other indexers with same or similar problems. None of them passed last version of FlareSolverr unfortunately two weeks ago about.

**Comment by behead974** [comment]
> @ilike2burnthing if I may say so, yes, so flaresolverr doesn't work with cloudflare. It finds the challenge and puts error. Here are the log lines Incoming request => POST /v1 body: {'maxTimeout': 35000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}} 2024-07-14 23:42:58 INFO Challenge detected. Title found: Just a moment... 2024-07-14 23:43:33 ERROR Error: Error solving the challenge. Timeout after 35.0 seconds. 2024-07-14 23:43:33 INFO Response in 35.725 s 2024-07-14 23:43:33 INFO 172.17.0.1 POST http://192.168.1.12:8191/v1 500 Internal Server Error
> 
> and I tried with flaresolverr windows too and the same error.

test :

docker run -d --name=flaresolverr \
-p 8191:8191 \
-e LOG_LEVEL=info \
--restart always \
jcolfej/flaresolverr:pr-1272

OK for me :)
