### ISSUE TITLE
[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by billouetaudrey** [FlareSolverr/FlareSolverr#1260]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Operating system: Linux
- Are you using Docker: yes
```

### Description

Hey, YGG stop working since yesterday.

Trying to fix it but nothing, any idea ?

Thanks

```
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
      - LANG=en_GB
   # dns: 1.1.1.1
 #   sysctls: 
 #     - net.ipv6.conf.all.disable_ipv6=1
#    network_mode: "host"
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
```

### Logged Error Messages

```text
2024-07-15 10:03:12 INFO     192.168.1.76 GET http://192.168.1.48:8191/ 200 OK
2024-07-15 10:03:25 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}
2024-07-15 10:03:26 INFO     Challenge detected. Title found: Just a moment...
2024-07-15 10:04:20 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-07-15 10:04:20 INFO     Response in 55.659 s
2024-07-15 10:04:20 INFO     172.18.224.1 POST http://192.168.1.48:8191/v1 500 Internal Server Error
2024-07-15 10:04:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}
2024-07-15 10:04:41 INFO     Challenge detected. Title found: Just a moment...
2024-07-15 10:05:36 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024-07-15 10:05:36 INFO     Response in 55.748 s
2024-07-15 10:05:36 INFO     172.18.224.1 POST http://192.168.1.48:8191/v1 500 Internal Server Error
2024-07-15 10:11:40 INFO     192.168.1.76 GET http://192.168.1.48:8191/ 200 OK
```

**Comment by MrAlucardDante** [comment]
Same thing here.
```
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      LANG: fr_FR
```

**Comment by billouetaudrey** [comment]
> Same thing here.
> 
> ```
> services:
>   flaresolverr:
>     image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
>     container_name: flaresolverr
>     environment:
>       PUID: 1000
>       PGID: 1000
>       TZ: Europe/Paris
>       CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
>       LANG: fr_FR
> ```
> 
> This might be related to #1253

Yes maybe

**Comment by Groslard** [comment]
Same error, logs with debug : 

> 
> 2024-07-15 11:07:08 DEBUG    ReqId 140657854633728 Waiting for title (attempt 18): Just a moment...
> 2024-07-15 11:07:09 DEBUG    ReqId 140657854633728 Timeout waiting for selector
> 2024-07-15 11:07:09 DEBUG    ReqId 140657854633728 Try to find the Cloudflare verify checkbox...
> 2024-07-15 11:07:09 DEBUG    ReqId 140657854633728 Cloudflare verify checkbox not found on the page.
> 2024-07-15 11:07:09 DEBUG    ReqId 140657854633728 Try to find the Cloudflare 'Verify you are human' button...
> 2024-07-15 11:07:09 DEBUG    ReqId 140657854633728 The Cloudflare 'Verify you are human' button not found on the page.
> 2024-07-15 11:07:11 DEBUG    ReqId 140657854633728 Waiting for title (attempt 19): Just a moment...
> 2024-07-15 11:07:12 DEBUG    ReqId 140657863026432 A used instance of webdriver has been destroyed
> 2024-07-15 11:07:12 ERROR    ReqId 140657863026432 Error: Error solving the challenge. Timeout after 60.0 seconds.
> 2024-07-15 11:07:12 DEBUG    ReqId 140657863026432 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 60.0 seconds.', 'startTimestamp': 1721037971913, 'endTimestamp': 1721038032690, 'version': '3.3.21'}
> 2024-07-15 11:07:12 INFO     ReqId 140657863026432 Response in 60.777 s
