### ISSUE TITLE
MCG-pok patch no longer works

### ISSUE THREAD

**Issue by miltuss** [FlareSolverr/FlareSolverr#1289]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: latest
- Last working FlareSolverr version:MCG-pok patch
- Operating system:Docker
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hello, this patch helped resolve cloudflare for a week, but it no longer works!
 https://github.com/MCG-pok/FlareSolverr/blob/master/src/flaresolverr_service.py

 How to fix Flaresolverr?

### Logged Error Messages

```text
Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [POST] at [http://10.10.0.11:8191/v1]
```

**Comment by Telkaoss** [comment]
same on YGG

`Challenge detected. Title found: Just a moment...
2024-07-26 00:40:33 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
`

**Comment by ilike2burnthing** [comment]
This didn't need to be an issue.
