### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): FlareSolverr was unable to process the request, Error solving the challenge. Timeout after 90.0 seconds

### ISSUE THREAD

**Issue by DaGreenX** [FlareSolverr/FlareSolverr#1304]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.2.1
- Last working FlareSolverr version:
- Operating system: Synology DSM 6 - Linux-4.4.302+-x86_64-with-glibc2.31
- Are you using Docker: [yes/no] Yes
- FlareSolverr User-Agent (see log traces or / endpoint): FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] Yes
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] Yes 
- If using captcha solver, which one: harvester
- URL to test this issue:
```

### Description

I  am not sure if this issue has been resolved. From reading the conversations, I understand that it works for some. Many tickets have been closed due to comments like “resolve this ticket or my life is ruined!” I understand the need to close tickets with such comments :) However, there is no communication about the resolution, or I missed it, and I apologize for opening a new ticket. I am just trying to understand if the problem is still present or if I missed some information and it is working again :) Thank you for the feedback!

### Logged Error Messages

```text
2024/07/31 10:07:11,stdout,2024-07-31 08:07:11 INFO     192.168.1.44 POST http://192.168.1.44:8191/v1 500 Internal Server Error

2024/07/31 10:07:11,stdout,2024-07-31 08:07:11 INFO     Response in 95.741 s

2024/07/31 10:07:11,stdout,2024-07-31 08:07:11 ERROR    Error: Error solving the challenge. Timeout after 90.0 seconds.

2024/07/31 10:05:47,stdout,2024-07-31 08:05:47 INFO     Challenge detected. Title found: Just a moment...

2024/07/31 10:05:35,stdout,"2024-07-31 08:05:35 INFO     Incoming request => POST /v1 body: {'maxTimeout': 90000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=2145'}
"


Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.

[v0.22.396.0] Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 90.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
```

**Comment by ArthurKnoep** [comment]
Duplicates of https://github.com/FlareSolverr/FlareSolverr/issues/1253

**Comment by romanocry** [comment]
Hello, need this solution too ;) , 
i can't update the flaresolverr_service.py on my own... Don't have access to Docker... 
Thanks.

**Comment by DaGreenX** [comment]
Okay, I followed the procedure from ticket [#1253](https://github.com/FlareSolverr/FlareSolverr/issues/1253) which wasn’t easy for a non-expert, especially since the environment wasn’t specified for executing this procedure. In my case, I’m using Synology, with FlareSolverr running under Docker. I was able to access the flaresolverr_service.py file via the terminal application on my Mac (the file was empty). The proposed modification works. If anyone needs help with the same configuration, I can assist.

**Comment by THollingworth** [comment]
Hey i'd love it if it's possible to give some support i am really not an expert on that ahah and i am having same issue with ygg

**Comment by MoryCorp** [comment]
What I did :

```
docker exec --user root -ti flaresolverr /bin/bash
echo "" > flaresolverr_service.py
vim flaresolverr_service.py
Copy the code from : https://raw.githubusercontent.com/MCG-pok/FlareSolverr/master/src/flaresolverr_service.py
press "V" on vim to enter visual mode
CTRL + V to paste
enter :wq to write and quit
ctrl + D to detach
docker compose restart
```
