### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by gaelarnoux** [FlareSolverr/FlareSolverr#1310]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: Latest
- Last working FlareSolverr version: 3 weeks ago
- Operating system:    Synology
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: No
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Bonjour,

J'ai déjà eu ce souci dans le passe, ensuite tous allait bien, jusqu'à il y a 1 mois

D'avance merci pour votre aide

### Logged Error Messages

```text
flaresolverr
date,stream,content
2024/08/03 09:21:21,stdout,2024-08-03 09:21:21 INFO     172.18.0.1 POST http://192.168.50.12:8191/v1 500 Internal Server Error
2024/08/03 09:21:21,stdout,2024-08-03 09:21:21 INFO     Response in 57.393 s
2024/08/03 09:21:21,stdout,2024-08-03 09:21:21 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
2024/08/03 09:20:30,stdout,2024-08-03 09:20:30 INFO     Challenge detected. Title found: Just a moment...
2024/08/03 09:20:24,stdout,"2024-08-03 09:20:24 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?do=search&order=desc&sort=publish_date&category=all'}
```

**Comment by igwall** [comment]
Hey 👋🏻, linked to #1253. A temporary solution is provided in the thread

**Comment by thymon13** [comment]
> Hey 👋🏻, linked to #1253. A temporary solution is provided in the thread

It used to work fine, but it doesn't work anymore...

**Comment by soflyj** [comment]
(1) set the env LANG variable to en_GB.
(2) You could increase the timeout.

I'm in the same boat as you. None of these have worked thus far.

**Comment by papampi** [comment]
> Hey 👋🏻, linked to #1253. A temporary solution is provided in the thread

Tried the solution mentioned in https://github.com/FlareSolverr/FlareSolverr/issues/1253#issuecomment-2234163353 , and also raised timeout to 120 but still not working ... 

```
2024-08-03 10:25:02 INFO     Incoming request => POST /v1 body: {'maxTimeout': 120000, 'cmd': 'request.get', 'url': 'https://ext.to/latest/'}
2024-08-03 10:25:09 INFO     Challenge detected. Title found: Just a moment...
2024-08-03 10:27:05 ERROR    Error: Error solving the challenge. Timeout after 120.0 seconds.
2024-08-03 10:27:05 INFO     Response in 122.616 s
2024-08-03 10:27:05 INFO     10.0.3.2 POST http://192.168.1.251:49152/v1 500 Internal Server Error
```

**Comment by Liphae33** [comment]
Hi , i try the fix in #1253 and it work for me

**Comment by umadgen** [comment]
Restart the container with the fix from #1253 works for me

**Comment by soflyj** [comment]
Did you follow this step? Because I copy and replace the file and still get the same error.

`[flaresolverr_service.py.txt](https://github.com/user-attachments/files/16179323/flaresolverr_service.py.txt)
Try to replace /app/flaresolverr_service.py right in Docker->Container->Files`

**Comment by umadgen** [comment]
I just used the docker image build from the pr

**Comment by soflyj** [comment]
@umadgen I'm no expert at python but could it be the the iframe id is *dynamic and won't always to hardcoded to 

`iframe = get_shadowed_iframe(driver, "div.cf-turnstile-wrapper")`

*I've inspected several cloudflare shadow-root
