### ISSUE TITLE
[1337x] (testing) Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by ishan190425** [FlareSolverr/FlareSolverr#1322]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Does not work on 1337x.to

### Logged Error Messages

```text
1337x.to/cat/Movies/seeders/desc/1/'}
2024-08-14 01:13:18 INFO     Challenge not detected!
2024-08-14 01:13:18 INFO     Response in 4.145 s
2024-08-14 01:13:18 INFO     192.168.1.213 POST http://192.168.1.213:8191/v1 200 OK
 ~ 
```

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting wiki - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If you need more help, provide the information requested in the template.
