### ISSUE TITLE
Getting error in simple code

### ISSUE THREAD

**Issue by Gujjugaming2k** [FlareSolverr/FlareSolverr#1325]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

{"status": "error", "message": "Error: Error solving the challenge. Timeout after 11.12 seconds.", "startTimestamp": 1723831818421, "endTimestamp": 1723831831028, "version": "3.3.21"}

getting above error with simple code, I have started docker once its runing after that only I run below code

import requests

url = "http://localhost:8191/v1"
headers = {"Content-Type": "application/json"}
data = {
    "cmd": "request.get",
    "url": "https://nopecha.com/demo/cloudflare",
    "maxTimeout": 11120
}
response = requests.post(url, headers=headers, json=data)
print(response.text)

### Logged Error Messages

```text
not seen any logs
```

**Comment by ilike2burnthing** [comment]
Your timeout is too short, default is 60000, can take longer. See pinned issues and recent PR for wider problem with FlareSolverr.
