### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Exception: System.Threading.Tasks.TaskCanceledException: http://localhost:8191/v1 500 Internal Server Error

### ISSUE THREAD

**Issue by Jewem** [FlareSolverr/FlareSolverr#1334]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:  FlareSolverr 3.3.21
- Last working FlareSolverr version: ?
- Operating system: Debian 8
- Are you using Docker: [yes]
- FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [yes/no]
```

### Description

the same error in the logs. 

Here is my docker-compose.yml configuration:

  flaresolverr:
    image: jcolfej/flaresolverr:pr-1272
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London

### Logged Error Messages

```text
flaresolverr  | 2024-08-28 19:37:14 INFO     172.19.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

**Comment by Jewem** [comment]
`flaresolverr  | 2024-08-28 19:35:34 INFO     Challenge detected. Title found: Just a moment...
flaresolverr  | 2024-08-28 19:37:14 ERROR    Error: Error solving the challenge. Timeout after 100.0 seconds.
flaresolverr  | 2024-08-28 19:37:14 INFO     Response in 116.654 s
flaresolverr  | 2024-08-28 19:37:14 INFO     172.19.0.1 POST http://localhost:8191/v1 500 Internal Server Error
`

**Comment by ilike2burnthing** [comment]
If you have an issue with a PR build, raise the issue on that PR. Looking quickly, you may need to change the image you're using.
