### ISSUE TITLE
[yggcookie] Exception (yggcookie): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: No challenge selectors found, unable to proceed: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: No challenge selectors found, unable to proceed (Test)

### ISSUE THREAD

**Issue by LeTailleCrayon** [FlareSolverr/FlareSolverr#134]
Hello,
I just got an error with Flare Solverr
Same for YggTorrent / YggCookie

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:
* **Last working FlareSolverr version**:
* **Operating system**: Docker
* **Are you using Docker**: [yes/no] yes
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] yes
* **If using captcha solver, which one:** FlareSolverr

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

No challenge selectors found, unable to proceed

Thanks

**Comment by TheNexter** [comment]
Same :(

**Comment by JulesLePrince** [comment]
Seems like www.yggtorrent.li now uses a Cloudflare protection which is detected as a captcha protection although it doesn't ask any captcha verification when I use it "manually"

**Comment by thymon13** [comment]
please read the notice : "⚠️ At this time none of the captcha solvers work. "

https://github.com/FlareSolverr/FlareSolverr#captcha-solvers

**Comment by totof-l** [comment]
There is an experimental alternative on the YggTorrent forum :

https://www4.yggtorrent.li/forum/index.php?threads/serveur-rss.54884

This is working for me as a workaround

**Comment by thymon13** [comment]
> There is an experimental alternative on the YggTorrent forum :
> 
> https://www4.yggtorrent.li/forum/index.php?threads/serveur-rss.54884
> 
> This is working for me as a workaround

is not working now :)

**Comment by ochidoris** [comment]
Is work for me. Sonarr is downloading my tv show just now

**Comment by LeTailleCrayon** [comment]
> Is work for me. Sonarr is downloading my tv show just now

It still not working for me 😭

**Comment by TheNexter** [comment]
> > Is work for me. Sonarr is downloading my tv show just now
> 
> It still not working for me 😭

Same :(

**Comment by ochidoris** [comment]
Désolé mon anglais est mauvais mais si nous sommes surun thread ygg c'est que nous parlons français. 
Depuis hier,  jackett/flaresolverr ne fonctionne plus a cause du nouveau système de captcha, j'ai donc testé la solution ci dessous. 
Ça ne fonctionne pas lorsque je fais une recherche de série,  il ne trouve pas l'épisode.  Mais ça fonctionne lorsque je fais un test indexeur dans sonarr. Le flux rss fonctionne via un reader rss mais pas à l'instant T, genre une fois à plusieurs heures d'intervalles. Là,  il vient de me télécharger automatiquement "my hero academia e10" sur le tracker d'ygg.
Donc je pense de temps à autres  que ça passe la protection... A voir.

**Comment by LeTailleCrayon** [comment]
> Désolé mon anglais est mauvais mais si nous sommes surun thread ygg c'est que nous parlons français.
> Depuis hier, jackett/flaresolverr ne fonctionne plus a cause du nouveau système de captcha, j'ai donc testé la solution ci dessous.
> Ça ne fonctionne pas lorsque je fais une recherche de série, il ne trouve pas l'épisode. Mais ça fonctionne lorsque je fais un test indexeur dans sonarr. Le flux rss fonctionne via un reader rss mais pas à l'instant T, genre une fois à plusieurs heures d'intervalles. Là, il vient de me télécharger automatiquement "my hero academia e10" sur le tracker d'ygg.
> Donc je pense de temps à autres que ça passe la protection... A voir.

Pas d'info pour Radarr... ?

**Comment by LeTailleCrayon** [comment]
J'espère qu'il y aura bientôt une solution à cette histoire de nouveau captcha... YggTorrent reste quand-même le meilleur tracker "Semi-privé", et je pense qu'ils sont conscient que beaucoup de gens passent par Jackett. Même si je comprends qu'ils pensent à se protéger des DDOS, il ne faut pas qu'ils aillent trop loin non plus au risque de voir des utilisateurs partir. (En solution temporaire, je vous recommande Sharewood mais c'est vraiment pas au même niveau que Ygg, j'espère donc que ce sera temporaire...) /

 I hope that this issue with the new captcha system will be resolved... YggTorrent is the best French "semi-private" tracker, and I think that they knows that a lot of users are using Jackett. I can understand that they are trying to protect their servers from DDOS attacks but if they do something too hard, they are taking a big risk. (I can advice you to use temporarily a tracker called "Sharewood" but it is not good enough like Ygg, I really hope that this issue will be solved by Ygg in a few days or weeks...)

**Comment by SmarLat** [comment]
Absolument d'accord, j’espère qu'une solution sera vite trouvée....

**Comment by TheNexter** [comment]
Vivement une putain d'api même payante rien à foutre, genre 10 euros par
ans ou 15 mais bordel une API c'est pas bien compliqué...

**Comment by SmarLat** [comment]
Compliqué de bypass la nouvelle protection de cloudflare Ça fait un petit moment qu'il parle de switch de reCAPTCHA à hCaptcha. Et je pense pas que les admins de ygg peuvent y faire quelque chose.

**Comment by thymon13** [comment]
Ce n’est pas YGG qui décide. Ils ont une protection via flarecloud et c’est eux qui change leur type de protection.

effectivement à l’heure actuelle il n’y a aucune solution.
Sur le forum de YGG quelqu’un a mis en place une solution via un serveur RSS. Ça permet au moins de syncro toutes les 24h environ. Mais pas pour faire des recherches.

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 will fix this issue. Will be released today.

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 released.

**Comment by ochidoris** [comment]
It's working.
You re the champion. Thx for all.

**Comment by Thomas-Negrault** [comment]
Should we use `CAPTCHA_SOLVER=hcaptcha-solver` ? For me with v1.2.6 it's not working,
With hcaptcha-solver:

```
flaresolverr    | 2021-05-30T13:17:28+00:00 INFO FlareSolverr v1.2.6
flaresolverr    | 2021-05-30T13:17:28+00:00 DEBUG Debug log enabled
flaresolverr    | 2021-05-30T13:17:28+00:00 INFO Using 'hcaptcha-solver' to solve the captcha.
flaresolverr    | 2021-05-30T13:17:28+00:00 DEBUG Testing Chrome installation...
flaresolverr    | 2021-05-30T13:17:28+00:00 DEBUG Launching browser...
flaresolverr    | 2021-05-30T13:17:29+00:00 DEBUG Test successful
flaresolverr    | 2021-05-30T13:17:29+00:00 INFO Listening on http://0.0.0.0:8191
...
flaresolverr    | 2021-05-30T13:19:01+00:00 INFO REQ-2 Incoming request: POST /v1
flaresolverr    | 2021-05-30T13:19:01+00:00 INFO REQ-2 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 Launching browser...
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 Using custom UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 Adding custom headers: {}
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 Navigating to... https://www4.yggtorrent.li/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 Overrides: {"headers":{"upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}}
flaresolverr    | 2021-05-30T13:19:01+00:00 INFO REQ-2 Cloudflare detected
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 No '#trk_jschal_js' challenge element detected.
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 No '.ray_id' challenge element detected.
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 No '.attack-box' challenge element detected.
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 Javascript challenge element '#cf-please-wait' detected.
flaresolverr    | 2021-05-30T13:19:01+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...
flaresolverr    | 2021-05-30T13:19:12+00:00 DEBUG REQ-2 Validating HTML code...
flaresolverr    | 2021-05-30T13:19:12+00:00 DEBUG REQ-2 Javascript challenge selectors found: 1, total selectors: 4
flaresolverr    | 2021-05-30T13:19:12+00:00 INFO REQ-2 Captcha challenge detected.
flaresolverr    | 2021-05-30T13:19:12+00:00 INFO REQ-2 Using 'hcaptcha-solver' to solve the captcha.
flaresolverr    | 2021-05-30T13:19:12+00:00 INFO REQ-2 Waiting to receive captcha token to bypass challenge...
flaresolverr    | 2021-05-30T13:19:12+00:00 INFO REQ-2 Response in 11.714 s
flaresolverr    | 2021-05-30T13:19:12+00:00 INFO REQ-2 Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported #31.
```

Without hcaptcha-solver:

```
flaresolverr    | 2021-05-30T13:20:25+00:00 INFO FlareSolverr v1.2.6
flaresolverr    | 2021-05-30T13:20:25+00:00 DEBUG Debug log enabled
flaresolverr    | 2021-05-30T13:20:25+00:00 DEBUG Testing Chrome installation...
flaresolverr    | 2021-05-30T13:20:26+00:00 DEBUG Launching browser...
flaresolverr    | 2021-05-30T13:20:26+00:00 DEBUG Test successful
flaresolverr    | 2021-05-30T13:20:26+00:00 INFO Listening on http://0.0.0.0:8191
...
flaresolverr    | 2021-05-30T13:21:02+00:00 INFO REQ-1 Incoming request: POST /v1
flaresolverr    | 2021-05-30T13:21:02+00:00 INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
flaresolverr    | 2021-05-30T13:21:02+00:00 DEBUG REQ-1 Launching browser...
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 Using custom UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 Adding custom headers: {}
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 Navigating to... https://www4.yggtorrent.li/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 Overrides: {"headers":{"upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}}
flaresolverr    | 2021-05-30T13:21:03+00:00 INFO REQ-1 Cloudflare detected
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 No '#trk_jschal_js' challenge element detected.
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 No '.ray_id' challenge element detected.
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 No '.attack-box' challenge element detected.
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 Javascript challenge element '#cf-please-wait' detected.
flaresolverr    | 2021-05-30T13:21:03+00:00 DEBUG REQ-1 Waiting for Cloudflare challenge...
flaresolverr    | 2021-05-30T13:21:14+00:00 DEBUG REQ-1 Validating HTML code...
flaresolverr    | 2021-05-30T13:21:14+00:00 DEBUG REQ-1 Javascript challenge selectors found: 1, total selectors: 4
flaresolverr    | 2021-05-30T13:21:14+00:00 INFO REQ-1 Captcha challenge detected.
flaresolverr    | 2021-05-30T13:21:14+00:00 INFO REQ-1 Response in 11.933 s
flaresolverr    | 2021-05-30T13:21:14+00:00 INFO REQ-1 Cloudflare Error: Captcha detected but no automatic solver is configured.
jackett         | 05-30 15:21:14 Error Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured.

```

**Comment by ngosang** [comment]
v1.2.6  will fix the issue for most of you.
If see the error `Captcha detected ...` you have to wait until YGG disables the captcha. Since long time ago FlareSolverr is not able to complete captcha challenges. Both plugins are outdated.

**Comment by Thomas-Negrault** [comment]
Could I access the Chrome Browser and complete the Captcha by hand ? Maybe after a successful captcha it will stop asking for one

**Comment by SmarLat** [comment]
thank you for your responsiveness and your work!

**Comment by almottier** [comment]
Same as @Thomas-Negrault for me. It is not working now.

**Comment by Oyo95** [comment]
Hi ! 

Thanks for your releas ! But it does'nt work for me too...

> flaresolverr@1.2.6 start
> node ./dist/index.js
2021-05-30T17:18:20+00:00 INFO FlareSolverr v1.2.6
2021-05-30T17:18:21+00:00 INFO Using 'hcaptcha-solver' to solve the captcha.
2021-05-30T17:18:27+00:00 INFO Listening on http://0.0.0.0:8191
2021-05-30T17:18:58+00:00 INFO REQ-1 Incoming request: GET /
2021-05-30T17:18:58+00:00 INFO REQ-1 Response in 0 s
2021-05-30T17:18:58+00:00 ERROR REQ-2 Body must be in JSON format
2021-05-30T17:18:58+00:00 INFO REQ-1 FlareSolverr is ready!
2021-05-30T17:18:58+00:00 INFO REQ-2 Incoming request: GET /favicon.ico
2021-05-30T17:20:12+00:00 INFO REQ-3 Incoming request: POST /v1
2021-05-30T17:20:12+00:00 INFO REQ-3 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-05-30T17:20:20+00:00 INFO REQ-3 Cloudflare detected
2021-05-30T17:20:31+00:00 INFO REQ-3 Captcha challenge detected.
2021-05-30T17:20:31+00:00 INFO REQ-3 Using 'hcaptcha-solver' to solve the captcha.
2021-05-30T17:20:31+00:00 INFO REQ-3 Waiting to receive captcha token to bypass challenge...
2021-05-30T17:20:31+00:00 INFO REQ-3 Response in 19.66 s
2021-05-30T17:20:31+00:00 INFO REQ-3 Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported #31.

**Comment by ilike2burnthing** [comment]
Access the site in browser, complete the hcaptcha challenge, sign in if you aren't already, get the cookie and replace the one currently used in Jackett.

**Comment by almottier** [comment]
When accessing the website from my browser, there is no hcaptcha to complete, just the browser verification. I use the same public IP for flaresolverr and my browser, (same user-agent too) 🤔

**Comment by LeTailleCrayon** [comment]
> Access the site in browser, complete the hcaptcha challenge, sign in if you aren't already, get the cookie and replace the one currently used in Jackett.

How can I "force" Cloudflare to let me complete the hcaptcha ? I've tried with a vpn but when I put the cookie in Jackett it doesn't work.

**Comment by ngosang** [comment]
Continue the discussion in #140

> How can I "force" Cloudflare to let me complete the hcaptcha ?

Remove the cookies in the browser.
