### ISSUE TITLE
Error loading Python lib libpython3.11.so.1.0: dlopen: libm.so.6: version `GLIBC_2.35' not found (required by libpython3.11.so.1.0)

### ISSUE THREAD

**Issue by slrslr** [FlareSolverr/FlareSolverr#1341]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:v3.3.21
- Operating system: Debian 11 (oldstable)
- Are you using Docker: no
```

### Description

Commands:

```
wget https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.21/flaresolverr_linux_x64.tar.gz --show-progress
tar -xzf flaresolverr_linux_x64.tar.gz && cd flaresolverr && ./flaresolverr
```

returns:

`[2137418] Error loading Python lib '/home/user/flaresolverr/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.35' not found (required by /home/user/flaresolverr/libpython3.11.so.1.0)

 apt search libpython|grep inst

```
libpython3-dev/oldstable,now 3.9.2-3 amd64 [installed,automatic]
libpython3-stdlib/oldstable,now 3.9.2-3 amd64 [installed,automatic]
libpython3.9/oldstable,now 3.9.2-1 amd64 [installed,automatic]
libpython3.9-dev/oldstable,now 3.9.2-1 amd64 [installed,automatic]
libpython3.9-minimal/oldstable,now 3.9.2-1 amd64 [installed,automatic]
libpython3.9-stdlib/oldstable,now 3.9.2-1 amd64 [installed,automatic]
```

$ apt search libc|grep inst

output [here](https://bin.disroot.org/?761ba23ffee716e1#2gvndFFtJ6eAMKf8TavHedfPL4rmmYmbMQgUZ7oqYjum)

Is there non-complicated workaround to make it working? I would upgrade to Debian 12 stable (if FlareSolverr would work in it).

### Logged Error Messages

```text
version `GLIBC_2.35' not found
```

**Comment by ilike2burnthing** [comment]
You've installed Python 3.11, Chrome/Chromium, Xvfb and the requirements as per the install instructions? https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by slrslr** [comment]
No, $ python3 --version
Python 3.9.2

I have followed only steps described at https://github.com/FlareSolverr/FlareSolverr#precompiled-binaries in paragraph "Precompiled binaries" which made me to download huge flaresolverr_linux_x64.tar.gz which I assumed contains everything needed.

Yours linked steps seems significantly complicated also considering that it is not recommended (IMBW) to install any custom version of the Python and I am rather layman in custom software installations. Also docker always felt bulky, so I am not using it, I have been using AppImages, .deb.

**Comment by ilike2burnthing** [comment]
Apologies, think I was half asleep when I wrote that. Yep, there are no dependencies for the precompiled binaries, nor is Docker needed.

Not sure I'd call 184MB 'huge', but I suppose it's all relative.

What is the output for `ldd --version`?

If it's showing a version earlier than 2.35, and trying to update/install libc6 doesn't help, then yes you may need to update the OS.

**Comment by slrslr** [comment]
Yes, I had older version of a ldd and new release of my Linux distribution had higher one. Thanks.
