### ISSUE TITLE
Not able to solve captcha due of timeout.

### ISSUE THREAD

**Issue by ANONYme72** [FlareSolverr/FlareSolverr#1348]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: 3.3.21
- Operating system: Windows
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): yes
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://topminecraftservers.org/vote/27358
```

### Description

Hello I am currently looking for a way to bypass the cloudflare captchas and I came across your solution, unfortunately I find that there are not enough resources on youtube or in the issues sections to solve my problem all alone.
I apologize in advance for creating this issue.
My problem is the following, after launching my container and checking that it was ready to be used, I send a request using the README example but changing the url of the website which I want to access however on my environment the captcha never get solve even after doubling the value of maxtimeout.

Thank you in advance for your help which will be invaluable.

### Logged Error Messages

```text
From my python script :


{"status": "error", "message": "Error: Error solving the challenge. Timeout after 120.0 seconds.", "startTimestamp": 1726095720544, "endTimestamp": 1726095841393, "version": "3.3.21"}


From docker log :

2024-09-11 20:02:00 flaresolverr  | 2024-09-12 00:02:00 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://topminecraftservers.org/vote/27358', 'maxTimeout': 120000}
2024-09-11 20:02:02 flaresolverr  | 2024-09-12 00:02:02 INFO     Challenge detected. Title found: Just a moment...
2024-09-11 20:04:01 flaresolverr  | 2024-09-12 00:04:01 ERROR    Error: Error solving the challenge. Timeout after 120.0 seconds.
2024-09-11 20:04:01 flaresolverr  | 2024-09-12 00:04:01 INFO     Response in 120.849 s
2024-09-11 20:04:01 flaresolverr  | 2024-09-12 00:04:01 INFO     172.18.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

### Screenshots

My container is consuming RAM and CPU usge :

![image](https://github.com/user-attachments/assets/de016324-393a-4dca-a4d4-78e64e4e6a52)

**Comment by asislife20** [comment]
I've run into a similar issue. I'm fairly sure its because both flaresolverr and the app your using it with need to have the same IP. I've tried running both as containers on docker desktop, but then the flaresolverr can't be seen by my jackett container all.
