### ISSUE TITLE
Crashing on startup in FreeBSD; Cannot connect to chrome

### ISSUE THREAD

**Issue by ezrapeace** [FlareSolverr/FlareSolverr#1351]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: latest
- Last working FlareSolverr version: N/A
- Operating system: FreeBSD under TrueNAS Core in iocage jail (13.1 p7)
- Are you using Docker: [no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [N/A] (fails in both envs)
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one: N/A
- URL to test this issue:
```

### Description

This version was working (3.3.13) (from a separate jail from my servarr apps) up until august 16. But the logs show that things broke while still at this version so I've ruled out version change as the issue. I have since installed FS in a fresh jail from a git clone, and in my servarr jail with the same result. 

I am installing from the README.md directions. Previously installed from a guide that used npm (back when you still used puppeteer). When attempting first start, I get the same "cannot connect to chrome" message I have been getting since August. 
`# python3.9 src/flaresolverr.py
2024-09-15 09:52:39 INFO     FlareSolverr 3.3.21
2024-09-15 09:52:39 INFO     Testing web browser installation...
2024-09-15 09:52:39 INFO     Platform: FreeBSD-13.1-RELEASE-p7-amd64-64bit-ELF
2024-09-15 09:52:39 INFO     Chrome / Chromium path: /usr/local/bin/chrome
ld-elf.so.1: /usr/local/lib/libtasn1.so.6: Undefined symbol "strverscmp@FBSD_1.7"
2024-09-15 09:52:39 ERROR    Chrome / Chromium version not detected!`

The logs mention this only being compatible with chromium 120, but I can't see how to downgrade chromium, when the latest is automatically installed. And searching the pkg db only version 128 is available?

I did see previous issues posted with a similar log output with what seemed to be solutions, but they were for docker installations with the solution being an updated docker image, which doesn't apply to me in an iocage jail.

### Logged Error Messages

```text
2024-09-15 06:01:03 INFO     FlareSolverr 3.3.13
2024-09-15 06:01:03 INFO     Testing web browser installation...
2024-09-15 06:01:03 INFO     Platform: FreeBSD-13.1-RELEASE-p7-amd64-64bit-ELF
2024-09-15 06:01:03 INFO     Chrome / Chromium path: /usr/local/share/flaresolverr/_internal/chrome/chrome
2024-09-15 06:01:04 INFO     Chrome / Chromium major version: 128
2024-09-15 06:01:04 INFO     Launching web browser...
version_main cannot be converted to an integer
Traceback (most recent call last):
  File "utils.py", line 302, in get_user_agent
  File "utils.py", line 183, in get_webdriver
  File "undetected_chromedriver/__init__.py", line 472, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 45, in __init__
  File "selenium/webdriver/chromium/webdriver.py", line 56, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 208, in __init__
  File "undetected_chromedriver/__init__.py", line 730, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 292, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 347, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 229, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50464
from session not created: This version of ChromeDriver only supports Chrome version 120
Current browser version is 128.0.6613.119


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flaresolverr.py", line 105, in <module>
  File "flaresolverr_service.py", line 72, in test_browser_installation
  File "utils.py", line 308, in get_user_agent
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:50464
from session not created: This version of ChromeDriver only supports Chrome version 120
Current browser version is 128.0.6613.119

[11380] Failed to execute script 'flaresolverr' due to unhandled exception!
```

**Comment by ilike2burnthing** [comment]
Try v3.3.21, and if that doesn't work then see the most recent PRs for contributor builds.

**Comment by ezrapeace** [comment]
Issue persists with v3.3.21. And I didn't see anything relevant in pull requests? What do you suggest at this point? I'm happy to provide any additional information you may need.

**Comment by ezrapeace** [comment]
I installed 21 into a fresh jail and I'm actually getting a slightly different result with that. It's unclear to me to what success though.

Starting Flaresolverr I'm hung here:

> [FlareSolverr]# python3.9 src/flaresolverr.py
> 2024-09-16 08:19:17 INFO     FlareSolverr 3.3.21
> 2024-09-16 08:19:17 INFO     Testing web browser installation...
> 2024-09-16 08:19:18 INFO     Platform: FreeBSD-13.1-RELEASE-p7-amd64-64bit-ELF
> 2024-09-16 08:19:18 INFO     Chrome / Chromium path: /usr/local/bin/chrome
> 2024-09-16 08:19:19 INFO     Chrome / Chromium major version: 128
> 2024-09-16 08:19:19 INFO     Launching web browser...
> 2024-09-16 08:19:19 INFO     Copying chromedriver executable...
> 2024-09-16 08:19:19 INFO     Chromedriver executable copied!

It's not clear to me if that means flaresolverr is now running, or if the process is hung? I usually run it as a service. And if it is running, what are the implications? How do I get flaresolverr running in my servarr jail with this information?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/pull/1163#issuecomment-2308926030

**Comment by ezrapeace** [comment]
Thank you. I'm not sure how I use this information, though? The link doesn't appear to be a git repository to clone from? 

Any guidance is much appreciated.

**Comment by ilike2burnthing** [comment]
https://github.com/21hsmw/FlareSolverr/tree/nodriver-support

**Comment by ezrapeace** [comment]
Thanks, I did follow the link to the commits page for nodriver-support, but I don't know what to do with the information on that page. I have never heard of nodriver-support until now.

**Comment by ezrapeace** [comment]
Thanks I did follow the link previously to the commits page for nodriver-support. Until now I'd never heard of it, but a little exploring took me to what I can only assume is a contributor version of Flaresolverr. I will try this one and report back.

**Comment by ezrapeace** [comment]
Issue persists. Also this version seems to be based off of 18.

> [~]# git clone https://github.com/21hsmw/FlareSolverr.git
> Cloning into 'FlareSolverr'...
> remote: Enumerating objects: 2028, done.
> remote: Total 2028 (delta 0), reused 0 (delta 0), pack-reused 2028 (from 1)
> Receiving objects: 100% (2028/2028), 1.40 MiB | 492.00 KiB/s, done.
> Resolving deltas: 100% (1323/1323), done.
> 
> [~]# cd FlareSolverr
> 
> [FlareSolverr]# python3.9 -m pip install -r requirements.txt
> Ignoring pefile: markers 'platform_system == "Windows"' don't match your environment
> Requirement already satisfied: bottle==0.12.25 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (0.12.25)
> Requirement already satisfied: waitress==2.1.2 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.1.2)
> Requirement already satisfied: selenium==4.15.2 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (4.15.2)
> Requirement already satisfied: func-timeout==4.3.5 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.3.5)
> Requirement already satisfied: prometheus-client==0.17.1 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.17.1)
> Collecting requests==2.31.0
>   Downloading requests-2.31.0-py3-none-any.whl (62 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 153.4 kB/s eta 0:00:00
> Collecting certifi==2023.7.22
>   Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 161.3 kB/s eta 0:00:00
> Requirement already satisfied: websockets==11.0.3 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (11.0.3)
> Requirement already satisfied: xvfbwrapper==0.2.9 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (0.2.9)
> Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (2.2.3)
> Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (0.26.2)
> Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (0.11.1)
> Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 7)) (3.3.2)
> Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 7)) (3.10)
> Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (2.4.0)
> Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (24.2.0)
> Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.3.1)
> Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.2.2)
> Requirement already satisfied: outcome in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.3.0.post0)
> Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium==4.15.2->-r requirements.txt (line 3)) (1.2.0)
> Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.15.2->-r requirements.txt (line 3)) (1.7.1)
> Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.15.2->-r requirements.txt (line 3)) (0.14.0)
> Installing collected packages: certifi, requests
>   Attempting uninstall: certifi
>     Found existing installation: certifi 2024.7.4
>     Uninstalling certifi-2024.7.4:
>       Successfully uninstalled certifi-2024.7.4
>   Attempting uninstall: requests
>     Found existing installation: requests 2.32.3
>     Uninstalling requests-2.32.3:
>       Successfully uninstalled requests-2.32.3
> Successfully installed certifi-2023.7.22 requests-2.31.0
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> [notice] A new release of pip is available: 23.0.1 -> 24.2
> [notice] To update, run: pip3 install --upgrade pip
> 
> [FlareSolverr]# python3.9 src/flaresolverr.py
> 2024-09-16 11:26:07 INFO     FlareSolverr 3.3.18
> 2024-09-16 11:26:07 INFO     Testing web browser installation...
> 2024-09-16 11:26:07 INFO     Platform: FreeBSD-13.1-RELEASE-p7-amd64-64bit-ELF
> 2024-09-16 11:26:07 INFO     Chrome / Chromium path: /usr/local/bin/chrome
> 2024-09-16 11:26:07 INFO     Chrome / Chromium major version: 128
> 2024-09-16 11:26:07 INFO     Launching web browser...
> 2024-09-16 11:36:11 ERROR    Error starting Chrome: Message: timeout: Timed outreceiving message from renderer: 600.000
>   (Session info: chrome=128.0.6613.119)
> 
> Traceback (most recent call last):
>   File "/root/FlareSolverr/src/utils.py", line 308, in get_user_agent
>     driver = get_webdriver()
>   File "/root/FlareSolverr/src/utils.py", line 195, in get_webdriver
>     PATCHED_DRIVER_PATH = os.path.join(driver.patcher.data_path, driver.patcher.exe_name)
> UnboundLocalError: local variable 'driver' referenced before assignment
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/FlareSolverr/src/flaresolverr.py", line 105, in <module>
>     flaresolverr_service.test_browser_installation()
>   File "/root/FlareSolverr/src/flaresolverr_service.py", line 72, in test_browser_installation
>     user_agent = utils.get_user_agent()
>   File "/root/FlareSolverr/src/utils.py", line 314, in get_user_agent
>     raise Exception("Error getting browser User-Agent. " + str(e))
> Exception: Error getting browser User-Agent. local variable 'driver' referencedbefore assignment

**Comment by ilike2burnthing** [comment]
You'll need to clone the specific branch, currently you're still just working with `master`.

**Comment by ezrapeace** [comment]
I believe I did with https://github.com/21hsmw/FlareSolverr.git? This would be the branch of user/project 21hsmw if I'm not mistaken? Please correct me if I am.

**Comment by ezrapeace** [comment]
Ok I believe I have done it properly this time (let me know). If so, the issue unfortunately persists. This shows v3.4 though. And weirdly the main issue here is that it can't find chrome at all.. after identifying v128?

> [~]# git clone --branch nodriver-support https://github.com/21hsmw/FlareSolverr.git
> Cloning into 'FlareSolverr'...
> remote: Enumerating objects: 2028, done.
> remote: Total 2028 (delta 0), reused 0 (delta 0), pack-reused 2028 (from 1)
> Receiving objects: 100% (2028/2028), 1.40 MiB | 365.00 KiB/s, done.
> Resolving deltas: 100% (1323/1323), done.
> 
> [~]# cd FlareSolverr
> 
> [FlareSolverr]# python3.9 -m pip install -r requirements.txt
> Ignoring pefile: markers 'platform_system == "Windows"' don't match your environment
> Requirement already satisfied: bottle==0.12.25 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (0.12.25)
> Requirement already satisfied: waitress==2.1.2 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.1.2)
> Requirement already satisfied: selenium==4.15.2 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (4.15.2)
> Requirement already satisfied: func-timeout==4.3.5 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.3.5)
> Collecting psutil==6.0.0
>   Downloading psutil-6.0.0.tar.gz (508 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.1/508.1 kB 167.0 kB/s eta 0:00:00
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Requirement already satisfied: prometheus-client==0.17.1 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.17.1)
> Requirement already satisfied: requests==2.31.0 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (2.31.0)
> Requirement already satisfied: certifi==2023.7.22 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2023.7.22)
> Collecting packaging==24.0
>   Downloading packaging-24.0-py3-none-any.whl (53 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 54.6 kB/s eta 0:00:00
> Collecting websockets==13.0
>   Downloading websockets-13.0-py3-none-any.whl (142 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 184.4 kB/s eta 0:00:00
> Collecting deprecated==1.2.14
>   Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
> Collecting mss==9.0.1
>   Downloading mss-9.0.1-py3-none-any.whl (22 kB)
> Requirement already satisfied: xvfbwrapper==0.2.9 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 17)) (0.2.9)
> Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (0.26.2)
> Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (0.11.1)
> Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.9/site-packages (from selenium==4.15.2->-r requirements.txt (line 3)) (2.2.3)
> Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 8)) (3.10)
> Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/site-packages (from requests==2.31.0->-r requirements.txt (line 8)) (3.3.2)
> Collecting wrapt<2,>=1.10
>   Downloading wrapt-1.16.0-py3-none-any.whl (23 kB)
> Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (2.4.0)
> Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.2.2)
> Requirement already satisfied: outcome in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.3.0.post0)
> Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (24.2.0)
> Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.15.2->-r requirements.txt (line 3)) (1.3.1)
> Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium==4.15.2->-r requirements.txt (line 3)) (1.2.0)
> Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.9/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.15.2->-r requirements.txt (line 3)) (1.7.1)
> Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.15.2->-r requirements.txt (line 3)) (0.14.0)
> Building wheels for collected packages: psutil
>   Building wheel for psutil (pyproject.toml) ... done
>   Created wheel for psutil: filename=psutil-6.0.0-cp39-cp39-freebsd_13_1_release_p7_amd64.whl size=259355 sha256=6966050970c9bec616c664c827dea6455b12428cb6ab7974d5125a057f0c1563
>   Stored in directory: /root/.cache/pip/wheels/76/1f/ff/be2a91abd34fa0da2843e59a2de5255e493387e6eaa214fa25
> Successfully built psutil
> Installing collected packages: wrapt, websockets, psutil, packaging, mss, deprecated
>   Attempting uninstall: websockets
>     Found existing installation: websockets 11.0.3
>     Uninstalling websockets-11.0.3:
>       Successfully uninstalled websockets-11.0.3
> Successfully installed deprecated-1.2.14 mss-9.0.1 packaging-24.0 psutil-6.0.0 websockets-13.0 wrapt-1.16.0
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> [notice] A new release of pip is available: 23.0.1 -> 24.2
> [notice] To update, run: pip3 install --upgrade pip
> 
> [FlareSolverr]# python3.9 src/flaresolverr.py
> 2024-09-16 12:27:44 INFO     FlareSolverr 3.4.0
> 2024-09-16 12:27:44 INFO     Testing web browser installation...
> 2024-09-16 12:27:44 INFO     Platform: FreeBSD-13.1-RELEASE-p7-amd64-64bit-ELF
> 2024-09-16 12:27:44 INFO     Chrome / Chromium path: /usr/local/bin/chrome
> 2024-09-16 12:27:44 INFO     Chrome / Chromium major version: 128
> 2024-09-16 12:27:44 INFO     Launching web browser...
> 2024-09-16 12:27:44 INFO     Launching web browser...
> Traceback (most recent call last):
>   File "/root/FlareSolverr/src/utils.py", line 450, in get_user_agent_nd
>     driver = await get_webdriver_nd()
>   File "/root/FlareSolverr/src/utils.py", line 187, in get_webdriver_nd
>     options = nd.Config()
>   File "/root/FlareSolverr/src/nodriver/core/config.py", line 88, in __init__
>     browser_executable_path = find_chrome_executable()
>   File "/root/FlareSolverr/src/nodriver/core/config.py", line 319, in find_chrome_executable
>     raise FileNotFoundError(
> FileNotFoundError: could not find a valid chrome browser binary. please make sure chrome is installed.or use the keyword argument 'browser_executable_path=/path/to/your/browser'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/FlareSolverr/src/flaresolverr.py", line 122, in <module>
>     asyncio.run(flaresolverr_service_nd.test_browser_installation_nd())
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "/root/FlareSolverr/src/flaresolverr_service_nd.py", line 71, in test_browser_installation_nd
>     user_agent = await utils.get_user_agent_nd()
>   File "/root/FlareSolverr/src/utils.py", line 456, in get_user_agent_nd
>     raise Exception("Error getting browser User-Agent. " + str(e))
> Exception: Error getting browser User-Agent. could not find a valid chrome browser binary. please make sure chrome is installed.or use the keyword argument 'browser_executable_path=/path/to/your/browser'

**Comment by ilike2burnthing** [comment]
@21hsmw this more likely to be an image issue or something specific to this user?

**Comment by FroggMaster** [comment]
@ezrapeace I was encountering issues with Chromium version 127/128 on a similar jail that was running FreeBSD 13.1. There appears to be an incompatibility with the latest version of Chromium and FlareSolverr on unix based systems. 


However I've written instructions on how to build an older chromium version from source here: 
https://github.com/FlareSolverr/FlareSolverr/issues/1318#issuecomment-2354834950

Unless you upgrade your FreeBSD Jail to a minimum of 13.3 you won't be able to follow these instructions as your kernel is massively out of date, however perhaps the above steps may be of some help to you. Side note, If you're running TrueNAS there is a manual update to 13.3 community version which will update your kernel and allow you to build chromium from source.

**Comment by ezrapeace** [comment]
Hi thanks for the info @21hsmw, and ofc it's my luck I'm in some problem cohort! Tell me, I've been considering making the transition to TrueNAS Scale. Is TrueNAS Core really so miserably behind the times, should I pull the trigger on that? What is the main TN you're seeing out in the wild these days?

Another really weird thing I noticed a couple days ago is that the Flaresolverr is reporting 13.1 but the jail is 13.3. Not sure if that means anything or not. But thought I'd mention it.

**Comment by FroggMaster** [comment]
> Hi thanks for the info @21hsmw, and ofc it's my luck I'm in some problem cohort! Tell me, I've been considering making the transition to TrueNAS Scale. Is TrueNAS Core really so miserably behind the times, should I pull the trigger on that? What is the main TN you're seeing out in the wild these days?
> 
> Another really weird thing I noticed a couple days ago is that Flaresolverr is reporting 13.1 but the jail is 13.3. Not sure if that means anything or not. But thought I'd mention it.

In regards to the issue regarding Flaresolverr showing the incorrect OS Version. I believe this may have to do with Flaresolverr caching some files; I had the same issue on my Jail until I removed and re-cloned the Flaresolverr repository. 

In regards to your questions about TrueNAS Core / Scale. I apologize in advance if this is a little lengthy: 
TrueNAS core is officially on FreeBSD 13.0, which will be end of life on 30 Apr 2026. If you're running a FreeBSD 13.3 jail while running TrueNAS 13.0. Your kernel will still be on the old 13.0 kernel which can cause incompatibility issues in newer jails. If you want to avoid updating, or re-creating your jails; I would suggest updating to the 13.3 community edition of TrueNAS available [HERE](https://download-core.sys.truenas.net/13.3/STABLE/RELEASE/x64/TrueNAS-13.3-RELEASE.iso). I am personally trying to avoid transition to SCALE simply because I don't want to reconfigure all my jails within a new sandbox environment. (Since the existing implementation of jails does not exist on Scale). Unfortunately IX Systems has always been known to be a little bit behind on their FreeBSD updates, eventually their support will end entirely for TrueNAS Core. 

If re-creating all your FreeBSD jails in a new systemd-nspawn sandbox environment seems like something you don't mind doing. Then I would definitely suggest updating to TrueNAS Scale. The UI is similar to TureNAS Core except Scale focuses more on Docker /  systemd-nspawn containers. One thing to note though, if you want to use a sandbox containers similar to jails this is done with with a 3rd party script called [JailMaker](https://github.com/Jip-Hop/jailmaker)

**Comment by ezrapeace** [comment]
These are exactly the reasons I've been putting it off, and will likely continue to until max pain lol I'm also not keen on the idea of trashing all the FreeBSD knowledge I've amassed over the years for Debian that I know nothing about.

My current plan is to wait until I have to expand storage. I'm currently hovering around 79% usage. But I'm already starting to see cracks in the walls, like this Flaresolverr issue. I also can't install servarr apps in a fresh (13.3) jail, they also crash despite correct permissions and configuration (maybe updating the kernel may fix that?). Fortunately I have them working in an older jail. It's got to be something with 13.3. But I've definitely not reached max pain yet. So I think I will hold off if I can. I will see about upgrading the kernal to 13.3, I think that will solve another issue I've been seeing as well. Good tip on Jailmaker, I'll def check that out.

Regarding Flaresolverr, I'm not sure it's caching. Or maybe deleting the FS folder and recloning isn't enough to clear things out? Essentially, I deleted the previous Flaresolverr folder cloning the main branch created, and then git cloned your branch and installed. From there it is reporting the OS as we see there. Maybe there's more I need to do to uninstall the previous version?

So tell me it sounds like you have it working, is this in 13.3? I wish I could go back to the 13.0 jail where FS was working fine.

**Comment by ilike2burnthing** [comment]
Closing in favour of #1318.

**Comment by FroggMaster** [comment]
> These are exactly the reasons I've been putting it off, and will likely continue to until max pain lol I'm also not keen on the idea of trashing all the FreeBSD knowledge I've amassed over the years for Debian that I know nothing about.
> 
> My current plan is to wait until I have to expand storage. I'm currently hovering around 79% usage. But I'm already starting to see cracks in the walls, like this Flaresolverr issue. I also can't install servarr apps in a fresh (13.3) jail, they also crash despite correct permissions and configuration (maybe updating the kernel may fix that?). Fortunately I have them working in an older jail. It's got to be something with 13.3. But I've definitely not reached max pain yet. So I think I will hold off if I can. I will see about upgrading the kernal to 13.3, I think that will solve another issue I've been seeing as well. Good tip on Jailmaker, I'll def check that out.
> 
> Regarding Flaresolverr, I'm not sure it's caching. Or maybe deleting the FS folder and recloning isn't enough to clear things out? Essentially, I deleted the previous Flaresolverr folder cloning the main branch created, and then git cloned your branch and installed. From there it is reporting the OS as we see there. Maybe there's more I need to do to uninstall the previous version?
> 
> So tell me it sounds like you have it working, is this in 13.3? I wish I could go back to the 13.0 jail where FS was working fine.

If you have yet to upgrade your TrueNAS install from the 13.0-U6.2 version I would definitely recommend upgrading to the 13.3 community version. This will upgrade the kernel on your TrueNAS system to a more up to date version of the 13.3 kernel. That should fix the errors that stem from a kernel mismatch in your 13.3 jail. I noticed that the daemon command would not even work in most of my 13.3 jails before I upgraded my TrueNAS install to the 13.3 community release. (This is still released by IX Systems, it's just for community users rather than Enterprise users.) 

Also just to be clear I have nothing to do with @21hsmw branch of Flaresolverr. I'm just another user, who is also using TrueNAS and Flaresolverr. :frog:
