### ISSUE TITLE
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Token solver failed to return a token.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Token solver failed to return a token.

### ISSUE THREAD

**Issue by renault1505** [FlareSolverr/FlareSolverr#136]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 1.2.5
* **Last working FlareSolverr version**: 1.2.5
* **Operating system**: LINUX
* **Are you using Docker**: [yes/no] YES
* **Are you using a proxy or VPN?** [yes/no] NO
* **Are you using Captcha Solver:** [yes/no] YES
* **If using captcha solver, which one:** HCaptcha Solver

### Description

Go to Jackett and test the connection to YggTorrent.

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

2021-05-29T17:42:41.750Z INFO REQ-1 Incoming request: POST /v1                                                              
2021-05-29T17:42:41.755Z INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine
/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"M
ozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}                   
2021-05-29T17:42:43.650Z INFO REQ-1 Cloudflare detected                                                                     
2021-05-29T17:42:43.793Z INFO REQ-1 Captcha challenge detected.                                                             
2021-05-29T17:42:43.793Z INFO REQ-1 Using 'hcaptcha-solver' to solve the captcha.                                           
2021-05-29T17:42:43.803Z INFO REQ-1 Waiting to receive captcha token to bypass challenge...                                 
StatusCodeError: 404 - "nonsense\n"                                                                                         
    at new StatusCodeError (/home/node/flaresolverr/node_modules/request-promise-core/lib/errors.js:32:15)                  
    at Request.plumbing.callback (/home/node/flaresolverr/node_modules/request-promise-core/lib/plumbing.js:104:33)         
    at Request.RP$callback [as _callback] (/home/node/flaresolverr/node_modules/request-promise-core/lib/plumbing.js:46:31) 
    at Request.self.callback (/home/node/flaresolverr/node_modules/request/request.js:185:22)                               
    at Request.emit (node:events:329:20)                                                                                    
    at Request.<anonymous> (/home/node/flaresolverr/node_modules/request/request.js:1154:10)                                
    at Request.emit (node:events:329:20)                                                                                    
    at IncomingMessage.<anonymous> (/home/node/flaresolverr/node_modules/request/request.js:1076:12)                        
    at Object.onceWrapper (node:events:435:28)                                                                              
    at IncomingMessage.emit (node:events:341:22) {                                                                          
  statusCode: 404,                                                                                                          
  error: 'nonsense\n',                                                                                                      
  options: {                                                                                                                
    uri: 'https://assets.hcaptcha.com/c/500c658/hsl.js',                                                                    
    method: 'GET',                                                                                                          
    callback: [Function: RP$callback],                                                                                      
    transform: undefined,                                                                                                   
    simple: true,                                                                                                           
    resolveWithFullResponse: false,                                                                                         
    transform2xxOnly: false                                                                                                 
  },              
....
body: 'nonsense\n',                                                                                                                   
    [Symbol(kCapture)]: false,                                                                                                            
    [Symbol(kHeaders)]: {                                                                                                                 
      date: 'Sat, 29 May 2021 17:42:44 GMT',                                                                                              
      'content-type': 'text/html',                                                                                                        
      'transfer-encoding': 'chunked',                                                                                                     
      connection: 'close',                                                                                                                
      'x-amz-meta-md5': '0377438312a93cf85307e3fa0fe437cf',                                                                               
      'x-amz-meta-privilege': '755',                                                                                                      
      'last-modified': 'Mon, 20 Aug 2018 21:31:04 GMT',                                                                                   
      'x-amz-error-code': 'NoSuchKey',                                                                                                    
      'x-amz-error-message': 'The specified key does not exist.',                                                                         
      'x-amz-error-detail-key': 'c/500c658/hsl.js',                                                                                       
      'x-amz-request-id': 'REKYPEPRXX9K94SZ',                                                                                             
      'x-amz-id-2': 'SQnhFa6OOPqI9bEd72plhGNj/D1Wslv3vJ04NIYYctHDAtQWfgL68SZt6emds+0L49lM3/iYUcY=',                                       
      'cf-cache-status': 'EXPIRED',                                                                                                       
      'cf-request-id': '0a5ad1ae230000f969a908e000000001',                                                                                
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',                             
      'strict-transport-security': 'max-age=2592000; includeSubDomains; preload',                                                         
      'x-content-type-options': 'nosniff',                                                                                                
      server: 'cloudflare',                                                                                                               
      'cf-ray': '6571855d0e6cf969-BRU',                                                                                                   
      'alt-svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400'                                                 
    },                                                                                                                                    
    [Symbol(kHeadersCount)]: 40,                                                                                                          
    [Symbol(kTrailers)]: null,                                                                                                            
    [Symbol(kTrailersCount)]: 0,                                                                                                          
    [Symbol(RequestTimeout)]: undefined                                                                                                   
  }                                                                                                                                       
}                                                                                                                                         
2021-05-29T17:42:46.373Z INFO REQ-1 Successful response in 4.623 s                                                                        
2021-05-29T17:42:46.373Z INFO REQ-1 Cloudflare Error: Token solver failed to return a token.                                                                                                               

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by Killianbe** [comment]
Doublon de doublon de doublon.. Cherchez avant de poster tjrs les memes erreurs pour YGG

**Comment by renault1505** [comment]
J'ai cherché et ce n'est pas le même message que les précédentes issues à ce sujet.
Peut être le souci derrière est le même mais ça, je suis pas censé le deviner :)

Amicalement.

**Comment by renault1505** [comment]
Parait que c'est un doublon, donc je cloture :)

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 released.
