### ISSUE TITLE
500 Internal Server Error Ygg.re

### ISSUE THREAD

**Issue by dj41ph4** [FlareSolverr/FlareSolverr#1370]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

Yes

### Environment

```markdown
- FlareSolverr version: LATEST
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] No
- Are you using a Proxy: [yes/no] No
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one:
- URL to test this issue: ygg.re
```

### Description

500 Internal Server Error Ygg.re

### Logged Error Messages

```text
Hello,

I've been experiencing issues with FlareSolverr when trying to access Yggtorrent. Everything was working fine until recently, but now I'm getting timeout errors, and it seems unable to bypass the Cloudflare challenge.

Here's a snippet of the log for reference:

2024-09-29 09:37:45 INFO     Incoming request => POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=seed', 'proxy': {}}
2024-09-29 09:37:47 INFO     Challenge detected. Title found: Just a moment...
2024-09-29 09:40:25 ERROR    Error: Error solving the challenge. Timeout after 180.0 seconds.
2024-09-29 09:40:25 INFO     Response in 181.068 s
2024-09-29 09:40:25 INFO     172.17.0.1 POST http://10.0.0.49:8191/v1 500 Internal Server Error
I'm running FlareSolverr with Prowlarr in Docker, and I've made sure everything is updated. Has anyone encountered a similar issue recently or knows of a potential workaround?

Thank you in advance!
```

**Comment by Markodingo** [comment]
J'ai la même erreur, aussi j'ai basculé sur Yggcookie qui lui, bizarrement, semble fonctionner.

**Comment by tetar998** [comment]
idem j ai la meme erreur

**Comment by bibiwan** [comment]
Same here, and I've tried different PRs, but different problems appears using them.

I'm gonna try with yggcookie for now.

**Comment by dj41ph4** [comment]
Je viens de compiler la solution, vous pouvez la trouver sur Docker.io :
dj41ph4/flaresolverrfix:ygg (pas dj41ph4/flaresolverrfix:yggfix).
---
I just compiled the solution, you can find it on Docker.io:
dj41ph4/flaresolverrfix:ygg (not dj41ph4/flaresolverrfix:yggfix).

**Comment by bibiwan** [comment]
> Je viens de compiler la solution, vous pouvez la trouver sur Docker.io : dj41ph4/flaresolverrfix:ygg .
> 
> I just compiled the solution, you can find it on Docker.io: dj41ph4/flaresolverrfix:ygg .

Merci.

**Comment by Markodingo** [comment]
> Je viens de compiler la solution, vous pouvez la trouver sur Docker.io : dj41ph4/flaresolverrfix:ygg .
> 
> I just compiled the solution, you can find it on Docker.io: dj41ph4/flaresolverrfix:ygg .

Fonctionne parfaitement, merci 👍

**Comment by PierreAlexx01** [comment]
Et pour ceux qui n'utilisent pas docker comment faire ?

**Comment by ilike2burnthing** [comment]
Do not use this image, see discussion here - https://github.com/FlareSolverr/FlareSolverr/issues/1371
