### ISSUE TITLE
Requests get slow over time in the same session

### ISSUE THREAD

**Issue by miuru0** [FlareSolverr/FlareSolverr#1372]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: idk
- Operating system: Windows 11
- Are you using Docker: [yes/no] happens with and without docker
- FlareSolverr User-Agent (see log traces or / endpoint): User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: happens in any url
```

### Description

Create a session, make requests on the session, request starts taking long to fullfill, without headless mode you notice the browser gets very slow and laggy, there's another issue that said this, but it got closed

### Logged Error Messages

```text
No error messages
```

**Comment by ilike2burnthing** [comment]
How is the rest of the system responding? What's the resource usage like? Please provide logs.

**Comment by miuru0** [comment]
Memory usage in the js vm went from 30 to 100 mb in 100 requests

Heap snaphshot after 100 requests
![image](https://github.com/user-attachments/assets/a418763b-da23-4352-a36e-227c31ae3ac8)
string part is this
```
"(function(){ return (function() { // Copyright 2012 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/**
 * Enum for WebDriver status codes.
 * @enum {number}
 */
const StatusCode = {
  STALE_ELEMENT_REFERENCE: 10,
  JAVA_SCRIPT_ERROR: 17,
  NO_SUCH_SHADOW_ROOT: 65,
  DETACHED_SHADOW_ROOT: 66
};

/**
 * Enum for node types.
 * @enum {number}
 */
const NodeType = {
  ELEMENT: 1,
  DOCUMENT: 9,
};

/**
 * Dictionary key to use for holding an element ID.
 * @const
 * @type {string}
 */
var ELEMENT_KEY = 'ELEMENT';

/**
 * Dictionary key to use for holding a shadow element ID.
 * @const
 * @type {string}
 */
const SHADOW_ROOT_KEY = 'shadow-6066-11e4-a52e-4f735466cecf';
const W3C_ELEMENT_KEY = 'element-6066-11e4-a52e-4f735466cecf';

/**
 * True if using W3C Element references.
 * @const
 * @type {boolean}
 */
var w3cEnabled = false;

/**
 * True if shadow dom is enabled.
 * @const
 * @type {boolean}
 */
const SHADOW_DOM_ENABLED = typeof S"
```
a search of this lead me to this SeleniumHQ/selenium#14534

**Comment by ilike2burnthing** [comment]
Try switching to 21hsmw/flaresolverr:nodriver, see if that resolves the issue. For further discussion - https://github.com/FlareSolverr/FlareSolverr/pull/1163
