### ISSUE TITLE
Flaresolverr stuck on Chromium 129 Ubuntu Server

### ISSUE THREAD

**Issue by Kazz3r24** [FlareSolverr/FlareSolverr#1373]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: 3.3.18
- Operating system: Ubuntu Server 22
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint): 
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] yes
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I have Flaresolverr being passed through an Nginx reverse proxy. My problem is that between Chromium 127-129 Flaresolverr seems stuck when starting. I at no point see port 8191 in netstat and system status shows the following.

`● flaresolverr.service - FlareSolverr
     Loaded: loaded (/etc/systemd/system/flaresolverr.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-09-29 23:22:49 EDT; 20s ago
   Main PID: 1929580 (python3.11)
      Tasks: 14 (limit: 18986)
     Memory: 91.7M
        CPU: 1.781s
     CGroup: /system.slice/flaresolverr.service
             ├─1929580 python3.11 /opt/FlareSolverr/src/flaresolverr.py
             ├─1929684 Xvfb :1712120280 -screen 0 800x680x24
             └─1929716 /home/kevin/.local/share/undetected_chromedriver/undetected_chromedriver --port=60025

Sep 29 23:22:49 lyra systemd[1]: Started FlareSolverr.
Sep 29 23:22:51 lyra flaresolverr[1929580]: 2024-09-30 03:22:51 INFO     FlareSolverr 3.3.21
Sep 29 23:22:51 lyra flaresolverr[1929580]: 2024-09-30 03:22:51 INFO     Testing web browser installation...
Sep 29 23:22:51 lyra flaresolverr[1929580]: 2024-09-30 03:22:51 INFO     Platform: Linux-6.5.0-35-generic-x86_64-with-glibc2.35
Sep 29 23:22:51 lyra flaresolverr[1929580]: 2024-09-30 03:22:51 INFO     Chrome / Chromium path: /snap/bin/chromium
Sep 29 23:22:52 lyra flaresolverr[1929580]: 2024-09-30 03:22:52 INFO     Chrome / Chromium major version: 129
Sep 29 23:22:52 lyra flaresolverr[1929580]: 2024-09-30 03:22:52 INFO     Launching web browser...
`

It doesn't get passed this point. I've tried several Chromium versions and the only one that seems to allow the service to run is the snap installation. This was working the last time I checked it maybe a month ago or so. I only just updated Flaresolverr today as I noticed it wasn't working in Prowlarr.

### Logged Error Messages

```text
No instructions anywhere for how to enable with non-docker...
```

**Comment by Redhawk18** [comment]
#1318
