### ISSUE TITLE
[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by pducharme** [FlareSolverr/FlareSolverr#1380]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version: 3.3.21
- Last working FlareSolverr version: 3.3.21
- Operating system: UnRAID (Docker from official and from binhex)
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one: N/A
- URL to test this issue: ygg.re
```

### Description

Since couple of weeks now, ygg.re can't solve the cloudflare and failed at the time limit (55 sec).  Also tried to put 99 sec., same issue occurs at 99sec.

### Logged Error Messages

```text
2024-10-02 16:01:56,006 DEBG 'flaresolverr' stdout output:
2024-10-02 16:01:56 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/auth/login'}

2024-10-02 16:01:58,616 DEBG 'flaresolverr' stdout output:
2024-10-02 16:01:58 INFO     Challenge detected. Title found: Just a moment...

2024-10-02 16:02:51,836 DEBG 'flaresolverr' stdout output:
2024-10-02 16:02:51 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.
```

**Comment by NathanFichefet** [comment]
I have the same problem

**Comment by Neragoth** [comment]
Same here

**Comment by daviddst** [comment]
Same here :

> [...]
> flaresolverr     | 2024-10-02 23:20:08 DEBUG    ReqId 140303688263424 The Cloudflare 'Verify you are human' button > not found on the page.
> flaresolverr     | 2024-10-02 23:20:10 DEBUG    ReqId 140303688263424 Waiting for title (attempt 27): Just a moment...
> flaresolverr     | 2024-10-02 23:20:11 DEBUG    ReqId 140303688263424 Timeout waiting for selector
> flaresolverr     | 2024-10-02 23:20:11 DEBUG    ReqId 140303688263424 Try to find the Cloudflare verify checkbox...
> flaresolverr     | 2024-10-02 23:20:11 DEBUG    ReqId 140303688263424 Getting ShadowRoot by selector: div:not(:has(div))
> flaresolverr     | 2024-10-02 23:20:11 DEBUG    ReqId 140303688263424 iframe found
> flaresolverr     | 2024-10-02 23:20:13 DEBUG    ReqId 140303930955520 A used instance of webdriver has been destroyed
> flaresolverr     | 2024-10-02 23:20:13 ERROR    ReqId 140303930955520 Error: Error solving the challenge. Timeout after 90.0 seconds.
> flaresolverr     | 2024-10-02 23:20:13 DEBUG    ReqId 140303930955520 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 90.0 seconds.', 'startTimestamp': 1727903921956, 'endTimestamp': 1727904013150, 'version': '3.3.21'}
> flaresolverr     | 2024-10-02 23:20:13 INFO     ReqId 140303930955520 Response in 91.194 s
> flaresolverr     | 2024-10-02 23:20:13 INFO     ReqId 140303930955520 172.18.0.8 POST http://flaresolverr:8191/v1 500 Internal Server Error`

**Comment by GeoHolz** [comment]
Same

**Comment by xavier8706** [comment]
I had (i think) the same issue, and by using the version of 21hsmw/flaresolverr:nodriver it works for couple of days now (just from time to time some high CPU consumption which after a restart is resolved).

I found this issue which lead me to 21hsmw version (https://github.com/FlareSolverr/FlareSolverr/issues/1361)

Hope this can help,

**Comment by n1nj444** [comment]
Same : 
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. cannot access local variable 'driver' where it is not associated with a value: FlareSolverr was unable to process the request

**Comment by SubbyDew** [comment]
Same issue on multiple indexers

**Comment by daviddst** [comment]
> I had (i think) the same issue, and by using the version of 21hsmw/flaresolverr:nodriver it works for couple of days now (just from time to time some high CPU consumption which after a restart is resolved).
> 
> I found this issue which lead me to 21hsmw version (#1361)
> 
> Hope this can help,

Thanks @xavier8706 for your tip, this release works for me as well.

**Comment by janemba** [comment]
Which release ?  I got the following issue:
```
2024-10-03 14:25:32 DEBUG    ReqId 140351660623552 Navigating to... https://www.ygg.re
2024-10-03 14:25:34 INFO     ReqId 140351660623552 Challenge detected. Title found: Just a moment...
2024-10-03 14:25:35 DEBUG    ReqId 140351660623552 Waiting for title (attempt 1): Just a moment...
2024-10-03 14:25:37 DEBUG    ReqId 140351660623552 Timeout waiting for selector
2024-10-03 14:25:37 DEBUG    ReqId 140351660623552 Checking if cloudflare captcha is present on page...
2024-10-03 14:25:39 DEBUG    ReqId 140351660623552 Cloudflare captcha found!
2024-10-03 14:25:39 DEBUG    ReqId 140351660623552 Found captcha iframe!
2024-10-03 14:25:39 DEBUG    ReqId 140351660623552 Cloudflare element not found on the page - 'TargetInfo' object has no attribute 'find'
2024-10-03 14:25:42 DEBUG    ReqId 140351660623552 Waiting for title (attempt 2): Just a moment...
```

Some attribute that do not exist anymore.

I'm using the following release:

https://github.com/FlareSolverr/FlareSolverr/issues/1361#issuecomment-2375332592

**Comment by jmsprsns** [comment]
Broken here as well. Ended up doing what AymeriicV did.

It seems occasionally replacing cookies is something that I have to fix less often than trying to go to war with Cloudflare.

**Comment by flodejr** [comment]
Update to use seleniumbase uc mode. https://github.com/seleniumbase/SeleniumBase

**Comment by nodiaque** [comment]
> I managed to find a fix For YggTorrent via prowlarr use ygg cookies follow the steps, added the flaresolver tag and there you go good Movies :)

Where did you set the cookie? I'm into prowler and I only see username/password prompt, no cookie. I do have advanced view on
