### ISSUE TITLE
This workaround for YGG stopped working couple of days  ago

### ISSUE THREAD

**Issue by caublet** [FlareSolverr/FlareSolverr#1385]
Enter inside your container with your user :
`docker exec --user your_user -ti flaresolverr /bin/bash`
In the container : 
`echo "" > flaresolverr_service.py`
Copy the content of https://github.com/MCG-pok/FlareSolverr/blob/master/src/flaresolverr_service.py : 
then add it into the empty file flaresolverr_service.py
get out from the container and restart it : `docker restart flaresolverr`

_Originally posted by @nanarCss in https://github.com/FlareSolverr/FlareSolverr/issues/1253#issuecomment-2234163353_

**Comment by nanarCss** [comment]
Try with this image, no need to modify the file anymore
21hsmw/flaresolverr:nodriver

;)

**Comment by maxcore** [comment]
@nanarCss MANY THX !!! working for me

**Comment by cannabarman** [comment]
Hello,
I don't have docker, I'm using Prowlarr thrue Home Assistant. Is it a way to have ygg working?

**Comment by nanarCss** [comment]
If you don't want to use it via docker, you can install it via source code directly :
https://github.com/21hsmw/FlareSolverr#from-source-code

**Comment by janemba** [comment]
I tried both source code and docker and the result is the same "HTTP error 500".

**Comment by caublet** [comment]
> Try with this image, no need to modify the file anymore 21hsmw/flaresolverr:nodriver
> 
> ;)

Thanks!
