### ISSUE TITLE
Flaresolverr no longer works with yggtorrent

### ISSUE THREAD

**Issue by miltuss** [FlareSolverr/FlareSolverr#1405]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

Yes

### Environment

```markdown
- FlareSolverr version: 21hsmw/flaresolverr:nodriver
- Last working FlareSolverr version: 21hsmw/flaresolverr:nodriver
- Operating system: Debian
- Are you using Docker:yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Flaresolverr no longer works for yggtorrent with variants `21hsmw/flaresolverr:nodriver` and `alexfozor/flaresolverr:pr-1300-experimental`. I use Flaresolverr with Prowlarr

### Logged Error Messages

```text
Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www.ygg.re/auth/login using form selector form.login-form
```

**Comment by okaiff** [comment]
Have you tried https://github.com/yoori/flare-bypasser ? The author seems to have given up searching for an element to click through the DOM tree and uses image processing - this works on several sites for me...

**Comment by 21hsmw** [comment]
Based on your error log, it looks like cloudflare was successfully bypassed since it started looking for the login form?

**Comment by spamoi33** [comment]
Use yggapi.eu instead

**Comment by ocervell** [comment]
Nope, it doesn't work for me either:
```

nas-flaresolverr-1  | 2024-11-10 11:26:07 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
nas-flaresolverr-1  | version_main cannot be converted to an integer
nas-flaresolverr-1  | 2024-11-10 11:26:11 INFO     Challenge detected. Title found: Just a moment...
nas-flaresolverr-1  | 2024-11-10 11:27:18 ERROR    Error: Error solving the challenge. Timeout after 70.0 seconds.
nas-flaresolverr-1  | 2024-11-10 11:27:18 INFO     Response in 71.229 s
nas-flaresolverr-1  | 2024-11-10 11:27:18 INFO     172.17.0.1 POST http://192.168.1.18:8191/v1 500 Internal Server Error
```

**Comment by Quack6765** [comment]
Same thing for me. Using the latest version 3.3.21

```
2024-11-12 10:31:36 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': '[https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date',](https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date%27,) 'proxy': {}}
2024-11-12 10:31:37 INFO     Challenge detected. Title found: Just a moment...
2024-11-12 10:32:37 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
```

**Comment by Whisper40** [comment]
Same error, version : 3.3.21 :
```
2024-11-13 18:26:44 INFO     Challenge detected. Title found: Just a moment...

2024-11-13 18:27:39 ERROR    Error: Error solving the challenge. Timeout after 155.0 seconds.

2024-11-13 18:27:39 INFO     Response in 155.805 s

2024-11-13 18:27:39 INFO     172.68.234.17 POST https://.../v1 500 Internal Server Error


      
```

**Comment by tiritibambix** [comment]
Same here

**Comment by fmatsos** [comment]
For those who are using Flaresolverr with *Arr servers: you can use Ygg Cookie indexer with it. It works fine.

I don't know why, but Ygg with credentials does not work anymore. But Ygg Cookie will.

**Comment by ocervell** [comment]
YGG Cookie sucks because you have to manually refresh the cookie, so any automated setup will break at some point. Use https://github.com/FlareSolverr/FlareSolverr/pull/1300 instead.

**Comment by Firemad03** [comment]
> YGG Cookie sucks because you have to manually refresh the cookie, so any automated setup will break at some point. Use #1300 instead.

Now YGG cookie need cloudflare too in Jackett :(

**Comment by Fabbbou** [comment]
Does someone have any clue to solve this ? It's been 3 month that i removed YGG from my indexers because of cloudflare its a bit sad
I hope someday we could bring back YGG 😢
