### ISSUE TITLE
[helltorrents] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by marys1234** [FlareSolverr/FlareSolverr#1409]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Not solving: https://helltorrents.com/login.php

### Logged Error Messages

```text
Logs:
024-11-07 16:33:43 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://helltorrents.com/login.php'}

2024-11-07 16:33:47 INFO     Challenge detected. Title found: Just a moment...

2024-11-07 16:34:39 ERROR    Error: Error solving the challenge. Timeout after 55.0 seconds.

2024-11-07 16:34:39 INFO     Response in 56.151 s

2024-11-07 16:34:39 INFO     10.88.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

**Comment by 21hsmw** [comment]
The main version of flaresolverr does not work properly.
There are only 2 working images currently:
- `alexfozor/flaresolverr:pr-1300-experimental`
- `21hsmw/flaresolverr:nodriver`

**Comment by judyynailss** [comment]
> The main version of flaresolverr does not work properly. There are only 2 working images currently:
> 
> * `alexfozor/flaresolverr:pr-1300-experimental`
> * `21hsmw/flaresolverr:nodriver`

I've given both a shot and haven't been able to get them to work on DDoS-Guard sites (simpsity.su, particularly). Finds the challenge (DDoS-Guard) then sits there.

**Comment by Jojont54** [comment]
Hello 21hsmw, this 2 images were working for weeks/mounths on my side but they are no longer working since 2/3 days. 

Even the prowlarr test is failed in the 21hsmw/flaresolverr:nodriver image I'm using on an Unraid server (I pull this image with portainer).

**Comment by TodesAnge1** [comment]
> Hello 21hsmw, this 2 images were working for weeks/mounths on my side but they are no longer working since 2/3 days.
> 
> Even the prowlarr test is failed in the 21hsmw/flaresolverr:nodriver image I'm using on an Unraid server (I pull this image with portainer).
> 
> 2024-11-17 11:36:30 INFO Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}} 2024-11-17 11:37:31 ERROR Error: Error solving the challenge. Timeout after 60.0 seconds. 2024-11-17 11:37:31 INFO Response in 61.366 s 2024-11-17 11:37:31 INFO 172.17.0.1 POST http://192.168.1.68:32771/v1 500 Internal Server Error

I have a same problem...

**Comment by thany** [comment]
I'm on the official `flaresolverr/flaresolverr` image (I think, it's difficult to check in Unraid) and that one should be the one that works.

@21hsmw If yours somehow works, have you opened a PR already with any fixes you have done? Because, respectfully, we shouldn't have to be juggling with a million obscure images when there's an official one. There's enough fragmentation of these *arr microservices as it is.
