### ISSUE TITLE
Synology NAS Error - UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value and Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value

### ISSUE THREAD

**Issue by Gibby503** [FlareSolverr/FlareSolverr#1410]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Have you ACTUALLY checked all these?

YES

### Environment

```markdown
- FlareSolverr version:latest (3.3.21)
- Last working FlareSolverr version:N/A
- Operating system:Synology OS via Docker Container
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:N/A
- URL to test this issue:
```

### Description

Getting the following errors when trying to run a docker container with flaresolverr, it then crashes - 

<html>
<body>

2024/11/10 17:40:45 | stdout | Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
-- | -- | --
2024/11/10 17:40:45 | stdout | raise Exception("Error getting browser User-Agent. " + str(e))
2024/11/10 17:40:45 | stdout | File "/app/utils.py", line 322, in get_user_agent
2024/11/10 17:40:45 | stdout | ^^^^^^^^^^^^^^^^^^^^^^
2024/11/10 17:40:45 | stdout | user_agent = utils.get_user_agent()
2024/11/10 17:40:45 | stdout | File "/app/flaresolverr_service.py", line 72, in test_browser_installation
2024/11/10 17:40:45 | stdout | flaresolverr_service.test_browser_installation()
2024/11/10 17:40:45 | stdout | File "/app/flaresolverr.py", line 108, in <module>
2024/11/10 17:40:45 | stdout | Traceback (most recent call last):
2024/11/10 17:40:45 | stdout |  
2024/11/10 17:40:45 | stdout | During handling of the above exception, another exception occurred:
2024/11/10 17:40:45 | stdout |  
2024/11/10 17:40:45 | stdout | UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
2024/11/10 17:40:45 | stdout | ^^^^^^
2024/11/10 17:40:45 | stdout | return driver
2024/11/10 17:40:45 | stdout | File "/app/utils.py", line 219, in get_webdriver
2024/11/10 17:40:45 | stdout | ^^^^^^^^^^^^^^^
2024/11/10 17:40:45 | stdout | driver = get_webdriver()
2024/11/10 17:40:45 | stdout | File "/app/utils.py", line 316, in get_user_agent
2024/11/10 17:40:45 | stdout | Traceback (most recent call last):
2024/11/10 17:40:45 | stdout |  
2024/11/10 17:40:45 | stdout | #19 0x007fb542101c <unknown>
2024/11/10 17:40:45 | stdout | #18 0x007fb5be5648 start_thread
2024/11/10 17:40:45 | stdout | #17 0x005561213db4 <unknown>
2024/11/10 17:40:45 | stdout | #16 0x0055612056cc <unknown>
2024/11/10 17:40:45 | stdout | #15 0x0055612054c8 <unknown>
2024/11/10 17:40:45 | stdout | #14 0x0055611c7858 <unknown>
2024/11/10 17:40:45 | stdout | #13 0x0055611eccb0 <unknown>
2024/11/10 17:40:45 | stdout | #12 0x0055611dc304 <unknown>
2024/11/10 17:40:45 | stdout | #11 0x0055611ec1d8 <unknown>
2024/11/10 17:40:45 | stdout | #10 0x0055611ec5f0 <unknown>
2024/11/10 17:40:45 | stdout | #9 0x0055611e9618 <unknown>
2024/11/10 17:40:45 | stdout | #8 0x005560f51d80 <unknown>
2024/11/10 17:40:45 | stdout | #7 0x005560f50904 <unknown>
2024/11/10 17:40:45 | stdout | #6 0x005560f908c0 <unknown>
2024/11/10 17:40:45 | stdout | #5 0x005560f910c8 <unknown>
2024/11/10 17:40:45 | stdout | #4 0x005560f46488 <unknown>
2024/11/10 17:40:45 | stdout | #3 0x005560f4d144 <unknown>
2024/11/10 17:40:45 | stdout | #2 0x005560f0b31c <unknown>
2024/11/10 17:40:44 | stdout | #1 0x005560f1b164 <unknown>
2024/11/10 17:40:44 | stdout | #0 0x005561214850 <unknown>
2024/11/10 17:40:43 | stdout | Stacktrace:
2024/11/10 17:40:43 | stdout | from chrome not reachable
2024/11/10 17:40:40 | stdout | 2024-11-10 17:40:40 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:36925
2024/11/10 17:39:18 | stdout | 2024-11-10 17:39:17 INFO     Launching web browser...
2024/11/10 17:39:18 | stdout | 2024-11-10 17:39:17 INFO     Chrome / Chromium major version: 120
2024/11/10 17:38:46 | stdout | 2024-11-10 17:38:46 INFO     Chrome / Chromium path: /usr/bin/chromium
2024/11/10 17:38:46 | stdout | 2024-11-10 17:38:46 INFO     Platform: Linux-5.10.55+-aarch64-with-glibc2.31
2024/11/10 17:38:46 | stdout | 2024-11-10 17:38:46 INFO     Testing web browser installation...
2024/11/10 17:38:46 | stdout | 2024-11-10 17:38:46 INFO     FlareSolverr 3.3.20

</body>
</html>

### Logged Error Messages

```text
<html>
<body>
<!--StartFragment-->
2024/11/10 03:34:45 | stdout | Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
-- | -- | --
2024/11/10 03:34:45 | stdout | raise Exception("Error getting browser User-Agent. " + str(e))
2024/11/10 03:34:45 | stdout | File "/app/utils.py", line 322, in get_user_agent
2024/11/10 03:34:45 | stdout | ^^^^^^^^^^^^^^^^^^^^^^
2024/11/10 03:34:45 | stdout | user_agent = utils.get_user_agent()
2024/11/10 03:34:45 | stdout | File "/app/flaresolverr_service.py", line 73, in test_browser_installation
2024/11/10 03:34:45 | stdout | flaresolverr_service.test_browser_installation()
2024/11/10 03:34:45 | stdout | File "/app/flaresolverr.py", line 108, in <module>
2024/11/10 03:34:45 | stdout | Traceback (most recent call last):
2024/11/10 03:34:45 | stdout |  
2024/11/10 03:34:45 | stdout | During handling of the above exception, another exception occurred:
2024/11/10 03:34:45 | stdout |  
2024/11/10 03:34:45 | stdout | UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
2024/11/10 03:34:45 | stdout | ^^^^^^
2024/11/10 03:34:45 | stdout | return driver
2024/11/10 03:34:45 | stdout | File "/app/utils.py", line 219, in get_webdriver
2024/11/10 03:34:45 | stdout | ^^^^^^^^^^^^^^^
2024/11/10 03:34:45 | stdout | driver = get_webdriver()
2024/11/10 03:34:45 | stdout | File "/app/utils.py", line 316, in get_user_agent
2024/11/10 03:34:45 | stdout | Traceback (most recent call last):
2024/11/10 03:34:45 | stdout |  
2024/11/10 03:34:45 | stdout | #19 0x007f91a2e01c <unknown>
2024/11/10 03:34:45 | stdout | #18 0x007f921f2648 start_thread
2024/11/10 03:34:45 | stdout | #17 0x005583e73db4 <unknown>
2024/11/10 03:34:45 | stdout | #16 0x005583e656cc <unknown>
2024/11/10 03:34:45 | stdout | #15 0x005583e654c8 <unknown>
2024/11/10 03:34:45 | stdout | #14 0x005583e27858 <unknown>
2024/11/10 03:34:45 | stdout | #13 0x005583e4ccb0 <unknown>
2024/11/10 03:34:45 | stdout | #12 0x005583e3c304 <unknown>
2024/11/10 03:34:45 | stdout | #11 0x005583e4c1d8 <unknown>
2024/11/10 03:34:45 | stdout | #10 0x005583e4c5f0 <unknown>
2024/11/10 03:34:45 | stdout | #9 0x005583e49618 <unknown>
2024/11/10 03:34:45 | stdout | #8 0x005583bb1d80 <unknown>
2024/11/10 03:34:45 | stdout | #7 0x005583bb0904 <unknown>
2024/11/10 03:34:45 | stdout | #6 0x005583bf08c0 <unknown>
2024/11/10 03:34:45 | stdout | #5 0x005583bf10c8 <unknown>
2024/11/10 03:34:45 | stdout | #4 0x005583ba6488 <unknown>
2024/11/10 03:34:45 | stdout | #3 0x005583bad144 <unknown>
2024/11/10 03:34:45 | stdout | #2 0x005583b6b31c <unknown>
2024/11/10 03:34:45 | stdout | #1 0x005583b7b164 <unknown>
2024/11/10 03:34:45 | stdout | #0 0x005583e74850 <unknown>
2024/11/10 03:34:41 | stdout | Stacktrace:
2024/11/10 03:34:41 | stdout | from chrome not reachable
2024/11/10 03:34:39 | stdout | 2024-11-10 03:34:33 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:56531
2024/11/10 03:32:58 | stdout | 2024-11-10 03:32:58 INFO     Launching web browser...
2024/11/10 03:32:58 | stdout | 2024-11-10 03:32:58 INFO     Chrome / Chromium major version: 120
2024/11/10 03:32:37 | stdout | 2024-11-10 03:32:37 INFO     Chrome / Chromium path: /usr/bin/chromium
2024/11/10 03:32:37 | stdout | 2024-11-10 03:32:36 INFO     Platform: Linux-5.10.55+-aarch64-with-glibc2.31
2024/11/10 03:32:37 | stdout | 2024-11-10 03:32:36 INFO     Testing web browser installation...
2024/11/10 03:32:37 | stdout | 2024-11-10 03:32:36 INFO     FlareSolverr 3.3.21
2024/11/10 03:31:40 | stdout | Exception: Error getting browser User-Agent. cannot access local variable 'driver' where it is not associated with a value
2024/11/10 03:31:40 | stdout | raise Exception("Error getting browser User-Agent. " + str(e))
2024/11/10 03:31:40 | stdout | File "/app/utils.py", line 322, in get_user_agent
2024/11/10 03:31:40 | stdout | ^^^^^^^^^^^^^^^^^^^^^^
2024/11/10 03:31:40 | stdout | user_agent = utils.get_user_agent()
2024/11/10 03:31:40 | stdout | File "/app/flaresolverr_service.py", line 73, in test_browser_installation
2024/11/10 03:31:40 | stdout | flaresolverr_service.test_browser_installation()
2024/11/10 03:31:40 | stdout | File "/app/flaresolverr.py", line 108, in <module>
2024/11/10 03:31:40 | stdout | Traceback (most recent call last):
2024/11/10 03:31:40 | stdout |  
2024/11/10 03:31:40 | stdout | During handling of the above exception, another exception occurred:
2024/11/10 03:31:40 | stdout |  
2024/11/10 03:31:40 | stdout | UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value
2024/11/10 03:31:40 | stdout | ^^^^^^
2024/11/10 03:31:40 | stdout | return driver
2024/11/10 03:31:40 | stdout | File "/app/utils.py", line 219, in get_webdriver
2024/11/10 03:31:40 | stdout | ^^^^^^^^^^^^^^^
2024/11/10 03:31:40 | stdout | driver = get_webdriver()
2024/11/10 03:31:40 | stdout | File "/app/utils.py", line 316, in get_user_agent
2024/11/10 03:31:40 | stdout | Traceback (most recent call last):
2024/11/10 03:31:40 | stdout |  
2024/11/10 03:31:40 | stdout | #19 0x007fa9efe01c <unknown>
2024/11/10 03:31:40 | stdout | #18 0x007faa6c2648 start_thread
2024/11/10 03:31:40 | stdout | #17 0x00555afb3db4 <unknown>
2024/11/10 03:31:40 | stdout | #16 0x00555afa56cc <unknown>
2024/11/10 03:31:40 | stdout | #15 0x00555afa54c8 <unknown>
2024/11/10 03:31:40 | stdout | #14 0x00555af67858 <unknown>
2024/11/10 03:31:40 | stdout | #13 0x00555af8ccb0 <unknown>
2024/11/10 03:31:40 | stdout | #12 0x00555af7c304 <unknown>
2024/11/10 03:31:40 | stdout | #11 0x00555af8c1d8 <unknown>
2024/11/10 03:31:40 | stdout | #10 0x00555af8c5f0 <unknown>
2024/11/10 03:31:40 | stdout | #9 0x00555af89618 <unknown>
2024/11/10 03:31:40 | stdout | #8 0x00555acf1d80 <unknown>
2024/11/10 03:31:40 | stdout | #7 0x00555acf0904 <unknown>
2024/11/10 03:31:40 | stdout | #6 0x00555ad308c0 <unknown>
2024/11/10 03:31:40 | stdout | #5 0x00555ad310c8 <unknown>
2024/11/10 03:31:40 | stdout | #4 0x00555ace6488 <unknown>
2024/11/10 03:31:40 | stdout | #3 0x00555aced144 <unknown>
2024/11/10 03:31:40 | stdout | #2 0x00555acab31c <unknown>
2024/11/10 03:31:40 | stdout | #1 0x00555acbb164 <unknown>
2024/11/10 03:31:40 | stdout | #0 0x00555afb4850 <unknown>
2024/11/10 03:31:40 | stdout | Stacktrace:
2024/11/10 03:31:38 | stdout | from chrome not reachable
2024/11/10 03:31:21 | stdout | 2024-11-10 03:31:16 ERROR    Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:45985
2024/11/10 03:29:24 | stdout | 2024-11-10 03:29:24 INFO     Launching web browser...
2024/11/10 03:29:24 | stdout | 2024-11-10 03:29:24 INFO     Chrome / Chromium major version: 120
2024/11/10 03:29:06 | stdout | 2024-11-10 03:29:06 INFO     Chrome / Chromium path: /usr/bin/chromium
2024/11/10 03:29:06 | stdout | 2024-11-10 03:29:06 INFO     Platform: Linux-5.10.55+-aarch64-with-glibc2.31
2024/11/10 03:29:06 | stdout | 2024-11-10 03:29:06 INFO     Testing web browser installation...
2024/11/10 03:29:06 | stdout | 2024-11-10 03:29:06 INFO     FlareSolverr 3.3.21

<!--EndFragment-->
</body>
</html>
```

### Screenshots

![image](https://github.com/user-attachments/assets/5e108ac8-4986-4cb1-922a-4cbef1bd2e00)

![image](https://github.com/user-attachments/assets/9d54bf8a-c184-4c75-95e5-c2d5e1984788)

**Comment by elazar** [comment]
I'm also attempting to run FlareSolverr 3.3.21 on a Synology NAS (model DS224+, DSM 7.2.2-72806 Update 2) using Docker with no VPN, proxy, or CAPTCHA solver, and encountered a similar error. Here are the differences I'm seeing in the logs as compared to what the original reporter of this issue supplied.

```
Platform: Linux-4.4.302+-x86_64-with-glibc2.31
Chrome / Chromium major version: 120
Started executable: `/app/chromedriver` in a child process with pid: 29
Error starting Chrome: Message: unknown error: cannot connect to chrome at 127.0.0.1:48367
from chrome not reachable
```
