### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Shibiz** [FlareSolverr/FlareSolverr#145]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 1.2.8
* **Last working FlareSolverr version**:
* **Operating system**: Docker
* **Are you using Docker**: [yes/no] Yes
* **Are you using a proxy or VPN?** [yes/no] No
* **Are you using Captcha Solver:** [yes/no] No
* **If using captcha solver, which one:**
* **URL to test this issue:**  https://www4.yggtorrent.li/engine/search?name=&do=search/

### Description

When i try to test my YGG tracker, i get an error message 

An error occurred while testing this indexer
Found no results while trying to browse this tracker

It seems that no challenge is detected

### Logged Error Messages

2021-06-01T19:10:08+00:00 INFO REQ-8 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"},
2021-06-01T19:10:08+00:00 INFO REQ-7 Challenge solved.,
2021-06-01T19:16:06+00:00 INFO REQ-12 Response in 5.188 s,
2021-06-01T19:16:06+00:00 INFO REQ-12 Challenge solved.,
2021-06-01T19:16:02+00:00 INFO REQ-12 Cloudflare detected,
2021-06-01T19:16:01+00:00 INFO REQ-12 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"},
2021-06-01T19:16:01+00:00 INFO REQ-12 Incoming request: POST /v1,
2021-06-01T19:16:01+00:00 INFO REQ-11 Response in 5.232 s,
2021-06-01T19:15:56+00:00 INFO REQ-11 Incoming request: POST /v1,
2021-06-01T19:15:56+00:00 INFO REQ-11 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"},
2021-06-01T19:15:56+00:00 INFO REQ-11 Cloudflare detected,
2021-06-01T19:16:01+00:00 INFO REQ-11 Challenge solved.

**Comment by ngosang** [comment]
Please, configure debug traces and share the logs.
https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace

**Comment by n0vae** [comment]
Hi, I'm not able to properly describe my issue for now but I can tell you that my flaresolverr/jackett/yggtorrent config broke a few hours/days ago. When testing indexer, I get the following :
"An error occurred while updating this indexer
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured."

Maybe it's related to some change on ygg side ?

**Comment by arediss** [comment]
Here are the logs (I use nodeJS)
[logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/6588047/logs.txt)

**Comment by baty0man** [comment]
Same issue here

**Comment by baty0man** [comment]
[logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/6590104/logs.txt)
logs attached.

Thanks for looking into it

**Comment by Jamy50** [comment]
same problem

**Comment by Silvers12** [comment]
same for me

**Comment by n0vae** [comment]
Hi all.

I just updated my flaresolver in Docker and everything's fine now.

**Comment by baty0man** [comment]
Which version?

**Comment by Silvers12** [comment]
After update docker flaresolver it work for me too.

**Comment by hergonoway** [comment]
> After update docker flaresolver it work for me too.
> V1.2.8

it worked again around the time of your comment, but it last for 2 hours in my case, now back to square one. :)

**Comment by Shibiz** [comment]
What CAPTCHA_SOLVER do you use guys to run it correctly ?

**Comment by Shibiz** [comment]
Still not working for me
Am i the only one ?

@ngosang Here are the logs with debug traces configured


      
      

;
      

>

  </script>

  


<script type="text/javascript" src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=6605c11b1a204c1a"></script></head>

<body>

  <table width="100%" height="100%" cellpadding="20">

    <tbody><tr>

      <td align="center" valign="middle">

          <div class="cf-browser-verification cf-im-under-attack">
      
  <noscript>

    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>

  </noscript>

  <div id="cf-content" style="display: block;">

    

    <div id="cf-bubbles">

      <div class="bubbles"></div>

      <div class="bubbles"></div>

      <div class="bubbles"></div>

    </div>

    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> yggtorrent.li.</h1>

    

    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">

      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>

    </div>

    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>

    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs">Please allow up to 5 seconds…</p>

    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting…</p>

  </div>

   <a href="https://davidcdaniel.us/scarcenapiform.php?del=8" style="display: none;">table</a>

  <form class="challenge-form" id="challenge-form" action="/?__cf_chl_jschl_tk__=5d83b8497c7ef7c30aa14ec3ecb9adb842796ab0-1623864503-0-Aa0_2b6SmLre8MX5yjtYGKYNkbUtwUln0goWCiW1vi1tjuyHMU0LIJMBUh5D7N-E2-3pcvFxEllpgg4hg8OfwLvd5axTkMTT5gh1ew_Ag6xrtymBdvE6lqD8_TZ7hh2HMNjqEb4s22VtHhQQ6F7I_Av2R-LI8jl6PPQaZGkl4t1rUL-BpPdJobb7DiURmJKJni4Nv3-RPe-KOAWh3SiX56O_WulWHtc3WCRe8YQwpg2TADPgMuN7ZYt0bpXHW1h0a84mYgJAh25Y2nErS_UTpxctvmL1LAC6BUctuheXdxFN9eyI1mIs3Jutd_UYZDJZ4svK8KAf8L2TM8xc0VvXx0ZCR9ihqRopoq444FPFAZy0WUi-fWPWE3longa0BtZ8NKbBWqayw_ACe3b7oSK4Xk0" method="POST" enctype="application/x-www-form-urlencoded">

    <input type="hidden" name="r" value="16470203c0ac7bde21eceb12dbf2793d976b677f-1623864503-0-AQesUWcKZrD+0QgEnquSt1ZZNOAI+urCmTukTyzGtzJUEqWSMpVrDzASgAC9hkbd6nlyA4lky4guRQ4rSn4tKXaVZ9lb3gbhdEQa6cEE+vMQ57qRGg8sxagZ/oU4v4AeHL0oNvQk+PkNs1YvuqSbI2D12eiO4s6Ob5/M+IXatcgPAC5FRomxa8KWRRToSJ4wrL/nsUkxLkfjT6pX5DAzxZdJJoNBxdhrBUPSpqSLPf90AJ1w2JNmjzgBbOLVoJAWQ/Dgb9KB0qccp9pCioekz0G8X4CuYQLPk5ofhNjaiBaDKsZwW8UXQwcRBy1RqTWvo+hKfjfAnBGjirW5ytxjdiF9Z+4EKqgRqAOY4x4FVsMRx2LKgcLHsCnQ+zXqW2cB3S/rWusfU/frpP68KLVuUdY6aUGqKZf0TFM9IwtFK5YBhkcszwsRCnAd53YraGehd8oztfliiFqkl8c5XbEDyeV277Lmz7vRiZ3X/yevFystZX8delJ6w19931508mGtoMG7llEnnfrD1ecUGwc6DIC3EYK6GumshuodDn1o6oBu+rkJ3pALuKXlbq9QJ4/+qF+uVc5EYHTty08P1pOUVuSL5DXae8T5BnfgT2l18ui0YV26jsyKMGvGUmY/zP9xmGTgsRuvc2VvvbNnClakCkiczHOlHogAko2pFOhxztzwTnw3+mTu6KubF+ZrWCEan4P2dKw7WSnicieq/w8M1ONwaK3CaYuXN5opAOTN8Fhx/goxO0pbJcfDM+CRYL4E4B3tHAd+7h0qON0mG6YX/IARru7rp/hNnOC+jw4vwZYiKK0/Gy6ZmV4YzedKT7vUudjhqn5AGXcyti0fhMPMDTHAW7au9WVdHxct3LeWvFdr/rG1afMsn2L9SJ1V1o4t9OKtyc987AQVcuoptKuQ2xooPlfqXaivGvGRiThEFUNa3rR9f5jPWpMC75CAH1lz1UYsG9IZrpgHZTw5ChzQRGulg4bM7Ha1zWQZhMyK1wIgp26gaFhkg3SRH9ZXJIHiyVtoXmZt1w6CuikZS9CpzX60k3HKnmy4ukQpRJ/TS2vHfgJhuOQLNMOblmDP+zDObN9it4Yre6kSDwjBdrzjw5yuz4HUcnewKcAZK0OpR5mZEW/vFlKp8XQcnr3li1//yIqp7UTrdvnbYB75u4qVFGdCMqnCvBFp/Ydb34h6YpK+IQwHrT8qwz0Fj0kCjPJ6fDiwJoH87riY0PFedQf/SCE0onMzAmWFWrEV7KZe6QxBXxGYdsHZWLRjntlKBtCiEFROFQmKWv/n7IjwuuU3sTp+NVD4eR042pvFEJ6KYnH89WJHu0HvsDZSkxeWnnMfwrtqWCvY7tPyTWUw9h8+QSEUjcP0zVxwmblQlwzsE6gFaWtcfpNAzXDLGod7IcROdRS1l81I2wOHtRvV5ZjnPpn7MqQWmi1/ew70ONTGX3J5Qli5E5C0Up3MVn0XfWQTr+sVNLNNcorZvANrMgBaleVM4kxBlRQZxVZMSnyNBvaMYxCqy8PZd2D/oieUbxf0X60e0mQr1wfuwyEJSo4xvBVv67/811bFKgubENdfpgnsdXC4DJ/vyJ/vmbuCJcGUPhXi2Tyz1uWDNgkA7xIDVEG0nQuVEBuwrY6EYefGvPRkM8ls6K5rLdFUSGcE1LESzh+SRWfBp/7jVFHC/SEKY/LAJk7aZwRHnlA0mLIoR1gFqRXCP5KPhCCeV10PddI82DXWqaxaNzInrwcFsn5rkR8dhNXOen93Ia0krYdty2Qn9ubcjIa1ltYVsSM6hcnvivegEXwO+umhHHmrw9UUY8gtZWh6TXRxESxC1OooGkQ5T5GteSoNdSvfDAIq/IgHhWKUMdXia5l3jJxg6kHC44cOi2l7HkmI3te3FGGEypWHG6IlzVWe1sxYpkT1fDfPDCfALy2/msKVLnUrla++178=">

    <input type="hidden" value="fbfb6afe3ed1ac9ca453636c5642752b" id="jschl-vc" name="jschl_vc">

    

    <input type="hidden" name="pass" value="1623864507.539-NZEYWL2bol">

    <input type="hidden" id="jschl-answer" name="jschl_answer">
      

>

     

    <script type="text/javascript">

      //<![CDATA[

      (function(){

          var a = document.getElementById('cf-content');

          a.style.display = 'block';

          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);

          var trkjs = isIE ? new Image() : document.createElement('img');

          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=6605c11b1a204c1a");

          trkjs.id = "trk_jschal_js";

          trkjs.setAttribute("alt", "");

          document.body.appendChild(trkjs);

          var cpo=document.createElement('script');

          cpo.type='text/javascript';

          cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=6605c11b1a204c1a";

          document.getElementsByTagName('head')[0].appendChild(cpo);

        }());

      //]]>

    </script>

  


  

  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=6605c11b1a204c1a')"> </div>

</div>


          

          <div class="attribution">

            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>

            <br>

            <span class="ray_id">Ray ID: <code>6605c11b1a204c1a</code></span>

          </div>

      </td>

     
      

>

  </tbody></table><img src="/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=6605c11b1a204c1a" id="trk_jschal_js" alt="">



</body></html>

2021-06-16T17:30:18+00:00 INFO REQ-2 Cloudflare detected

2021-06-16T17:30:18+00:00 DEBUG REQ-2 Javascript challenge element '#trk_jschal_js' detected.

2021-06-16T17:30:18+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...

2021-06-16T17:30:18+00:00 DEBUG REQ-2 Challenge element is visible.

2021-06-16T17:30:18+00:00 DEBUG REQ-2 Found challenge element again.

2021-06-16T17:30:18+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...

2021-06-16T17:30:19+00:00 DEBUG REQ-2 Challenge element is visible.

2021-06-16T17:30:19+00:00 DEBUG REQ-2 Found challenge element again.

2021-06-16T17:30:19+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...

2021-06-16T17:30:20+00:00 DEBUG REQ-2 Challenge element is visible.

2021-06-16T17:30:20+00:00 DEBUG REQ-2 Found challenge element again.

2021-06-16T17:30:20+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...

2021-06-16T17:30:21+00:00 DEBUG REQ-2 Challenge element is visible.

2021-06-16T17:30:21+00:00 DEBUG REQ-2 Found challenge element again.

2021-06-16T17:30:21+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...

2021-06-16T17:30:22+00:00 DEBUG REQ-2 Challenge element is visible.

2021-06-16T17:30:22+00:00 DEBUG REQ-2 Found challenge element again.

2021-06-16T17:30:22+00:00 DEBUG REQ-2 Waiting for Cloudflare challenge...

2021-06-16T17:30:23+00:00 DEBUG REQ-2 Challenge element not found.

2021-06-16T17:30:23+00:00 DEBUG REQ-2 Validating HTML code...

2021-06-16T17:30:23+00:00 DEBUG REQ-2 Javascript challenge selectors found: 1, total selectors: 4

2021-06-16T17:30:23+00:00 INFO REQ-2 Challenge solved.

2021-06-16T17:30:23+00:00 INFO REQ-2 Response in 5.913 s

**Comment by ngosang** [comment]
Cloudflare is disabled at this moment.
