### ISSUE TITLE
User-Agent detected by CouldFlare (Docker ARM)

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#15]
FlareSolverr 1.2.0
Docker ARM32

The default User-Agent in ARM is `Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36`
This User-Agent is detected by CouldFlare.

Steps to reproduce:
Fails:
```
{
    "cmd": "request.get",
    "url": "https://yggtorrent.si/",
    "maxTimeout": 60000
}
```

Works:
```
{
    "cmd": "request.get",
    "url": "https://yggtorrent.si/",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36",
    "maxTimeout": 60000
}
```

I think we should use the Windows User-Agent when the user doesn't set it.

**Comment by abeloin** [comment]
Since we are using version 81 from alpine wouldn't be better for it to be?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

**Comment by ngosang** [comment]
Yes, you are right. I have tested several sites and It's working for me but fell free to open a PR to change it.
Take a look at your email. You should have an invitation.
