### ISSUE TITLE
Exception (): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported 

### ISSUE THREAD

**Issue by jphp0** [FlareSolverr/FlareSolverr#152]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: [yes/no]
* **Are you using a proxy or VPN?** [yes/no]
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by Tomarok** [comment]
Same probleme for me

**Comment by noxzobax** [comment]
Same here since yesterday  and for two friend of me. It's very strange cause sometimes it was working and sometimes not, but now it completely done and not working anymore. 

### Environment

- FlareSolverr version: 1.2.8
- Last working FlareSolverr version: 1.2.8
- Operating system: Tested on Windows/Linux/Synology
- Are you using Docker: yes
- Are you using a proxy or VPN? I've tried with and without
- Are you using Captcha Solver: yes
- If using captcha solver, which one: hcaptcha-solver
- URL to test this issue: I'm sorry I've no url

At the first time I had this error:

> Error on 20210606194204 for YGGtorrent.txtFlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)    at FlareSolverrSharp.Solvers.FlareSolverr.&lt;&gt;c__DisplayClass5_0.&lt;&lt;Solve&gt;b__0&gt;d.MoveNext()




Then this one:

> Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported #31.  ---&gt; FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: hcaptcha-solver is not able to solve the new hCaptcha challenge. This issue is already reported #31.    at FlareSolverrSharp.Solvers.FlareSolverr.&lt;&gt;c__DisplayClass5_0.&lt;&lt;Solve&gt;b__0&gt;d.MoveNext()

**Comment by SmarLat** [comment]
Here we go again...

**Comment by WoisWoi** [comment]
I'm experiencing the same issue (1.2.8 version).

**Comment by BedoM** [comment]
1.2.8 same

**Comment by BenZiia** [comment]
Hello,

Just use v1.2.7, it works.

On docker, instead of usijng flaresolverr/flaresolverr:latest , use flaresolverr/flaresolverr:v1.2.7

**Comment by WoisWoi** [comment]
> 
> 
> Hello,
> 
> Just use v1.2.7, it works.
> 
> On docker, instead of usijng flaresolverr/flaresolverr:latest , use flaresolverr/flaresolverr:v1.2.7

Not working for me

**Comment by a2re** [comment]
> Hello,
> 
> Just use v1.2.7, it works.
> 
> On docker, instead of usijng flaresolverr/flaresolverr:latest , use flaresolverr/flaresolverr:v1.2.7

Thanks, this version works for me too
