### ISSUE TITLE
H_captcha changed their way ?

### ISSUE THREAD

**Issue by YggNode** [FlareSolverr/FlareSolverr#156]
Hello,

on https://www4.yggtorrent.li/, it's not working anymore.

for me, it seems h_captcha changed the way they're processing challenge :
when i make a basic request on it, i got all hcaptcha page code source, and moreover (i didn't see it before), a cookie like that :

```
"cookies": [
            {
                "name": "cf_chl_prog",
                "value": "a9",
                "domain": "www4.yggtorrent.li",
                "path": "/",
                "expires": 1623081952,
                "size": 13,
                "httpOnly": false,
                "secure": false,
                "session": false
            }
        ]
```

Their doc about how their system works if you interested in.
https://docs.hcaptcha.com/

Great thanks for all your work.

**Comment by SmarLat** [comment]
Hope it will be fixed soon!

**Comment by BenZiia** [comment]
Hello,

Just use v1.2.7, it works.

On docker, instead of usijng flaresolverr/flaresolverr:latest , use flaresolverr/flaresolverr:v1.2.7
