### ISSUE TITLE
[Question] - Docker how to connect FlareSolverr and Jackett?

### ISSUE THREAD

**Issue by Jorman** [FlareSolverr/FlareSolverr#159]
Hi, I'm running Jackett and FlareSolver in docker,
FlareSolver have his network `flaresolverr_default` and Jackett is under the default `bridge` network
I tried to put the FlareSolver docker ip inside Jackett configuration but I can't get it working, so in Jackett side I tried
`http://172.27.0.2/16:8191`
`http://flaresolverr:8191`
`http://localhost:8191`
I know that is a pretty noob question, but I don't know how to connect Jackett to FlareSolver, also because every time the ip of FlareSolver changes. I searched a bit and seems that I can connect docker to more than one network, but I get some difficult to do that.

Any help will be appreciated

J

**Comment by ngosang** [comment]
The easiest way is to use a docker-compose.yml file with both services. They will be in the same network and you can use `http://flaresolverr:8191`
You can accomplish  the same thing without docker-compose, just make sure both services are in the dame Docker network, not bridge.

**Comment by Jorman** [comment]
Yes, thank you, @ngosang, I'll to it
