### ISSUE TITLE
Empty or Incorrect Solution Response

### ISSUE THREAD

**Issue by Prince25** [FlareSolverr/FlareSolverr#162]
### Environment

* **FlareSolverr version**: v1.2.8
* **Last working FlareSolverr version**: v1.2.6
* **Operating system**: Windows
* **Are you using Docker**: no
* **Are you using a proxy or VPN?** yes
* **Are you using Captcha Solver:** no
* **URL to test this issue:** https://www.meshmonitors.com/products.json?limit=250&page=1

### Description
Trying to test scraping program on the provided URL. The solution response is an empty HTML, `<html><head></head><body></body></html>`. Here is the entire response object (changed it to `txt` since I cannot upload `json`): [emptyWithHeadless.txt](https://github.com/FlareSolverr/FlareSolverr/files/6680310/emptyWithHeadless.txt)

However, setting `HEADLESS` to `false` produced interesting results. The solution response HTML is the "This www.meshmonitors.com page can’t be found" (screenshot 2) page you normally see nonexistent domains. The kicker is that by observing the browser, I see the desired page after the Cloudflare page (screenshot 1 below) but it changes to the "no webpage found" page for a split second before closing. Here is the HTML page with the `txt` extension: [NoWebpageWithoutHeadless.txt](https://github.com/FlareSolverr/FlareSolverr/files/6680318/NoWebpageWithoutHeadless.txt) and the object `json` file: 
[NoWebpageWithoutHeadlessJSON.txt](https://github.com/FlareSolverr/FlareSolverr/files/6680320/NoWebpageWithoutHeadlessJSON.txt).

Flaresolverr had been working just fine until update v1.2.7 and beyond. Tried debug mode and HTML trace but it wasn't helpful though it did say "page navigated away" a couple of times.

### Screenshots
![The desired HTML](https://user-images.githubusercontent.com/28243638/122636500-6e5e0e00-d09e-11eb-9b02-2b0cc90ddebe.png)
![Page not found](https://user-images.githubusercontent.com/28243638/122637095-b2064700-d0a1-11eb-9e94-6559ca85fc17.png)

**Comment by ngosang** [comment]
FlareSolverr v1.2.9
