### ISSUE TITLE
How To Deploy On Heroku?

### ISSUE THREAD

**Issue by alexpandain** [FlareSolverr/FlareSolverr#179]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: [yes/no]
* **Are you using a proxy or VPN?** [yes/no]
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
You can deploy the Docker image anywhere.
If you want to build your own software, It will work and you will be able to bypass Cloudflare.
If you want to use with Jackett it's not going to work because both services must be in the same network.

**Comment by erickyun** [comment]
> You can deploy the Docker image anywhere. If you want to build your own software, It will work and you will be able to bypass Cloudflare. If you want to use with Jackett it's not going to work because both services must be in the same network.

İf Jackett was also deployed on Heroku would it still not work then?
