### ISSUE TITLE
Windows installer / executable

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#18]
For now Windows users can install it for source code. It's working.
https://github.com/FlareSolverr/FlareSolverr#from-source-code

Doc:
* https://github.com/vercel/pkg
* https://github.com/nexe/nexe

**Comment by Wells83** [comment]
hi, i have test a windows installation, when i tst with jackett:

2020-12-14T15:39:05.878Z INFO REQ-21 Incoming request: POST /v1
2020-12-14T15:39:05.878Z INFO REQ-21 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.yggtorrent.si/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2020-12-14T15:39:06.859Z INFO REQ-21 Cloudflare detected
2020-12-14T15:40:10.089Z ERROR REQ-21 Maximum timeout reached. maxTimeout=60000 (ms)

**Comment by TheNexter** [comment]
Approuved, we need a windows version, or a jackett integration in .exe

**Comment by Wilson2013** [comment]
Yes Please!! Can it be made to work with Win 7 64-bit please? I noticed that newer versions of NodeJS won't install on Windows 7. 

Thanks!!!!

**Comment by TheNexter** [comment]
Up, so important to be popular and adopted

**Comment by TheNexter** [comment]
.exe is here, unzip them inside the folder "dist"

Edit the path in the file "auto" and "dist.bat" and add to task planner the .vbs to launch automaticaly the flaresolverr at start, thx to the french discord team
[dist.zip](https://github.com/FlareSolverr/FlareSolverr/files/5776252/dist.zip)

**Comment by ngosang** [comment]
Windows executable is available:
https://github.com/FlareSolverr/FlareSolverr#precompiled-binaries

**Comment by ngosang** [comment]
@ilike2burnthing @garfield69 fyi

**Comment by 3xploiton3** [comment]
sorry how to install in windows 10 and fill FlareSolverr API URL (from jackett)
instruction unfamilliar for me

![image](https://user-images.githubusercontent.com/19517680/104148749-1859b000-5406-11eb-8474-1bb676072410.png)
![image](https://user-images.githubusercontent.com/19517680/104148750-1d1e6400-5406-11eb-8209-abb057bb2531.png)

**Comment by TheNexter** [comment]
![image](https://user-images.githubusercontent.com/17613028/104297723-7b5d4c80-54c3-11eb-8b10-3d03d0d44f12.png)

in jackett

http://iplocalofyourpc:8191

**Comment by WalidOuld** [comment]
thanks a lot for the update.
do you have any idea on how to make it launch on startup and minimized just as jackett ? it would be great.
thanks again 👍

**Comment by TheNexter** [comment]
> thanks a lot for the update.
> do you have any idea on how to make it launch on startup and minimized just as jackett ? it would be great.
> thanks again 👍



[flaresolverr.zip](https://github.com/FlareSolverr/FlareSolverr/files/5817056/flaresolverr.zip)
Launch .vbs with task planner windows, modify .bat and .vbs with good adress of flaresolver.exe (in bat) and .bat (in vbs)

**Comment by ngosang** [comment]
I have this issue to work on the auto-start => #70
@TheNexter maybe you can open a PR. The only requirement is to not use VBS, just bat.
