### ISSUE TITLE
Request made by axios fails with error: 'Cloudflare Error: No challenge selectors found, unable to proceed'

### ISSUE THREAD

**Issue by mgeorgetw** [FlareSolverr/FlareSolverr#182]
### Environment

* **FlareSolverr version**: 1.2.9
* **Operating system**: macOS Big Sur
* **Are you using Docker**: No.
* **Are you using a proxy or VPN?:** No.
* **Are you using Captcha Solver:** No.
* **URL to test this issue:** https://www.wantgoo.com/investrue/wtxm&/historical-five-minutes-candlesticks?before=1628734873370

### Description

I am trying to access some JSON from [this url](https://www.wantgoo.com/investrue/wtxm&/historical-five-minutes-candlesticks?before=1628734873370) using [axios](https://github.com/axios/axios) for Node.js, but it always return "403 Forbidden" as well as a FlareSolverr error: "Cloudflare Error: No challenge selectors found, unable to proceed". 

Interestingly, I am able to access other urls from this site (like [this one](https://www.wantgoo.com/investrue/wtxm&/realtimeprice?equalandafter=1628756640508)) with axios and FlareSolverr just fine. And sometimes `curl` can return the correct JSON, but axios always fails.

**Comment by ngosang** [comment]
Fixed in [FlareSolverr v2.0.0](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.0.0)
If you are using Jackett, version v0.18.1041 or higher is required to bypass Cloudflare.
