### ISSUE TITLE
Use as library (not proxy server)

### ISSUE THREAD

**Issue by Revadike** [FlareSolverr/FlareSolverr#189]
Would you consider adding support for using `FlareSolverr` as node.js library (without running a proxy server)?
Something like this, maybe:

```js
const FlareSolverr = require("FlareSolverr");

(async() => {
  let result = await FlareSolverr.exec({
    "cmd": "request.get",
    "url":"http://www.google.com/",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleW...",
    "maxTimeout": 60000,
    "headers": {
      "X-Test": "Testing 123..."
    }
  });
  
  console.log(result); // <!DOCTYPE html> <html lang="en" ...
})();
```

**Comment by DRSDavidSoft** [comment]
Additionally, it would be nice to expose Pupetter in the `FlareSolverr` too, so maybe it would be possible to use Pupetter plugins (e.g. Userscripts or browser plugins, such as AdsBypasser and FastForward)

**Comment by ngosang** [comment]
I don't have interest in develop this myself but I'm open to accept PRs.

**Comment by ngosang** [comment]
FlareSolverr v3 is in Python. This issues does not apply anymore.

**Comment by Revadike** [comment]
Ew, python! 🤢
