### ISSUE TITLE
2.0.0 won't start on Debian Buster

### ISSUE THREAD

**Issue by fana13** [FlareSolverr/FlareSolverr#206]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.0.0
* **Last working FlareSolverr version**: 1.2.9
* **Operating system**: Debian Buster
* **Are you using Docker**: No
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?**  Yes
* **Are you using Captcha Solver:**  No
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

When i launch command : npm start in /opt/FlareSolverr, i've got a timeout error

### Logged Error Messages

```
npm start

> flaresolverr@2.0.0 start
> node ./dist/server.js

2021-10-23T12:34:48+02:00 INFO FlareSolverr v2.0.0
2021-10-23T12:34:48+02:00 INFO Testing web browser installation...
/opt/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:170
            reject(new Errors_1.TimeoutError(`Timed out after ${timeout} ms while trying to connect to the browser! Only Chrome at revision r${preferredRevision} is guaranteed to work.`));
                   ^

TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r95.0a1 is guaranteed to work.
    at Timeout.onTimeout (/opt/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:170:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

Node.js v17.0.1

```

**Comment by ngosang** [comment]
I think the issue is your machine is not faster enough. I added a new environment var in v2.0.2 to set the timeout but I'm not sure if it will fix your issue.

**Comment by fana13** [comment]
Now with latest update, i've got this error : 
```
npm start

> flaresolverr@2.0.2 start
> node ./dist/server.js

2021-11-01T08:29:40+01:00 INFO FlareSolverr v2.0.2
2021-11-01T08:29:40+01:00 INFO Testing web browser installation...
2021-11-01T08:29:41+01:00 ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://localhost:37707/devtools/browser/5cee41f0-f42e-40b6-bc6d-9e099406b0ec',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'connect ECONNREFUSED ::1:37707',
  error: Error: connect ECONNREFUSED ::1:37707
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 37707
  }
}
```

**Comment by ngosang** [comment]
I have no clue. I recommend you to use the Docker image instead.

**Comment by fana13** [comment]
Yes with Docker image, it works like a charm.
I really don't understand why i've got this error...
Thanks for all by the way
