### ISSUE TITLE
How should I write postdata ?

### ISSUE THREAD

**Issue by DevDavid1307** [FlareSolverr/FlareSolverr#223]
### Environment

* **FlareSolverr version**: 2.0.2
* **Last working FlareSolverr version**:
* **Operating system**: mac
* **Are you using Docker**: no
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** yes
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://sweepwidget.com/cdn-cgi/bm/cv/result?req_id=6afd74e08f4c3523

### Description

the postdata format is "a=1&b=1"，But there are objects and arrays in my request，How should I write postdata?

### Screenshots

![image](https://user-images.githubusercontent.com/16041023/142365849-36fbde57-9edc-4a0c-b012-37bd3bda17ad.png)

**Comment by ngosang** [comment]
Sorry but is not supported and it can not be fixed by FlareSolverr (the bug is in Puppter/Firefox). I recommend you to use FlareSolverr to grab the cookie and write your own script => https://github.com/FlareSolverr/FlareSolverr/discussions/222
