### ISSUE TITLE
dummy.test

### ISSUE THREAD

**Issue by somedevreally** [FlareSolverr/FlareSolverr#227]
hello,
am using flaresolverr docker container, and its been hitting `dummy.test` every few seconds
![image](https://user-images.githubusercontent.com/26795436/142931145-ed311b2b-9261-48cf-9897-cfba7a626859.png)

thanks

**Comment by ngosang** [comment]
I see that too. I can't find what is the purpose but Firefox makes a request on each start to check something.
I don't know how to disable that on Firefox but you it is not harmful because that domain does not exist.
