### ISSUE TITLE
FlareSolverr logo

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#23]
We need a logo but I don't have the skills.
* Cloud + circular arrows can be fine

**Comment by TheNexter** [comment]
English is not my language but i have proposition for you
![image](https://user-images.githubusercontent.com/17613028/103099846-5e460400-4610-11eb-9461-c2d32cf54901.png)
If you want the vector, say to me

**Comment by ngosang** [comment]
I don't like the red cross. Could you send another proposal in svg?

**Comment by ilike2burnthing** [comment]
Just an idea, not a final design (it's very patched together) - https://www.svgviewer.dev/s/1UpzKoGA
