### ISSUE TITLE
idope and prostylex unable to connect to server

### ISSUE THREAD

**Issue by lukjod** [FlareSolverr/FlareSolverr#241]
Flaresolverr 2.0.2 and Prowlarr newest from docker always give me error about connection:

log:
HTTP Error - Res: [POST] http://192.168.1.197:8191/v1: 500.InternalServerError
{"status":"error","message":"Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=60000 (ms)","startTimestamp":1639162346107,"endTimestamp":1639162411826,"version":"v2.0.2"}

**Comment by ilike2burnthing** [comment]
Likely an extension of https://github.com/FlareSolverr/FlareSolverr/issues/234

Free up resources, increase the browser timeout, and keep retrying.

**Comment by lukjod** [comment]
how to increase browser timeout on flaresolverr dosker, which file should I change?

**Comment by lukjod** [comment]
how to increase browser timeout on flaresolverr dosker, which file should I change?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by lukjod** [comment]
right, did it but afaik for change of maxTimeout is responsible Prowlarr, change only of BROWSER_TIMEOUT didn't help, I ve asked them on discord maybe they will do smthg about it
