### ISSUE TITLE
Docker + Raspberry pi 4 + Fatal error in , line 0

### ISSUE THREAD

**Issue by Jamyz** [FlareSolverr/FlareSolverr#247]
### Environment

* **v2.0.2**:
* **Raspbian GNU/Linux 10 (buster)**:
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using Captcha Solver:** no
```
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ea5d58c

```

**Comment by ngosang** [comment]
It's working fine for me in the same hardware.
Try with the latest release and read careful the install instructions.

**Comment by Jamyz** [comment]
> the latest releas
