### ISSUE TITLE
Fatal error on startup

### ISSUE THREAD

**Issue by WazoAkaRapace** [FlareSolverr/FlareSolverr#258]
### Environment

* **FlareSolverr version**: 2.1.0
* **Last working FlareSolverr version**: idk
* **Operating system**: Raspberry Pi 3 - Raspbian Buster
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: not this far...
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no

### Description

Starting flaresolverr with the default docker compose file. It was working like a month ago... 

### Logged Error Messages
All the logs displayed are here : 
```flaresolverr    |
flaresolverr    |
flaresolverr    | #
flaresolverr    | # Fatal error in , line 0
flaresolverr    | # unreachable code
flaresolverr    | #
flaresolverr    | #
flaresolverr    | #
flaresolverr    | #FailureMessage Object: 0x7e8415bc
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/211#issuecomment-962504356

**Comment by WazoAkaRapace** [comment]
Fixed by updating libseccomp2
```
wget https://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.3-2_armhf.deb
dpkg -i libseccomp2_2.5.3-2_armhf.deb
```
