### ISSUE TITLE
The cookies provided by FlareSolverr are not valid [Cinecalidad.lat]

### ISSUE THREAD

**Issue by angel-lizander** [FlareSolverr/FlareSolverr#263]
Using docker, with docker compose, same container, same device, same network, same type. Tested on different enviroment. 

Even not using docker, I got the same error. No IPV6. 

Flaresolverr return there's no cloudfire to resolve, and the request was sucess without any error, but Jackett insist theres something to resolve. Finally I got this error .

![Captura de pantalla 2021-12-19 011226](https://user-images.githubusercontent.com/31111274/146664696-21807f96-6578-46ec-92ef-f0dcbbf3bea1.png)

**Comment by AntoineLemaire** [comment]
Hello, there is the same issue with YggTorrent
I'm also using docker to install it, lastest image v2.1.0

![image](https://user-images.githubusercontent.com/2025537/146726577-1af3d4e2-6d27-4b1e-b94b-99f0fedffd5c.png)

**Comment by ngosang** [comment]
@ilike2burnthing can you reproduce this issue? It's working fine for me in Cinecalidad and YGGtorrent.

**Comment by ilike2burnthing** [comment]
I don't get any Cloudflare page for Cinecalidad, enhanced logs show the correct HTML for the site (although Jackett is saying no results have been found).

YGGtorrent is working fine.

On rare occasion I have had this issue with some sites though - Jackett says the cookies are invalid, but FlareSolverr says Cloudflare wasn't detected and it was successful. Of course I go to try find an example for you, but everything is working at the moment.

Looks like a user had the same issue with 1337x - https://github.com/FlareSolverr/FlareSolverr/issues/225 (@soggychips is that still the case?)

@ngosang would enhanced Jackett and/or debug FlareSolverr logs be enough for you work with even if you can't replicate it yourself?

**Comment by ngosang** [comment]
I see that error from time to time but it's hard to replicate. I think FlareSolverr is working well most of the time, if this issue becomes more common I will reopen the issue.

**Comment by Zamana** [comment]
The first time I configured FlareSolverr correctly, it didn't "work" for 1337x. But the next day the access to 1337x was working fine. So I guess that you need to let FlareSolverr "polling" the site, and then it will eventually works...

Thanks what I think.

**Comment by soggychips** [comment]
> Looks like a user had the same issue with 1337x - #225 (@soggychips is that still the case?)
> 

This is absolutely still the case. It still does not work for 1337x. It's been a couple months now at this point.

The symptoms are identical to yours: "Flaresolverr return there's no cloudfire to resolve, and the request was sucess without any error, but Jackett insist theres something to resolve"

**Comment by ngosang** [comment]
Change the 1337 domain in Jackett. These are working for me:
* https://1337x.unblockit.how/
* https://1337x.nocensor.biz/
