### ISSUE TITLE
FlareSolverr aborts during build

### ISSUE THREAD

**Issue by Locutus64** [FlareSolverr/FlareSolverr#267]
I'm attempting to install FlareSolver to work with Jackett and it aborts before it stats building. I'm assuming from the below it's a permissions issue. Any suggestion on how to correct it? Thanks

Manjaro KDE 21.2rc1 Arch based
Latest Jacket-Develop version

~~~
  -> Found flaresolverr.sysusers
  -> Found flaresolverr.tmpfiles
==> Validating source files with sha512sums...
    flaresolverr-v2.0.2-linux-x64.zip ... Passed
    flaresolverr.sysusers ... Passed
    flaresolverr.tmpfiles ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting flaresolverr-v2.0.2-linux-x64.zip with bsdtar
==> Entering fakeroot environment...
==> Starting package()...
chown: invalid user: ‘flaresolverr:flaresolverr’
==> ERROR: A failure occurred in package().
    Aborting...
~~~

**Comment by ngosang** [comment]
The user `flaresolverr` is created during installation with AUR package.
https://aur.archlinux.org/packages/flaresolverr-bin/

If it's not working you you take a look at the comments. Some user posted a command to create the user manually.

**Comment by snakyjake1** [comment]
https://aur.archlinux.org/packages/flaresolverr-bin#comment-841766

sudo useradd --system --shell=/usr/sbin/nologin flaresolverr
