### ISSUE TITLE
[pirateiro] Exception (pirateiro): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### ISSUE THREAD

**Issue by 3xploiton3** [FlareSolverr/FlareSolverr#269]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.0.2
* **Last working FlareSolverr version**:
* **Operating system**: windows 11
* **Are you using Docker**: [/no]
* **FlareSolverr User-Agent (see log traces or / endpoint)**: 
* **Are you using a proxy or VPN?** [/no]
* **Are you using Captcha Solver:** [/no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
Update to FlareSolverr >= 2.1.0

**Comment by jasonshearer** [comment]
Same issue and I am running 2.1.0
