### ISSUE TITLE
32 bit ARM docker image fails to start

### ISSUE THREAD

**Issue by SmartBoy84** [FlareSolverr/FlareSolverr#273]
When starting the docker image using docker-compose, I get the following string of errors:

> flaresolverr exited with code 133
flaresolverr  |
flaresolverr  |
flaresolverr  | #
flaresolverr  | # Fatal error in , line 0
flaresolverr  | # unreachable code
flaresolverr  | #
flaresolverr  | #
flaresolverr  | #
flaresolverr  | #FailureMessage Object: 0x7e89358c

**Comment by SmartBoy84** [comment]
Adding `privileged: true` to the docker-compose.yml file seems to fix it but I feel like that's not an ideal solution so I'll leave this open until a contributor sees and decides to close it.

**Comment by ngosang** [comment]
I have a Raspberry Pi 4 with ARM32 and It's working well without the privileged flag.
Since there is a workaround I'm closing this issue if you don't matter.
