### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.: Parse error (Test)

### ISSUE THREAD

**Issue by MozkaTeacher** [FlareSolverr/FlareSolverr#274]
### Environment

* **FlareSolverr version**: 2.1.0
* **Operating system**: Debian 10
* **Are you using Docker**: yes
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no

### Description

Hello suddenly FlareSolver stopped to work for on of my indexer. Can you please help me ?

### Error Messages

FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.

### Screenshots

![2EABAAFD-D182-41EE-A375-2BDB8719E0B0](https://user-images.githubusercontent.com/43102748/147793813-50f58822-94c0-4036-9144-c529cbdea286.jpeg)

**Comment by ilike2burnthing** [comment]
Make sure the site link you're using is - https://www3.yggtorrent.re/

Can you access the site in browser from the same device and IP?

**Comment by ngosang** [comment]
Probably the user IP is blocked so nothing we can do.
