### ISSUE TITLE
 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by leekyy** [FlareSolverr/FlareSolverr#275]
### Environment

* **FlareSolverr version**: 2.10
* **Last working FlareSolverr version**: no
* **Operating system**: macos12.1
* **Are you using Docker**: no
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** yes
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://www.google.com/

### Description

The following errors will appear about 2 minutes after I run `npm start`

### Logged Error Messages

❯ npm start                       

> flaresolverr@2.1.0 start
> node ./dist/server.js

2022-01-03T00:23:05+08:00 INFO FlareSolverr v2.1.0
2022-01-03T00:23:05+08:00 INFO Testing web browser installation...
2022-01-03T00:23:36+08:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/leek/Sites/FlareSolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (/Users/leek/Sites/FlareSolverr/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/Users/leek/Sites/FlareSolverr/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/Users/leek/Sites/FlareSolverr/node_modules/puppeteer/lib/helper.js:95:27)
    at testWebBrowserInstallation (/Users/leek/Sites/FlareSolverr/dist/services/sessions.js:75:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Screenshots

![image](https://user-images.githubusercontent.com/20851015/147882263-d91df167-1782-4035-990b-03c77b97e888.png)

**Comment by leekyy** [comment]
when i try change  puppeteer to latest version，the project is runing。

**Comment by arpitgupta** [comment]
I am seeing a similar issue in my container running on synology nas.

**Comment by leekyy** [comment]
> 

It's not just synology nas. I've tried docker in synology, MacOS, win10 and CentOS. Without exception, they all have problems.

**Comment by leekyy** [comment]
> I am seeing a similar issue in my container running on synology nas.
> 
> ```
> 
> 2022-01-07T05:46:41+00:00 INFO FlareSolverr v2.1.0
> 2022-01-07T05:46:41+00:00 INFO Testing web browser installation...
> 2022-01-07T05:47:16+00:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
>     at /home/node/flaresolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
>     at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:70:21)
>     at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:295:16)
>     at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:16)
>     at async testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:75:5)
>   -- ASYNC --
>     at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
>     at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
>     at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
>     at testWebBrowserInstallation (/home/node/flaresolverr/dist/services/sessions.js:75:16)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```

It's not just synology nas. I've tried docker in synology, MacOS, win10 and CentOS. Without exception, they all have problems.

**Comment by arpitgupta** [comment]
Ah i just looked at the timeout error. I built the docker image from source on my nas and running a container from that has at least for now cleared up the issue for me. May be we just need a new build published.

**Comment by ngosang** [comment]
That error could be caused by:
* You hardware is not powerful enough (or you don't have enough free resources). You can try to increase the `BROWSER_TIMEOUT` => https://github.com/FlareSolverr/FlareSolverr#environment-variables
* FlareSolverr is not installed correctly. The Docker images are well tested but I don't have hardware to test MacOS or NAS.

I think you are mixing different issues in this one. If you want help, please, provide clear information about how you installed FlareSolver (Docker or source code), OS and hardware.

> when i try change puppeteer to latest version，the project is running

@leekyy I think it's unlikely that it will fix this issue. Could yo do more tests?

**Comment by jamesmacwhite** [comment]
I've hit this on Windows precompiled binary with 2.1.0. It worked fine until recently, but now constantly fails on the web browser test. Downgrading back to 2.0.2 solved it, but weird that it has been working before.

RAM wise I have 24 GB with 8 GB in use, so memory is not constrained.

**Comment by ngosang** [comment]
FlareSolverr 2.2.0 is released. That version includes important changes related to this issue.

**Comment by QAQQL** [comment]
I encountered the same problem, but I solved it with the following configuration
![图片](https://user-images.githubusercontent.com/51136763/208558092-50451049-d20c-45a4-accd-b32264d6fad6.png)

![图片](https://user-images.githubusercontent.com/51136763/208557885-06c35bf6-22cd-4acb-a82a-3ab6293e516b.png)
