### ISSUE TITLE
How do I run FlareSolverr as a non-service?

### ISSUE THREAD

**Issue by snakyjake1** [FlareSolverr/FlareSolverr#281]
### Description
How do I run FlareSolverr as a non-service?
I've installed FlareSolverr on Arch Linux via AUR.
I am using Jackett.

### Environment

* **Operating system**: Arch Linux
* **Are you using Docker**: No

**Comment by ngosang** [comment]
I recommend you to keep it as a service but it is possible to run as user.

Disable Systemd service:
1. `systemctl stop flaresolverr`
2. `systemctl disable flaresolverr`

Run as "flaresolverr" user:
1. `runuser -l flaresolverr -c '/usr/bin/flaresolverr'`

https://aur.archlinux.org/packages/flaresolverr-bin
