### ISSUE TITLE
Is there a forum for flareSolverr?

### ISSUE THREAD

**Issue by SmoothAdmin** [FlareSolverr/FlareSolverr#285]
I am a Windows user that doesn't code. I need to understand the steps better to configure FlareSolverr once its up and running and I am able to connect to local IP:8191 using the FireFox Nightly provided. 

I am using Sonarr/Jackett.

I had a qucick look on Google and didn't see anything, that's why I am asking.

Thanks,

**Comment by ilike2burnthing** [comment]
If you open http://127.0.0.1:8191 in browser on the same device that FlareSolverr is active on, what is returned?

If that's working, and Jackett is running on the same device, you should just need to add http://127.0.0.1:8191 as the FlareSolverr API URL to Jackett, apply server settings, and then test an indexer using Cloudflare's DDoS Protection.

**Comment by ngosang** [comment]
You can request help using the GitHub discussions. Issues are for bugs.
