### ISSUE TITLE
FlareSolver crashes after running for the first time.

### ISSUE THREAD

**Issue by SmoothAdmin** [FlareSolverr/FlareSolverr#289]
### Environment

* **FlareSolverr version**: 2.1.0
* **Last working FlareSolverr version**: none
* **Operating system**: Windows 2019 Server Standard Edition
* **Are you using Docker**: [yes/no] no
* **FlareSolverr User-Agent (see log traces or / endpoint)**: ??
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

After unzipping and running Flaresolverr for the first time if I close the session window and or reboot the server when I attempt to restart flaresolverr again I get this error:

Microsoft Windows [Version 10.0.17763.2452]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\SVC.Plex>cd \flaresolverr

C:\flaresolverr>flaresolverr
2022-01-31T13:21:08-05:00 INFO FlareSolverr v2.1.0
2022-01-31T13:21:08-05:00 INFO Testing web browser installation...
2022-01-31T13:21:42-05:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\Page.js:485:53)
    at Page.<anonymous> (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\helper.js:95:27)
    at testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:75:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

I am running Java version 8 Update 321, there are no other updates to Java according the control panel app. I am also running Flaresolverr as Aministrator.

**Comment by ngosang** [comment]
FlareSolverr doesn't use Java. That error could be caused by:
* Your PC is slow and you need to increase the timeout with this environment variable `BROWSER_TIMEOUT=60000`
* It could be related to Windows permissions. Try to unzip FlareSolverr in your personal folder => https://github.com/FlareSolverr/FlareSolverr/issues/282#issuecomment-1025430294

**Comment by ngosang** [comment]
Do you use Proxy?

**Comment by SmoothAdmin** [comment]
> FlareSolverr doesn't use Java. That error could be caused by:
> 
> * Your PC is slow and you need to increase the timeout with this environment variable `BROWSER_TIMEOUT=60000`
> * It could be related to Windows permissions. Try to unzip FlareSolverr in your personal folder => [Certificate error #282 (comment)](https://github.com/FlareSolverr/FlareSolverr/issues/282#issuecomment-1025430294)

.js files by normal standards are Java Script files...

My PC isn't slow, lol, its far from it. I am using an Dell R810 with 40 cores 80 threads. This VM has 12 cords at 2.4Ghz each. And 16GB of RAM. The Host files reside on 10 x 1TB SSD's. So it very far from being a slow server. While I am watching something on my Plex which is running on this server the CPU is using 1%, memory 4.3GB/16GB. 

The user account has local admin access, even still it doesn't account for when the application fails if I removed it and reboot the server and unzip and start it again it will run. Even run as Administrator under my account.

There is should be way to create a log of the output from what the app is doing for better troubleshooting.

**Comment by ngosang** [comment]
There are more users experiencing similar issues in Windows but I only use Linux and I can not reproduce the issue in my Windows VM.
The recommended way is to use the Docker container, but, if you can't you can install it from source code => https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by Jleagle** [comment]
> .js files by normal standards are Java Script files...

Just in case you didn't realise Java and JavaScript are totally unrelated, this repo only uses the latter.
