### ISSUE TITLE
container image v2.2.0: won't start (tsc not found)

### ISSUE THREAD

**Issue by Iristyle** [FlareSolverr/FlareSolverr#291]
### Environment

* **FlareSolverr version**: ghcr.io/flaresolverr/flaresolverr:latest / sha256:1c619cfb0de06d394ca4424fd59f3b7ff05afa4d2c4681eb926cca5941fcbc6f
* **Last working FlareSolverr version**: previous release (v2.1.0) - ourboros logged "flaresolverr updated from 674cc19168 to 1c619cfb0d"
* **Are you using Docker**: yes

### Description

ouroboros auto-upgraded the container image and now it immediately crashes on startup - looks like a bad build

```
> flaresolverr@2.2.0 start
> tsc && node ./dist/server.js
sh: tsc: not found
```

Interestingly Docker Hub shows:
https://hub.docker.com/layers/flaresolverr/flaresolverr/v2.2.0/images/sha256-931f3ab2659127199252dc2ae8b1182fed54b4ae54c42b99a759ad042bca978f?context=explore
Note the sha256-931f3ab2659127199252dc2ae8b1182fed54b4ae54c42b99a759ad042bca978f

While ghcr shows:
https://github.com/flaresolverr/FlareSolverr/pkgs/container/flaresolverr
Note the sha256:861d9d4edbbcf68c480b6f7267ed671def7b9fe629d7a6d1e4e0c3009a789a2b

Not sure why all the SHA256 digests are different

**Comment by Iristyle** [comment]
Bug was introduced in this commit 2 days ago - https://github.com/FlareSolverr/FlareSolverr/commit/fe6cfd75b878660e1cf2fcbcaa285331693afafa#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R6

The server can be started with `node ./dist/server.js` no problem ... but `tsc` is not part of the image

```terminal
iristyle@Ulua:/mnt/c/Users/iristyle$ docker run --rm -it ghcr.io/flaresolverr/flaresolverr:latest /bin/sh
~/flaresolverr $ find . | grep tsc
./node_modules/@tsconfig
./tsconfig.json
~/flaresolverr $ node ./dist/server.js
2022-02-01T22:03:25+00:00 INFO FlareSolverr v2.2.0
2022-02-01T22:03:25+00:00 INFO Testing web browser installation...
2022-02-01T22:03:28+00:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
2022-02-01T22:03:28+00:00 INFO Test successful
2022-02-01T22:03:28+00:00 INFO Listening on http://0.0.0.0:8191
```

**Comment by Iristyle** [comment]
Ah it's missing the typescript package in the container. Once `npm install` is performed in the container, everything is ok

```
iristyle@Ulua:/mnt/c/Users/iristyle$ docker run --rm -it ghcr.io/flaresolverr/flaresolverr:latest /bin/sh
~/flaresolverr $ npm install

added 534 packages, and audited 649 packages in 10s

54 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.4.0
npm notice Run npm install -g npm@8.4.0 to update!
npm notice


~/flaresolverr $ npm start

> flaresolverr@2.2.0 start
> tsc && node ./dist/server.js

2022-02-01T22:15:32+00:00 INFO FlareSolverr v2.2.0
2022-02-01T22:15:32+00:00 INFO Testing web browser installation...
2022-02-01T22:15:35+00:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
2022-02-01T22:15:36+00:00 INFO Test successful
2022-02-01T22:15:36+00:00 INFO Listening on http://0.0.0.0:8191
```

**Comment by Mrpink200** [comment]
hi thx for this info. i m running docker on synology, and i ve really few knoledge on it. any solution in my situation ?

**Comment by ngosang** [comment]
The Docker image does not contains `tsc` because it's not required. The entrypoint runs this command `CMD ["node", "./dist/server.js"]`

Why are you running `npm start` instead of `node ./dist/server.js` ?

**Comment by tsullyman** [comment]
> The Docker image does not contains `tsc` because it's not required. The entrypoint runs this command `CMD ["node", "./dist/server.js"]`
> 
> Why are you running `npm start` instead of `node ./dist/server.js` ?

The docker image on Synology does... I think it's broken? I just get this as well and it does not start.

"flaresolverr@2.2.0 start
> tsc && node ./dist/server.js
sh: tsc: not found"

Why is the docker image trying to use tsc on synology???

**Comment by tsullyman** [comment]
It looks like the docker image in synology tries to start using the following. 

/usr/bin/dumb-init -- npm start

Don't know if this can be changed, but its broken

**Comment by tsullyman** [comment]
I fixed it by Recreating the container as the synology wizard picks up the correct run command to use then, the original container was created when npm start worked obviously. Anyone using synology for this image would have had their image break though.

**Comment by ngosang** [comment]
I don't know anything about Synology. Where I can find the Docker image or the template you are using?
If I include `tsc` and all build dependencies in the Docker image, the size increases in 100MB so I prefer to avoid that.

**Comment by tsullyman** [comment]
I just download the image from flaresolverr/flaresolverr in the synology docker registry, it pulls from public. When deploying it originally maybe 6-12 months ago, the default settings included npm start. When I download it fresh now and re-deployed it it did not include NPM.

**Comment by Iristyle** [comment]
Correct - thanks for closing. I had looked at portainer and saw the start command was `npm start`, but should have double checked the Dockerfile in the image.

After destroying / recreating the container it picked up the correct entrypoint / cmd
