### ISSUE TITLE
How to use custom userAgent for request?

### ISSUE THREAD

**Issue by thank243** [FlareSolverr/FlareSolverr#296]
```
export interface V1RequestBase {
  cmd: string
  cookies?: Protocol.Network.CookieParam[],
  maxTimeout?: number
  proxy?: Proxy
  session: string
  headers?: Record<string, string> // deprecated v2, not used
  userAgent?: string // deprecated v2, not used
}
```
I saw that userAgent is deprecated. So how can I use custom ua now?

**Comment by ngosang** [comment]
You can't change the User-Agent anymore. FlareSolverr will use the real User-Agent from the Firefox web browser installed. Any change in the User-Agent is detected by Cloudflare.

**Comment by DRSDavidSoft** [comment]
@ngosang Is it still technically possible to use a custom user agent, even if detected by Cloudflare? Would appreciate setting it to a custom Firefox version for site-related reasons.

**Comment by ngosang** [comment]
No sorry, we have to many users to deal with the potential issues caused by changes in the UA.
You can fork this project or try to use FlareSolverr 1.x.x (with no support).
