### ISSUE TITLE
Can't access property "documentTitle", this.browsingContext.currentWindowGlobal is null

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#297]
This issue is reported with FlareSolverr 2.2.0 in Windows and CentOS.
I think it's not related to user permissions but a Firefox bug. We are using the latest nightly.
I'm not able to reproduce the issue, just once.

Related #295 #286 #289 #282

**Comment by DenysTsi** [comment]
Hey, had this issue as I had Fiddler running, I think you can reproduce with it directly.

**Comment by HLFH** [comment]
Same issue.

**Comment by ilike2burnthing** [comment]
@ngosang worth closing, as we're no longer using Firefox?

**Comment by ngosang** [comment]
Yes, FlareSolverr 3.0.0 uses Selenium with Chrome and this issue is not present.
