### ISSUE TITLE
Running as service fails

### ISSUE THREAD

**Issue by Buster14** [FlareSolverr/FlareSolverr#303]
### Environment

* **FlareSolverr version**: v2.21
* **Last working FlareSolverr version**:
* **Operating system**: Windows server 2019
* **Are you using Docker**: no
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** no 
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description
Hi, i tried registering the windows exe as service with cmd prompt

sc flaresolverrr binpath:path to flaresolverr.exe

But when i start the service it says :
Error 1053 the service did not respond to the start or request in timely fashion.

I understand i could run it as batch but it's more reliable to run it as service to ensure its continuity,
thanks

### Screenshots

[Imgur](https://imgur.com/GcpyCkR)

**Comment by ngosang** [comment]
@ilike2burnthing Could your take a look?

**Comment by ngosang** [comment]
Related #70

**Comment by ilike2burnthing** [comment]
I can recreate the issue but couldn't find a solution.

@Buster14 I'd suggest setting up a scheduled task using the files in #70.

**Comment by RogueScholar** [comment]
This behavior is present because the application fails to send the expected IPC signals to the Windows Service Control Manager (SCM) that are described [here](https://learn.microsoft.com/en-us/windows/win32/services/service-programs "Win32 Services: Service Programs").
