### ISSUE TITLE
 [epublibre] The cookies provided by FlareSolverr are not valid (Config)

### ISSUE THREAD

**Issue by jonsego** [FlareSolverr/FlareSolverr#306]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v2.2.1
* **Last working FlareSolverr version**: v2.2.1
* **Operating system**: Linux NAS 5.10.0-0.bpo.9-amd64  SMP Debian 5.10.70-1~bpo10+1 (2021-10-10) x86_64
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** [yes/no] No
* **Are you using Captcha Solver:** [yes/no] No
* **If using captcha solver, which one:**
* **URL to test this issue:** https://epublibre.unblockit.cam/catalogo/index/0/nuevo/todos/sin/todos/--/ajax

### Description
An error occurred while aading Epublibre. Flaresolverr cookies not valid. (On Jackett, on FlareSolverr dont detect cloudflare)

I have net.ipv6.conf.all.disable_ipv6=1 in both containers. I have test with host and bridge network and have ipv6 disable on the host.

### Logged Error Messages
[logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/8049070/logs.txt)

Logs from Jackett and from FlareSolverr

https://github.com/Jackett/Jackett/issues/12942

**Comment by ngosang** [comment]
I can not reproduce the issue. Try the latest version.
