### ISSUE TITLE
[1337x] Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=70000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=70000 (ms) (Test)

### ISSUE THREAD

**Issue by callaa3** [FlareSolverr/FlareSolverr#313]
### Environment

* **FlareSolverr version**: 2.1.0 Maybe new version works but I can't use that for reasons covered here: https://gist.github.com/Zamana/68060da614909ed3531acbda6154f67d
* **Last working FlareSolverr version**: N/A First install
* **Operating system**: TrueNas
* **Are you using Docker**: [yes/no] no
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Chrome I guess, no idea where logs are
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] a what? no...
* **If using captcha solver, which one:** N/A
* **URL to test this issue:** https://1337x.unblockit.cam/ and https://1337x.nocensor.biz/

### Description
First time I have used this.
For https://1337x.unblockit.cam/ I get Error 1
For https://1337x.nocensor.biz/ I get Error 2
I guess that means my Jacket install is talking to FlareSolverr OK
I have connected to Jacket install and I can curl the pages no problem. Neither blocked by my ISP. I did search but 1000 different hints for same error messages. 🙈

### Logged Error Messages

Error 1
An error occurred while testing this indexer
Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=70000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=70000 (ms)
Error 2
An error occurred while testing this indexer
Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: FlareSolverr can not resolve CAPTCHA challenges. Since the captcha doesn't always appear, you may have better luck with the next request.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: FlareSolverr can not resolve CAPTCHA challenges. Since the captcha doesn't always appear, you may have better luck with the next request.

Looks like there is no logs without Docker https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace ???

### Screenshots
Let me know if these are needed

**Comment by DVDIsDead** [comment]
>Looks like there is no logs without Docker https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace ???

literally the first part of that link tells you how to set the log level. set those environment variables before/while starting flaresolverr. -e is just how you set an environment variable inside the docker container

**Comment by ngosang** [comment]
The new domains are working for me.
https://1337x.unblockit.llc/
https://1337x.nocensor.sbs/
