### ISSUE TITLE
error " le point d'entrée de la procédure GetHostNameW est introuvable dans la bibliothèque de liens dynamique WS2_32.dll

### ISSUE THREAD

**Issue by Bmxfou** [FlareSolverr/FlareSolverr#314]
bonjour,

en voulant executé flaresolverr.exe sous windows 7 64 bit j'ai l'erreur suivante:
" le point d'entrée de la procédure GetHostNameW est introuvable dans la bibliothèque de liens dynamique WS2_32.dll

J'ai fais un sfc/ scannow et le problème reste le même j'ai bien la dll dans system32

**Comment by ngosang** [comment]
Sorry but I can not help you. Try to reinstall or install from source-code.
