### ISSUE TITLE
Flaresolverr stays blocked on CloudFlare challenge until curl timeout

### ISSUE THREAD

**Issue by bjerem** [FlareSolverr/FlareSolverr#319]
**### Environment**

* FlareSolverr version: v2.2.1
* Operating system : Docker
* Are you using Docker : yes
* FlareSolverr User-Agent : Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* Are you using a proxy or VPN? no
* Are you using Captcha Solver: no
* URL to test this issue:  https://www3.yggtorrent.re/rss/download?id=861240&passkey=MYPASSKEY

**### Description**
During script development, I tried to download a torrent file but hit the timeout set in curl request. In the debug files, we can see this information :

> 
> flaresolverr    | 2022-02-19T20:49:38+01:00 DEBUG REQ-1 Javascript challenge element '#trk_jschal_js' detected. 
> flaresolverr    | 2022-02-19T20:49:38+01:00 DEBUG REQ-1 Challenge element is visible
> flaresolverr    | 2022-02-19T20:49:38+01:00 DEBUG REQ-1 Found challenge element again
> flaresolverr    | 2022-02-19T20:49:38+01:00 DEBUG REQ-1 Waiting for Cloudflare challenge...
> flaresolverr    | 2022-02-19T20:49:39+01:00 DEBUG REQ-1 Javascript challenge element '#trk_jschal_js' detected.
> flaresolverr    | 2022-02-19T20:49:39+01:00 DEBUG REQ-1 Challenge element is visible
> flaresolverr    | 2022-02-19T20:49:39+01:00 DEBUG REQ-1 Found challenge element again
> flaresolverr    | 2022-02-19T20:49:39+01:00 DEBUG REQ-1 Waiting for Cloudflare challenge...
> flaresolverr    | 2022-02-19T20:49:40+01:00 DEBUG REQ-1 Javascript challenge element '#trk_jschal_js' detected.
> flaresolverr    | 2022-02-19T20:49:40+01:00 DEBUG REQ-1 Challenge element is visible
> flaresolverr    | 2022-02-19T20:49:40+01:00 DEBUG REQ-1 Found challenge element again
> flaresolverr    | 2022-02-19T20:49:40+01:00 DEBUG REQ-1 Waiting for Cloudflare challenge...
> flaresolverr    | 2022-02-19T20:49:41+01:00 ERROR REQ-1 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=60000 (ms)
> flaresolverr    | 2022-02-19T20:49:41+01:00 INFO REQ-1 Response in 62.689 s
> flaresolverr    | 2022-02-19T20:49:41+01:00 DEBUG REQ-1 Unexpected error: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
> flaresolverr    | 2022-02-19T20:49:41+01:00 DEBUG REQ-1 Validating HTML code...
> flaresolverr    | 2022-02-19T20:49:41+01:00 ERROR REQ-1 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been 

I encountered this issue by using the following curl command :
`curl -L -X POST "http://FLARESOLVER-IP-ADDRESS:8191/v1" -H 'Content-Type: application/json' --data-raw '{"cmd": "request.get","url": "https://www3.yggtorrent.re/rss/download?id=861240&passkey=MYPASSKEY","maxTimeout": 60000}'`

However I have no problem with this URL /Curl command : 
`curl -L -X POST "http://FLARESOLVER-IP-ADDRESS:8191/v1" -H 'Content-Type: application/json' --data-raw '{"cmd": "request.get","url":"https://www3.yggtorrent.re/rss?action=generate&type=subcat&id=2156&passkey=MYPASSKEY","maxTimeout": 60000}'`

**Comment by ngosang** [comment]
Downloading files is not supported in FlareSolverr 2.x.x #290
You can write your own script to grab the Cookies and the User-Agent from FlareSolverr and use cURL to download the tfile.
