### ISSUE TITLE
UAM improvements

### ISSUE THREAD

**Issue by YggNode** [FlareSolverr/FlareSolverr#324]
Hi,

I'm using the last version of flaresolverr (2.2.1) : no issue with but i've a few things to ask you.

It seems to me that Cloudflare improve their security and challenges at the end. You can still passthrough with flaresolverr, but when i copy/paste cookies i got from flare, with UA corresponding, i got 503 (IUAM normal reponse) while when i just copy cookies' values from firefox on my Window10 with UA related, it's working perfectly.

Can you try this and tell me if it's only on my own or if you've the same problem ?

I'll be gratefull cause i'm literaly f*** my brain on that thing since 24 hours full and i've no idea why is it doing like that...

**Comment by YggNode** [comment]
i respond to myself but i figure out what happened :

i had in mind that in previous version of flare, we could bring our personnal user agent like :
{
    "cmd": "request.get",
    "url": "https://www3.yggtorrent.re/",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
    "maxTimeout": 60000,
    "download": false
}

But i'm not seeing it now in readme : is it on purpose or no ?

and so i discovered that cloudflare linked cookies with user agent and my requests warer blocked because of that :
Flare was requesting with its UA, and then i was requesting with cookies and my UA which is not the same...

If your change is on purpose, i don't think it's a good idea but if it's not, then maybe reintroducing this option would be cool, and if you can't do it anymore because you switch on firefox then.... too bad

**Comment by alperyilmaz** [comment]
@YggNode thanks for replying to your own post bcs I also spent long time in order to figure out collecting cookie and use it with curl.
The readme says we need to use Flaresolverr UA, but it does not mention (AFAIK) what is that UA. 
So, do you know what is UA used by Flaresolverr?

**Comment by ilike2burnthing** [comment]
It's shown in the output when starting up FlareSolverr, e.g.:

```text
2022-03-19T04:39:40+00:00 INFO FlareSolverr v2.2.2
2022-03-19T04:39:40+00:00 INFO Testing web browser installation...
2022-03-19T04:40:10+00:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
2022-03-19T04:40:14+00:00 INFO Test successful
2022-03-19T04:40:14+00:00 INFO Listening on http://0.0.0.0:8191
```

**Comment by YggNode** [comment]
Hello,

@alperyilmaz that's why i'm not using the last release because my tool is configured with another UA and i don't want to have to update my code with every version of flare so that's why i'm using previous one. i think using a dedicated UA is easier to analyse for cloudflare bot while using what you want is more difficult

In this way, i can tell flare to ask for cookie with my proper UA used aswell in my code.

and for your question, UA is returned when you're doing a basic request to flare

**Comment by ngosang** [comment]
I'm using a Firefox web browser with his real User-Agent. Any change is detected by Cloudflare. I have to update Firefox from time to time to avoid detection and to fix security issues, so, the UA will change in future releases.
You can get the User-Agent from:
* The request response.
* Calling this endpoint GET http://127.0.0.1:8191/
