### ISSUE TITLE
Add Certifications, ERROR Error: SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by w4po** [FlareSolverr/FlareSolverr#326]
### Environment

* **FlareSolverr version**: **_v2.2.1_**
* **Last working FlareSolverr version**: **_v2.2.1_**
* **Operating system**: Windows 11
* **Are you using Docker**: no
* **FlareSolverr User-Agent **: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
* **Are you using a proxy or VPN?** **_yes_**
* **Are you using Captcha Solver:** no
* **URL to test this issue:** Any https site

### Description
I am using Charles WebProxy with SSL Proxying enabled.
I can't use FlareSolverr because of missing certifications of Charles in order to enable SSL traffic.
I always get this error: "Error: SEC_ERROR_UNKNOWN_ISSUER"
It can be solved if I turned off Charles's proxy, but I don't want to.
I need to use Charles with FlareSolverr for debugging.
So How can I add External Certificate (I've already added it, but every new instance runs without it).

### Logged Error Messages
```
C:\Users\User\Desktop\flaresolverr>flaresolverr.exe
2022-03-07T05:15:40+02:00 INFO FlareSolverr v2.2.1
2022-03-07T05:15:40+02:00 DEBUG Debug log enabled
2022-03-07T05:15:40+02:00 INFO Testing web browser installation...
2022-03-07T05:15:40+02:00 DEBUG FlareSolverr user home directory is OK: C:\Users\User
2022-03-07T05:15:40+02:00 DEBUG Test URL: https://www.google.com
2022-03-07T05:15:40+02:00 DEBUG Creating new session...
2022-03-07T05:15:40+02:00 DEBUG Launching web browser...
2022-03-07T05:15:44+02:00 ERROR Error: SEC_ERROR_UNKNOWN_ISSUER at https://www.google.com
    at navigate (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:130:21)
    at async Frame.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:501:16)
    at async Page.goto (C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1167:16)
    at async testWebBrowserInstallation (C:\snapshot\FlareSolverr\dist\services\sessions.js:80:5)
```

**Comment by ilike2burnthing** [comment]
Stop FlareSolverr, open Firefox in FlareSolverr's folder, add cert in Firefox's settings, close Firefox, start FlareSolverr.

See if that works for you.

**Comment by w4po** [comment]
@ilike2burnthing Tried that and only works for that instance, each new instance comes without that certification.

**Comment by ngosang** [comment]
I don't see the way fix SEC_ERROR_UNKNOWN_ISSUER for all domains in Firefox. You have to add the exceptions one by one.
I keep this open as an enhancement.

**Comment by sidneyki** [comment]
This is a errors I get when I do a test in jackett


Exception (1337x): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received. at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer) at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(Http

**Comment by ngosang** [comment]
We are not using Firefox in FlareSolverr v3. Also the proxy is not implemented yet. #657

**Comment by archon-valec** [comment]
Those of us on windows unfortunately aren't using version 3 yet, can this remain open?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#from-source-code
