### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser. (Test)

### ISSUE THREAD

**Issue by SulliL** [FlareSolverr/FlareSolverr#330]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v2.2.1"
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: yes
* **FlareSolverr User-Agent : Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

Jackett.Common.IndexerException: Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.  ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext() --- End of stack trace from previous location ---    at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)    at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)    at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 607    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1383    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 771    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | --

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by pirochel** [comment]
I have the exact same problem, and everything was working wonderful before the domain change

**Comment by gumballwat** [comment]
hello,
i have same problem

**Comment by TheNexter** [comment]
Same cloudflare again :(

**Comment by BHAALOL** [comment]
Same for me !

**Comment by Enohriel** [comment]
Same issue since yesterday 9pm

**Comment by Jamyz** [comment]
Same issue!

**Comment by Khroners** [comment]
Same. Tried different versions of Jackett & flaresolverr

**Comment by Dirky14** [comment]
Same issue for me

**Comment by goffrier** [comment]
same here, though it worked this morning for 10 minutes

**Comment by goffrier** [comment]
i got a fix, though a quite annoying one, use yggcookie, the cookie changes every day i think, you'll have to get it back

**Comment by Tsuna77** [comment]
working for 1 hour and crash again

**Comment by crashseb** [comment]
same problem for me

**Comment by amberflag48** [comment]
Same issue for me too.

**Comment by goffrier** [comment]
i think the dev left the boat sinking

**Comment by Jamyz** [comment]
> i think the dev left the boat sinking

I dont think! Maybe they test before updating. So let's wait.

**Comment by goffrier** [comment]
i dunno, lot's of issues unresolved, none where the dev replied, and he also commits to his other projects

**Comment by Jamyz** [comment]
I try to change lines inside the container.
but i have the same issue
`2022-03-18T15:46:10+01:00 INFO REQ-2 Incoming request => POST /v1 body: {"maxTimeout":160000,"cmd":"request.get","url":"https://www3.yggtorrent.re/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"}
2022-03-18T15:46:10+01:00 WARN REQ-2 Request parameter 'userAgent' was removed in FlareSolverr v2.
2022-03-18T15:48:26+01:00 INFO REQ-2 Cloudflare detected
2022-03-18T15:48:48+01:00 INFO REQ-2 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.
2022-03-18T15:48:48+01:00 INFO REQ-2 Response in 157.916 s`

**Comment by Axzanaeb** [comment]
Same issue here, but not for [yggtorrent]

**Comment by PHD59fr** [comment]
**The fix is pending merge...** [PR here](https://github.com/FlareSolverr/FlareSolverr/pull/336)

Waiting for it to be fixed, to quickly fix the problem, pull and build haroldm's docker fix:

```
git clone -b fix https://github.com/haroldm/FlareSolverr.git
cd FlareSolverr
docker build -t fsolver .
docker run -d #YOUR OPTION# fsolver:latest
```

**Comment by Jamyz** [comment]
> **The fix is pending review...** [PR here](https://github.com/FlareSolverr/FlareSolverr/pull/336)
> 
> 
> 
> Waiting for it to be fixed, to quickly fix the problem, pull and build haroldm's docker fix:
> 
> 
> 
> ```
> 
> git clone -b fix https://github.com/haroldm/FlareSolverr.git
> 
> cd FlareSolverr
> 
> docker build -t fsolver .
> 
> docker run -d #YOUR OPTION# fsolver:latest
> 
> ```

I try it soon !!!! Thanks

**Comment by Jamyz** [comment]
@PHD59fr how to use for raspberry when i build is for amd64. Thanks

**Comment by PHD59fr** [comment]
> @PHD59fr how to use for raspberry when i build is for amd64. Thanks

I think you have to use buildx with "--platform" argument (linux/amd64, linux/arm64, or darwin/amd64)

**Comment by Jamyz** [comment]
i try "docker buildx build --platform linux/arm/v7 -t fsolver ."
But i have this error 
`[+] Building 1.5s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                             0.5s
 => => transferring dockerfile: 32B                                              0.0s
 => [internal] load .dockerignore                                                0.3s
 => => transferring context: 34B                                                 0.0s
 => ERROR [internal] load metadata for docker.io/library/node:16-alpine3.15      0.6s
------
 > [internal] load metadata for docker.io/library/node:16-alpine3.15:
------
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files``

**Comment by goffrier** [comment]
> docker run -d #YOUR OPTION# fsolver:latest

this works wonder thank you

**Comment by BHAALOL** [comment]
> **The fix is pending review...** [PR here](https://github.com/FlareSolverr/FlareSolverr/pull/336)
> 
> Waiting for it to be fixed, to quickly fix the problem, pull and build haroldm's docker fix:
> 
> ```
> git clone -b fix https://github.com/haroldm/FlareSolverr.git
> cd FlareSolverr
> docker build -t fsolver .
> docker run -d #YOUR OPTION# fsolver:latest
> ```

Thanks a lot ! It works really well !

**Comment by ilike2burnthing** [comment]
[v2.2.2](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.2)

**Comment by Enohriel** [comment]
Issue came back for me :

```
2022-04-06T20:13:28+02:00 INFO FlareSolverr v2.2.2
[...]
 2022-04-06T20:13:41+02:00 INFO REQ-1 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.
```

**Comment by EienFr** [comment]
> Issue came back for me :
> 
> ```
> 2022-04-06T20:13:28+02:00 INFO FlareSolverr v2.2.2
> [...]
>  2022-04-06T20:13:41+02:00 INFO REQ-1 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.
> ```

Same for me

**Comment by BHAALOL** [comment]
Same

**Comment by yemlef** [comment]
same here as well

**Comment by AnonJervis** [comment]
Yup, with v2.2.2 I'm still getting ban IP issue as well

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/355
