### ISSUE TITLE
[1337x] Exception (1337x): Cloudflare Error: Cloudflare has blocked this request.

### ISSUE THREAD

**Issue by tordenflesk** [FlareSolverr/FlareSolverr#337]
### Environment

* **FlareSolverr version**: latest
* **Last working FlareSolverr version**: 
* **Operating system**: Debian 10
* **Are you using Docker**: Yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** No
* **Are you using Captcha Solver:** No
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

None of 1337x's URLs work in Jackett. I can browse to them just fine.
### Logged Error Messages

Logs:
[_flaresolverr_logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/8306136/_flaresolverr_logs.txt)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/330

**Comment by ilike2burnthing** [comment]
[v2.2.2](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.2)
