### ISSUE TITLE
Could you add Heroku ?

### ISSUE THREAD

**Issue by erickyun** [FlareSolverr/FlareSolverr#352]
I know its possible to deploy with heroku but don't know how? 

I did found someone comment somewhere the person wrote there :

"To deploy flaresolverr on heroku just make [Dockerfile](https://github.com/FlareSolverr/FlareSolverr/blob/master/Dockerfile) and push it to heroku, and be sure to use this [buildpack](https://github.com/jontewks/puppeteer-heroku-buildpack)"

but I wasn't able to do the steps right I think. I would appreciate it if you could add Heroku to deploy Flaresolverr on it?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/179

**Comment by erickyun** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/179#issuecomment-945208781

> If you want to use with Jackett it's not going to work because both services must be in the same network.

İf Jackett was also deployed on Heroku would it still not work then?

**Comment by ilike2burnthing** [comment]
I have zero idea of how Heroku functions, but so long as Jackett and FlareSolverr are running on the same device and share the same IP they should work.
