### ISSUE TITLE
[BUG] Getting 403 status when its a 200 response

### ISSUE THREAD

**Issue by JReming85** [FlareSolverr/FlareSolverr#353]
### Environment

* **FlareSolverr version**: Latest Windows / Latest Docker
* **Last working FlareSolverr version**: N/A
* **Operating system**: Windows Server 2012 / Ubuntu 20 LTS
* **Are you using Docker**: [yes/no] Both
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no] No
* **Are you using Captcha Solver:** [yes/no] No
* **If using captcha solver, which one:** N/A
* **URL to test this issue:**  https://discourse.openbullet.dev

### Description

Sometimes when I try to request, it works perfectly but returns status 403 with the response being correct

example img
![image](https://user-images.githubusercontent.com/21246660/161650094-91bb7040-f368-402a-9370-6d46f6a7cb9d.png)

**Comment by ngosang** [comment]
I can see this issue from time to time but I don't know how to fix it. It looks like a race condition in Firefox or an issue in Puppeter.
Maybe it will be fixed with #365 For now consider the response code no reliable.
