### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser. (Test)

### ISSUE THREAD

**Issue by EienFr** [FlareSolverr/FlareSolverr#355]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.2.2
* **Last working FlareSolverr version**: 2.2.2
* **Operating system**: Linux
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no

### Description

Same that the issue https://github.com/FlareSolverr/FlareSolverr/issues/330 before updating to 2.2.2

### Logged Error Messages

An error occurred while testing this indexer
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.

**Comment by ilike2burnthing** [comment]
@haroldm any insights? For whatever it's worth, it doesn't appear to be affecting Windows setups.

**Comment by goffrier** [comment]
same issue here, running latest flaresolverr on docker

**Comment by gh0sti** [comment]
so must need an update to handle cloudflare on some different 1337 domains.

**Comment by neoestremi** [comment]
Same issue here and a friend of mine too.

**Comment by n0wfal** [comment]
> Same issue here and a friend of mine too.
> 
> EDIT : If it can help someone or dev team to investigate : I opened a web browser on a PC in the same LAN, (neither the PC and flaresolverr runs a VPN), accessed YGG without issue, tested the indexer again and it worked. My friend tried too and it works.

I tried the same and it was working for me. Opened the browser and was able to access the page. Also curl request from within the container was working as well.

**Comment by wz366** [comment]
same issue here, running 2.2.2 flaresolverr on docker

**Comment by neoestremi** [comment]
> Same issue here and a friend of mine too.
> 
> EDIT : If it can help someone or dev team to investigate : I opened a web browser on a PC in the same LAN, (neither the PC and flaresolverr runs a VPN), accessed YGG without issue, tested the indexer again and it worked. My friend tried too and it works.

Fix was temporary, getting blocked again.
I would try with VPN but I since both prowlarr and flaresolverr are 2 separate containers, I don't know how to do it, does only one need it ? Both ?

**Comment by uSyzex** [comment]
> > Same issue here and a friend of mine too.
> > EDIT : If it can help someone or dev team to investigate : I opened a web browser on a PC in the same LAN, (neither the PC and flaresolverr runs a VPN), accessed YGG without issue, tested the indexer again and it worked. My friend tried too and it works.
> 
> Fix was temporary, getting blocked again. I would try with VPN but I since both prowlarr and flaresolverr are 2 separate containers, I don't know how to do it, does only one need it ? Both ?

They need to be in the same network, so if Prowlarr is behind a VPN Flare needs to be too.

**Comment by neoestremi** [comment]
> > > Same issue here and a friend of mine too.
> > > EDIT : If it can help someone or dev team to investigate : I opened a web browser on a PC in the same LAN, (neither the PC and flaresolverr runs a VPN), accessed YGG without issue, tested the indexer again and it worked. My friend tried too and it works.
> > 
> > 
> > Fix was temporary, getting blocked again. I would try with VPN but I since both prowlarr and flaresolverr are 2 separate containers, I don't know how to do it, does only one need it ? Both ?
> 
> They need to be in the same network, so if Prowlarr is behind a VPN Flare needs to be too.

Thank you, that's what I thought, but they're in different containers, and I'm using Truchart's apps catalog in TrueNAS so it's not as easy as making a new container using both. I'll try what I can think of but still, it's weird my PC can access it with the same IP.

**Comment by xcybermanx** [comment]
same issue here, running 2.2.2 flaresolverr on docker

2022-04-08T10:51:01+00:00 INFO REQ-3 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser

**Comment by loulich** [comment]
Same here with jackett and FlareSolverr in docker on ubuntu, , i've tested on synology in docker and not working too.
But effectively i've tested on windows and it's ok...

**Comment by gh0sti** [comment]
1337 renewed its domain so jackett should be able to point back to the original domain and shouldn't have problems anymore with flaresolvrr

**Comment by Pommefrais3** [comment]
Any solution? 
I still have this error and I don't know what to do to fix it.

**Comment by ilike2burnthing** [comment]
Access the site in browser from the same IP and/or retry multiple times, doesn't always work but seems to be the best bet until there is a fix.

**Comment by EienFr** [comment]
> Access the site in browser from the same IP and/or retry multiple times, doesn't always work but seems to be the best bet until there is a fix.

It could be a problem when you got an hosted instance like me throw a VPS. I try to curl the url but stuck because of cloudflare. So the only issue is to install a desktop on my linux vps or waiting for a fix.

BTW, for ygg, when trying to use the yggcookie method it seems that there is an extra field before cf_clearence (promo_code).

**Comment by Valhallle** [comment]
Hello, I have the same problem.
Telling me my IP is probably banned, but I tried on web browser it work perfectly

**Comment by neoestremi** [comment]
> Access the site in browser from the same IP and/or retry multiple times, doesn't always work but seems to be the best bet until there is a fix.

Maybe something to do with browser version ? Is it possible to add others and make it random when triggered ? Just a thought.

**Comment by n0wfal** [comment]
Seems to be working now. But fails occassionally.
`2022-04-08T15:35:36+00:00 INFO REQ-13 Cloudflare detected
2022-04-08T15:35:37+00:00 INFO REQ-13 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.
2022-04-08T15:35:37+00:00 INFO REQ-13 Response in 3.965 s
2022-04-08T15:35:44+00:00 INFO REQ-14 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://1337x.nocensor.sbs/cat/Movies/time/desc/1/"}
2022-04-08T15:35:46+00:00 INFO REQ-14 Cloudflare detected
2022-04-08T15:35:48+00:00 INFO REQ-14 Challenge solved
2022-04-08T15:36:08+00:00 WARN REQ-14 Page not reloaded (do not report!): Cause: TimeoutError: Navigation timeout of 2000 ms exceeded`

**Comment by EienFr** [comment]
> Seems to be working now. But fails occassionally. `2022-04-08T15:35:36+00:00 INFO REQ-13 Cloudflare detected 2022-04-08T15:35:37+00:00 INFO REQ-13 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser. 2022-04-08T15:35:37+00:00 INFO REQ-13 Response in 3.965 s 2022-04-08T15:35:44+00:00 INFO REQ-14 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://1337x.nocensor.sbs/cat/Movies/time/desc/1/"} 2022-04-08T15:35:46+00:00 INFO REQ-14 Cloudflare detected 2022-04-08T15:35:48+00:00 INFO REQ-14 Challenge solved 2022-04-08T15:36:08+00:00 WARN REQ-14 Page not reloaded (do not report!): Cause: TimeoutError: Navigation timeout of 2000 ms exceeded`
> 
> PS: switched to https://1337x.to/ and it seems to be working without issues now.

Same here, working sometimes on YGG

**Comment by ilike2burnthing** [comment]
Do not post 'same here' comments if you are not also adding some other new information. If you really want to add a 'same here' sentiment, give a thumbs up reaction to the OP.

This isn't directed at anyone in particular.

**Comment by EienFr** [comment]
As the original OP it works now sometimes on YGG so issue closed.

**Comment by ilike2burnthing** [comment]
There's a wider issue, not just affecting ygg, so we'll leave this open so someone can resolve it.

**Comment by EienFr** [comment]
> There's a wider issue, not just affecting ygg, so we'll leave this open so someone can resolve it.

Oh OK. It's because it was opened for YGG. Thinking that for other issue a new one should be open.

**Comment by ilike2burnthing** [comment]
Bar an awkward workaround that sometimes doesn't work, and is difficult to impossible to do for others, the initial issue with YGG isn't resolved, and it also affects other sites, so FlareSolverr needs to be updated. No reason to open a new issue when it's still related to your OP.

**Comment by boced66** [comment]
Change the url for : www3.yggtorrent.la
Work for me

**Comment by Pommefrais3** [comment]
> Change the url for : www3.yggtorrent.la Work for me

they haven't put back / reactivated their Cloudflare protection service yet so pretty normal for now

**Comment by ngosang** [comment]
FlareSolverr v2.2.3

**Comment by ApexAlpha** [comment]
The new update (2.2.4) fixed this for me. Thank you.
