### ISSUE TITLE
[1337x] Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### ISSUE THREAD

**Issue by linuxdaemon** [FlareSolverr/FlareSolverr#362]
### Environment

* **FlareSolverr version**: v2.2.1
* **Last working FlareSolverr version**: Unknown
* **Operating system**: Linux
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:** none
* **URL to test this issue:** https://1337x.to/cat/Movies/time/desc/1/

### Description

I added the indexer using the default settings in Jackett after configuring FlareSolverr, and it repeatedly fails the tests and returns this error. It appears that it is detecting that there is no cloudflare challenge present but then still failing to access the site because of invalid cookies. 

### Logged Error Messages

The only error was in Jackett when it tried to use the cookies.

**Comment by ilike2burnthing** [comment]
Update to v2.2.2

Try disabling IPv6 for both the Jackett and FlareSolverr containers - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

Failing that, reconfigure the indexer and change to another site link.

**Comment by ngosang** [comment]
FlareSolverr v2.2.3
