### ISSUE TITLE
[Feature Request] Add Auth token or whitelist

### ISSUE THREAD

**Issue by JReming85** [FlareSolverr/FlareSolverr#367]
I have an issue where whenever I spin up the docker my whole system becomes unusable after a few days because some one finds the endpoint and abuses the crap out of it.

The times htop actually starts up, I just see tons of firefox instances running, and I will have to either try to stop the docker or restart the vm depending on how bad it gets as I cant even login from the console sometimes.

For now I went and just exposed the port to localhost and will be using nginx to reverse proxy it w/ ip auth but would love to see some way to protect the endpoint out of the box.  Easiest thing I can think of is either a whitelist or auth keys

**Comment by ilike2burnthing** [comment]
Given that in most (all?) cases FlareSolverr needs to be on the same device, or at least have the same public IP, as the initial request in order for the cookies to be valid, why do you need it to be exposed to the world?

**Comment by JReming85** [comment]
Why have it default to 0.0.0.0 then or why proxy entry

**Comment by ilike2burnthing** [comment]
Not sure I understood your questions, can you expand on them?

**Comment by JReming85** [comment]
your setup guide (docker) has it defaulting to the global/any address e.g. 0.0.0.0 (`-p 8191:8191 \`).

If you installed it on a VPS or or anything with a public ip, it will be wide open.  If its ment for localhost traffic only it should be specified (`-p 127.0.0.1:8191:8191 \`)

On top of that you allow a proxy server to be specified `"proxy": {"url": "http://127.0.0.1:8888"}` which means if you are running it remote it doesnt matter where its hosted as you can use the same proxy for both the client/server.

Lastly if all you are doing is scraping data it doesnt even matter if you use a proxy because you get all the content you need from the response.  You can just parse the response.

**Comment by ilike2burnthing** [comment]
I'll let @ngosang answer the first part.

In many (most?) cases Cloudflare doesn't just look at the IP, but also certain aspects of the UA (not sure if it does anything beyond that), so while you could run FlareSolverr and (for example) Jackett on two separate servers with different public IPs but using the same proxy, if you tried running one on a Windows device you would quickly run into issues of invalid cookies.

Your explanation does seem to give valid use cases though.

**Comment by JReming85** [comment]
Also to note if running remotely, you can also grab the UA and spoof it in the software/script.

**Comment by ngosang** [comment]
If you are using Docker, you don't need to expose the port. You can have connection with other containers in the same Docker network without exposing the ports.

You can change the host with the environment variable `HOST` => https://github.com/FlareSolverr/FlareSolverr/blob/3f279e9aa92a2d3f11af4eefd4d6d81c7d24a1a0/src/server.ts#L7
