### ISSUE TITLE
docker is not behaving similar in different machines

### ISSUE THREAD

**Issue by alperyilmaz** [FlareSolverr/FlareSolverr#368]
### Environment

* **FlareSolverr version**: v2.2.1
* **Last working FlareSolverr version**: v2.2.1
* **Operating system**: Linux
* **Are you using Docker**:  yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:** please see below for detailed instructions

### Description

Hi,

First of all thanks to developer(s) of this project, this is the only solution which can pass the cloudflare detection for the site I'm scraping from.

I'm using the docker version of flaresolverr and it works great in my laptop, I just generate cf_clearance cookie and then use it in a script. However, when I tried to migrate the system to a server, I had encountered problems. 

I used flaresolverr in a Raspberry Pi at home and a server in remote location in docker environment and they both fail (or succeed rarely) to generate cookies. Since I was using docker, I was expecting they behave same but they didn't. So, I'm guessing something is leaking into docker environment from host OS and cloudflare protection can detect it (that it's laptop or headless server). 

I wasn't sure where to start for troubleshooting so I'm asking for help.

Here's the first script to generate cookie:
```bash
#!/usr/bin/bash
docker run -d  --rm --name=flaresolverr   -p 8191:8191   -e LOG_LEVEL=info    ghcr.io/flaresolverr/flaresolverr:latest
sleep 5

until curl -s -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{"cmd": "sessions.create"}'; do echo Trying again..; sleep 5; done

SESSION=$(curl -s -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{"cmd": "sessions.list"}' | jq '.sessions[0]' | sed -e 's/"//g')
sleep 2

# this is just to initiate traffic, does not collect cookie, maybe it's unnecessary
curl -s -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{"cmd":"request.get","maxTimeout":60000,"session":"'$SESSION'","url":"'$URL'"}'

curl -s -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{"cmd":"request.get","maxTimeout":60000,"session":"'$SESSION'","url":"'$URL'","returnOnlyCookies": true}' |\
  jq '[.solution.cookies[] | ([.name,.value|@uri]|join("="))]|join(";")' | \
  sed -e's/"//g' >| active_cookie
```

The cookie should at least have `cf_clearance`, `PHPSESSID` and `XSRF-TOKEN-V2` items. By the way, the response occasionally tells "Cloudflare Error: Cloudflare has blocked this request" but still the cookie works.

After that, the cookie can be used with curl. Below I gave couple examples, one is for querying a search page, visiting an ad page and finally getting details about an ad. Header information for curl might be too crowded and contain unnecessary items, I just collected it from Chrome Dev Tools "Copy as cURL".

```bash
COOKIE="$(cat active_cookie)"

# search

curl $URL -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: '"$HOST"'}' -H 'Connection:keep-alive' -H 'Referer: '"$URL"'}' -H 'Cookie: '"$COOKIE"'' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'DNT: 1' -H 'Sec-GPC: 1' --data-raw 'sort_by=0&min_price=36&max_price=500&seller_online%5B%5D=online&hide_botted=1&page=1' --compressed

# individual ad 

curl $AD_URL -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Connection: keep-alive' -H 'Cookie: '"$COOKIE"'' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'TE: trailers' --compressed


## individual ad details

curl $AD_URL -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: '"$HOST"'}' -H 'Connection: keep-alive' -H 'Referer: '"$AD_URL"'}' -H 'Cookie: '"$COOKIE"'' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'DNT: 1' -H 'Sec-GPC: 1' --data-raw 'get_details=1' --compressed
```

If curl command successfully works you should see webpage content. If cookie fails you see a webpage telling "Having trouble?"

URL, AD_URL and HOST information are at [pastebin site](https://pastebin.com/raw/4MgS795n). Sorry for hiding URL/HOST info, I didn't want the target site to find this post and develop a defence against flaresolverr.

If you can advise me about how to troubleshoot this problem it will be greatly appreciated.

### Logged Error Messages

**error messages**
2022-04-19T15:23:18+00:00 INFO REQ-3 Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.

### Screenshots

no screenshots are available

**Comment by ilike2burnthing** [comment]
Update to v2.2.4, issue resolved in v2.2.3

**Comment by alperyilmaz** [comment]
I updated to 2.2.4, it produces cookies successfully in a headless server. However, the cookie is not usable with *curl* still..

**Comment by ilike2burnthing** [comment]
Assuming the same public IP is being used for FlareSolverr as for curl on your headless server (no proxy or VPN for either) - try disabling IPv6 for the FlareSolverr container and use `curl -4` to force using IPv4.

**Comment by ngosang** [comment]
@alperyilmaz Using the cookie is not enough, you have to set the same user-agent in cURL. You can find the FlareSolverr User-Agent in the FlareSolverr response, with the cookies.
It's also highly recommended to run the scripts in the same machine as FlareSolverr. CloudFlare can detect the IP mismatch.

**Comment by alperyilmaz** [comment]
@ilike2burnthing , using the curl option `-4` is doing the trick. I also had another error message about HTTP/2 and it was resolved with `--http1.1`  option.
Thanks for your help.
