### ISSUE TITLE
NFR: Not possible to fetch image/binary documents behind Cloudflare

### ISSUE THREAD

**Issue by archadamaster** [FlareSolverr/FlareSolverr#369]
### Environment

* **FlareSolverr version**: 2.2.2
* **Last working FlareSolverr version**: 2.2.2
* **Operating system**: Docker image
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:** 

### Description

Cloudflare protects static CDN content like images and etc, and when making requests static HTML is returned (preview frame of the browser).

```
"response": "<html><head><meta name=\"viewport\" content=\"width=device-width; height=device-height;\"><link rel=\"stylesheet\" href=\"resource://content-accessible/ImageDocument.css\"><link rel=\"stylesheet\" href=\"resource://content-accessible/TopLevelImageDocument.css\"><link rel=\"stylesheet\" href=\"chrome://global/skin/media/TopLevelImageDocument.css\"><title>pro_racket_offensive_7_power_z1_fl_17911.jpg (JPEG Image, 2500&nbsp;×&nbsp;1667 pixels) — Scaled (32%)</title></head><body><img src=\"https://static....jpg\" alt=\"https://static.....jpg\" class=\"shrinkToFit\" width=\"800\" height=\"533\"></body></html>",
```

### NFR 
Add parameter for request to return binary data (base64 encoded) or detect automatically.

### Logged Error Messages
No error logs

**Comment by ilike2burnthing** [comment]
Quick aside, you should update to v2.2.4

**Comment by archadamaster** [comment]
Updated, does not solve the "issue".

**Comment by ilike2burnthing** [comment]
Wasn't intended to, like I said it was just a quick aside.

**Comment by ngosang** [comment]
Duplicate #207
