### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): [...] Only Chrome at revision rlatest is guaranteed to work.

### ISSUE THREAD

**Issue by vipera7** [FlareSolverr/FlareSolverr#384]
### Environment

* **FlareSolverr version**: 2.2.4
* **Last working FlareSolverr version**: 2.2.4
* **Operating system**: CentOS 7
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://www5.yggtorrent.la/

### Description
Installed FlareSolver from docker
Installed Jackett from docker
Configured Jackett to use FlareSolver
Configured Jackett to use ygg using the user/password auth
Worked a week agggo
Now, when clicking the test button I got the error message

### Logged Error Messages

> 2022-04-25T14:14:52+02:00 INFO REQ-203 Cloudflare detected
> 2022-04-25T14:15:23+02:00 INFO REQ-203 Challenge solved
> 2022-04-25T14:16:02+02:00 INFO REQ-204 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://www5.yggtorrent.la/engine/search?category=2140&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date"}
> 2022-04-25T14:16:08+02:00 WARN REQ-204 Page not reloaded (do not report!): Cause: TimeoutError: Navigation timeout of 18333.333333333332 ms exceeded
> 2022-04-25T14:16:33+02:00 ERROR REQ-204 Unexpected error: ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
> 2022-04-25T14:16:44+02:00 ERROR REQ-204 TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
> 2022-04-25T14:16:44+02:00 INFO REQ-204 Response in 42.246 s
> 2022-04-25T14:16:45+02:00 ERROR REQ-204 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=55000 (ms)
> 2022-04-25T14:16:45+02:00 INFO REQ-204 Response in 152.614 s
2022-04-25T16:01:38+02:00 WARN REQ-213 Page not reloaded (do not report!): Cause: Error: Navigation failed because browser has disconnected!
2022-04-25T16:01:38+02:00 ERROR REQ-213 Unexpected error: Error: Protocol error (Network.getCookies): Session closed. Most likely the page has been closed.

### Screenshots

![Error](https://i.imgur.com/XIHbhrH.png)

**Comment by LeonardMeyer** [comment]
Same problem :

> 2022-05-29T19:20:13+02:00 INFO REQ-53 Incoming request => POST /v1 body: {"maxTimeout":90000,"cmd":"request.get","url":"https://www5.yggtorrent.la/engine/search?category=2145&name=%22Everything%22%20%22Everywhere%22%20%22All%22%20%22at%22%20%22Once%22%20%222022%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"}
> 
> 2022-05-29T19:20:59+02:00 ERROR REQ-53 TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
> 
> 2022-05-29T19:20:59+02:00 INFO REQ-53 Response in 46.405 s

Looks like a temporary failure because the subsequent requests end up working. This is getting Prowlarr confused and displaying a status error in its UI and log as well: 

> [Warn] HttpClient: HTTP Error - Res: [POST] http://flaresolverr:8191/v1: 500.InternalServerError
> 
> {"status":"error","message":"TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.","startTimestamp":1653844813385,"endTimestamp":1653844859790,"version":"v2.2.4"} 
> 
> [Warn] Cardigann: YGGtorrent HTTP request failed: [500:InternalServerError] [POST] at [http://flaresolverr:8191/v1]

**Comment by ngosang** [comment]
I think you made a mistake in the installation. Reinstall following the instructions in the readme, I changed some things in the latest release.

FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496
