### ISSUE TITLE
overload infinite

### ISSUE THREAD

**Issue by Gadiman6996** [FlareSolverr/FlareSolverr#385]
![Cattura](https://user-images.githubusercontent.com/103646128/165385579-da401475-7838-4807-b7e7-a435266abb5a.PNG)

the solver configuration runs infinitely like this .. what can be the problem?

**Comment by ngosang** [comment]
I can not reproduce the issue but you can test the latest releases:

FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496
