### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by HLFH** [FlareSolverr/FlareSolverr#390]
### Environment

* **FlareSolverr version**: 2.2.4
* **Operating system**: ArchLinux
* **Are you using Docker**: no
* **Are you using a proxy or VPN?** no

### Description

mai 03 11:42:15 arch-server flaresolverr[720762]: 2022-05-03T11:42:15+01:00 INFO REQ-1787 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:16 arch-server flaresolverr[720762]: 2022-05-03T11:42:16+01:00 INFO REQ-1788 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:16 arch-server flaresolverr[720762]: 2022-05-03T11:42:16+01:00 INFO REQ-1789 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:17 arch-server flaresolverr[720762]: 2022-05-03T11:42:17+01:00 INFO REQ-1790 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:17 arch-server flaresolverr[720762]: 2022-05-03T11:42:17+01:00 INFO REQ-1791 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:18 arch-server flaresolverr[720762]: 2022-05-03T11:42:18+01:00 INFO REQ-1792 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:19 arch-server flaresolverr[720762]: 2022-05-03T11:42:19+01:00 INFO REQ-1793 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:19 arch-server flaresolverr[720762]: 2022-05-03T11:42:19+01:00 INFO REQ-1794 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:20 arch-server flaresolverr[720762]: 2022-05-03T11:42:20+01:00 INFO REQ-1795 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:20 arch-server flaresolverr[720762]: 2022-05-03T11:42:20+01:00 INFO REQ-1796 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://baloo.one","maxTimeout":120000}
mai 03 11:42:20 arch-server flaresolverr[720762]: (node:720762) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListe>

My server basically stops running and I have to force reboot, and I think it is related to flaresolverr.

**Comment by JBurlison** [comment]
![image](https://user-images.githubusercontent.com/1290966/168844798-60883608-26fd-4159-aba5-63f475317a1e.png)

**Comment by ngosang** [comment]
I can not reproduce the issue but you can test the latest releases:

FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496
