### ISSUE TITLE
Get premature response when Timeout occurs

### ISSUE THREAD

**Issue by RibomBalt** [FlareSolverr/FlareSolverr#394]
### Environment

* **FlareSolverr version**: 2.2.4 (latest)
* **Last working FlareSolverr version**: no
* **Operating system**: Win10, 21H2 (19044.1645)
* **Are you using Docker**: [yes/no] no
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:** [https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021GL097654](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021GL097654)

### Description

In my previous issue #354, the patch [d34b43e](https://github.com/FlareSolverr/FlareSolverr/commit/d34b43e0a8af2ea9afa45aab7c12f93d69266c49) fixed the incorrect timeout length when retrying. However, if the timeout just occurs, I was wondering if there are some workarounds to get the premature response, instead of nothing but an exception. Here I got some clues.

https://github.com/FlareSolverr/FlareSolverr/blob/3f279e9aa92a2d3f11af4eefd4d6d81c7d24a1a0/src/services/solver.ts#L138-L143
Here the response would be `undefined` if `pageTimeout` is reached.
https://github.com/FlareSolverr/FlareSolverr/blob/3f279e9aa92a2d3f11af4eefd4d6d81c7d24a1a0/src/services/solver.ts#L103-L121
Here in the `response` is referenced in `payload`, even if it's `undefined`. On the other hand, it is very possible to get the content with `await page.content()`.

So, I guess it would be better to check whether the `response` is `undefined` in advance? For example with something like:
```typescript
const payload: ChallengeResolutionT = {
          status,
          message,
          result: {
              url: page.url(),
              status: null,
              headers: null,
              response: null,
              cookies: await page.cookies(),
              userAgent: sessions.getUserAgent()
          }
      }

      if (response){
          payload.result.status = response.status();
          payload.result.headers = response.headers();
      }
```

### Logged Error Messages

Flaresolverr logs:
> 2022-05-09T18:54:27+08:00 INFO FlareSolverr v2.2.4
> 2022-05-09T18:54:27+08:00 DEBUG Debug log enabled
> 2022-05-09T18:54:27+08:00 INFO Testing web browser installation...
> 2022-05-09T18:54:27+08:00 DEBUG FlareSolverr user home directory is OK: C:\Users\1
> 2022-05-09T18:54:27+08:00 DEBUG Test URL: http://www.baidu.com
> 2022-05-09T18:54:27+08:00 DEBUG Creating new session...
> 2022-05-09T18:54:27+08:00 DEBUG Launching web browser...
> 2022-05-09T18:54:31+08:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
> 2022-05-09T18:54:31+08:00 INFO Test successful
> 2022-05-09T18:54:31+08:00 INFO Listening on http://127.0.0.1:8191
> 2022-05-09T18:54:36+08:00 INFO REQ-1 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021GL097654","maxTimeout":20000}
> 2022-05-09T18:54:36+08:00 DEBUG REQ-1 Creating new session...
> 2022-05-09T18:54:36+08:00 DEBUG REQ-1 Launching web browser...
> 2022-05-09T18:54:37+08:00 DEBUG REQ-1 Navigating to... https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021GL097654
> 2022-05-09T18:54:44+08:00 ERROR REQ-1 Unexpected error: TypeError: Cannot read properties of undefined (reading 'status')
> 2022-05-09T18:54:45+08:00 ERROR REQ-1 Error: Unable to process browser request. TypeError: Cannot read properties of undefined (reading 'status')
> 2022-05-09T18:54:45+08:00 INFO REQ-1 Response in 9.127 s

Response Json:
`{'status': 'error', 'message': 'Error: Unable to process browser request. TypeError: Cannot read properties of undefined (reading 'status')', 'startTimestamp': 1652095634434, 'endTimestamp': 1652095643502, 'version': 'v2.2.4'}`

**Comment by ngosang** [comment]
This page is not working well in FlareSolverr but Cloudflare is not enabled so you can go directly to the page without FlareSolverr.
