### ISSUE TITLE
Use global browser instance, keep cookies, delay exit

### ISSUE THREAD

**Issue by procknight** [FlareSolverr/FlareSolverr#4]
Hello,

to improve performance and resource usage, is it possible to:

* use one browser instance for all requests (only max one instance open at all times)
* keep existing cookies for some time (so subsequent requests to the same site do not require a new challenge at FlareSolverr level - without setting cookies in the caller)
* delaying browser exit for a few minutes, to make the above possible

**Comment by NoahCardoza** [comment]
I have no affiliation with this project but, wouldn't it just be easier for you to cache the cookies on your side? And after not make a request to the server again until the cookies "expire"?

**Comment by procknight** [comment]
For me as a FlareSolverr user, no, it's not easier to:

- request a resource via FlareSolverr
- save the cookies returned from FlareSolverr
- use another library to request additional resources with those cookies
- handle a cloudflare challenge gracefully at any time  (you don't have the guarantee that cloudflare will not challenge you again, just because the cookie is still valid) and then fall back to FlareSolverr (restarting the cycle)

as opposed to just call FlareSolverr a second time.

This is a lot of complexity that could by absorbed by FlareSolverr. It means moving complexity away from the caller and towards FlareSolverr and has the following advantages:

- SSL fingerprinting cannot be bypassed by another library: we need the original browser for that (today this doesn't seem necessary, but this could change every minute), otherwise as Cloudflare SSL fingerprinting becomes more aggressive, subsequent requests from libraries with a SSL fingerprint different than that of the browser (completing the challenge) will fail. I believe this is only a question of when and is probably the most important point here.

- keeping the browser open for multiple requests and sites for X amount of time: improves performance and RAM usage very much, especially for multiple requests

- and of course, this simplifies what the caller has to do a lot (but this is probably the least important point)

**Comment by NoahCardoza** [comment]
Ah, yes. I see what you are talking about. You want to route the request through the same browser to handle additional challenges.

I haven't used FlareSolver but it looks like an interesting project that I might contribute to if I find the time. If so, I'll look into your request.

**Comment by NoahCardoza** [comment]
Check out my fork: https://github.com/NoahCardoza/FlareSolverr

I added a `session` parameter which will either generate a random UUID or you can pass your own identifier. Each instance gets a `session` identifier which allows them to stay open until you call an `expire` command which will close the session. I need to add some documentation, but if you look at the `index.js` you should be able to figure it out for now.

**Comment by procknight** [comment]
@NoahCardoza thank you so much! I will test this soon!

**Comment by NoahCardoza** [comment]
@procknight Just a minor update: I've now moved the project to [CloudProxy](https://github.com/NoahCardoza/CloudProxy) and converted it to TypeScript.

**Comment by ngosang** [comment]
FlareSolverr 1.2.0 is out!
It includes this feature.
Installation => https://github.com/FlareSolverr/FlareSolverr#docker
