### ISSUE TITLE
php based to example not work

### ISSUE THREAD

**Issue by amidevous** [FlareSolverr/FlareSolverr#401]
```
<?php
$ch1 = curl_init();
curl_setopt($ch1, CURLOPT_URL, "http://127.0.0.1:8191/v1");
curl_setopt($ch1, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch1, CURLOPT_HEADER, 0);
curl_setopt($ch1, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch1,CURLOPT_SSL_VERIFYPEER, false);
$hdrs1[]="Content-Type: application/json";
curl_setopt($ch1, CURLOPT_HTTPHEADER, $hdrs1);
$POST= '{
  "cmd": "request.get",
  "url":"http://www.google.com/",
  "maxTimeout": 60000
}';
curl_setopt($ch1, CURLOPT_POSTFIELDS, $_POST);
$res1 = curl_exec($ch1);
echo $res1;
exit;
```

return error

`{"status":"error","message":"Error: Request parameter 'cmd' is mandatory.","startTimestamp":1654232398312,"endTimestamp":1654232398312,"version":"v2.2.4"}`

**Comment by fabiomb** [comment]
convert the $post variable to json

$post = json_encode ($post);

**Comment by amidevous** [comment]
no it's already in json
may the mistake is mine
in my variable I have $_POST and not $POST

curl_setopt($ch1, CURLOPT_POSTFIELDS, $POST);

and no

curl_setopt($ch1, CURLOPT_POSTFIELDS, $_POST);

**Comment by ngosang** [comment]
It's possible => https://stackoverflow.com/questions/6213509/send-json-post-using-php
