### ISSUE TITLE
Flaresolverr behind proxy

### ISSUE THREAD

**Issue by billettg** [FlareSolverr/FlareSolverr#403]
### Environment

* **FlareSolverr version**: 2.2.4
* **Last working FlareSolverr version**: ?
* **Operating system**: Ubuntu host/docker
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** yes - AWS Squid http proxy - http://ec2-3-65-25-124.eu-central-1.compute.amazonaws.com:3129
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue: https://1337x.to/cat/Movies/time/desc/1/

UK based ARR stack on Ubuntu server with Docker, ISP blocks a lot of torrent sites, so I use a Squid http proxy in AWS based in Frankfurt to bypass this, but can't get Flaresolverr to work with it.

### Description

Testing via Prowlarr.

1. Global proxy set in Prowlarr
2. Flaresolverr test successful (shows in log: 2022-06-10T17:08:40+01:00 INFO Test successful)
3. Test with 1337x indexer with flaresolverr tag fails (2022-06-10T17:09:22+01:00 ERROR REQ-2 Error: Unable to process browser request. Error: NS_ERROR_NET_RESET at https://x1337x.ws/cat/Movies/time/desc/1/)

So how to set http proxy in Flaresolverr (or Prowlarr)? Or is there a better way to work around this?

I've tried setting environment variables http_proxy and https_proxy on the docker container, but Flaresolverr appears to ignore these.

Other indexers work via the proxy, the proxy works perfectly, and I can access the 1337x using curl or web browser with proxy set (hits Cloudflare). Other sites are affected but just testing with 1337x.

### Diagnostics

ENV:
0 LOG_LEVEL=info
1 LOG_HTML=false
2 CAPTCHA_SOLVER=none
3 TZ=Europe/London
4 HTTP_PROXY="http://ec2-3-65-25-124.eu-central-1.compute.amazonaws.com:3129"
5 HTTPS_PROXY="http://ec2-3-65-25-124.eu-central-1.compute.amazonaws.com:3129"
6 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
7 NODE_VERSION=16.14.2
8 YARN_VERSION=1.22.18
9 PUPPETEER_PRODUCT=firefox
10 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
11 PUPPETEER_EXECUTABLE_PATH=/usr/bin/firefox

Curl from host without proxy (no Flaresolverr):

curl -v https://1337x.to/cat/Movies/time/desc/1/
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to 1337x.to:443

Curl from host with proxy (no Flaresolverr):

curl -v -x "http://ec2-3-65-25-124.eu-central-1.compute.amazonaws.com:3129" https://1337x.to/cat/Movies/time/desc/1/

Connected to ec2-3-65-25-124.eu-central-1.compute.amazonaws.com (3.65.25.124) port 3129 (#0)
Establish HTTP proxy tunnel to 1337x.to:443
< HTTP/1.1 200 Connection established

[_flaresolverr_logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/8880521/_flaresolverr_logs.txt)

**Comment by ilike2burnthing** [comment]
`HTTP_PROXY` and `HTTPS_PROXY` are not valid variables for FlareSolverr.

Does your global proxy in Prowlarr have credentials? If so, FlareSolverr can't use them.

If you want to use a proxy with FlareSolverr, you'll either have to set this at a system level and have everything use it, or set proxy container and use it to pass your FlareSolverr traffic through.

**Comment by billettg** [comment]
No credentials in Prowlarr for the proxy as I'm not using any authentication in Squid.

I tried setting the proxy on the Docker daemon, and on the container itself as per the Docker documentation but this still didn't work so have given up and migrated Flaresolverr to it's own instance on the proxy server, which is unrestricted :)
