### ISSUE TITLE
Medium posts and 404 error

### ISSUE THREAD

**Issue by fabiomb** [FlareSolverr/FlareSolverr#405]
I'm trying to get the content of a Medium.com post using flareSolver because get_headers and file_get_contents (PHP) does not work with it.

Here are some examples:

https://cajundiscordian.medium.com/is-lamda-sentient-an-interview-ea64d916d917
https://katelibc.medium.com/porting-doom-to-a-ux-8cecab02b531

and what i receive is a 404 error page, everything seems fine:

stdClass Object ( [status] => ok [message] => [startTimestamp] => 1655064056865 [endTimestamp] => 1655064062337 [version] => v2.2.4 [solution] => stdClass Object ( [url] => https://cajundiscordian.medium.com/is-lamda-sentient-an-interview-ea64d916d917 [status] => 200 [headers] => stdClass Object ( [date] => Sun, 12 Jun 2022 20:00:59 GMT [content-type] => text/html; charset=utf-8 [cf-ray] => 71a52d06589a08dd-EZE [age] => 13962 [cache-control] => no-cache, no-store, max-age=0, must-revalidate [expires] => Mon, 13 Jun 2022 20:00:59 GMT [strict-transport-security] => max-age=15552000; includeSubDomains; preload [vary] => Accept-Encoding [cf-cache-status] => HIT [content-security-policy] => frame-ancestors 'self' https://medium.com [expect-ct] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" [medium-fulfilled-by] => edgy/8.3.0, valencia/main-20220608-171518-136a7010b7, lite/main-20220610-150737-163c4d074c, rito/main-20220609-194817-71ed07a013, tutu/main-20220610-192632-cf16b2100d [medium-missing-time] => 413 [worker-cache-key] => cajundiscordian.medium.com/is-lamda-sentient-an-interview-ea64d916d917 [worker-cache-middleware] => true [worker-missing-cookies] => 0 [x-content-type-options] => nosniff [x-envoy-upstream-service-time] => 847 [x-request-received-at] => 1655046878458 [server] => cloudflare [content-encoding] => gzip [alt-svc] => h3=":443"; ma=86400, h3-29=":443"; ma=86400 [x-firefox-http3] => h3 ) [response] => "",
[cookies] => Array ( [0] => stdClass Object ( [name] => uid [value] => lo_131520646fed [domain] => .medium.com [path] => / [expires] => 1686600058 [size] => 18 [httpOnly] => 1 [secure] => 1 [session] => ) [1] => stdClass Object ( [name] => __cfruid [value] => 3621c2115f628341b456dc94948ab244f209674c-1655064058 [domain] => .medium.com [path] => / [expires] => -1 [size] => 59 [httpOnly] => 1 [secure] => 1 [session] => 1 ) [2] => stdClass Object ( [name] => dd_cookie_test_b30fad38-3f2b-48c0-ba34-b31321ceb164 [value] => test [domain] => cajundiscordian.medium.com [path] => / [expires] => 1655064060 [size] => 55 [httpOnly] => [secure] => [session] => [sameSite] => Strict ) [3] => stdClass Object ( [name] => dd_cookie_test_ee23bb39-053c-4f9c-abc8-55f1cd937e08 [value] => test [domain] => cajundiscordian.medium.com [path] => / [expires] => 1655064060 [size] => 55 [httpOnly] => [secure] => [session] => [sameSite] => Strict ) [4] => stdClass Object ( [name] => dd_cookie_test_818b2437-2cc8-4724-8733-f4550cab135c [value] => test [domain] => cajundiscordian.medium.com [path] => / [expires] => 1655064062 [size] => 55 [httpOnly] => [secure] => [session] => [sameSite] => Strict ) [5] => stdClass Object ( [name] => _dd_s [value] => rum=0&expire=1655064961198 [domain] => cajundiscordian.medium.com [path] => / [expires] => 1655064961 [size] => 31 [httpOnly] => [secure] => [session] => [sameSite] => Strict ) [6] => stdClass Object ( [name] => dd_cookie_test_2e4f01fd-fe51-49ad-9298-febb22916627 [value] => test [domain] => cajundiscordian.medium.com [path] => / [expires] => 1655064062 [size] => 55 [httpOnly] => [secure] => [session] => [sameSite] => Strict ) ) [userAgent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0 ) )

(i'm not showing the response here because it is the full html) 

but in the response there's a 404 page from medium, not the content.

The problem here is... i receive a status 200 when a 404 should be and i'm only using this to verify if the url is real or not (maybe an overkill method, i know) 

My source code is pretty simple: 

$post = [
    'cmd' => 'request.get',
    'url' => $url,
    'maxTimeout'   => 60000
    ];

$ch = curl_init();

    curl_setopt($ch, CURLOPT_URL,"http://localhost:8191/v1");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt( $ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($post));
    
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    
    $server_output = curl_exec($ch);
    $respuesta = json_decode($server_output);
    curl_close ($ch);

    print_r ($respuesta);

    exit;

What i'm missing here? Of course both urls works fine from the browser and there's no 404 over there

**Comment by fabiomb** [comment]
More info from the console, it says there's no cloudflare over there (!) but when i try other methods it sends me to cloudflare... wtf?

2022-06-12T17:00:56-03:00 INFO REQ-9 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://cajundiscordian.medium.com/is-lamda-sentient-an-interview-ea64d916d917","maxTimeout":60000}
2022-06-12T17:01:00-03:00 INFO REQ-9 Cloudflare not detected
2022-06-12T17:01:02-03:00 INFO REQ-9 Response in 5.472 s

**Comment by ngosang** [comment]
I don't see any Cloudflare protection on that page. Use the latest releases anyway:
