### ISSUE TITLE
Error: Unable to process browser request, consume of all HW resources.

### ISSUE THREAD

**Issue by 9Mad-Max5** [FlareSolverr/FlareSolverr#406]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.2.4
* **Last working FlareSolverr version**: unkown
* **Operating system**: linux
* **Are you using Docker**: [yes]
* **FlareSolverr User-Agent (see log traces or / endpoint)**: log
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** [no]
* **If using captcha solver, which one:** no one is used
* **URL to test this issue:** https://warez-world.org/ajax

### Description

In my case, using feedcrawler to call some sites.
This utilizes the flaresolverr to making request to ddos protected sites.
Afterwards, the following Error Message occurs.
During this period, flaresolverr uses all available hardware resource.
This could only be prohibited with the deploy features of docker.

### Logged Error Messages

2022-06-13T16:25:42+00:00 INFO REQ-399 Incoming request => POST /v1 body: {"cmd":"request.post","url":"https://warez-world.org/ajax","session":"72f2e760-eb2d-11ec-b483-219f2bf6b4f1","postData":"p=1&t=l&q=1"}
2022-06-13T16:26:42+00:00 ERROR REQ-399 Error: Unable to process browser request. Error: Maximum timeout reached. maxTimeout=60000 (ms)
2022-06-13T16:26:42+00:00 INFO REQ-399 Response in 60.062 s

### Screenshots

No Screenshots had been made

**Comment by ngosang** [comment]
I can not reproduce the issue but you can test the latest releases:

FlareSolverr 2.2.5 => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.5
Jackett v0.20.1496 => https://github.com/Jackett/Jackett/releases/tag/v0.20.1496
