### ISSUE TITLE
Error on Yggtorrent ARM64 only

### ISSUE THREAD

**Issue by vic1997** [FlareSolverr/FlareSolverr#41]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### Instruction on how to enable debug and html trace

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

**FlareSolverr Version**: 1.2.0

**Docker**: yes

**OS**: Ubuntu ARM64

**Last Working FlareSolverr Version**: first time use

**Are you using a proxy or VPN?** no

**Using Captcha Solver:** no

**If using captcha solver, which one:**

### Description

When I check Yggtorrent url with curl or jackett, it give me this error but not with Google. It only crash on ARM64 (haven't tested ARM32) and not on x86.

### Logged Error Messages

`2020-12-16T21:57:02.879Z INFO REQ-2 Cloudflare detected
2020-12-16T21:57:19.465Z DEBUG REQ-2 Waiting for Cloudflare challenge...
/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:209
        this.emit('error', new Error('Page crashed!'));
                           ^
Error: Page crashed!
    at Page._onTargetCrashed (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:209:28)
    at CDPSession.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:129:57)
    at CDPSession.emit (node:events:329:20)
    at CDPSession._onMessage (/home/node/flaresolverr/node_modules/puppeteer/lib/Connection.js:166:18)
    at Connection._onMessage (/home/node/flaresolverr/node_modules/puppeteer/lib/Connection.js:83:25)
    at WebSocket.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/home/node/flaresolverr/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:329:20)
    at Receiver.receiverOnMessage (/home/node/flaresolverr/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (node:events:329:20)
Emitted 'error' event on Page instance at:
    at Page._onTargetCrashed (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:209:14)
    at CDPSession.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:129:57)
    [... lines matching original stack trace ...]
    at Receiver.emit (node:events:329:20)
npm ERR! code 1
npm ERR! path /home/node/flaresolverr
npm ERR! command failed
npm ERR! command sh -c node ./dist/index.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-12-16T21_58_04_029Z-debug.log`

### Screenshots

https://i.imgur.com/7syQvjW.png

**Comment by abeloin** [comment]
It could be caused by a too small shared memory space if the page rendered is to big.

Can you try running your container with shm-size set to :
`--shm-size=128mb`

**Comment by vic1997** [comment]
@abeloin Ok thank's. The problem was that my VM didn't have enough ram. She had 400MB and I increase to 1GB, it work now :) thank you !

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I'm having the exact same issue. What is the fix? Is it the smh-size or the total VM ram size?

**Comment by LeVraiRoiDHyrule** [comment]
> @LeVraiRoiDHyrule C'est que je n'avais pas assez de ram, du coup quand ça voulait lancer chrome bah ça marchait pas, j'ai donc fait le ménage pour descendre l'utilisation de la ram et j'ai augmenté la taille total de la ram. Je crois qu'il faut au moins 400mo de libre. Depuis je suis passé sur une machine avec plus de ram donc je n'ai plus ce genre de soucis.

Let's keep it in English if others have the same question.

When you mean VM, you mean Docker right? You don't mean that you have Docker inside a VM? What machine are you running flaresolverr onto? I'm on a Raspberry pi 4

**Comment by vic1997** [comment]
> > @LeVraiRoiDHyrule C'est que je n'avais pas assez de ram, du coup quand ça voulait lancer chrome bah ça marchait pas, j'ai donc fait le ménage pour descendre l'utilisation de la ram et j'ai augmenté la taille total de la ram. Je crois qu'il faut au moins 400mo de libre. Depuis je suis passé sur une machine avec plus de ram donc je n'ai plus ce genre de soucis.
> 
> Let's keep it in English if others have the same question.
> 
> When you mean VM, you mean Docker right? You don't mean that you have Docker inside a VM? What machine are you running flaresolverr onto? I'm on a Raspberry pi 4

Damn, yes I completely forgot to speak in English. When I had the error I was under docker in a VM. Now I'm on a physical machine with docker and the machine is in x86 and not in arm like the raspberry pi.
