### ISSUE TITLE
Memory Leak / CPU Leak when calling specific websites

### ISSUE THREAD

**Issue by JReverse** [FlareSolverr/FlareSolverr#42]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### Instruction on how to enable debug and html trace

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

**FlareSolverr Version**:
Latest

**Docker**: [yes/no]
yes

**OS**: 
Centos 8.2

**Last Working FlareSolverr Version**:
None

**Are you using a proxy or VPN?** [yes/no]
no

**Using Captcha Solver:** [yse/no]
no

**If using captcha solver, which one:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

        static void Main(string[] args)
        {
            MainAsync().Wait();
        }

        static async Task MainAsync()
        {
            var handler = new ClearanceHandler("http://-snip-:8191/")
            {
                UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
                MaxTimeout = 60000,
            };

            var client = new HttpClient(handler);
            var content = await client.GetStringAsync("http://cfuam.audiograb.net/hit");
            Console.WriteLine(content);
        }

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

<img width="202" alt="Screenshot_1" src="https://user-images.githubusercontent.com/40630518/102425978-1140ad00-3fd4-11eb-9084-552c5b4f2ef6.png">

**Comment by abeloin** [comment]
Can reproduce on Chromium with puppeteer. Without it, it work.

**Comment by ngosang** [comment]
The issue is in the line `const cfChallengeElem = await page.$(selector)` The method never returns and the browser is running forever. I think it's time to refactor the code and remove some hacks...

**Comment by ngosang** [comment]
Fixed in FlareSolverr v1.2.1
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v1.2.1
