### ISSUE TITLE
Only chrome is guaranteed to work

### ISSUE THREAD

**Issue by hrxfab** [FlareSolverr/FlareSolverr#43]
### Instruction on how to enable debug and html trace

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

**FlareSolverr Version**:

**Docker**: [yes]

**OS**: 

**Last Working FlareSolverr Version**: FlareSolverr v1.2.0

**Are you using a proxy or VPN?** [no]

**Using Captcha Solver:** [yes]

**If using captcha solver, which one:**
unknown

### Description

Call of FlareSolver since JackettUI

### Logged Error Messages
 An error occurred while testing this indexer
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.

**Comment by abeloin** [comment]
On what platform is docker running?

Usually, this is an indication that the environment where the container run is very slow(either low power or processing  a lot of concurrent tasks). This make loading chrome longer and result in a time out .

**Comment by hrxfab** [comment]
Hi,

it's running on a docker file on a Synology NAS. I will try to increase the resources allocated to the docker

**Comment by chicungunya** [comment]
Hello, I have the same error on a Raspberry Pi 3.
Do you have a tips for me ? 
Thanks !

**Comment by ngosang** [comment]
1. Use the official Docker images. Do not try to build it yourself. => https://github.com/FlareSolverr/FlareSolverr#docker
2. You need enough RAM. At least 300MB of RAM to work.
