### ISSUE TITLE
SteamDB does not give information

### ISSUE THREAD

**Issue by ShiGhost** [FlareSolverr/FlareSolverr#436]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v2.2.4
* **Last working FlareSolverr version**:
* **Operating system**: Debian 10
* **Are you using Docker**: [yes/no] yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**
* **URL to test this issue:** https://steamdb.info/sub/99331/apps/

### Description

The site is protected and does not allow to get information from the site. In html I get the following line  `<p>SteamDB requires a fully up to date browser. If this page keeps refreshing, try clearing cookies for this site.</p>`

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
This site has Cloudflare protection but it's not standard.
It will be required to make changes in FlareSolverr but I don't have much time right now.

**Comment by ngosang** [comment]
They disabled protection for now. If they enable it in the future i will reopen the issue.
