### ISSUE TITLE
Sharemania does not give information 

### ISSUE THREAD

**Issue by 362227** [FlareSolverr/FlareSolverr#445]
### Environment

* **FlareSolverr version**:2.2.5
* **Last working FlareSolverr version**:
* **Operating system**:centos7
* **Are you using Docker**: [no]
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [no]
* **Are you using Captcha Solver:** [no]
* **If using captcha solver, which one:**
* **URL to test this issue: https://www.sharemania.us

### Description

https://www.sharemania.us

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
Try 2.2.6 and provide more information about the link, the error...
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.6
