### ISSUE TITLE
Why did Firefox get downgraded by so much? 

### ISSUE THREAD

**Issue by txtsd** [FlareSolverr/FlareSolverr#446]
Wouldn't latest stable be good?

**Comment by ngosang** [comment]
Sadly it's detected by Cloudflare. :cry: 
I'm working in FlareSolverr 3.0 that will be based on Latest Chromium + Selenium + Python, but there isn't release timeline yet.

**Comment by txtsd** [comment]
Oh no! I'm sad we have to move away from Firefox.
