### ISSUE TITLE
Evaluate adding --disable-dev-shm-usage to reduce memory requirement

### ISSUE THREAD

**Issue by abeloin** [FlareSolverr/FlareSolverr#45]
By default Chrome use /dev/shm for temp

In our docker image, this is mapped to tmpfs:
`shm on /dev/shm type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=65536k,inode64)`

It might be a good idea to disable it an use /tmp instead via:
--disable-dev-shm-usage

See this for more info: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#tips

**Comment by ngosang** [comment]
Tested with and without Docker in my machine. I don't notice any difference.
