### ISSUE TITLE
disable ipv6 in application option

### ISSUE THREAD

**Issue by KyleSanderson** [FlareSolverr/FlareSolverr#456]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v2.2.6
* **Last working FlareSolverr version**: existing well defined bug
* **Operating system**: Linux
* **Are you using Docker**: [yes/no] cri-o w/ Cilium
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Firefox
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

* Use flaresolverr with IPv6
* Doesn't work.

### Logged Error Messages

* Invalid cookies returned
[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

https://github.com/FlareSolverr/FlareSolverr/issues?q=ipv6

The request is can there be an explicit option to Flaresolverr added to ignore ipv6. The container has a link local v6 address but nothing internet routable, which results in AAAA records being valid but not preferred. Checking the source address if it's IPv6 or IPv4 may resolve the problem.

**Comment by ilike2burnthing** [comment]
Disable IPv6 for the container or host.

I'll leave open in case @ngosang wants to add something like this.

**Comment by KyleSanderson** [comment]
> Disable IPv6 for the container or host.
> 
> I'll leave open in case @ngosang wants to add something like this.

That's not an option.

**Comment by ilike2burnthing** [comment]
Why not?

**Comment by ngosang** [comment]
Try FlareSolverr 3.0.0. It's using Chrome.
