### ISSUE TITLE
Not a bug (some help if is posible)

### ISSUE THREAD

**Issue by andress134** [FlareSolverr/FlareSolverr#46]
Hello, how can use this lib to bypass cloudflare?
I have a scriptp for generate traffic, vote etc, and we need to bypass cloudflare
here is a exemple of my script

```js
request.get({
  url: VoteURL,
  headers: {
    'cookie': cookies[ourproxy] || '',
    'user-agent': 'Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36'
  },
  proxy: 'http://' + ourproxy
}, function(error, response, body) {
if (cookies[ourproxy] !== undefined){
exec(`curl -s -Lo /dev/null --cookie '${cookies[ourproxy]}' -x '${ourproxy}' --user-agent 'Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36' -m 1 "${VoteURL}?[1-50]" </dev/null &>/dev/null &`, function(error, stdout, stderr) {});

is posible to use your lib to solve my solution? if yes, how

**Comment by ngosang** [comment]
Yes, its possible but you have to write some code.
1. You have to install FlareSolverr server. It should be possible to use FLareSolverr as library but it's not supported yet.
2. Make the first request to the `voteURL` with FlareSolverr API => https://github.com/FlareSolverr/FlareSolverr#usage
3. You can save the cookies from the FlareSolverr response to make the following requests using your code.

NOTE: After FlareSolverr solves the challenge. CloudFlare sets a cookie that it's valid for some time. If you send that cookie with your request they won't ask yo to solve the challenge.
