### ISSUE TITLE
[mteamtp] (updating) Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 55 seconds elapsing. 

### ISSUE THREAD

**Issue by gengchengcheng** [FlareSolverr/FlareSolverr#461]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:
* **Last working FlareSolverr version**:
* **Operating system**:
* **Are you using Docker**: [yes/no]
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no]
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by TinPoChan** [comment]
Having the same error here, I switch to m-team 2fa and it's still working fine, you can switch to that temporarily.

**Comment by gengchengcheng** [comment]
thanks，i will try,sometimes it may happen


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlareSolverr/FlareSolverr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FlareSolverr/FlareSolverr] [mteamtp] (updating) Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 55 seconds elapsing.  (Issue #461)





 
Having the same error here, I switch to m-team 2fa and it's still working fine, you can switch to that temporarily.

**Comment by ilike2burnthing** [comment]
If you continue to have issues, provide the information requested in your initial post and reopen.
