### ISSUE TITLE
[btschool] (updating) Exception: System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by KoMing92** [FlareSolverr/FlareSolverr#464]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:2.2.6
* **Last working FlareSolverr version**
* **Operating system**:Synology
* **Are you using Docker**: [yes/no]yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
* **Are you using a proxy or VPN?** [yes/no]no
* **Are you using Captcha Solver:** [yes/no]no
* **If using captcha solver, which one:**no
* **URL to test this issue:**https://pt.btschool.club/

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 55 seconds elapsing. ---> System.TimeoutException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled. at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSol

**Comment by ilike2burnthing** [comment]
Retry a few times, see if you just got unlucky. If you don't see the captcha image in the configuration panel then it hasn't worked.

If you continue to have issues, try increasing the `FlareSolverr Max Timeout` in Jackett's settings.

**Comment by KoMing92** [comment]
> Retry a few times, see if you just got unlucky. If you don't see the captcha image in the configuration panel then it hasn't worked.
> 
> If you continue to have issues, try increasing the `FlareSolverr Max Timeout` in Jackett's settings.

I didn't see the captcha image, then I increasing the `FlareSolverr Max Timeout`,it didn't work. and the error message of Jackett is 'Login Failed, got redirected.'

**Comment by ilike2burnthing** [comment]
What did you increase it to? How many times did you retry?
