### ISSUE TITLE
Resource temporarily unavailable (flaresolverr:8191) (Need help please)

### ISSUE THREAD

**Issue by PixLzzz** [FlareSolverr/FlareSolverr#47]
### Environment

**FlareSolverr Version**:

**Docker**: yes

**OS**: Ubuntu

**Last Working FlareSolverr Version**: latest

**Are you using a proxy or VPN?** no

**Using Captcha Solver:** yes

**If using captcha solver, which one:** hcaptcha-solver

### Description

I followed instructions to add flaresolver to my docker-compose.yml and jackett then. However when i try to add yggtorrent indexer, it says the following error message. This might appear simple for you but im learning so i still have some basic difficulties in that areas...Please be tolerant :D 
Thank you ! 🙏 

### Jackett Error Messages

Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Resource temporarily unavailable (flaresolverr:8191) ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken) at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean asy
### Screenshots

[Place any screenshots of the issue here if needed]

Docker-compose.yml : 

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      # Used to change the verbosity of the logging
      - LOG_LEVEL=debug
      - LOG_HTML=true
      # Enables hcaptcha-solver => https://github.com/JimmyLaurent/hcaptcha-solver
      - CAPTCHA_SOLVER=hcaptcha-solver
      # Enables CaptchaHarvester => https://github.com/NoahCardoza/CaptchaHarvester
      #- CAPTCHA_SOLVER=harvester
      #- HARVESTER_ENDPOINT=https://127.0.0.1:5000/token
    ports:
      - 8191:8191
    restart: unless-stopped

**Comment by ngosang** [comment]
By default each container is isolated and cannot connect to other container. There are several ways. The easiest for me is deploy Jackett and FlareSolverr together in the same docker-compose.yml file.
The alternative => https://stackoverflow.com/questions/45481943/connecting-two-docker-containers

**Comment by PixLzzz** [comment]
Well, first of all, thanks for your help, really appreciate it ! However i have my jackett and flaresolverr already in the same docker-compose file. I also tried with the "depends on". However nothing changes...
There is my jackett conf just above the flaresolverr one.
Thanks again ! 
<img width="551" alt="Capture d’écran 2020-12-19 à 15 33 23" src="https://user-images.githubusercontent.com/36031553/102699006-89df7d80-420f-11eb-8b6e-fab10ba5b20c.png">

**Comment by ngosang** [comment]
This could help => https://github.com/FlareSolverr/FlareSolverr/issues/44#issuecomment-748520556

**Comment by PixLzzz** [comment]
Thank you ! Solved :D
