### ISSUE TITLE
[bt4g] (testing) Exception (bt4g): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by fabh2o** [FlareSolverr/FlareSolverr#488]
### Environment

* **FlareSolverr version**: v2.2.6
* **Last working FlareSolverr version**:
* **Operating system**: Linux
* **Are you using Docker**: [yes/no] yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://bt4g.org/search/2022

### Description

Use BT4G indexer in Jackett

### Logged Error Messages
From FlareSolverr:
```
INFO REQ-1 Incoming request => POST /v1 body: {"maxTimeout":55000,"cmd":"request.get","url":"https://bt4g.org/search/2022"}
 INFO REQ-1 Cloudflare detected
REQ-1 Javascript challenge element '#trk_jschal_js' detected.
DEBUG REQ-1 Waiting for Cloudflare challenge...
DEBUG REQ-1 Javascript challenge element '#trk_jschal_js' detected.
DEBUG REQ-1 Challenge element is hidden
DEBUG REQ-1 Validating HTML code...
INFO REQ-1 Challenge solved
DEBUG REQ-1 Reloading the page
INFO REQ-1 Response in 4.017 s
```
From Jackett
```
Error Jackett.Common.IndexerException: Exception (bt4g): The cookies provided by FlareSolverr are not valid
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/481
