### ISSUE TITLE
Add support for DDOS Guard

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#49]
Protected site => https://anidex.info/

Info: https://ddos-guard.net/

**Comment by ilike2burnthing** [comment]
Resolved with v2.2.0?

**Comment by ngosang** [comment]
Lol, it's not working for https://anidex.info/ because I made a mistake. Anidex works in Jackett because it has some anti-captcha code in the C# indexer. I will fix this issue in the next release to avoid future problems.

**Comment by ngosang** [comment]
Fixed in FlareSolverr 2.2.4 + https://github.com/Jackett/Jackett/pull/13171
