### ISSUE TITLE
Flaresolverr "solves" a challenge but returns incorrect data

### ISSUE THREAD

**Issue by Zeks** [FlareSolverr/FlareSolverr#490]
### Environment
Flaresolverr 2.2.6
ubuntu 20.04
2.2.4 sometime back worked
docker version
default user agent
no proxy
no captcha solver
Url to test: https://www.fanfiction.net/u/11008092

### Description

tryign to fetch the link above produces this trace:
![image](https://user-images.githubusercontent.com/1160852/187124813-0e1f9003-0272-461a-9f55-9701b98a7842.png)

The  page returned is challenge page instead of the required one and is attached to this message.
[favourites_11008092.zip](https://github.com/FlareSolverr/FlareSolverr/files/9441604/favourites_11008092.zip)

**Comment by Zeks** [comment]
Full trace shows it trying to cycle endlessly, I think. Trace attached
[logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/9441653/logs.txt)
:

**Comment by ipaqi** [comment]
possible link to #481 ? Certainly the delay proposed there might work

**Comment by Zeks** [comment]
> possible link to #481 ? Certainly the delay proposed there might work

unfortunately I use dockerized flaresolver in kube cluster so I will have to wait till new version is out
