### ISSUE TITLE
Add support for BitMitigate

### ISSUE THREAD

**Issue by ilike2burnthing** [FlareSolverr/FlareSolverr#50]
Protected sites => https://nyaa.net/ & https://sukebei.nyaa.net/

Info: https://bitmitigate.com/

Previous issue - https://github.com/Jackett/Jackett/issues/9410

**Comment by Xefir** [comment]
Theses websites does not exists anymore, been replaced by another sort of streaming service without the bitmitigate system in front of it.

**Comment by ilike2burnthing** [comment]
Can be reopened if someone finds another site using it.
