### ISSUE TITLE
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Failed to launch the browser process!

### ISSUE THREAD

**Issue by silveralextv** [FlareSolverr/FlareSolverr#51]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu Server

**.Net Runtime**:

**.Net Version**:

**Jackett Version**: v0.17.159

**Last Working Jackett Version**: v0.17.159

**Are you using a proxy or VPN?** [no]

### Logged Error Messages

2020-12-26T23:34:19.955Z INFO REQ-1 Incoming request: POST /v1
2020-12-26T23:34:19.957Z INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www2.yggtorrent.si/new_search/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
Error: Failed to launch the browser process!
/home/alex/FlareSolverr/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/alex/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.helper_1.helper.addEventListener (/home/alex/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2020-12-26T23:34:20.006Z ERROR REQ-1 Failed to launch the browser process!
/home/alex/FlareSolverr/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

**Comment by ilike2burnthing** [comment]
Thanks for moving the issue over from Jackett.

Can you provide:
```
FlareSolverr Version:
Docker: [yes/no]
Last Working FlareSolverr Version:
Using Captcha Solver: [yes/no]
If using captcha solver, which one:
```
Also include debug logs - https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace

Hopefully someone will be able to help you soon, once they're back from the holidays.

**Comment by silveralextv** [comment]
FlareSolverr Version:
Docker: no
Last Working FlareSolverr Version: v1.2.0
Using Captcha Solver: no
If using captcha solver, which one:

**Comment by ilike2burnthing** [comment]
Current FlaveSolverr version presumably being v1.2.1?

Did you ever set up a captcha solver? If not, then you're not using one - https://github.com/FlareSolverr/FlareSolverr#captcha-solvers

**Comment by silveralextv** [comment]
I update FlareSolverr and nothing has been fixed. I'll look for captcha solvers, i'll give you news.

**Comment by silveralextv** [comment]
Nothing works. Ever the same error.

**Comment by ilike2burnthing** [comment]
Can you post the debug logs? https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace

**Comment by silveralextv** [comment]
I can't I use with npm.

**Comment by silveralextv** [comment]
`Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Failed to launch the browser process! /home/alex/FlareSolverr-1.2.1/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md : FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Failed to launch the browser process! /home/alex/FlareSolverr-1.2.1/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md`

**Comment by WazoAkaRapace** [comment]
You should try to setup jackett and flaresolverr on the same Docker host. That's how I made it working for ygg...

**Comment by silveralextv** [comment]
@WazoAkaRapace It doesn't work.

**Comment by 3th3r** [comment]
Hi, I add the same issue.

To resolve this error you need to map port 8191, `- port 8191:8191`
I didn't test this with a docker run command, but it worked fine with docker-compose.

My docker-compose.yml
```
version: "2.1"
services:
  flaresolverr:
     image: ghcr.io/flaresolverr/flaresolverr:latest
     container_name: flaresolverr
     environment:
       - LOG_LEVEL=info
       - CAPTCHA_SOLVER=hcaptcha-solver
     ports:
       - 8191:8191
     restart: unless-stopped
```

For the past hour it worked fine with Yggtorrent, 
But if the flareserver server it running it prevent accessing the "yggtorrent" setting in jackett, if flare solver is configured.

**Comment by ngosang** [comment]
> Error: Failed to launch the browser process!
/home/alex/FlareSolverr/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

FlareSolverr is not able to start Chrome browser because there is a missing dependency.

The best way to fix that is to use the FlareSolverr Docker image. It includes all dependencies and it's tested.

If you are installing from source code you have to install more dependencies in your system but I can't provide additional support. https://github.com/alixaxel/chrome-aws-lambda/issues/164

**Comment by silveralextv** [comment]
I solve the problem by running FlareSolverr in a Docker container.
