### ISSUE TITLE
Question about flaresolverr

### ISSUE THREAD

**Issue by Ghost0159** [FlareSolverr/FlareSolverr#515]
Hello, I have a seedbox and on my seedbox it is unfortunately impossible to install flaresolver in order to use it with jackett, so I would like to know if there was another solution to use flaresolver, and I also wanted to know if using flaresolverr is legal?

**Comment by ngosang** [comment]
FlareSolverr is only required for some trackers with Cloudflare protection. Jackett supports +500 so you can use other trackers.
I'm not a lawyer so I don't know. I just provide the code AS IS for free without any guarantee / liability.
