### ISSUE TITLE
Still got captcha after using FlareSolverr

### ISSUE THREAD

**Issue by jinmvp** [FlareSolverr/FlareSolverr#517]
Still got captcha after using FlareSolverr
### Environment

* **FlareSolverr version**: 2.2.8
* **Last working FlareSolverr version**: 2.2.8
* **Operating system**: Win 10 x64
* **Are you using Docker**: [yes/no] No
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** [yes/no] No
* **Are you using Captcha Solver:** [yes/no] No
* **If using captcha solver, which one:** XEvil
* **URL to test this issue:** https://www.wayfair.com

### Description

I want to get HTML Source of the home page.

### Screenshots

![image](https://user-images.githubusercontent.com/87594788/191179809-4060dcf5-6cd9-482b-96ce-616b63fc8691.png)
Also is FlareSolverr support XEvil for recaptcha and hcaptcha solving?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#captcha-solvers

https://github.com/FlareSolverr/FlareSolverr/issues/128
