### ISSUE TITLE
[QUESTION/HELP] Don't know how to finish the configuration process

### ISSUE THREAD

**Issue by darlopvil** [FlareSolverr/FlareSolverr#520]
### Environment

* **FlareSolverr version**: v.2.2.8
* **Last working FlareSolverr version**: nothing, this is the first one
* **Operating system**: Win10 x64
* **Are you using Docker**: [yes/no] no
* **FlareSolverr User-Agent (see log traces or / endpoint)**: ???
* **Are you using a proxy or VPN?** [yes/no] Yes, a VPN
* **Are you using Captcha Solver:** [yes/no] No
* **If using captcha solver, which one:**
* **URL to test this issue:**

Hi, 

I'm new here. I did the Jackett set up, and it happens to be that i need to install this software for some websites. Downloaded and copied the files as said in the readme section, but i don't understand what the last step does:

> In the environment variables section you can find how to change the configuration.

Does it refers to the Windows environment variables section? If so, which file may in link to the program?

I'm attaching this to just show that the program runs perfectly: 

![imagen](https://user-images.githubusercontent.com/60988792/191539328-adb3f098-1249-4c5c-8961-30ce0aab8294.png)

I'd like to ask about the listening link, is this one what i need to paste in the "FlareSolverr API URL" field in Jackett? 

Sorry if I'm asking some easy-to-get bullshit, but i'm very lost atm and don't know either if this is even the correct place to ask this or if I've to open the issue at the Jackett repository.

**Comment by ilike2burnthing** [comment]
Just add http://127.0.0.1:8191 as the FlareSolverr API URL in Jackett's settings, apply, and you're dine.
