### ISSUE TITLE
[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.

### ISSUE THREAD

**Issue by zarevskaya** [FlareSolverr/FlareSolverr#525]
Hey, i have this issue:

[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: latest
* **Last working FlareSolverr version**:
* **Operating system**: debian
* **Are you using Docker**: [yes/no] yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no] 
* **Are you using Captcha Solver:** [yes/no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Screenshots

![Capture d’écran 2022-09-25 162432](https://user-images.githubusercontent.com/60230221/192148752-2d4c6dc3-045d-446a-93e5-2c230fa9ac62.png)

Have a nice day :)

**Comment by ngosang** [comment]
Could you try the beta?
https://github.com/FlareSolverr/FlareSolverr/issues/522

**Comment by zarevskaya** [comment]
Yes, i have the same issue.

**Comment by zarevskaya** [comment]
@ngosang Hello,

I have the same error with the new update of FlareSolverr. 

Any idea to fixe this issue?

Thank yuo

**Comment by ngosang** [comment]
Jackett v0.20.2495 + FlareSolverr 3.0.0 fix most issues
