### ISSUE TITLE
Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing

### ISSUE THREAD

**Issue by chaniqure** [FlareSolverr/FlareSolverr#526]
An error occurred while updating this indexer
Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing. ---> System.TimeoutException: The operation was canceled. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException (125): Operation canceled --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of inner exception stack trace --- --- End

**Comment by ilike2burnthing** [comment]
Provide the information initially requested and reopen.

**Comment by chaniqure** [comment]
I built a jackett myself and reported this error when adding the "https://kp.m-team.cc/" website index

![2](https://user-images.githubusercontent.com/25723223/192286572-83434cb7-cfb2-4ec3-a6bc-9aa947b68d0f.png)
![3](https://user-images.githubusercontent.com/25723223/192286635-a8dc650b-441a-4d40-87d1-37496d30cd82.png)
![4](https://user-images.githubusercontent.com/25723223/192286653-e4988f34-0f7e-4bcd-aff8-c30e435396fb.png)

**Comment by ilike2burnthing** [comment]
Again, provide the information that was requested in the template that you deleted.

**Comment by ilike2burnthing** [comment]
Also, the timeout is typically 55000, not 5000.
