### ISSUE TITLE
I built a jackett myself and reported this error when adding the "https://kp.m-team.cc/" website index

### ISSUE THREAD

**Issue by chaniqure** [FlareSolverr/FlareSolverr#527]
I built a jackett myself and reported this error when adding the "https://kp.m-team.cc/" website index

![2](https://user-images.githubusercontent.com/25723223/192286572-83434cb7-cfb2-4ec3-a6bc-9aa947b68d0f.png)
![3](https://user-images.githubusercontent.com/25723223/192286635-a8dc650b-441a-4d40-87d1-37496d30cd82.png)

_Originally posted by @chaniqure in https://github.com/FlareSolverr/FlareSolverr/issues/526#issuecomment-1258029931_

**Comment by ngosang** [comment]
Check the "FlareSolverr Max Timeout (ms) configuration in the Jackett UI. You have to set a higher value than 5000 = 5 seconds.
Set 50.000 or 100.000 to see what happens.
