### ISSUE TITLE
[1337x] (testing) Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. TimeoutError: Navigation timeout of 18333.333333333332 ms exceeded: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. TimeoutError: Navigation timeout of 18333.333333333332 ms exceeded

### ISSUE THREAD

**Issue by walidjami** [FlareSolverr/FlareSolverr#534]
I've read many posts about getting FlareSolverr to work with jackett, most of which conclude that disabling ipv6 on the docker containers is necessary. I disabled ipv6 on both FlareSolverr and Jackett containers but am still getting error.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v2.29
* **Last working FlareSolverr version**: n/a
* **Operating system**: unRAID
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?**  no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

Adding 1337x as indexer gives 

### Logged Error Messages

 An error occurred while testing this indexer
Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. TimeoutError: Navigation timeout of 18333.333333333332 ms exceeded: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. TimeoutError: Navigation timeout of 18333.333333333332 ms exceeded

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/37970662/193479517-41731a01-ea54-4934-b05e-6ed22e775c4d.png)

**Comment by ValetVlad** [comment]
> Try increasing the timeout to see if it resolves your issue.

How do you even adjust navigation timeout? I don't see a relevant environment variable or request param

**Comment by ilike2burnthing** [comment]
Increase the timeout in Jackett.

**Comment by basudip** [comment]
new Beta 2 solve the issue. Was facing same issue for the last one month. 

[https://github.com/FlareSolverr/FlareSolverr/issues/522](url)

**Comment by walidjami** [comment]
Awes
