### ISSUE TITLE
docker error : npm ERR! command sh -c node ./dist/index.js

### ISSUE THREAD

**Issue by kornflex** [FlareSolverr/FlareSolverr#54]
Hello,

Happy new year !

I've launched flaresolverr with docker. But I have this error :
```
 
npm ERR! path /home/node/flaresolverr
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c node ./dist/index.js
See logs in .....
```

The logs are : 

```
21 timing command:run-script Completed in 36952ms
22 timing command:start Completed in 37001ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:329:20)
23 verbose stack     at maybeClose (node:internal/child_process:1055:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
24 verbose pkgid flaresolverr@1.2.1
```

admin@jarvis:~$ curl -L -X POST 'http://192.168.0.200:8191/v1' -H 'Content-Type: application/json' --data-raw '{
  "cmd": "request.get",
  "url":"http://www.google.com/",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleW...",
  "maxTimeout": 60000,
  "headers": {
    "X-Test": "Testing 123..."
  }
}'
**curl: (7) Failed to connect to 192.168.0.200 port 8191: Connection refused**

Could you help me please ?

Thank you

**Comment by ngosang** [comment]
It seems that the Docker image you are using is wrong.
Are you using the official images in Dockerhub or Github? Or building your own image in local?
Please, start again from scratch following the documentation => https://github.com/FlareSolverr/FlareSolverr#docker

**Comment by albino1** [comment]
I have this same error as well on my Synology.  I'm using the official FlareSolverr docker from here:

https://hub.docker.com/r/flaresolverr/flaresolverr

Sometimes it seems like it starts fine, but you can't access it.  Upon restart I get the same error sequence:

```
20:06:14 npm ERR! path /home/node/flaresolverr
20:06:14 npm ERR! command failed
20:06:14 npm ERR! signal SIGTERM
20:06:15 npm ERR! command sh -c node ./dist/index.js
20:06:15 
20:06:15 npm ERR! A complete log of this run can be found in:
20:06:15 npm ERR!     /home/node/.npm/_logs/2021-01-07T20_06_14_015Z-debug.log
20:06:15 
20:06:52 
20:06:52 > flaresolverr@1.2.1 start
20:06:52 > node ./dist/index.js
20:06:52 
20:06:53 2021-01-07T20:06:53.727Z INFO REQ-0 FlareSolverr v1.2.1 listening on http://0.0.0.0:8191
```

Going to the `http://x.x.x.x:8191/` URL just gives me `This site can’t be reached`.

This might be a Synology specific issue, as the built in docker support Synology is a bit iffy.

**Comment by jamaroney** [comment]
doesn't work with idope

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-operation-was-cancelled
