### ISSUE TITLE
[btschool] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14

### ISSUE THREAD

**Issue by sensenboylg** [FlareSolverr/FlareSolverr#544]
An error occurred while updating this indexer
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5 UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1 navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13 execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25 execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25 execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20 onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36 onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18 handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/536
