### ISSUE TITLE
VPN Error ?

### ISSUE THREAD

**Issue by Zazou89** [FlareSolverr/FlareSolverr#55]
deleted

**Comment by ngosang** [comment]
I need the debug logs. Could you configure FlareSolverr with debug traces and share the logs?
https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace

**Comment by Zazou89** [comment]
I already configured with debug logs, that's weird. Only this is returned on logs : 

```
> flaresolverr@1.2.1 start
> node ./dist/index.js

2021-01-07T11:28:06.194Z INFO REQ-0 FlareSolverr v1.2.1 listening on http://0.0.0.0:8191

```
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='FlareSolverr' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -e 'LOG_LEVEL'='debug' -e 'LOG_HTML'='true' --net=container:OpenVPN-Client 'flaresolverr/flaresolverr' d59046a6e24a4ac321ca2f140f21d431c4c82d515b023153bda8875a1dc90922
```

**Comment by ngosang** [comment]
Make a request

**Comment by Zazou89** [comment]
yes yes, making a request but nothing more on logs, that's weird.

**Comment by ilike2burnthing** [comment]
Given that they're on the same Docker network, have you tried using the container IP (e.g. http://172.17.0.2:8191) instead?

**Comment by Zazou89** [comment]
Okay I changed the network of main container (OpenVPN) from Bridge to Host mode and now it seems working. I'm a beginner, I don't know the difference between these network mode.

**Comment by Zazou89** [comment]
Okay, test works on Jackett but not on Radarr (he doesn't use VPN container). Not easy to use a VPN :o

**Comment by ilike2burnthing** [comment]
If nothing appears in Jackett's logs when you make a request in Radarr, then the issue is either how you have the indexer set up, or a Docker network issue. Hopefully the folks over at Radarr can help.
