### ISSUE TITLE
Flaresolverr Issue, Detecting Headless Browser

### ISSUE THREAD

**Issue by ecchirealm** [FlareSolverr/FlareSolverr#558]
## How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**:3.0.0.beta3
* **Last working FlareSolverr version**:
* **Operating system**:ubuntu
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**

### Description

flaresolverr not able to bypass cloudflare, it worked in a previous version, I think the reason for it is there was a security added where it detects if the browser is headless

### Logged Error Messages

Server error: `POST http://127.0.0.1:8191/v1` resulted in a `500 Internal Server Error` response:
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 700.0 seconds.", "startTimestamp": 166 (truncated...)

**Comment by ilike2burnthing** [comment]
Please keep all reports of issues with beta versions to their respective threads - https://github.com/FlareSolverr/FlareSolverr/issues/522
