### ISSUE TITLE
Unexpected error: ProtocolError: Protocol error (Page.navigate): And  Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome on a specific site

### ISSUE THREAD

**Issue by Tutunova** [FlareSolverr/FlareSolverr#566]
FlareSolverr version: 2.2.10
Last working FlareSolverr version: 2.2.10
Operating system: win10
Are you using Docker: [yes/no] no
FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Are you using a proxy or VPN? [yes/no] no
Are you using Captcha Solver: [yes/no] no
If using captcha solver, which one:
URL to test this issue: https://recurbate.com/signin

When i try to get this url with sending this request {"cmd":"request.get","url":"https://recurbate.com/signin","maxTimeout<MaxTimeout>}
i get this output:
`ERROR REQ-10 Unexpected error: ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1
navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14

2022-10-25T08:28:48-03:00 ERROR REQ-10 Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1
navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14`

This just happens in that site for me, other sites work fine
Also, there are some sites that have cf, but flare just passes straight away, without scraping cookies, is there a mode to fix that?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/536
