### ISSUE TITLE
Stealth plugin?

### ISSUE THREAD

**Issue by Deathnetworks** [FlareSolverr/FlareSolverr#569]
> When some request arrives, it uses puppeteer with the **stealth plugin**

Am I missing something or despite what the readme suggests this doesn't actually use the puppeteer stealth addon?

If it did it'd be 

```
// puppeteer-extra is a drop-in replacement for puppeteer,
// it augments the installed puppeteer with plugin functionality
const puppeteer = require('puppeteer-extra')

// add stealth plugin and use defaults (all evasion techniques)
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
```

instead of what we have 

`import {Page, HTTPResponse} from 'puppeteer'`

Right? I only mention because puppeter-stealth **claim** they can currently bypass all capchas etc, which I'm assuming includes the new cloudflare 'check if secure' page

Well just food for thought, other than a few sites I can't scrape anymore FlareSolverr is still working find for me

**Comment by ilike2burnthing** [comment]
[v.3.0.0](https://github.com/FlareSolverr/FlareSolverr/issues/650) is now out, which moves from Puppeteer and the stealth plugin to Selenium with the undetected-chromedriver.
