### ISSUE TITLE
can not run FlareSolverr. auto stop if I run it.

### ISSUE THREAD

**Issue by dongxi8** [FlareSolverr/FlareSolverr#580]
can not run FlareSolverr 

### Environment

* **FlareSolverr version**: 2.2.10
* **Last working FlareSolverr version**:
* **Operating system**: qnap QTS 5.0.1.2194
* **Are you using Docker**: [yes/no] yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![image](https://user-images.githubusercontent.com/1157840/201249263-c4bf34f5-32f2-46bb-86f6-75e496ca2049.png)

[Place any screenshots of the issue here if needed]

**Comment by dongxi8** [comment]
![Uploading 7757F04C-E77E-4A97-8A2D-FBBDD2F14EE3.jpeg…]()

**Comment by dongxi8** [comment]
![A01CE45A-B97B-4F67-AEB1-49780E9F37F1](https://user-images.githubusercontent.com/1157840/201251780-67fbd8b7-d62a-45bf-a850-c4aefe3f6f7f.jpeg)

**Comment by ilike2burnthing** [comment]
Try increasing `BROWSER_TIMEOUT` - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by dongxi8** [comment]
> Try increasing `BROWSER_TIMEOUT` - https://github.com/FlareSolverr/FlareSolverr#environment-variables

I set BROWSER_TIMEOUT  and maxTimeout both to 600000, but it still not work

**Comment by ilike2burnthing** [comment]
Then try switching to the beta instead - https://github.com/FlareSolverr/FlareSolverr/issues/522

**Comment by jun4rui** [comment]
I also have this problem, I installed it using the official docker in unraid

**Comment by jun4rui** [comment]
I switched to v2.2.9 and found an error saying that accessing google.com timed out. I suspect it was because I was in mainland China and could not access google.
