### ISSUE TITLE
Unexpected error: ProtocolError: Protocol error (Page.navigate): frameId not supported

### ISSUE THREAD

**Issue by marujun** [FlareSolverr/FlareSolverr#581]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: v2.2.10
* **Last working FlareSolverr version**: none
* **Operating system**: Ubuntu 20.04.5
* **Are you using Docker**: yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
* **Are you using a proxy or VPN?** no
* **Are you using Captcha Solver:** no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://www.baidu.com/

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
BROWSER_TIMEOUT=90000
```bash
curl -L -X POST 'http://192.168.31.3:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url":"https://kp.m-team.cc/login.php",
  "maxTimeout": 90000
}'
```

### Logged Error Messages
```
�2022-11-12T08:05:15+08:00 INFO REQ-3 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://kp.m-team.cc/login.php","maxTimeout":90000}
>2022-11-12T08:05:15+08:00 DEBUG REQ-3 Creating new session...
?2022-11-12T08:05:15+08:00 DEBUG REQ-3 Launching web browser...
V2022-11-12T08:05:18+08:00 DEBUG REQ-3 Navigating to... https://kp.m-team.cc/login.php
�2022-11-12T08:05:48+08:00 ERROR REQ-3 Unexpected error: ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
=UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1
Dnavigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13
Cexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
?execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
Bexecute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20
>onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
FonMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
HhandleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14

:2022-11-12T08:05:48+08:00 INFO REQ-3 Response in 32.991 s
�2022-11-12T08:05:48+08:00 ERROR REQ-3 Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
=UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1
Dnavigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13
Cexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
?execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
Bexecute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20
>onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
FonMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
HhandleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14
```
[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/1955015/201446760-7f127022-bc5c-45d1-9c68-5adcb2462e18.png">

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/536
