### ISSUE TITLE
[1337x] (testing) Exception (1337x): FlareSolverr error with Jackett.

### ISSUE THREAD

**Issue by angelo-pokecraft** [FlareSolverr/FlareSolverr#583]
### Environment

*  ***FlareSolverr Version:***
`2.2.10`
* ***Latest working FlareSolverr version***:
`None / Unknown.`
* ***Operating System***:
`Windows 11 v22623.891`
* ***Are you using Docker***:
`No i am not.`
* ***FlareSolverr User-Agent***:
`INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0`
* ***Are you using a proxy or VPN?***
`No i am not.`
* ***Are you using a Captcha Solver:***
`No i am not.`
* ***URL to test this issue:***
`https://1337x.unblockit.page/`

### Description

`My provider has blocked my access to 1337x, however this is the only not yet blocked link that works,
when i attempted to edit the link in Jackett (latest version), the app gave me a config error for FlareSolverr.
I have edited Jackett's config file to point to the 127.0.0.1:8191 IP address that FlareSolverr uses on my system,
i restarted Jackett and attempted to retest Jacketts connection to https://1337x.unblockit.page/,
however i now have a huge error i cannot make sense out off.`

`Thanks in advance.`
`Angelo.`

### Logged Error Messages

`Exception (1337x):`
`FlareSolverr was unable to process the request, please check FlareSolverr logs.`
`Message: Error:`
`Unable to process browser request.`
`ProtocolError:`
`Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5` `UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1` `navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13` `execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25` `execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25` `execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20` `onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36` `onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18` `handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14 :`
`FlareSolverr was unable to process the request, please check FlareSolverr logs.`
`Message: Error:`
`Unable to process browser request.`
`ProtocolError:`
`Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5` `UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1` `navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13` `execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25` `execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25` `execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20` `onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36`
`onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18` `handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14`

### Screenshots

![image](https://user-images.githubusercontent.com/21986450/201497343-0974f081-a87d-46b7-9bb4-2236adac2d02.png)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/536
