### ISSUE TITLE
 Request parameter 'cmd' is mandatory

### ISSUE THREAD

**Issue by Roboxkin** [FlareSolverr/FlareSolverr#587]
Post request
http://localhost:8191/v1

Options
data-raw={"cmd": "request.get","url":"http://www.google.com/","maxTimeout": 60000}

Answer
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 155
ETag: W/"9b-JKSgchowsD0UEFQvQBdMGcQ1JU0"
Date: Thu, 17 Nov 2022 11:20:55 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"status":"error","message":"Error: Request parameter 'cmd' is mandatory.","startTimestamp":1668684055422,"endTimestamp":1668684055423,"version":"v2.2.10"}

What am I doing wrong and what is right?
sorry i don't speak english

**Comment by ngosang** [comment]
Here you have some examples.

Python:
```python
import requests

url = "http://127.0.0.1:8191/v1"
payload = {
    "cmd": "request.get",
    "url": "https://www6.yggtorrent.lol/engine/search?name=harry&do=search",
    "maxTimeout": 60000
}
headers = {"Content-Type": "application/json"}
response = requests.request("POST", url, json=payload, headers=headers)
print(response.text)
```

cURL
```shell
curl --request POST \
  --url http://127.0.0.1:8191/v1 \
  --header 'Content-Type: application/json' \
  --data '{
	"cmd": "request.get",
	"url": "https://www6.yggtorrent.lol/engine/search?name=harry&do=search",
	"maxTimeout": 60000
}
'
```
