### ISSUE TITLE
"status":"error"

### ISSUE THREAD

**Issue by Roboxkin** [FlareSolverr/FlareSolverr#592]
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 155
ETag: W/"9b-lWQCayoIFw4FY7l+Iiq5uhZ1iSo"
Date: Sat, 19 Nov 2022 05:17:57 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"status":"error","message":"Error: Request parameter 'cmd' is mandatory.","startTimestamp":1668835077075,"endTimestamp":1668835077075,"version":"v2.2.10"}

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/591
