### ISSUE TITLE
[bt4g] (testing) Exception (bt4g): FlareSolverr was unable to process the request, please check FlareSolverr logs.

### ISSUE THREAD

**Issue by 3xploiton3** [FlareSolverr/FlareSolverr#595]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.2.10
* **Last working FlareSolverr version**:
* **Operating system**: windows 11
* **Are you using Docker**: [no]
* **FlareSolverr User-Agent (see log traces or / endpoint)**:
* **Are you using a proxy or VPN?** [yes]
* **Are you using Captcha Solver:** [no]
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
Exception (bt4g): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5 UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1 
[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots
![ (3)](https://user-images.githubusercontent.com/19517680/203238325-fac62f50-ab62-4b58-89b1-8190816d632d.png)

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/536
