### ISSUE TITLE
[yggcookie] (testing) Exception (yggcookie): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by Nitra971** [FlareSolverr/FlareSolverr#602]
### Environment

* **FlareSolverr version**: 2.2.1
* **Last working FlareSolverr version**: 19/11/2022
* **Operating system**: Windows 10
* **Are you using Docker**: No
* **FlareSolverr User-Agent (see log traces or / endpoint)**:  Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
* **Are you using a proxy or VPN?** : No
* **Are you using Captcha Solver:** : No
* **If using captcha solver, which one:**
* **URL to test this issue:** : https://www5.yggtorrent.fi

### Description

When I try to use the Flaresolverr via Jackett, I get an error message telling me '' The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid ''.
I looked at the solutions suggested in the other posts. I don't use a VPN, I don't use a proxy, IPv6 is disabled and finally the jackett and the Flaresolverr are on the same network and on the same computer.

### Logged Error Messages

I'm on Windows so I don't see how to get the Flaresolverr logs. If someone can explain me how to do it.

### Screenshots

![image](https://user-images.githubusercontent.com/118977929/203772719-d0098359-408a-423d-809a-354b1c6a0ddc.png)

**Comment by lborruto** [comment]
Issue already posted: https://github.com/FlareSolverr/FlareSolverr/issues/596

        On Yggtorrent forum, they say Flaresolverr blocked RSS flux to prevent DDoS attacks, the issue should be solved in a few days.

_Originally posted by @Ekks-O in https://github.com/FlareSolverr/FlareSolverr/issues/596#issuecomment-1326074025_

**Comment by Nitra971** [comment]
Sorry, i didn't see this post. 
I just make another try with Flaresolverr 2.2.10 and it's seem to work. In any case, I will wait for an update in a few days. 

Thx for the reply.
