### ISSUE TITLE
[1337x] Exception (1337x): FlareSolverr was unable to process the request

### ISSUE THREAD

**Issue by shubham399** [FlareSolverr/FlareSolverr#605]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **v2.2.8**:
* **Last working FlareSolverr version**:
* **Win 11**:
* **Are you using Docker**: [yes/no] yes
* **FlareSolverr User-Agent (see log traces or / endpoint)**: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
* **Are you using a proxy or VPN?** [yes/no] no
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages
```
2022-11-27T12:29:46+05:30 DEBUG REQ-3 Launching web browser...
2022-11-27T12:29:48+05:30 DEBUG REQ-3 Navigating to... https://1337x.unblockit.page/cat/Movies/time/desc/1/
2022-11-27T12:30:07+05:30 INFO REQ-3 Response in 21.288 s
execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14
```

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by shubham399** [comment]
Also Tried with FlareSolverr v2.2.10
and getting

```
2022-11-27T12:43:38+05:30 ERROR REQ-6 Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1
navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14

2022-11-27T12:43:38+05:30 INFO REQ-6 Response in 20.694 s
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/536
