### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by Yoann30305** [FlareSolverr/FlareSolverr#612]
Issue when i try to test ygg on jackett with flaresolverr

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/596

Also, in future don't just wipe out the template, it's there for a reason.
