### ISSUE TITLE
[bt4g] (testing) Exception (bt4g): FlareSolverr was unable to process the request, ProtocolError: Protocol error (Page.navigate): frameId not supported 

### ISSUE THREAD

**Issue by Aholicknight** [FlareSolverr/FlareSolverr#618]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### How to enable debug and html traces

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

* **FlareSolverr version**: 2.2.10
* **Last working FlareSolverr version**:
* **Operating system**: Windows 11
* **Are you using Docker**: [yes/no] no
* **FlareSolverr User-Agent (see log traces or / endpoint)**: do not know
* **Are you using a proxy or VPN?** [yes/no] yes
* **Are you using Captcha Solver:** [yes/no] no
* **If using captcha solver, which one:**
* **URL to test this issue:** https://bt4g.org

### Description

trying to test BT4G and it does not work for some reason. I am using the latest version of Jackett and FlareSolverr

### Logged Error Messages

```
Exception (bt4g): FlareSolverr was unable to process the request, please check FlareSolverr logs. 
Message: Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported
RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5 UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1
navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13 execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25 execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20
onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36 onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14 : 
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request.
ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5
UnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1 navigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13
execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25 execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
execute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20 onPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36
onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14
```

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

![msedge_20221216_868WYJKCLU](https://user-images.githubusercontent.com/7843719/207462793-7813e39c-8803-4e42-982b-9ece7d567772.png)

![msedge_20221216_2G5E3ba2UT](https://user-images.githubusercontent.com/7843719/207462825-84acce08-8bd3-4100-b85e-58aa983154c7.png)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/536
