### ISSUE TITLE
Cant proxyfi firefox, foxyproxy and other tool 

### ISSUE THREAD

**Issue by hastalamuerte** [FlareSolverr/FlareSolverr#619]
Hello .Thanks for your work! 

I was try 2 versions 
master stable for windows and python beta 3 with crome browser (it cant find chromium with standalone not installed - help plz with it too) 

  click on exe. It start instance, but i cant proxify browser or anything by adding 0.0.0.0 localhost 127.0.0.1 http https  with ports 8888 8189 - nothing

 start python instance 
2022-12-15 05:55:39 INFO     Test successful
2022-12-15 05:56:04 INFO     Serving on http://0.0.0.0:8191
but again no proxy no reqs, resps. 
plz help

**Comment by hastalamuerte** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/277 same issue - no answers. But i cant use it in Docker , cause it will by container maddness, proxy for proxy under vpn on vps - just need to make it work with no Jacket , or other wheelchairs . Thx . Also i found a issue about autostart and autoupdate - but still nothing on windows.

**Comment by hastalamuerte** [comment]
Execute FlareSolverr binary. In the environment variables section you can find how to change the configuration. 
Where is it? ))))

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/522#issuecomment-1352850339
