### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.

### ISSUE THREAD

**Issue by ChaigneauDoryan** [FlareSolverr/FlareSolverr#649]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 2.2.10
- Last working FlareSolverr version: 2.2.10
- Operating system: linux
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0
- Are you using a proxy or VPN: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
```

### Description

My jacket has been telling me for several weeks now that the response time is too long... do you have any solution ?

I tried to create a docker container on the flaresolverr beta image (ngosang) but it doesn't even start...

Thanks !

### Logged Error Messages

```text
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: TimeoutError: Timed out after 40000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
```

**Comment by Matosh-fr** [comment]
Hello, 
You have to change your version to version 3.0.0:
flaresolverr/flaresolverr:latest

![image](https://user-images.githubusercontent.com/81532640/210675214-ff22b3c8-9c3e-47f5-ab6b-1a871cb4348d.png)

and use flaresolverr to resolv the catcha :
![image](https://user-images.githubusercontent.com/81532640/210675141-505b9795-feca-4a73-bd49-26548e3f2d94.png)

Then it should work :D

**Comment by ngosang** [comment]
#650
