### ISSUE TITLE
Lot of defunct process

### ISSUE THREAD

**Issue by ochbob** [FlareSolverr/FlareSolverr#653]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: latest - 3.0
- Last working FlareSolverr version: v2.2.10
- Operating system: Debian 11
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a proxy or VPN: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: NR
```

### Description

HEllo,

since beta v3 and final, I found a lot of zombie processes, just running for few minutes.

Screenshot from [dalamudx](https://github.com/dalamudx) but, I encounter the same issue on my side.

 ![image](https://user-images.githubusercontent.com/88395653/208466668-ac76d526-58a8-431f-ac74-3d712345a207.png)

![image](https://user-images.githubusercontent.com/88395653/208465744-baf08fde-9a79-4247-909c-81ed9439d651.png)

### Logged Error Messages

```text
No specific error log
```

**Comment by ngosang** [comment]
Confirmed. I'm working on it.
It's not that bad since those process are not running nor using resources.

**Comment by ActiniumTO** [comment]
@ngosang you have and discord or telegram that would be possible to talk with you?

**Comment by ngosang** [comment]
By email ngosang / hotmail / es
