### ISSUE TITLE
Implement proxy auth support in FlareSolverr 3

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#657]
Implement proxy support in FlareSolverr 3. It was supported in FlareSolverr 2, but it was removed in the refactor.
Related #650

**Comment by ngosang** [comment]
Implemented in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.2.0

**Comment by ilike2burnthing** [comment]
Reopening as a req for proxy auth support.

**Comment by ngosang** [comment]
I'm ok with having this issue open but It's not supported by Chrome. We will have to use some kind of plugin for Chrome or Selenium. Related => #666

**Comment by jacobprice808** [comment]
So, correct me if I'm wrong, but the version of Undetected Chromedriver (3.4.6) used in this project doesn't support proxies with auth? Did you guys see this issue on the Undetected Chromedriver repo: [#1306](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1306)? There are some solutions on that thread. If there are still implementation issues, I can take a further dive then PR. Just want to know the context first. Did you modify 3.4.6 at all for it to work with this project? Would updating to 3.5.0 break anything?

**Comment by ilike2burnthing** [comment]
@jacobprice808 https://github.com/FlareSolverr/FlareSolverr/pull/803#issuecomment-1619278195

**Comment by jacobprice808** [comment]
I think I fixed this problem: [#807](https://github.com/FlareSolverr/FlareSolverr/pull/807)

**Comment by ngosang** [comment]
Included in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.0

**Comment by ilike2burnthing** [comment]
@ngosang any chance to get Jackett's proxy credentials sent with requests? Currently it's just the URL.

**Comment by ngosang** [comment]
I can do that. https://github.com/FlareSolverr/FlareSolverrSharp/issues/23
