### ISSUE TITLE
Implement session support in FlareSolverr 3

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#658]
Implement session support in FlareSolverr 3. It was supported in FlareSolverr 2, but it was removed in the refactor.
Related https://github.com/FlareSolverr/FlareSolverr/issues/650

**Comment by Xefir** [comment]
I've made a PR for that : https://github.com/FlareSolverr/FlareSolverr/pull/674 :)

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.1.0
