### ISSUE TITLE
Running from source

### ISSUE THREAD

**Issue by laendle** [FlareSolverr/FlareSolverr#663]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.1
- Last working FlareSolverr version: 2.2.10
- Operating system: Windows 10
- Are you using Docker: [no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a proxy or VPN: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue: doesn't get that far
```

### Description

Follow steps listed here: https://github.com/FlareSolverr/FlareSolverr#from-source-code

Install chromium (NOT chrome) results in a portable zip file download and therefore, clean registry and system. BUT, how to set a path for the `chrome.exe`?

As it is this simply doesn't run. Please verify running from source instructions, the errors are clear.

### Logged Error Messages

```text
415, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "c:\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Python311\Lib\subprocess.py", line 1433, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Python311\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:
```

```
Exception: Error getting browser User-Agent. expected str, bytes or os.PathLike object, not NoneType
```
```


### Screenshots

_No response_

**Comment by ngosang** [comment]
In Windows you have to install Chrome. Portable version is nor supported yet.
I improved the error message => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.0.2

**Comment by laendle** [comment]
> In Windows you have to install Chrome. Portable version is nor supported yet. I improved the error message => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.0.2


you may want to update the readme.md to remove the reference and link to Chromium since it's a zip that extracts as a portable

**Comment by ilike2burnthing** [comment]
See their '[Not-as-easy steps](https://www.chromium.org/getting-involved/download-chromium/#not-as-easy-steps)' in that link.
