### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by SteffanCline** [FlareSolverr/FlareSolverr#665]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:2.x
- Last working FlareSolverr version:2.x
- Operating system:Ubuntu 22
- Are you using Docker: [yes/no] No
```

### Description

What are the plans going forward on the precompiled binaries? The instructions still indicate precompiled binaries, python and docker. I

### Logged Error Messages

```text
No logs
```

**Comment by ilike2burnthing** [comment]
If you're going to tick a box saying you checked other issues, maybe actually do that first - https://github.com/FlareSolverr/FlareSolverr/issues/660

Also, if you're just asking a question, then follow the instruction and open a new discussion instead.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/commit/2d97f882764caf6563647109871b5230d5899840
