### ISSUE TITLE
find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory

### ISSUE THREAD

**Issue by GravuTrad** [FlareSolverr/FlareSolverr#668]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version:
- Operating system: Centos 7.9
- Are you using Docker: [yes/no] Yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
- Are you using a proxy or VPN: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory

### Logged Error Messages

```text
find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
```

### Screenshots

![Flaresolverr](https://user-images.githubusercontent.com/25709963/211674309-10a1f6ef-318b-468c-b0b4-2b4f80382459.PNG)

**Comment by GravuTrad** [comment]
Hello.
I have an additional question totally not regarding this log return: It is possible to permit only one ip to access to the flaresolverr script. (when hosted on a server)
Thanks.

**Comment by GravuTrad** [comment]
Is it important to have at less a libseccomp2=2.5.1-1 version? (my centos have less)

**Comment by ngosang** [comment]
> find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory

I can not reproduce that issue. I'm using Docker in Ubuntu machine and I never seen that. Try updating Docker or the Host OS.

> Is it possible to permit only one ip to access to the flaresolverr script? (when hosted on a server)

No, but you don't need to expose FlareSolverr to the Internet. Read about Docker networks.

> Is it important to have at less a libseccomp2=2.5.1-1 version? (my centos have less)

I think that is only for old Debian

**Comment by Tryum** [comment]
I got the same issue with v3.0.2, reverting to v3.0.0 for now.
If you want to investigate this further, I can create another instance with lastest and provide more logs.

**Comment by GravuTrad** [comment]
You haven't the problem anymore by reverting to an older version? 3.0.1 could be sufficient? or really only 3.0.0?

**Comment by Tryum** [comment]
I changed to 3.0.1, and it works too.

**Comment by JackW6809** [comment]
I am also encountering this error on v3.0.2, reverting to v3.0.1 works. (Docker)

**Comment by GravuTrad** [comment]
Correct. The revert to 3.0.1 works. I keep this version until someone wnats to check this bug.

**Comment by GravuTrad** [comment]
bug always present in 3.0.3

**Comment by GravuTrad** [comment]
> 
> > Is it possible to permit only one ip to access to the flaresolverr script? (when hosted on a server)
> 
> No, but you don't need to expose FlareSolverr to the Internet. Read about Docker networks.

Can you explain more please? thanks.

**Comment by GravuTrad** [comment]
bug always present in 3.0.4

**Comment by ngosang** [comment]
Fixed in 4d1610517684bd0d0aa9fd9036e2cd28a1294eb4
FlareSolverr 3.1.0

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.1.0

**Comment by GravuTrad** [comment]
Perfect. Solved. Thanks.
