### ISSUE TITLE
How do we view FlareSolverr Logs?

### ISSUE THREAD

**Issue by JoshDi** [FlareSolverr/FlareSolverr#68]
Can you please provide instructions or the location of the FlareSolverr logs when using docker? 

Thank you!

**Comment by ngosang** [comment]
Try `docker logs flaresolverr`

https://docs.docker.com/engine/reference/commandline/logs/

**Comment by laichiaheng** [comment]
@ngosang I'm not using Docker, where can I see them?

**Comment by ilike2burnthing** [comment]
In the FlareSolverr command prompt or shell window you're running. Alternatively output to a file, e.g.

```cmd
YOUR_COMMAND_HERE > log.txt
```
