### ISSUE TITLE
[1337x] (testing) Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by shresth45** [FlareSolverr/FlareSolverr#682]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: 3.0.2
- Operating system: Debian 10
- Are you using Docker: [yes/no] Yes
- FlareSolverr User-Agent (see log traces or / endpoint): {"msg": "FlareSolverr is ready!", "version": "3.0.2", "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}
- Are you using a proxy or VPN: [yes/no] yes
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: https://1337x.unblockninja.com
```

### Description

Exception (1337x): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid
[Click here to open an issue on GitHub for FlareSolverr.](https://github.com/FlareSolverr/FlareSolverr/issues/new?template=bug_report.yml&title=[1337x]%20(testing)%20Exception%20(1337x)%3A%20The%20cookies%20provided%20by%20FlareSolverr%20are%20not%20valid%3A%20The%20cookies%20provided%20by%20FlareSolverr%20are%20not%20valid)

### Logged Error Messages

```text
2023-01-27 19:25:57 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://1337x.unblockninja.com/cat/Movies/time/desc/1/'}
2023-01-27 19:26:04 INFO     Challenge not detected!
2023-01-27 19:26:05 INFO     Response in 7.879 s
```

**Comment by ilike2burnthing** [comment]
Try dropping the VPN/proxy.

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/664#issuecomment-1407438313
