### ISSUE TITLE
[epublibre] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by ibeltran** [FlareSolverr/FlareSolverr#683]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: None
- Operating system: DSM 7.1.1-42962
- Are you using Docker: [yes/no] Yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
- Are you using a proxy or VPN: [yes/no] No
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one: -
- URL to test this issue: https://epublibre.unblockit.ink/catalogo/index/0/nuevo/todos/sin/todos/--/ajax
```

### Description

- While trying to add Epublibre indexer to Jackett, I'm getting an error stating "The cookies provided by FlareSolverr are not valid"
- Checking the log for Flaresolverr, it says "Challenge not detected!"
- However, when I execute `curl https://epublibre.unblockit.ink/catalogo/index/0/nuevo/todos/sin/todos/--/ajax` from Jacket or Flaresolverr containers, I can see CloudFlare challenge page

Response to the questions I've seen on other issues:
- Are Jackett and FlareSolverr running on the same device and using the same IP?
Yes they are running inside Docker on my NAS, and they get the same external IP address
- Disable IPv6 for both containers or the host.
I've disabled it for all of them, the issue is still there

### Logged Error Messages

```text
2023-01-28 10:50:49 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://epublibre.unblockit.ink/catalogo/index/0/nuevo/todos/sin/todos/--/ajax'}
2023-01-28 10:50:51 INFO     Challenge not detected!
2023-01-28 10:50:52 INFO     Response in 2.919 s
2023-01-28 10:50:52 INFO     172.18.0.4 POST http://flaresolverr:8191/v1 200 OK
```

**Comment by IIPoliII** [comment]
I have the same issue with YGG

**Comment by ngosang** [comment]
Fixed in latest versions.
