### ISSUE TITLE
How to run flaresolverr in background & auto start like jackett?

### ISSUE THREAD

**Issue by 3xploiton3** [FlareSolverr/FlareSolverr#69]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### Environment

**FlareSolverr Version**:

**Docker**: [yes/no]

**OS**: windows 10

**Last Working FlareSolverr Version**:

**Are you using a proxy or VPN?** [no]

**Using Captcha Solver:** [not yet]

**If using captcha solver, which one:**

### Description

can we run flaresolverr in start up & background process? if possible, give us tutorial
without having run flaresolverr.exe

**Comment by ngosang** [comment]
It should be easy but we don't have instructions/tools yet.
#70

**Comment by yorai1212** [comment]
Did you find a solution?

**Comment by ilike2burnthing** [comment]
See linked issue.
