### ISSUE TITLE
Cant make it work. Still got "Attention required" message

### ISSUE THREAD

**Issue by khorezm0** [FlareSolverr/FlareSolverr#7]
So i had just cloned this repo, and a project is launching ok.
But when i make POST request to it, solver responses with status OK, but response value is "Attention required"

![image](https://user-images.githubusercontent.com/44477986/87456433-fc707f80-c617-11ea-8fdd-892645d3a29e.png)

I've tried this link: "http://ru.pm-498.info/en/live.html"

I just wondering what should i do to fix it.
Regards.

**Comment by NoahCardoza** [comment]
Check out my spin-off of this project, [CloudProxy](https://github.com/NoahCardoza/CloudProxy).

I just tested it and it works successfully on the example URL you provided. However, my request wasn't flagged by CF. If you encounter this error feel free to open an issue on my repo, try and paste the entire `response` value so I can see what kind to message CF is sending. It could be related to your IP.

**Comment by khorezm0** [comment]
> Check out my spin-off of this project, [CloudProxy](https://github.com/NoahCardoza/CloudProxy).
> 
> I just tested it and it works successfully on the example URL you provided. However, my request wasn't flagged by CF. If you encounter this error feel free to open an issue on my repo, try and paste the entire `response` value so I can see what kind to message CF is sending. It could be related to your IP.

Oh Thanks, i'll take a look. I'd bypassed too at first time, but when i did ~10th request, it got banned like this.

**Comment by NoahCardoza** [comment]
Well with the use of sessions which I added to my version you won't have to keep passing the challenge over and over. You'll only need to pass it once per session instance.

**Comment by ngosang** [comment]
FlareSolverr 1.2.0 is out!
It's working for all sites protected by CloudFlare.
Installation => https://github.com/FlareSolverr/FlareSolverr#docker
