### ISSUE TITLE
Flaresolverr does not work

### ISSUE THREAD

**Issue by thegrunge36** [FlareSolverr/FlareSolverr#709]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:last one
- Last working FlareSolverr version:last one
- Operating system:Debian
- Are you using Docker: [yes/no]no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]yes
- Are you using a Proxy: [yes/no]no
- Are you using Captcha Solver: [yes/no]no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

For a few days flaresolverr does not launch. I even formatted but nothing changed.

### Logged Error Messages

```text
jonathan@Jonathan:/opt/flaresolverr$ sudo chmod +x flaresolverr
[sudo] Mot de passe de jonathan : 
jonathan@Jonathan:/opt/flaresolverr$ ./flaresolverr
2023-02-21T08:10:07-05:00 INFO FlareSolverr v2.2.10
2023-02-21T08:10:07-05:00 INFO Testing web browser installation...
2023-02-21T08:10:48-05:00 ERROR TimeoutError: Navigation timeout of 40000 ms exceeded
    at /snapshot/FlareSolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111
jonathan@Jonathan:/opt/flaresolverr$
```

**Comment by ilike2burnthing** [comment]
`last one` isn't a version. Log shows v2.2.10, current release is v3.0.2, try that instead.

Try without a VPN or proxy, and try a different `TEST_URL` - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by thegrunge36** [comment]
Hello, this is the latest version for linux, unless there is a way to build the latest version.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#from-source-code

**Comment by thegrunge36** [comment]
I'm stuck here in the terminal. After installing everything I open the terminal in master folder and I enter the command: pip install -r requirements.txt

the command is not found

Run pip install -r requirements.txt command to install FlareSolverr dependencies.
Run python src/flaresolverr.py command to start FlareSolverr.

**Comment by thegrunge36** [comment]
I don't know if it's related to the rest of the procedure you gave me yesterday but this morning like magic it works. 


Loaded: loaded (/etc/systemd/system/flaresolverr.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-02-22 03:23:51 EST; 4h 36min ago
   Main PID: 2152759 (flaresolverr)
      Tasks: 10 (limit: 18911)
     Memory: 40.9M
        CPU: 4.319s
     CGroup: /system.slice/flaresolverr.service
             └─2152759 /opt/flaresolverr/flaresolverr

fév 22 05:09:33 Jonathan flaresolverr[2152759]: 2023-02-22T05:09:33-05:00 DEBUG REQ-1 Launching web browser...
fév 22 05:09:35 Jonathan flaresolverr[2152759]: 2023-02-22T05:09:35-05:00 DEBUG REQ-1 Using proxy: undefined
fév 22 05:09:35 Jonathan flaresolverr[2152759]: 2023-02-22T05:09:35-05:00 DEBUG REQ-1 Navigating to... https://prowlarr.servarr.com/v1/ping
fév 22 05:09:35 Jonathan flaresolverr[2152759]: 2023-02-22T05:09:35-05:00 INFO REQ-1 Cloudflare not detected
fév 22 05:09:35 Jonathan flaresolverr[2152759]: 2023-02-22T05:09:35-05:00 DEBUG REQ-1 Reloading the page
fév 22 05:09:35 Jonathan flaresolverr[2152759]: 2023-02-22T05:09:35-05:00 INFO REQ-1 Response in 1.723 s
fév 22 07:59:41 Jonathan flaresolverr[2152759]: 2023-02-22T07:59:41-05:00 INFO REQ-2 Incoming request => GET /favicon.ico
fév 22 07:59:42 Jonathan flaresolverr[2152759]: 2023-02-22T07:59:42-05:00 INFO REQ-3 Incoming request => GET /
fév 22 07:59:44 Jonathan flaresolverr[2152759]: 2023-02-22T07:59:44-05:00 INFO REQ-4 Incoming request => GET /
fév 22 07:59:46 Jonathan flaresolverr[2152759]: 2023-02-22T07:59:46-05:00 INFO REQ-5 Incoming request => GET /
