### ISSUE TITLE
Add a new endpoint to test FlareSolverr / public IP

### ISSUE THREAD

**Issue by ngosang** [FlareSolverr/FlareSolverr#71]
Add a new endpoint in FlareSolver. Eg: http://flaresolver:8191/test
Use an external service like https://api.ipify.org/ to test if Chrome is working, there is Internet connectivity, get the public IP, get the public User-Agent...
Return the test results and information (public IP...) to the user.

**Comment by NiiggerLifeMatter** [comment]
https://www.npmjs.com/package/puppeteer-page-proxy



const useProxy = require('puppeteer-page-proxy');
await useProxy(page, 'http://127.0.0.1:80');
(Alternativly if you need to auth --->  await useProxy(page, 'http://USERNAME:PASS@127.0.0.1:80');    <----)
can be done but sharing the same proxy, 
I am not unsure how to modify the API the development pihlosofy is different in nodejs other than gnu-c or golang

**Comment by ngosang** [comment]
Proxy => #26

**Comment by NiiggerLifeMatter** [comment]
> Proxy => #26

const useProxy = require('puppeteer-page-proxy');




puppeteer.launch({ headless: false }).then(async browser => {
  const page = await browser.newPage()
  await page.setViewport({ width: 800, height: 600 })
  await useProxy(page, 'http://124.5.40.1:80');
  console.log(`All done, check the screenshots. ✨`)
  await browser.close()
})
whats wrong with that?

**Comment by ngosang** [comment]
Chrome is tested at startup. a85e9c2c8c87d881a71140040c904e6490ac2f39
