### ISSUE TITLE
Could not run in headless mode

### ISSUE THREAD

**Issue by thaodx** [FlareSolverr/FlareSolverr#710]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.0.2
- Last working FlareSolverr version: N/A
- Operating system: OSX
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): N/A
- Are you using a VPN: No
- Are you using a Proxy: No
- Are you using Captcha Solver: No
- If using captcha solver, which one:
- URL to test this issue: any URL
```

### Description

Even headless mode is enabled, the chrome window still popped up

### Logged Error Messages

```text
N/A
```

**Comment by ilike2burnthing** [comment]
Try v3.0.3

**Comment by ngosang** [comment]
I'm doing some tricks in the code to run headless in Windows and Linux. I don't have macOS to run some tests but probably you are right.
It's possible to run Docker containers in macOS, I recommend you that.
