### ISSUE TITLE
session.create is error

### ISSUE THREAD

**Issue by Cat2Boy** [FlareSolverr/FlareSolverr#716]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

i have run a docker in my mac:
docker run -d \
  --name=flaresolverr \
  -p 8191:8191 \
  -e LOG_LEVEL=info \
  --restart unless-stopped \
  ghcr.io/flaresolverr/flaresolverr:latest

i want to create a   seesion in my terminal:

curl -L -X POST 'http://localhost:8191/v1' \
-H 'Content-Type: application/json' \
-d '{
  "cmd": "sessions.create",
  "session":"123"
}'

result is:
{"status": "error", "message": "Error: Not implemented yet.", "startTimestamp": 1677486520765, "endTimestamp": 1677486520765, "version": "3.0.2"}%      

sessions.list  session.destroy  problem is same 
only request.get and request.post is work

### Logged Error Messages

```text
result is:
{"status": "error", "message": "Error: Not implemented yet.", "startTimestamp": 1677486520765, "endTimestamp": 1677486520765, "version": "3.0.2"}%
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/650

>Missing features could be implemented in the future by me or by other contributors. PRs will be accepted.
[...]
> - Session support
>
>[...]

**Comment by ngosang** [comment]
Implemented in 49fd1aacfc55548983bf1eed3b533a00a4b27eb0
FlareSolverr v3.1.0

**Comment by Cat2Boy** [comment]
wow thanks author. to use right now

**Comment by Zeks** [comment]
thnaks for this. helps a lot
