### ISSUE TITLE
I want to set Proxy ip with username and password.

### ISSUE THREAD

**Issue by awesome1128** [FlareSolverr/FlareSolverr#719]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.0.2
- Last working FlareSolverr version:
- Operating system:windows
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
- Are you using a VPN: yes
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hi support team!
Nice to meet you.
I have cloned and installed FlareSolverr 3.0.2, and running on my windows machine.
It works fine.

I want to set proxy ip with username and password, but I saw there is a way to set proxy ip only when requesting.
How can I set proxy ip with username and password?

Actually, if there is no way to set username and password, no need to set proxy ip in body request.
Please let me know, help me.
Thank you!

### Logged Error Messages

```text
No error.
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/657

**Comment by awesome1128** [comment]
Hi there?
Please let me know about proxy with username and password.
Thanks

**Comment by ilike2burnthing** [comment]
See above.

**Comment by awesome1128** [comment]
I saw it, what does that mean?

**Comment by ilike2burnthing** [comment]
It's an open issue, follow that for progress.

**Comment by awesome1128** [comment]
Seems like FlareSolverr can't be used proxy with username and password.
All kinds of Proxies can be used with username and password.
If username and password are not supported for now, the proxy concept is useless in FlareSolverr.

Do I have to wait until FlareSolverr team develops to support username and password?
Please let me know. Thanks!

**Comment by rix1337** [comment]
> "FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection." -> This is a description of FlareSolverr, I am not clear what proxy server means if FlareSolverr doesn't provide proxy authentication.
FlareSolverr still is exactly that. What you are asking for is FlareSolverr to use another independent proxy server.

> Do I have to wait until FlareSolverr team develops to support username and password? Please let me know. Thanks!
You could switch back to FlareSolverr 2 (not recommended) - which did support proxies.

Or you could add proxy support to FlareSolverr 3
Or you could find/pay someone to add proxy support to FlareSolverr 3

This issue is redundant. The same request was already made in #657

**Comment by awesome1128** [comment]
Hi @rix1337 , thanks for letting me know, but which version I can use for FlareSolverr 2?
Thanks again.

**Comment by rix1337** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.2.10

That one should also be available on docker hub.

I would not recommend it though. Cloudflare Detection requires an up 2 date solver.

**Comment by awesome1128** [comment]
Thank you so much!
