### ISSUE TITLE
Help me make a systemd .service

### ISSUE THREAD

**Issue by txtsd** [FlareSolverr/FlareSolverr#72]
### Description

Help me make a systemd .service file to launch this as a service.

I've been trying to make one for several hours, but the service keeps failing with this message: `Pkg: Error reading from file.`

Here's what I'm using:
(The user and group are created and managed by the package manager.)
```
[Unit]
Description=FlareSolverr Service
After=network-online.target

[Service]
User=flaresolverr
Group=flaresolverr
Restart=always
RestartSec=5
TimeoutStopSec=20
Type=simple
ExecStart=/opt/flaresolverr/flaresolverr
WorkingDirectory=/opt/flaresolverr

[Install]
WantedBy=multi-user.target

```

**Comment by ngosang** [comment]
I only published the x64 Linux package. Are you sure you have right architecture?
Execute `cd /opt/flaresolverr && /opt/flaresolverr/flaresolverr` to be sure the executable is in place.

**Comment by txtsd** [comment]
It was in the correct place. The problem was makepkg's strip, so I had to do a `options=('!strip')` in the PKGBUILD. It works fine now.

Here's the [AUR package](https://aur.archlinux.org/packages/flaresolverr/).

Let me know if the `After` and `WantedBy` fields are correct for this type of a service, and if there should be any other changes.

**Comment by Jorman** [comment]
For my configuration this (that is pretty the same as AUR package) works:
```
[Unit]
Description=FlareSolverr
After=jackett.service
Requires=jackett.service

[Service]
SyslogIdentifier=FlareSolverr

Environment="CAPTCHA_SOLVER=hcaptcha-solver"

Restart=always
RestartSec=5
Type=simple
User=YOUR_USER
Group=YOUR_GROUP
WorkingDirectory=/opt/FlareSolverr
ExecStart=/opt/FlareSolverr/flaresolverr
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
```
I use this only for jackett, if is not your case, you can remove `After=jackett.service` and `Requires=jackett.service`

J

**Comment by ngosang** [comment]
FlareSolverr v1.2.6 released.

**Comment by csgost** [comment]
[Unit]
Description=FlareSolverr Service
After=network.target

[Service]
Type=simple
User=root
Group=root

WorkingDirectory=/opt/FlareSolverr/flaresolverr
ExecStart=/bin/bash -lc "./flaresolverr"

Environment=HOME=/root
Environment=CAPTCHA_SOLVER=hcaptcha-solver
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Restart=always
RestartSec=5

StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/blob/master/flaresolverr.service
