### ISSUE TITLE
Kill threads if and when FlareSolverr crashes as well as retrying startup

### ISSUE THREAD

**Issue by 4C3T** [FlareSolverr/FlareSolverr#727]
### Have you checked our README?

- [x] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:2.2.10
- Last working FlareSolverr version:2.1.10
- Operating system:Windows 10 Enterprise
- Are you using Docker: [yes/no] No
- FlareSolverr User-Agent (see log traces or / endpoint): Huh?
- Are you using a VPN: [yes/no] Yes
- Are you using a Proxy: [yes/no] No
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one:
- URL to test this issue: Not applicable
```

### Description

I've had some troubles which started out of the blue when Radarr & Sonarr started reporting errors, not to mention that Prowlarr was screaming errors, and that revealed that FlareSolverr wasn't running.
So, tried starting it, but it died (Hidden process), so I opened up the console and died.
`2023-03-10T02:56:20+01:00 INFO FlareSolverr v2.2.10
2023-03-10T02:56:20+01:00 INFO Testing web browser installation...
2023-03-10T02:57:04+01:00 ERROR TimeoutError: Navigation timeout of 40000 ms exceeded
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:108:111`

Thought it might be Windows Firewall, so I shut it down. No change.
Thought it was my VPN but doesn't appear so.
Could be Windows being Windows, and I'll have to check if anything else is behaving like muppets.
Also checked, no such folder structure exist. Even created the folder structure, but no data was written to it.

Regardless, it would be very nice if this flaresolverr.exe could, in the event of cataclysmic failures (Ie: Not starting for some reason), kill all processes that it creates (Firefox.exe) instead of just leaving these running. Thankfully I'm using Process Explorer so it's fairly quick and easy to "Kill process tree" as opposed to Task Manager with right-click, close, "Yes?/No?" for each process.
Could be nice if it either had a command switch for attempting to continuously run all processes at startup until everything is working normally, or just exit (perhaps with a better error code than the above, if indeed an app-error).

Also, in the future one could hope for a service installer so that it can be installed like the others.
Maybe even integrate this into Prowlarr & Jackett? Wishful thinking but would eliminate a few problems perhaps..?

### Logged Error Messages

```text
No log files that I could find
```

**Comment by ilike2burnthing** [comment]
v2 is no longer supported, update to v3 and see if your issue continues

**Comment by 4C3T** [comment]
Yeah, sure. Would be very nice if there was an executable to run too and not having to run Python & stuff.
Still would be nice if it was incorporated directly into Prowlarr & Jackett.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/660

**Comment by DrStrange** [comment]
@4C3T, No, your Windows install is not misbehaving. Google seemed to have taken a dislike to flaresolverr v2? Look at #706 -  Note how reddit is spelt reditt. Also see #703 for the initial fix.
I use v3.0.4 in windows 10 which I can confirm does not have this issue so I don't know if `set TEST_URL=https://www.reditt.com/` still works. It's easy to build a v3 Windows binary, just make sure flaresolverr.exe can find package.json. It might be overkill to install Python/Chrome/PyInstaller if you don't use them for anything else.

**Comment by 4C3T** [comment]
> @4C3T If you want to stick with v2 you can check out #706 to see if this fixes your error or if your Windows install is actually misbehaving - Google seems to have taken a dislike to flaresolverr v2. Note how reddit is spelt reditt. Also see #703 for the initial fix. I do not know if `set TEST_URL=https://www.reditt.com/` still works for v2.2.10 as i no longer use v2. I can confirm v3 does not have your error.
> 
> It's straight forward to build a v3 Windows binary. The only manual intervention needed for a v3 build is that package.json needs copied or moved so flaresolverr.exe can find it (see details in #660 - package.json needs to be placed one folder level above the folder where flaresolverr.exe is). Overkill to install Python/Chrome/PyInstaller/Python Dependencies to keep Flaresolverr v3 up to date if you have no other applications that require these softwares? Maybe? What value does one put on Flaresolverr?

After carefully reading the #706 while being a bit tired (Haven't slept well lately), I managed to get FlareSolverr working with the `set TEST_URL=https://www.reditt.com/` system variable.

I didn't see it first as it wasn't highlighted and at first I actually thought it was a parameter somewhere inside a config-file so I kept scrolling back & forth a few times.

Everything's working now I think, but it's weird that this address changed everything without any errors indicating this would cause it, or at least something that would give the hint that something was related to that.
I mean, " ERROR TimeoutError: Navigation timeout of 40000 ms exceeded
    at C:\snapshot\FlareSolverr\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:108:111" isn't exactly a lot to go on...


Anywhoo, I entered the parameter into system properties (Start+Pause/Break->Advanced system settings then under Environment variables (<-Not sure about the translation here).
Haven't tested a reboot yet, but this should suffice I think.


As for the v.3.x I'll have a look some day when I'm a bit more up to the task and not tired all the time.
