### ISSUE TITLE
Flaresolverr container will not start for the past 5 days

### ISSUE THREAD

**Issue by ksheyman** [FlareSolverr/FlareSolverr#734]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 2.2.1
- Last working FlareSolverr version: unknown
- Operating system: Ubuntu 22.04
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): unknown
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: 
```

### Description

About 4 days ago flaresolverr randomly stopped working. It may have been related to an update of Docker itself but I'm not certain. I tried pulling the flaresolverr image again and no difference, the container will not start. I cannot think of anything else that may have changed.

### Logged Error Messages

```text
2023-03-15T20:38:45+00:00 INFO FlareSolverr v2.2.1
2023-03-15T20:38:45+00:00 INFO Testing web browser installation...
2023-03-15T20:39:29+00:00 ERROR TimeoutError: Navigation timeout of 40000 ms exceeded
    at /home/node/flaresolverr/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:107:111
```

**Comment by Rumpa112** [comment]
**### URL to test this issue**: https://hidden.com/

An URL of a private track or any other private site should not be shown here or anywhere else, how stupid can one be? **NOT talking about the OP.** These trackers are private for a fucking reason. If I (or anyone else) were to inform them about this stupidity. This poor user would be banned asap and it would not be his fault!

**Comment by ksheyman** [comment]
> **### URL to test this issue**: https://hidden.com/
> 
> An URL of a private tracker or any other private site should not be shown here or anywhere else, how stupid can one be? **NOT talking about the OP.** These trackers are private for a fucking reason. If I (or anyone else) were to inform them about this stupidity. This poor user would be banned asap and it would not be his fault!

Thank you, this did not occur to me at all so I guess that's how stupid one can be lol. Edited the comment to remove.

**Comment by Rumpa112** [comment]
> > **### URL to test this issue**: https://hidden.com/
> > An URL of a private tracker or any other private site should not be shown here or anywhere else, how stupid can one be? **NOT talking about the OP.** These trackers are private for a fucking reason. If I (or anyone else) were to inform them about this stupidity. This poor user would be banned asap and it would not be his fault!
> 
> Thank you, this did not occur to me at all so I guess that's how stupid one can be lol. Edited the comment to remove.

Like I wrote, Didn't mean you 😉 The one that made the form should have thought of this IMO.

**Comment by ilike2burnthing** [comment]
Please ignore the above, it's perfectly fine to name and link to private trackers. Here's an entire repo where we do exactly that, often at the behest of the tracker admins or with their help - https://github.com/Jackett/Jackett

As to your issue, v2.2.1 is over a year old, that it worked up to now is more of a surprise than anything. Pull the latest image and try again.

**Comment by Rumpa112** [comment]
Yeah listen to the smart man, he knows things 😆😆😆

Den ons 15 mars 2023 23:51ilike2burnthing ***@***.***> skrev:

**Comment by ksheyman** [comment]
> Please ignore the above, it's perfectly fine to name and link to private trackers. Here's an entire repo where we do exactly that, often at the behest of the tracker admins or with their help - https://github.com/Jackett/Jackett
> 
> As to your issue, v2.2.1 is over a year old, that it worked up to now is more of a surprise than anything. Pull the latest image and try again.

Well I'm an idiot. I was using portainer and I swear to god I had it pull the image at least twice and it was still 2.2.1 lol. Once I did it manually it updated and is working now. I'll close this, thank you.
