### ISSUE TITLE
Unable to process browser request. Error: Maximum timeout reached

### ISSUE THREAD

**Issue by Nesego** [FlareSolverr/FlareSolverr#74]
### Environment

**FlareSolverr Version**: 1.2.3

**Docker**: NO

**OS**: Ubuntu Server 18.04 "Bionic Beaver" LTS (64bits)

**Last Working FlareSolverr Version**: 1.2.3

**Are you using a proxy or VPN?** no

**Using Captcha Solver:** well, trying...

**If using captcha solver, which one:** hcaptcha-solver

### Description

Hi, on Jackett i'm getting a timeout error since yesterday when the cloudflare solve seemed to work fine until now *without using any captcha solver*. I don't and **won't use Docker** on my server since i've been working with on standalone Quickbox for a long time.

I figured maybe the issue is that I should start using hcaptcha now. Although documentation is very thin and i'm getting *fund errors* when trying to install hcaptcha and get it running and have no idea what it means ! Can you help me with that :) ?

Finally my last question : is the `docker-compose.yml` used as a config file even in standalone mode ? I set it up to include hcaptcha (assuming it would work...).

### Logged Error Messages

Jackett error :
```
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)
```

Log error :
```
● flaresolverr.service - Flaresolverr Daemon
   Loaded: loaded (/etc/systemd/system/flaresolverr.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-01-19 15:23:40 UTC; 1h 44min ago
 Main PID: 20100 (node)
       IP: 3.0M in, 2.9M out
    Tasks: 11 (limit: 4915)
   Memory: 152.3M
      CPU: 31.365s
   CGroup: /system.slice/flaresolverr.service
           └─20100 /usr/bin/node /home/nesego/Flaresolverr/FlareSolverr/dist/index.js

janv. 19 16:51:14 neseplex.eu node[20100]: 2021-01-19T16:51:14.005Z ERROR REQ-6 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)
janv. 19 17:07:05 neseplex.eu node[20100]: 2021-01-19T17:07:05.722Z INFO REQ-7 Incoming request: POST /v1
janv. 19 17:07:05 neseplex.eu node[20100]: 2021-01-19T17:07:05.723Z INFO REQ-7 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www2.yggtorrent.si/new_search/search?c
janv. 19 17:07:06 neseplex.eu node[20100]: 2021-01-19T17:07:06.296Z INFO REQ-7 Cloudflare detected
janv. 19 17:08:06 neseplex.eu node[20100]: 2021-01-19T17:08:06.012Z ERROR REQ-7 Error: Maximum timeout reached. maxTimeout=60000 (ms)
janv. 19 17:08:06 neseplex.eu node[20100]:     at exports.toError (/home/nesego/Flaresolverr/FlareSolverr/node_modules/await-timeout/src/utils.js:20:38)
janv. 19 17:08:06 neseplex.eu node[20100]:     at Timeout.fn (/home/nesego/Flaresolverr/FlareSolverr/node_modules/await-timeout/src/index.js:32:46)
janv. 19 17:08:06 neseplex.eu node[20100]:     at listOnTimeout (node:internal/timers:556:17)
janv. 19 17:08:06 neseplex.eu node[20100]:     at processTimers (node:internal/timers:499:7)
janv. 19 17:08:06 neseplex.eu node[20100]: 2021-01-19T17:08:06.012Z ERROR REQ-7 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms)
```

<img width="639" alt="Capture d’écran 2021-01-19 à 18 22 33" src="https://user-images.githubusercontent.com/40238259/105070783-13d76c00-5a84-11eb-98c3-ca0cbd0a4f6f.png">

Last but not least, thanks for the hard work. Which, as you know, has been lifesaving for YGG users lately ;)

**Comment by ngosang** [comment]
Could you share the URL? Try to open the URL in your web browser (remove the cookies) to see if the challenge is resolved in less time.

> I figured maybe the issue is that I should start using hcaptcha now. Although documentation is very thin and i'm getting fund errors when trying to install hcaptcha and get it running and have no idea what it means ! Can you help me with that :) ?

hcaptcha resolver is not working. You can disable it.

> Finally my last question : is the docker-compose.yml used as a config file even in standalone mode ? I set it up to include hcaptcha (assuming it would work...).

No, it's not required. It's helpful for Docker installs.

**Comment by Nesego** [comment]
Hi ! Thanks for your answer. Ok, got it for hcaptcha and the docker-compose.yml file.

Not sure if I get what you ask. Are you talking about the url of the tracker i'm trying to access ? Thing is flaresolverr is installed on a distant server, so will I see how my account/cookie filled in Jackett is affected if I connect to the tracker from my laptop ?

**Comment by Nesego** [comment]
Here you go. The error changed this time, reminds me of an issue i've seen passing by. I'll go check in the meantime.

```
janv. 19 21:03:04 neseplex.eu node[20100]: 2021-01-19T21:03:04.189Z INFO REQ-14 Incoming request: POST /v1
janv. 19 21:03:04 neseplex.eu node[20100]: 2021-01-19T21:03:04.568Z INFO REQ-14 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www2.yggtorrent.si/new_search/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; 
janv. 19 21:03:38 neseplex.eu node[20100]: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.
janv. 19 21:03:38 neseplex.eu node[20100]:     at Timeout.onTimeout (/home/nesego/Flaresolverr/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:170:20)
janv. 19 21:03:38 neseplex.eu node[20100]:     at listOnTimeout (node:internal/timers:556:17)
janv. 19 21:03:38 neseplex.eu node[20100]:     at processTimers (node:internal/timers:499:7)
janv. 19 21:03:38 neseplex.eu node[20100]: 2021-01-19T21:03:38.055Z ERROR REQ-14 Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.
janv. 19 21:03:53 neseplex.eu node[20100]: 2021-01-19T21:03:53.499Z INFO REQ-15 Incoming request: GET /
janv. 19 21:03:53 neseplex.eu node[20100]: 2021-01-19T21:03:53.499Z INFO REQ-15 Successful response in 0 s
janv. 19 21:03:53 neseplex.eu node[20100]: 2021-01-19T21:03:53.499Z INFO REQ-15 FlareSolverr is ready!
```

**Comment by bisol84** [comment]
The website was down. All is now OK.

**Comment by Nesego** [comment]
Holly mother of... Well, ok :D 🗡️ 
Thanks !
