### ISSUE TITLE
[yggtorrent] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by WaffleBoyQc** [FlareSolverr/FlareSolverr#760]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.do/
```

### Description

i try to login and give me The cookies provided by FlareSolverr are not valid.

I can provide this result on resolver 

2023-04-16 16:43:51 INFO     172.19.0.2 POST http://172.19.0.3:8191/v1 200 OK
2023-04-16 16:44:06 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.do/'}

### Logged Error Messages

```text
The cookies provided by FlareSolverr are not valid
```

**Comment by ilike2burnthing** [comment]
Provide the environment information requested.
