### ISSUE TITLE
cookies param is not passed to _evil_logic function hence cookies set on request.get or request.post don't get applied

### ISSUE THREAD

**Issue by RudraPSinha** [FlareSolverr/FlareSolverr#766]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.1.2
- Last working FlareSolverr version: NA
- Operating system: Windows
- Are you using Docker:  no
- FlareSolverr User-Agent (see log traces or / endpoint): NA
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: NA
- If using captcha solver, which one: NA
- URL to test this issue: NA
```

### Description

I was sending the following request body to the endpoint at `http://localhost:8191/v1` 

```
{
    "cmd": "request.post",
    "session":"ALPHA2",
    "url": "http://localhost:3000/api/signup",
    "postData": "country_origin=India&country_code=91&phone_number=XXXXXXXX&password=abcdefghij&password_cypher=abcdefghij&captcha_id=ecc",
    "maxTimeout": 60000,
    "cookies": [{"name":"nas", "value":"daily"}]
}
````

on the localhost:3000 server, I was running a test server to observe the header and post data that are being sent over through flaresolverr. It came to my notice that the cookies params are entirely ignored when checked on the test server for the incoming data. I tested two variation for the cookie parameter, first the one as given in the above payload, and another in the `a=b;` format. Neither worked, so I took a cursory view of the source code and found that the driver doesn't set the cookies that are passed to the logic through something like this in python selenium: 

 `driver.add_cookie({'name': 'foo', 'value': 'bar'})`
 
 As this is missing, hence the driver never applies any cookies that are passed to the flaresolverr api. 

### Logged Error Messages

```text
NA
```

**Comment by ReadMost** [comment]
Guess cookie format is not correct, it should be [{"name": "A", "value": "aa", "secure": True...}] and so on

**Comment by ngosang** [comment]
It's not implemented yet. Follow this issue => #659
