### ISSUE TITLE
Flaresolverr 3.1.2 ignoring proxy param

### ISSUE THREAD

**Issue by duku602** [FlareSolverr/FlareSolverr#774]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.1.2
- Last working FlareSolverr version: -
- Operating system: linux
- Are you using Docker: YES
- FlareSolverr User-Agent (see log traces or / endpoint): -
- Are you using a VPN: NO
- Are you using a Proxy: YES
- Are you using Captcha Solver: NO
- If using captcha solver, which one: -
- URL to test this issue: https://ipinfo.io/ip
```

### Description

Anytime when I try using a proxy/socks it gets ignored, doesn't matter if I use sessions.create cmd with proxy or request.get.

I am using the latest version 3.1.2 running with docker-compose

Request POST http://localhost:8191/v1
```json
{
    "cmd": "request.get",
    "url": "https://ipinfo.io/ip",
    "maxTimeout": 60000,
    "proxy": {
        "url": "socks4://98.188.47.132:4145"
    }
}
``` 

Response 
```Json
{
    "status": "ok",
    "message": "Challenge not detected!",
    "solution": {
        "url": "https://ipinfo.io/ip",
        "status": 200,
        "cookies": [],
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
        "headers": {},
        "response": "<html><head></head><body>xxx.xx.227.209</body></html>"
    },
    "startTimestamp": 1683664878149,
    "endTimestamp": 1683664879110,
    "version": "3.1.2"
}
```

please fix it.

### Logged Error Messages

```text
no errors
```

**Comment by 362227** [comment]
+1

**Comment by Senforge** [comment]
Same issue.

**Comment by mihneamanolache** [comment]
Hey all, any updates on this issue? +1 here.

**Comment by ajtatum** [comment]
I was thinking of leveraging this for a project in combination with [CloudProxy](https://github.com/claffin/cloudproxy) and was going to submit a request to allow for Proxy Authorization as that's what CloudProxy provides in their API response, but if it doesn't work with proxies at all then that request is mute at the moment. It would be great to have this working with proxies and with proxy authorization, eg, being able to use http://username:password:192.168.0.1:8899 as a proxy address.

**Comment by ngosang** [comment]
Implemented in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.2.0
