### ISSUE TITLE
Can you use  FlareSolverr on a vps and use it on a complete different network ?> 

### ISSUE THREAD

**Issue by NiiggerLifeMatter** [FlareSolverr/FlareSolverr#78]
Can you use  FlareSolverr on a vps and use it on a complete different network ?

Lets say I have a server and I want to run it on my local machine which is another network how to I use it and can I see use nases in NODEJS/PYTHON?

**Comment by NiiggerLifeMatter** [comment]
https://www.npmjs.com/package/puppeteer-page-proxy

const useProxy = require('puppeteer-page-proxy');

await useProxy(page, 'http://127.0.0.1:80');

**Comment by ngosang** [comment]
Do not spam with the proxy thing.

> Can you use FlareSolverr on a vps and use it on a complete different network ?

Yes, you can use FlareSolverr in a different network but if you are trying to bypass Cloudflare its not going to work well. Cloudflare checks that the cookie and IP matches. My advise is to run FlareSolverr + your software in the same network.
