### ISSUE TITLE
Cookie processing does not work (with proposed fix)

### ISSUE THREAD

**Issue by hwertz** [FlareSolverr/FlareSolverr#781]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system: Ubuntu 22.04 (Python 3.11 installed via PPA and running FlareSolverr in a Python 3.11 venv).
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:  (this would affect any URL)
```

### Description

I set flaresolverr up a few days ago, wonderful work!   I had very little trouble getting an existing program to make flaresolverr proxy requests instead of connecting to origin server.  Good work!

Anyway, I have to provide a few cookies and found they didn't work; I assumed I had a problem with encoding or something. Finally look at flaresolverr source and there's no code to actually use cookies in a request.get or request.put request!

Here's a short and effective patch that does so.

Caveats:
Chrome will not let you try to set cookies for any domain but the one you are on (if you load a cookie add-on, I noticed it doesn't either, unlike firefox where it'll let you freely set cookies for whatever domain you want).  Therefore, this sets cookies at the END, after the request was made, so the browser is on the right domain (so cookies are primed and ready for the *next* request).  This means you MUST use a session (I'm using session=1 since I'm only using 1 session), since the first request cannot get/put with cookies set and you will get the "no cookies set" response from the site.  Then the cookies are set for subsequent requests!  (For my purposes, I'm using the same cookies on each request, so this is perfectly fine for my use.)

I found if I set cookies before the request, chromedriver or chrome rejects the request outright and neither cloudflare or the site come up, there'd need to be more elaborate logic to make sure the session is on the right domain before it sends in the cookies to set them ahead of the request (or catch the "cookies are for the wrong domain" error from chromedriver or wherever it's coming from) .  Which is doable, but here's a short and simple *2 line* patch against Flaresolverr-3.1.2. 

Enjoy!
--Henry

Patch:
[flaresolverr-cookies-patch.txt](https://github.com/FlareSolverr/FlareSolverr/files/11538297/flaresolverr-cookies-patch.txt)

### Logged Error Messages

```text
Nothing relevant; cookies do show in request logs
 as received by flaresolverr but are not processed
 by it, with this patch they are.
```

**Comment by ngosang** [comment]
Implemented in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.2.0
