### ISSUE TITLE
[torrentleech] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by nacjacks** [FlareSolverr/FlareSolverr#794]
### Have you checked our README?

- [X] I have checked the README

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: yes
- FlareSolverr User-Agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I am receiving this error when trying to add torrentleech.org as an indexer in Jackett. I have disabled ipv6 in both containers and both containers are running on the host network as suggested in another post but neither solution seems to have help.

### Logged Error Messages

```text
flaresolverr-flaresolverr1
date	stream	content
2023-06-02T19:27:03.724816633Z	stdout	2023-06-02 13:27:03 INFO     192.168.1.201 POST http://192.168.1.201:8191/v1 200 OK
2023-06-02T19:27:03.724327921Z	stdout	2023-06-02 13:27:03 INFO     Response in 2.791 s
2023-06-02T19:27:03.407924617Z	stdout	2023-06-02 13:27:03 INFO     Challenge not detected!
2023-06-02T19:27:00.932906247Z	stdout	2023-06-02 13:27:00 INFO     Incoming request => POST /v1 body: {'postData': 'username=NOPE&password=NOPE&alt2FAToken=', 'maxTimeout': 55000, 'cmd': 'request.post', 'url': 'https://www.torrentleech.org/user/account/login/'}
2023-06-02T19:25:29.640365756Z	stdout	2023-06-02 13:25:29 INFO     192.168.1.122 GET http://192.168.1.201:8191/ 200 OK
2023-06-02T19:25:29.566400878Z	stdout	2023-06-02 13:25:29 INFO     Serving on http://0.0.0.0:8191
2023-06-02T19:25:29.537846516Z	stdout	2023-06-02 13:25:29 INFO     Test successful!
2023-06-02T19:25:29.537075449Z	stdout	2023-06-02 13:25:29 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
2023-06-02T19:25:27.147384363Z	stdout	2023-06-02 13:25:27 INFO     Launching web browser...
2023-06-02T19:25:27.147212066Z	stdout	2023-06-02 13:25:27 INFO     Chrome / Chromium major version: 113
2023-06-02T19:25:27.012395016Z	stdout	2023-06-02 13:25:27 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-06-02T19:25:27.011608599Z	stdout	2023-06-02 13:25:27 INFO     Platform: Linux-3.10.108-x86_64-with-glibc2.31
2023-06-02T19:25:27.009110810Z	stdout	2023-06-02 13:25:27 INFO     Testing web browser installation...
2023-06-02T19:25:27.008341202Z	stdout	2023-06-02 13:25:27 INFO     FlareSolverr 3.2.0
```

**Comment by Locutus64** [comment]
Having a issue with TorrentLeech as well

```
An error occurred while updating this indexer
Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing. ---> System.TimeoutException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled. at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at FlareSolverrSharp.Solvers.FlareSolverr.<>c__Dis
[Click here to open an issue on GitHub for FlareSolverr.](https://github.com/FlareSolverr/FlareSolverr/issues/new?template=bug_report.yml&title=[torrentleech]%20(updating)%20Exception%3A%20System.Threading.Tasks.TaskCanceledException%3A%20The%20request%20was%20canceled%20due%20to%20the%20configured%20HttpClient.Timeout%20of%2060%20seconds%20elapsing.%0A%20---%3E%20System.TimeoutException%3A%20A%20task%20was%20canceled.%0A%20---%3E%20System.Threading.Tasks.TaskCanceledException%3A%20A%20task%20was%20canceled.%0A%20%20%20at%20System.Threading.Tasks.TaskCompletionSourceWithCancellation%601.WaitWithCancellationAsync(CancellationToken%20cancellationToken)%0A%20%20%20at%20System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage%20request%2C%20Boolean%20async%2C%20CancellationToken%20cancellationToken)%0A%20%20%20at%20System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage%20request%2C%20Boolean%20async%2C%20Boolean%20doRequestAuth%2C%20CancellationToken%20cancellationToken)%0A%20%20%20at%20System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage%20request%2C%20Boolean%20async%2C%20CancellationToken%20cancellationToken)%0A%20%20%20at%20System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage%20request%2C%20Boolean%20async%2C%20CancellationToken%20cancellationToken)%0A%20%20%20at%20System.Net.Http.HttpClient.%3CSendAsync%3Eg__Core%7C83_0(HttpRequestMessage%20request%2C%20HttpCompletionOption%20completionOption%2C%20CancellationTokenSource%20cts%2C%20Boolean%20disposeCts%2C%20CancellationTokenSource%20pendingRequestsCts%2C%20CancellationToken%20originalCancellationToken)%0A%20%20%20---%20End%20of%20inner%20exception%20stack%20trace%20---%0A%20%20%20---%20End%20of%20inner%20exception%20stack%20trace%20---%0A%20%20%20at%20System.Net.Http.HttpClient.HandleFailure(Exception%20e%2C%20Boolean%20telemetryStarted%2C%20HttpResponseMessage%20response%2C%20CancellationTokenSource%20cts%2C%20CancellationToken%20cancellationToken%2C%20CancellationTokenSource%20pendingRequestsCts)%0A%20%20%20at%20System.Net.Http.HttpClient.%3CSendAsync%3Eg__Core%7C83_0(HttpRequestMessage%20request%2C%20HttpCompletionOption%20completionOption%2C%20CancellationTokenSource%20cts%2C%20Boolean%20disposeCts%2C%20CancellationTokenSource%20pendingRequestsCts%2C%20CancellationToken%20originalCancellationToken)%0A%20%20%20at%20FlareSolverrSharp.Solvers.FlareSolverr.%3C%3Ec__Dis)
```

**Comment by ilike2burnthing** [comment]
@Locutus64 that's a different error, it's timing out. Continue over at https://github.com/Jackett/Jackett/issues/14410.

**Comment by ilike2burnthing** [comment]
@nacjacks add TorrentQQ, test. Does it work? If not, what's the error? If it does though, does FlareSolverr show it being processed?

Enable debug and HTML logging, provide the output of your test for TorrentLeech - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by nacjacks** [comment]
TorrentQQ worked with no issues.

Attached is the zipped html output of TorrentLeech
[flaresolverr-flaresolverr1.html.zip](https://github.com/FlareSolverr/FlareSolverr/files/11640053/flaresolverr-flaresolverr1.html.zip)

**Comment by ilike2burnthing** [comment]
Odd, FlareSolverr isn't getting the challenge page, just the TorrentLeech login page.

Please provide an enhanced Jackett log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by nacjacks** [comment]
[log.txt](https://github.com/FlareSolverr/FlareSolverr/files/11640469/log.txt)

**Comment by ilike2burnthing** [comment]
Very strange. If you access the *.org site in browser from the same IP, do you get a Cloudflare challenge page? You may need to try opening it in a private window if you've recently accessed the site.

Try the official TL proxies in Jackett instead of *.org, see if they work for you.

**Comment by nacjacks** [comment]
I get a challenge page when opening the org site in a browser but it redirects without input from me.

**Comment by nacjacks** [comment]
*.cc worked without any issues

**Comment by ilike2burnthing** [comment]
K, well I'll leave this open for @ngosang to have a look at, but stick with *.cc for now.

**Comment by kjettern** [comment]
+1 on the issue. cc working here as well.

**Comment by klepp0906** [comment]
just to +1
I'm getting the following
![image](https://github.com/FlareSolverr/FlareSolverr/assets/10392920/efd1c918-c2b1-41e9-80f0-187aa9274637)
which appears to be working, yet prowlarr has it failing.  for now ive been working around it by simply using one of the mirrors that does not have cloudflare up (yet).

**Comment by ilike2burnthing** [comment]
@klepp0906 follow the troubleshooting steps here, and let me know if you come across any issues with them - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

Is LearnFlakes working for you?

**Comment by klepp0906** [comment]
> @klepp0906 follow the troubleshooting steps here, and let me know if you come across any issues with them - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting
> 
> Is LearnFlakes working for you?

learnflakes & hd-space are both working for me with flaresolverr yes.  only TL is giving me problems as of the point in which they added cloudflare.

just woke up but ill look at the troubleshooting steps now.   at a brief glance, not using a vpn or proxy or ipv6, and not using docker (on windows) which seems to omit most of it.

will get some coffee flowing and mess with it some more though and report back

**Comment by BakedDanish** [comment]
having the same issue with my seedbox. added Flaresolver, getting the following error...
An error occurred while updating this indexer
The cookies provided by FlareSolverr are not valid

**Comment by ilike2burnthing** [comment]
@BakedDanish follow the troubleshooting steps here, and let me know if you come across any issues with them - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

Otherwise, try the official TL proxies in Jackett instead of *.org, see if they work for you.

**Comment by ilike2burnthing** [comment]
IPv6 can be disabled per container - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by BakedDanish** [comment]
How is that possible when I do not have root/admin rights to change sysctl ?
"sysctl: permission denied on key 'net.ipv6.conf.all.disable_ipv6'"

**Comment by ilike2burnthing** [comment]
You're doing that for the container, not the host?

**Comment by IamGimli** [comment]
So, I had this issue and I found that I had to disable IPv6 not only on the Flaresolverr system, but also on the system that was running Jackett. 

That makes sense if Flaresolverr has an issue supporting IPv6 Cloudflare challenges and creating cookies for them, then Jackett won't be able to use the cookies created by Flaresolverr using IPv4 to access the site using IPv6.

**Comment by BakedDanish** [comment]
IPV6 is already disabled on my seedbox so that is not a cause for my issue.

**Comment by ngosang** [comment]
Fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.1
