### ISSUE TITLE
Cannot crawl this page using cloudflare.

### ISSUE THREAD

**Issue by Roninchen** [FlareSolverr/FlareSolverr#799]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
4ca63dafd0ef   ghcr.io/flaresolverr/flaresolverr:latest   "/usr/bin/dumb-init …"   12 minutes ago   Up 12 minutes                 0.0.0.0:8191->8191/tcp   flaresolverr
```

### Description

Cannot crawl this page using cloudflare.

https://dexcheck.io/eth-api/token_top_traders?size=20&sort_by=realized_profit&sort_side=desc&timeframe=1&top=false&coingecko=0&exclude_bots=1&page=4

### Logged Error Messages

```text
{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://dexcheck.io/eth-api/token_top_traders?size=20&sort_by=realized_profit&sort_side=desc&timeframe=1&top=false&coingecko=0&exclude_bots=1&page=4", "status": 200, "cookies": [], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head><meta name=\"color-scheme\" content=\"light dark\"></head><body><pre style=\"word-wrap: break-word; white-space: pre-wrap;\">{\"message\":\"Something went wrong\",\"success\":false}\n</pre></body></html>"}, "startTimestamp": 1686484686111, "endTimestamp": 1686484688083, "version": "3.2.1"}%
```

**Comment by ilike2burnthing** [comment]
I'm not getting any challenge page when accessing the site in browser, and it appears FlareSolverr isn't either. Are you getting one in browser?

**Comment by Roninchen** [comment]
https://dexcheck.io/app/eth/top-traders

The interface comes from this, https://dexcheck.io/app/eth/top-traders
All its interfaces are inaccessible

**Comment by ilike2burnthing** [comment]
That has nothing to do with Cloudflare.

**Comment by Roninchen** [comment]
Do you have a way to get his data through this website interface?
https://dexcheck.io/eth-api/token_top_traders?size=20&sort_by=realized_profit&sort_side=desc&timeframe=1&top=false&coingecko=0&exclude_bots=1&page=1

https://dexcheck.io/app/eth/top-traders

**Comment by Roninchen** [comment]
Do you have a way to get his data through this website interface?
https://dexcheck.io/eth-api/token_top_traders?size=20&sort_by=realized_profit&sort_side=desc&timeframe=1&top=false&coingecko=0&exclude_bots=1&page=1

https://dexcheck.io/app/eth/top-traders

**Comment by ilike2burnthing** [comment]
Could be cookies, or maybe the referer.

**Comment by Roninchen** [comment]
Can you crack it for me, I can pay you usdt

**Comment by ilike2burnthing** [comment]
No thanks, otherwise busy.
