### ISSUE TITLE
Challenge not detected! - (There is no challenge but the cookies wont work)

### ISSUE THREAD

**Issue by NixV37** [FlareSolverr/FlareSolverr#802]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.1
- Last working FlareSolverr version: ?
- Operating system: Windows
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): none
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://www.cyberbackgroundchecks.com/email
```

### Description

Just open the binary for windows, then try to send a request for that page, for some reason it will only return __cf_bm and thats all (I mean there is no other cloudflare cookie), then using that cookie with requests wont work.

Tried with a vpn so that I can get a challenge by hand (On the browser), when I get one the other cloudflare cookie gets generated (I dont remember the name but something like clarance or smth).

With that cookie the request works but without it, it wont, even if I take the cookies from the browser when there was no challenge.

### Logged Error Messages

```text
2023-06-16 02:31:08 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.cyberbackgroundchecks.com/email', 'maxTimeout': 60000}
2023-06-16 02:31:22 INFO     Challenge not detected!
2023-06-16 02:31:22 INFO     Response in 13.831 s
2023-06-16 02:31:22 INFO     127.0.0.1 POST http://localhost:8191/v1 200 OK
```

### Screenshots

Well thats everything I guess, If anyone knows anything about this, please help me thanks <3

**Comment by NixV37** [comment]
I saw some similar issues but never found a solution, only saying that im not using the same ip and that type of stuff, but I am doing it so idk

**Comment by ilike2burnthing** [comment]
Disable IPv6, see if that helps. If not, enable debug and HTML logging, provide the output for that URL.

**Comment by NixV37** [comment]
Sure, trying now

**Comment by NixV37** [comment]
How can I disable IPv6 tho, sorry for asking but I cant find anything

**Comment by ilike2burnthing** [comment]
First google result - https://networking.grok.lsu.edu/Article.aspx?articleid=17573

**Comment by NixV37** [comment]
Oh ok yeah it is disabled, tried again and didnt work:

[log.txt](https://github.com/FlareSolverr/FlareSolverr/files/11777741/log.txt)

**Comment by ilike2burnthing** [comment]
Your user account is hitler? I think we're done here.

**Comment by NixV37** [comment]
What? no its my brother's computer lol he just makes fun of that type of shit

Already told him to change it few times

**Comment by NixV37** [comment]
Anyways if u still dont want to continue I understand it its ok

**Comment by ilike2burnthing** [comment]
Your 'brother' is a fucking idiot, and likely to get his head kicked in.

There's nothing for FlareSolverr to bypass, there's no challenge, and I don't see one in browser either.

**Comment by NixV37** [comment]
Ill kick him for you no worries.

Yeah Ill have to find it by myself, its strange tbh
