### ISSUE TITLE
[btmet] (testing) Exception (btmet): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by MG665** [FlareSolverr/FlareSolverr#808]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: FlareSolverr 3.2.1
- Last working FlareSolverr version: None, first version used is 3.2.1
- Operating system: Windows Server 2022 Data Center Edition x64
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
- Are you using a VPN: Data Center IP (non-residential)
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://btmet.com/search.php?q=2023&o=1
```

### Description

Jackett doesn't work with btmet and many other websites when FlareSolverr is on, gets a wrong FlareSolverr cookie according to the error message.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (btmet): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid
Click here to open an issue on GitHub for FlareSolverr.
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/13345045/16345f25-b330-4852-b3be-68784dd03cc4)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13345045/1a25b8fa-016e-4d53-bc71-e2ab4a6830e8)

**Comment by MG665** [comment]
**Update:** Using residential internet and a local copy of FlareSolverr works with that same indexer. So this is likely not an issue with Flaresolverr itself, but rather the remote network given that CF filters most hosting IP addresses/servers. 
The only confusing part is that FS shows that the challenge was solved successfully on the remote data center machine, yet the cookies are wrong on the destination client running Jackett.
![image](https://github.com/FlareSolverr/FlareSolverr/assets/13345045/9203e6e7-0cee-437e-a626-ccff54f55dd4)

**Comment by ilike2burnthing** [comment]
Jackett and FlareSolverr should ideally be on the same device and need to share the same IP, so if using a VPN or proxy, they'd need to share same server. IPv6 should also be disabled.
