### ISSUE TITLE
Please option to "puppeteer-page-proxy"

### ISSUE THREAD

**Issue by NiiggerLifeMatter** [FlareSolverr/FlareSolverr#81]
I would like to send an api request to my website like

curl -s "http://mywebsite.com/?curl=HTTPS://SCRAPPEDWEBSITE.NET&proxy=http://12.12.15.15:8080"

https://www.npmjs.com/package/puppeteer-page-proxy

**Comment by NiiggerLifeMatter** [comment]
https://www.npmjs.com/package/puppeteer-page-proxy

const useProxy = require('puppeteer-page-proxy');

await useProxy(page, 'http://127.0.0.1:80');

**Comment by ngosang** [comment]
We already have an issue to implement proxy support. I will consider using this package.
#26
