### ISSUE TITLE
Cloudflare Error: The solver 'hcaptcha-solver' is not a valid captcha solving method

### ISSUE THREAD

**Issue by RudyBzhBzh** [FlareSolverr/FlareSolverr#82]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### Instruction on how to enable debug and html trace

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

**FlareSolverr Version**: v1.2.3 (installed from zip, not compiled from source)

**Docker**: [yes/no] no

**OS**: Debian buster

**Last Working FlareSolverr Version**: 

**Are you using a proxy or VPN?** [yes/no] no

**Using Captcha Solver:** [yes/no] Not yet... it's the issue

**If using captcha solver, which one:** Tried both (hcaptcha-solver & harvester)

### Description

I'm trying to activate a Captcha Solver as explained in the Readme.
So I set my environment variable in Flaresolverr systemd service with one of these 2 options (tried both) :
Environment="CAPTCHA_SOLVER=hcaptcha-solver"  OR
Environment="CAPTCHA_SOLVER=harvester"
Reload systemd daemon ; Restart Flaresolverr
The variable seems to be set but Flaresolverr doesn't know the option/module.
Do I have to install solvers myself (how ?) ? Or are they included in Flaresolverr's zip ?

Thanks for your advices.

### Logged Error Messages

```
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.102Z INFO REQ-1 Cloudflare detected
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.104Z DEBUG REQ-1 No '#trk_jschal_js' challenge element detected.
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.105Z DEBUG REQ-1 No '.ray_id' challenge element detected.
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.105Z DEBUG REQ-1 No '.attack-box' challenge element detected.
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.105Z DEBUG REQ-1 Javascript challenge selectors found: 0, total selectors: 3
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.106Z INFO REQ-1 Captcha challenge detected.
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.109Z INFO REQ-1 Successful response in 0.323 s
Jan 27 12:46:17 grabber flaresolverr[27204]: 2021-01-27T11:46:17.109Z INFO REQ-1 Cloudflare Error: The solver 'hcaptcha-solver' is not a valid captcha solving method.
Jan 27 12:46:17 grabber jackett[20110]: 01-27 12:46:17 Error Jackett.Common.IndexerException: Exception (cpasbien): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: The solver 'hcaptcha-solver' is not a valid captcha solving method.

```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by RudyBzhBzh** [comment]
Well, after some more tries, it's seems the previous error is that the Cloudflare challenge requested cannot be resolved by the solvers included in Flaresolverr... not that Flaresolverr doesn't find a solver module (to confirm...)

Other refresh leads me to these sorts of logs (challenge recognize by Flaresolverr this time...) :
```
Jan 27 16:09:16 grabber flaresolverr[28510]: 2021-01-27T15:09:16.612Z INFO REQ-7 Cloudflare detected
Jan 27 16:09:16 grabber flaresolverr[28510]: 2021-01-27T15:09:16.620Z DEBUG REQ-7 Javascript challenge element '#trk_jschal_js' detected.
Jan 27 16:09:16 grabber flaresolverr[28510]: 2021-01-27T15:09:16.621Z DEBUG REQ-7 Waiting for Cloudflare challenge...
Jan 27 16:09:22 grabber flaresolverr[28510]: 2021-01-27T15:09:22.625Z DEBUG REQ-7 Found challenge element again...
Jan 27 16:09:23 grabber flaresolverr[28510]: 2021-01-27T15:09:23.004Z DEBUG REQ-7 Page reloaded.
Jan 27 16:09:23 grabber flaresolverr[28510]: 2021-01-27T15:09:23.012Z DEBUG REQ-7 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr"><head>
```
[...] HTML Dump of the tracker's website... But I can't find any cookie in the header ?! Don't know if it's normal [...]
```
Jan 27 16:09:23 grabber flaresolverr[28510]: </body></html>
Jan 27 16:09:29 grabber flaresolverr[28510]: 2021-01-27T15:09:29.018Z DEBUG REQ-7 Validating HTML code...
Jan 27 16:09:29 grabber flaresolverr[28510]: 2021-01-27T15:09:29.018Z DEBUG REQ-7 Javascript challenge selectors found: 1, total selectors: 3
Jan 27 16:09:29 grabber flaresolverr[28510]: 2021-01-27T15:09:29.024Z INFO REQ-7 Successful response in 12.751 s
Jan 27 16:09:29 grabber jackett[20110]: 01-27 16:09:29 Error Jackett.Common.IndexerException: Exception (cpasbien): The cookies provided by FlareSolverr are not valid
```

So, it looks like Jackett is waiting for a cookie for this indexer (is it really needed ?), not provided by Flaresolverr...

Obviously, I'm lost if it's an wrong Indexer definition or a real issue on Flaresolverr...
I tried to remove all cookie/user-agent related informations in the indexer definition but the exception is the same (cookie provided by FS not valid.

**Comment by ilike2burnthing** [comment]
`At this time none of the captcha solvers work. You can check the status in the open issues. Any help is welcome.`
https://github.com/FlareSolverr/FlareSolverr#captcha-solvers

**Comment by ngosang** [comment]
Related 8aa7723f4578aa930e4123f27abffe6b54cf7818
