### ISSUE TITLE
 Some trackers return an error after 70s try on Jackett

### ISSUE THREAD

**Issue by Artyaom** [FlareSolverr/FlareSolverr#820]
### Have you checked our README?

- [x] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.1
- Last working FlareSolverr version: N/A
- Operating system: WD11
- Are you using Docker: No
- FlareSolverr User-Agent (see log traces or / endpoint): N/A
- Are you using a VPN: No
- Are you using a Proxy: No
- Are you using Captcha Solver: No
- If using captcha solver, which one: /
- URL to test this issue:
```

### Description

I get that error : Jackett.Common.IndexerException: Exception (torrentz2eu): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 70.0 seconds.

It happens with 1337x, Torrent9, TorrentZ2, YTS

Didn't change API URL, still localhost:8191

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (1337x): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 70.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 70.0 seconds.
```

**Comment by acolis** [comment]
Can confirm same on trcakers: Idope, Tokyo Toshokan, Torlock, TorrentCore,

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/811
