### ISSUE TITLE
Idope and TorrentCore not solving challenges

### ISSUE THREAD

**Issue by Woody-Stock** [FlareSolverr/FlareSolverr#830]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.2
- Last working FlareSolverr version: 3.2.2
- Operating system: Windows 10 19045.3208
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: Privado SmartDNS
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://idope.se/   https://torrentcore.xyz/
```

### Description

Exception (idope): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

I have the same message for TorrentCore.

Flaresolver wasn't working for me anymore since 3.2.1 and started working again with 3.2.2.
However, soon after, those two websites started not resolving challenges. Other sites using it are fine.

### Logged Error Messages

```text
Exception (idope): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/811
