### ISSUE TITLE
ModuleNotFoundError: No module named 'ipaddress' from linux binary

### ISSUE THREAD

**Issue by bipinkrish** [FlareSolverr/FlareSolverr#832]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.2
- Last working FlareSolverr version: -
- Operating system: Linux (PopOS)
- Are you using Docker: [yes/no] -
- FlareSolverr User-Agent (see log traces or / endpoint): -
- Are you using a VPN: [yes/no] - 
- Are you using a Proxy: [yes/no] -
- Are you using Captcha Solver: [yes/no] -
- If using captcha solver, which one: -
- URL to test this issue: -
```

### Description

I downloaded binary from the releases section , extracted, when i try to start it by `./flaresolverr ` it gave me that error 
I tried after installing `ipaddress` package from pip by not luck
I am using Python 3.10.6 do i need 3.11 even for the binary? because it is not mentioned for that.

### Logged Error Messages

```text
[291123] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
  File "pathlib.py", line 14, in <module>
  File "urllib/parse.py", line 40, in <module>
ModuleNotFoundError: No module named 'ipaddress'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[291123] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

**Comment by bipinkrish** [comment]
Yep need 3.11

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1641789820
