### ISSUE TITLE
flaresolver dosen't work anymore with yggtorrent.wtf wesite

### ISSUE THREAD

**Issue by Siagutrop** [FlareSolverr/FlareSolverr#833]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes]
- FlareSolverr User-Agent (3.0.2 and 3.2.2 win):
- Are you using a VPN: [yes and no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
```

### Description

after 2 am french time the flaresolver dosen't work anymore with yggtorrent.wtf cloudflare security ddos check with win install or with docker install with or without VPN just drop this error in log 

### Logged Error Messages

```text
2023-07-30 11:45:04 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2023-07-30 11:45:19 INFO     Challenge detected. Selector found: #challenge-spinner
2023-07-30 11:46:06 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-07-30 11:46:06 INFO     Response in 61.468 s
2023-07-30 11:46:06 INFO     192.168.1.51 POST http://192.168.1.45:8191/v1 500 Internal Server Error
```

**Comment by oopolooo18** [comment]
Same problem
After this night flaresolverr dosen't work anymore on yggtorrent.wtf

![image](https://github.com/FlareSolverr/FlareSolverr/assets/6190560/0c0213cf-b79b-49f9-b33b-ec062324bf9e)

![image](https://github.com/FlareSolverr/FlareSolverr/assets/6190560/df38d2a7-23ae-456f-8819-c004f911fa6f)

**Comment by superop78** [comment]
Same problem

**Comment by raffi78** [comment]
hi all
same issue here
radar/jackett/flaresolver KO
radar/prowlar/flaresolver KO

**Comment by XamYp** [comment]
Hi,
Same issue

**Comment by maxtouf** [comment]
Same

**Comment by tifo71** [comment]
Same. Please update

**Comment by Nackophilz** [comment]
They've just added a reinforced challenge to the site, so you just have to wait, nothing more.

**Comment by Nackophilz** [comment]
Until it lowered the security to normal mode and no longer to attack mode

**Comment by tifo71** [comment]
> They've just added a reinforced challenge to the site, so you just have to wait, nothing more.

wait an update of flaresolverr ?

**Comment by Nackophilz** [comment]
> > They've just added a reinforced challenge to the site, so you just have to wait, nothing more.
> 
> wait an update of flaresolverr ?

Nope, wait to ygg to lower their security :) that happen sometimes

**Comment by tifo71** [comment]
> > > They've just added a reinforced challenge to the site, so you just have to wait, nothing more.
> > 
> > 
> > wait an update of flaresolverr ?
> 
> Nope, wait to ygg to lower their security :) that happen sometimes

ah ok yes sometimes it's temporary

**Comment by tifo71** [comment]
maybe with an update of flaresolverr they can get it to work

**Comment by Nackophilz** [comment]
No way, when the "under attack" mode is activated, flaresolverr can't bypass it, it's a known problem with this site, and there's no way to bypass it, all you can do atm, its wait for ygg to stop this mode each time they put i on  :)

**Comment by tifo71** [comment]
> Wait 6 months

they activate it for 6 months ??

**Comment by Nackophilz** [comment]
Not at all, they activated it yesterday, it may last a few days, then they remove it, it's nothing new.

**Comment by SnowTechnical** [comment]
Same problem here

**Comment by Xantoom** [comment]
Is there any good yggtorrent alternative?

**Comment by Nackophilz** [comment]
Not to my knowledge, or at least not viable enough to talk about.

**Comment by tifo71** [comment]
> Is there any good yggtorrent alternative?

there's sharewood but much less than YGGtorrent

**Comment by tifo71** [comment]
> Not at all, they activated it yesterday, it may last a few days, then they remove it, it's nothing new.

yeah, hope they take it off after a while. As long as they have attacks, they'll keep it active.

**Comment by tifo71** [comment]
update : it work with yggcookie and put cookie and user agent mode. So far so good
![image_2023-07-30_220715409](https://github.com/FlareSolverr/FlareSolverr/assets/130233722/b7fef801-def9-48df-8935-7714d6efa261)

**Comment by ncp55** [comment]
> update : it work with yggcookie and put cookie and user agent mode. So far so good ![image_2023-07-30_220715409](https://user-images.githubusercontent.com/130233722/257073867-b7fef801-def9-48df-8935-7714d6efa261.png)

doesn't work for me

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/811

**Comment by digitalnomad91** [comment]
Working solution & another workaround for when undetect\_chromedriver & flaresolverr aren't working if/when cloudflare is winning again in this war of attrition:

https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1660158095

**Comment by tifo71** [comment]
> Working solution & another workaround for when undetect_chromedriver & flaresolverr aren't working if/when cloudflare is winning again in this war of attrition:
> 
> [#811 (comment)](https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1660158095)

Hello, 

Ok great. Is it possible to integrate it into the Windows version of FlareSolverr ?

**Comment by mrnachu** [comment]
Hello,

It works today (on Prowlarr) with an update to the latest version of flarsolverr (3.2.2).

**Comment by tifo71** [comment]
> Hello,
> 
> It works today (on Prowlarr) with an update to the latest version of flaresolverr (3.2.2).

are you on windows ?

**Comment by mrnachu** [comment]
No with the latest official docker image.

**Comment by mrnachu** [comment]
> > Hello,
> > It works today (on Prowlarr) with an update to the latest version of flaresolverr (3.2.2).
> 
> are you on windows ?

No with the latest official docker image.

**Comment by XamYp** [comment]
> > > > > Hello,
> > > > > It works today (on Prowlarr) with an update to the latest version of flaresolverr (3.2.2).
> > > > 
> > > > 
> > > > are you on windows ?
> > > 
> > > 
> > > No with the latest official docker image.
> > 
> > 
> > hi are you sure ?
> 
> Hello,
> 
> Yes I'm sure
> 
> Prowlarr : ![Prowlarr](https://user-images.githubusercontent.com/141167865/257584913-b539b9ec-739a-43a9-9dcf-91af9175f52b.png)
> 
> Radarr : ![Radarr](https://user-images.githubusercontent.com/141167865/257584980-eda78aec-c12a-43c5-b129-819d6c723e5b.png)

Can you send us your docker-compose for flaresolverr please? I want to check something.

**Comment by mrnachu** [comment]
> > > > > > Hello,
> > > > > > It works today (on Prowlarr) with an update to the latest version of flaresolverr (3.2.2).
> > > > > 
> > > > > 
> > > > > are you on windows ?
> > > > 
> > > > 
> > > > No with the latest official docker image.
> > > 
> > > 
> > > hi are you sure ?
> > 
> > 
> > Hello,
> > Yes I'm sure
> > Prowlarr : ![Prowlarr](https://user-images.githubusercontent.com/141167865/257584913-b539b9ec-739a-43a9-9dcf-91af9175f52b.png)
> > Radarr : ![Radarr](https://user-images.githubusercontent.com/141167865/257584980-eda78aec-c12a-43c5-b129-819d6c723e5b.png)
> 
> Can you send us your docker-compose for flaresolverr please? I want to check something.

Yes for sure.

My docker-compose : 
```Common Workflow Language
---
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```

**Comment by raffi78** [comment]
strange
do not work for me

**Comment by AlarakHS** [comment]
sill not working for me neither

Do you think it's a permanant change on ygg ?

**Comment by fifipil909** [comment]
Upgrading to the lastest docker image worked for me.

**Comment by drafboll** [comment]
I updated flaresolverr and jackett docker images and it s good for me 
![image](https://github.com/FlareSolverr/FlareSolverr/assets/122564851/2fff28c4-29ef-48b1-8acf-eca550c006db)

**Comment by SnowTechnical** [comment]
Am I the only one, who despite the updates it still does not work? I tried everything but still the same error...
I don't understand what I'm doing wrong

`2023/08/03 16:12:06	stdout	2023-08-03 15:12:06 INFO     ReqId 140169873413888 172.26.0.1 POST http://192.168.1.124:8191/v1 500 Internal Server Error
2023/08/03 16:12:06	stdout	2023-08-03 15:12:06 INFO     ReqId 140169873413888 Response in 62.816 s
2023/08/03 16:12:06	stdout	2023-08-03 15:12:06 DEBUG    ReqId 140169873413888 Response => POST /v1 body: {'status': 'error', 'message': 'Error: Error solving the challenge. Timeout after 60.0 seconds.', 'startTimestamp': 1691071863939, 'endTimestamp': 1691071926755, 'version': '3.3.2'}
2023/08/03 16:12:06	stdout	2023-08-03 15:12:06 ERROR    ReqId 140169873413888 Error: Error solving the challenge. Timeout after 60.0 seconds.
2023/08/03 16:12:06	stdout	2023-08-03 15:12:06 DEBUG    ReqId 140169873413888 A used instance of webdriver has been destroyed
2023/08/03 16:11:06	stdout	2023-08-03 15:11:06 DEBUG    ReqId 140169839843072 Navigating to... https://www3.yggtorrent.wtf/engine/search?category=2145&do=search&order=desc&sort=publish_date
2023/08/03 16:11:06	stdout	2023-08-03 15:11:06 DEBUG    ReqId 140169873413888 New instance of webdriver has been created to perform the request
2023/08/03 16:11:04	stdout	2023-08-03 15:11:04 DEBUG    ReqId 140169873413888 Started executable: `/app/chromedriver` in a child process with pid: 1002
2023/08/03 16:11:03	stdout	2023-08-03 15:11:03 DEBUG    ReqId 140169873413888 Launching web browser...
2023/08/03 16:11:03	stdout	2023-08-03 15:11:03 INFO     ReqId 140169873413888 Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=2145&do=search&order=desc&sort=publish_date', 'proxy': {}}`

**Comment by SnowTechnical** [comment]
Currently I'm using the provided docker-compose. I have access via the browser to flaresolver so it works, but impossible to have a functional result with jacket or prowlarr I tried with yours but I don't really know how to use it.

```
---
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.2
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1026
      - PGID=100
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
```

**Comment by SnowTechnical** [comment]
@mushuthecat
Yes YGG and I try with cookie and with torrent

**Comment by fifipil909** [comment]
For example, my log entries looks slightly different 
 `
2023-08-03 14:46:15 INFO     Incoming request => POST /v1 body: {'maxTimeout': 50000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&category=2145&sub_category=2178'}
2023-08-03 14:46:19 INFO     Challenge detected. Title found: Just a moment...
2023-08-03 14:46:27 INFO     Challenge solved!
2023-08-03 14:46:27 INFO     Response in 12.231 s
2023-08-03 14:46:27 INFO     192.168.2.18 POST http://192.168.2.18:8191/v1 200 OK
2023-08-03 14:46:29 INFO     Incoming request => POST /v1 body: {'maxTimeout': 50000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/'}
2023-08-03 14:46:31 INFO     Challenge detected. Title found: Just a moment...
2023-08-03 14:46:39 INFO     Challenge solved!
2023-08-03 14:46:39 INFO     Response in 10.066 s
2023-08-03 14:46:39 INFO     192.168.2.18 POST http://192.168.2.18:8191/v1 200 OK
2023-08-03 14:58:16 INFO     192.168.2.53 GET http://192.168.2.18:8191/ 200 OK
`

**Comment by mushuthecat** [comment]
> @mushuthecat Yes YGG and I try with cookie and with torrent

Hi,

Please check your docker-compose.yaml

This is an extract of my version make sure to use the latest version also...
```
version: '3'

services:
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - CAPTCHA_SOLVER=hcaptcha-solver
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: always
```

**Comment by superop78** [comment]
I deleted my docker image locally and relaunched my docker stack. I took recover the produced image today. now it works fine

**Comment by SnowTechnical** [comment]
I finally succeeded! The ipv6 was activated on my router... The simple fact of deactivating and it works
