### ISSUE TITLE
How do you use sessions.create with a docker image?

### ISSUE THREAD

**Issue by Zeks** [FlareSolverr/FlareSolverr#85]
I am not sure how to do "sessions.create" mentioned in the docs on the main page. 
Is it a param we send through curl, is it a command for command line?

**Comment by ngosang** [comment]
Take a look at the example => https://github.com/FlareSolverr/FlareSolverr#usage
But change `"cmd": "request.get"`with `sessions.create` or other parameters. It could be more examples but I think it's enough info.
