### ISSUE TITLE
FS Not Working with Cloudflare - Timeout Issue attempting to locate the Cloudflare verify checkbox.

### ISSUE THREAD

**Issue by Bastien42** [FlareSolverr/FlareSolverr#851]
**Description:**
I'm experiencing an issue with FlareSolverr running on a Raspberry Pi through Docker. It seems to be failing when encountering Cloudflare challenges. The debug log indicates a timeout when trying to find the Cloudflare verify checkbox on the page. The version of FlareSolverr being used is 3.3.0.

**Steps to Reproduce:**
1. Set up FlareSolverr on a Raspberry Pi using Docker.
2. Run FlareSolverr with the necessary configurations.
3. Make a request to a website protected by Cloudflare, for example:
   `POST /v1 body: {'maxTimeout': 180000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=2145&do=search&order=desc&sort=publish_date', 'proxy': {}}`

**Expected Behavior:**
FlareSolverr should successfully handle the Cloudflare challenge and return the response.

**Actual Behavior:**
FlareSolverr encounters a Cloudflare challenge and times out while attempting to locate the Cloudflare verify checkbox.

**Debug Log:**
```
08/02/2023 11:24:42 PM
2023-08-02 21:24:42 INFO     ReqId 547751981472 Challenge detected. Title found: Just a moment...
08/02/2023 11:24:42 PM
2023-08-02 21:24:42 DEBUG    ReqId 547751981472 Waiting for title (attempt 1): Just a moment...
08/02/2023 11:24:52 PM
2023-08-02 21:24:52 DEBUG    ReqId 547751981472 Timeout waiting for selector
08/02/2023 11:24:52 PM
2023-08-02 21:24:52 DEBUG    ReqId 547751981472 Try to find the Cloudflare verify checkbox...
08/02/2023 11:24:54 PM
2023-08-02 21:24:54 DEBUG    ReqId 547751981472 Cloudflare verify checkbox not found on the page. Error: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="cf-stage"]//label[@class="ctp-checkbox-label"]/input"}
08/02/2023 11:24:54 PM
  (Session info: chrome=115.0.5790.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
08/02/2023 11:24:54 PM
Stacktrace:
08/02/2023 11:24:54 PM
...
```

**Environment:**
- FlareSolverr version: 3.3.0
- Raspberry Pi running Docker
- Chrome / Chromium version: 115
- Platform: Linux-6.1.41-v8+-aarch64-with-glibc2.36

**Additional Information:**
- I'm also using Prowlarr on the same Raspberry Pi through Docker, but I'm not sure if it's related to this issue.

Please let me know if there's any further information needed to troubleshoot this problem. Thank you!

[flaresolverr-2023-08-02T21-35-17.log.gz](https://github.com/FlareSolverr/FlareSolverr/files/12244996/flaresolverr-2023-08-02T21-35-17.log.gz)

**Comment by ilike2burnthing** [comment]
See also:
https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1662837099
https://github.com/FlareSolverr/FlareSolverr/issues/811#issuecomment-1663033891

**Comment by ngosang** [comment]
Fixed in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.1
