### ISSUE TITLE
Unterminated string starting at

### ISSUE THREAD

**Issue by pokemaster974** [FlareSolverr/FlareSolverr#852]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.0
- Last working FlareSolverr version:
- Operating system: Windows
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- URL to test this issue: https://www3.yggtorrent.wtf/engine/search?name=&description=&file=&uploader=&category=2145&sub_category=2183
```

### Description

When I try to flaresolve the following command line : `curl -L -X POST "http://localhost:8191/v1" -H "Content-Type: application/json" --data-raw "{\"cmd\": \"request.get\",\"maxTimeout\": 60000,\"url\":\"https://www3.yggtorrent.wtf/engine/search?category=2145&sub_category=2183\"}"`
it will give me error.

I know this is because the "`&`" character.
I've tried with changing "`&`" with "`%26`", flaresolverr will work but this character changing will break the search parameters on the website (the site won't take into account the parameters).
Is it a way to escape this character ?

### Logged Error Messages

```text
2023-08-03 00:28:54 ERROR    Unterminated string starting at: line 1 column 29 (char 48)
2023-08-03 00:28:54 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

**Comment by ngosang** [comment]
That URL is working for me. Maybe you are copying some weird character. Try using Postman / Insomnia to make the requests.
