### ISSUE TITLE
In free farm not work 500 Internal Server Error

### ISSUE THREAD

**Issue by kai456789** [FlareSolverr/FlareSolverr#859]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.2
- Last working FlareSolverr version:
- Operating system:Linux-5.15.0-1034-oracle-aarch64-with-glibc2.31
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

https://pt.0ff.cc/  can not work

curl -L -X POST 'http://127.0.0.1:8191/v1' -H 'Content-Type: application/json' --data-raw '{
>   "cmd": "request.get",
>   "url":"https://pt.0ff.cc/",
>   "maxTimeout": 6000
> }'
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 6.0 seconds.", "startTimestamp": 1691473256640, "endTimestamp": 1691473263653, "version": "3.3.2"}

### Logged Error Messages

```text
POST http://127.0.0.1:8191/v1 200 OK
flaresolverr  | 2023-08-08 05:40:56 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://pt.0ff.cc/', 'maxTimeout': 6000}
flaresolverr  | 2023-08-08 05:40:58 INFO     Challenge detected. Title found: Just a moment...
flaresolverr  | 2023-08-08 05:41:03 ERROR    Error: Error solving the challenge. Timeout after 6.0 seconds.
flaresolverr  | 2023-08-08 05:41:03 INFO     Response in 7.013 s
flaresolverr  | 2023-08-08 05:41:03 INFO     POST http://127.0.0.1:8191/v1 500 Internal Server Error
```

**Comment by ilike2burnthing** [comment]
Timeout is generally set to `60000` not `6000`.

**Comment by kovalav** [comment]
The same thing for https://cf.insurino.se/

everything was working a month ago

**Comment by ilike2burnthing** [comment]
Update FlareSolverr if you haven't already. The above appears to be one of user error.
