### ISSUE TITLE
[idope] (testing) Exception (idope): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by lolp12** [FlareSolverr/FlareSolverr#864]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [no]
- FlareSolverr User-Agent (endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [/no]
- Are you using Captcha Solver: [/no]

- URL to test this issue:
```

### Description

trying to solve idope provider

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (idope): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid
Click here to open an issue on GitHub for FlareSolverr.
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/79724978/8bcfdc0e-ab89-4349-ac15-931fd83d39c4)

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If you still have issues, provide the environment information as requested above.

**Comment by asulwer** [comment]
is this a new issue?  i have experienced something similar.

**Comment by ilike2burnthing** [comment]
The troubleshooting steps above are designed to resolve most similar issues.

**Comment by asulwer** [comment]
the troubleshooting steps are not the solution to everything and are very generic.  cookie issues are not solvable with troubleshooting steps.

**Comment by lolp12** [comment]
ok thanks i will try to check

**Comment by ilike2burnthing** [comment]
@asulwer yes, that would be why I used the word 'most' rather than 'all'.

**Comment by ilike2burnthing** [comment]
Troubleshooting issues are closed after roughly a week if there's no response from OP (I closed 4 yesterday). OP can reopen if they choose to respond.

**Comment by asulwer** [comment]
@ilike2burnthing i noticed that you have a Pull Request that upgraded [undetected_chromedriver to v3.5.3](https://github.com/FlareSolverr/FlareSolverr/pull/860)!  that solves this issue plus mine!  push that so others can have a solution as well.

**Comment by ilike2burnthing** [comment]
[v3.3.3](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.3)
