### ISSUE TITLE
Unable to add flaresolverr to prowlarr

### ISSUE THREAD

**Issue by doctorase** [FlareSolverr/FlareSolverr#870]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: v3.3.2
- Last working FlareSolverr version: 
- Operating system: Synology NAS
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hi, i'm trying to setup flaresolverr in prowlarr, but it says an error: "Failed to test proxy: X.X.X.X"
X is the NAS IP. 

### Logged Error Messages

```text
This is the Prowlarr log:
https://hastebin.com/share/oqaqohucem.sql

This is the flaresolverr docker log:
https://hastebin.com/share/utenasewad.yaml
```

**Comment by ilike2burnthing** [comment]
Increase the timeout, see if that helps.
