### ISSUE TITLE
Flaresolver Doesn't close chrome instances

### ISSUE THREAD

**Issue by Shawky69** [FlareSolverr/FlareSolverr#878]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.2
- Last working FlareSolverr version:
- Operating system: WIN10
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] 
- Are you using a Proxy: [yes/no] Yes
- Are you using Captcha Solver: [yes/no] No
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Im using the latest flaresolver version which is 3.3.2 and after some time the flaresolver doesn't close the chrome instances and keep stacking them up until 100% CPU usage
i've no AV installed and have disabled windows defender firewall
using flaresolver on RDP

### Logged Error Messages

```text
None
```

**Comment by ilike2burnthing** [comment]
Based on https://github.com/FlareSolverr/FlareSolverr/issues/761 and https://github.com/FlareSolverr/FlareSolverr/issues/772 this should be resolved.

How are you using FlareSolverr?

Please provide debug logs (no HTML) - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by brachna** [comment]
Exact same issue on 3.3.2 Windows 10. Having this issue for months now.
I'm doing requests to FlareSolverr once a minute from Python script.
Noticed that after crash my installed Chrome has a pending update, don't know if that's related.

**Comment by ilike2burnthing** [comment]
Are you using the precompiled binaries or running from source?

What directory are you running FlareSolverr from?

How are you launching FlareSolverr (double-clicking the executable, command prompt, script, scheduled task, etc.)?

Are you running FlareSolverr as admin or a normal user?

Are you using Chrome/Chromium at the same time?

**Comment by brachna** [comment]
Precompiled release.
C:\Apps\flaresolverr
Double-clicking.
Normal user.
I don't run them at the same time.

**Comment by ilike2burnthing** [comment]
Are you running an AV (e.g. Windows Defender) or any other security software? If so, have you tried disabling it or creating an exclusion for FlareSolverr?

**Comment by brachna** [comment]
I disable Windows Defender but it re-enables itself sometimes. No other AV on my system.
Both FlareSolverr.exe and and its folder are added to exclusions.

**Comment by ilike2burnthing** [comment]
When WD is disabled, does the issue continue?

**Comment by brachna** [comment]
When WD is disabled everything seems to be fine. When I find that WD enabled itself and I turn it off - everything seems to be fine.
At the time when I find that instances don't close themselves I rapidly terminate them and FlareSolverr or my system crashes because of lack of memory. It happens suddenly and rapidly. I can't give definitive answer that WD is the culprit.

**Comment by ilike2burnthing** [comment]
I suggest switching to a better AV; Kaspersky and Bitdefender have great free AVs.

Alternatively, try https://github.com/ionuttbara/windows-defender-remover

**Comment by Zeks** [comment]
Not sure if it's related to that but I am seeing very sus begaviour with the most recent docker version: it will overutilize cpu and start getting a ton of server errors grinding to a halt after maybe 40 minutes of work. this on a mint virtual machine

**Comment by maurogsp** [comment]
@eliosh were you able to find a workaround or fix for this? I'm facing the same with falresolverr latest version (3.3.21)

**Comment by eliosh** [comment]
My solution is really weird.
I started 5 different instances on different port each. 
Asking only one url per instance at a time is working very well.
