### ISSUE TITLE
Unable to set proxy using docker image

### ISSUE THREAD

**Issue by Sectimus** [FlareSolverr/FlareSolverr#883]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: latest  3.3.3
- Last working FlareSolverr version: none
- Operating system: Ubuntu 20.04 LTS Linux-5.15.0-79-generic-x86_64-with-glibc2.31
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] no (tried netowrk-mode: "service:gluetun", still didn't bypass block)
- Are you using a Proxy: [yes/no] no, but i'd like to!
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: ExtraTorrent.st
```

### Description

Proxy support was added in [v.2.0.0](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v2.0.0) -  [commit](https://github.com/FlareSolverr/FlareSolverr/commit/cfd158462fec8586b85042728cf70a63af2e50ea).

However using the [docker image](https://hub.docker.com/r/flaresolverr/flaresolverr) we are unable to set a proxy. This makes it impossible to use Flaresolverr on a tracker that is blocked by an ISP. I can use my mullvad proxy to get to the cloudlfare stage, however flaresolverr gets blocked as it is not going through my mullvad proxy.

### Logged Error Messages

```text
None
```

### Screenshots

![5](https://github.com/FlareSolverr/FlareSolverr/assets/33827951/6396d9f2-9a30-414c-b673-888f25cdef69)
![1](https://github.com/FlareSolverr/FlareSolverr/assets/33827951/5998ad11-5864-4bbc-869d-76d1546a2be4)
![2](https://github.com/FlareSolverr/FlareSolverr/assets/33827951/5c3bea4e-21c4-47ea-aafc-d6f1ac7f830b)
![3](https://github.com/FlareSolverr/FlareSolverr/assets/33827951/e889b0dc-06a8-4dfa-b271-deb26807693f)
![4](https://github.com/FlareSolverr/FlareSolverr/assets/33827951/3115dc0a-5878-4471-9b0d-e267c08debc2)

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverrSharp/issues/23
