### ISSUE TITLE
3.3.4 wont detect CloudFlare Protection

### ISSUE THREAD

**Issue by uefcommand** [FlareSolverr/FlareSolverr#892]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.4
- Last working FlareSolverr version: None - New install
- Operating system:Unraid 6.12.4
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: yes
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hello I can not get Flaresolverr to work on any of my torrent trackers. I am using Prowlarr with it set it up as a tag and every time Cloudflare is in use I still get the error Unable to access <site>, blocked by CloudFlare Protection. I have uninstalled and reinstalled the application as well as put the application on the host network and same issue. I am running a VPN and I am using the VPN container as a proxy for Prowlarr. What other information do you need? per the logs it seems not to be detecting the challenge. 

### Logged Error Messages

```text
2023-09-07 13:02:48 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://movietorrent.co/?s=', 'proxy': {'url': 'http://<serverip>:8118/'}}
2023-09-07 13:02:49 INFO     Challenge not detected!
2023-09-07 13:02:49 INFO     Response in 1.546 s
2023-09-07 13:02:49 INFO     172.17.0.1 POST http://<serverip>:8191/v1 200 OK
```

**Comment by andtoliom** [comment]
Maybe if you run the server with LOG_LEVEL=debug? So we can see what error do you get...

**Comment by uefcommand** [comment]
Yeah I thought about that already but the debug log provides pages and pages of red text that makes no sense.

**Comment by ilike2burnthing** [comment]
Provide it anyway.
