### ISSUE TITLE
How To Get PDF Content？

### ISSUE THREAD

**Issue by xulei324** [FlareSolverr/FlareSolverr#895]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: latest
- Last working FlareSolverr version: no
- Operating system: Mac Os
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

I want open PDF URL to get PDF file, but chrome has plug-in pdf viewer, so i got response is :

`{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://crsreports.congress.gov/product/pdf/IF/IF12489", "status": 200, "cookies": [{"domain": ".congress.gov", "httpOnly": true, "name": "__cfruid", "path": "/", "sameSite": "None", "secure": true, "value": "083164affec0842a492b52caefa3eec0fe0eec86-1694256453"}, {"domain": ".congress.gov", "expiry": 1694258253, "httpOnly": true, "name": "__cf_bm", "path": "/", "sameSite": "None", "secure": true, "value": "Jptt2tDzHU0UFjWy10RJT4Ljq7HLf226kMagfSGADaQ-1694256453-0-ASWBkWnbxCrKOsQXDsxUpnwoICC7xFahOkJHwxvK9k3y+RxK5kBOo6kpYan7ZjJ8U8BWM5Z/YfF7CiR5dVXWbiQ="}], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head></head><body style=\"height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(38, 38, 38);\"><embed name=\"9D950A8E9C90A743206B6C6C88CBFA03\" style=\"position:absolute; left: 0; top: 0;\" width=\"100%\" height=\"100%\" src=\"about:blank\" type=\"application/pdf\" internalid=\"9D950A8E9C90A743206B6C6C88CBFA03\"></body></html>"}, "startTimestamp": 1694256452933, "endTimestamp": 1694256453812, "version": "3.2.1"}`

The response body is pdfviewer code，how can i get binary resource?

### Logged Error Messages

```text
`{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://crsreports.congress.gov/product/pdf/IF/IF12489", "status": 200, "cookies": [{"domain": ".congress.gov", "httpOnly": true, "name": "__cfruid", "path": "/", "sameSite": "None", "secure": true, "value": "083164affec0842a492b52caefa3eec0fe0eec86-1694256453"}, {"domain": ".congress.gov", "expiry": 1694258253, "httpOnly": true, "name": "__cf_bm", "path": "/", "sameSite": "None", "secure": true, "value": "Jptt2tDzHU0UFjWy10RJT4Ljq7HLf226kMagfSGADaQ-1694256453-0-ASWBkWnbxCrKOsQXDsxUpnwoICC7xFahOkJHwxvK9k3y+RxK5kBOo6kpYan7ZjJ8U8BWM5Z/YfF7CiR5dVXWbiQ="}], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head></head><body style=\"height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(38, 38, 38);\"><embed name=\"9D950A8E9C90A743206B6C6C88CBFA03\" style=\"position:absolute; left: 0; top: 0;\" width=\"100%\" height=\"100%\" src=\"about:blank\" type=\"application/pdf\" internalid=\"9D950A8E9C90A743206B6C6C88CBFA03\"></body></html>"}, "startTimestamp": 1694256452933, "endTimestamp": 1694256453812, "version": "3.2.1"}`
```

**Comment by ilike2burnthing** [comment]
Why are you using FlareSolverr for this if there's no challenge?

**Comment by ilike2burnthing** [comment]
I'm not seeing that in browser and neither is FlareSolverr: `Challenge not detected!`.
