### ISSUE TITLE
Help Install Yggtorent

### ISSUE THREAD

**Issue by sango74** [FlareSolverr/FlareSolverr#9]
Hello,
I installed the module for Jacket with the following method
On Debian10
-	Root / apt install nodejs npm
-	Root / copie fichier FlareSolverr-master .zip Unzzip 
-	Root /  docker build -t flaresolverr:latest .
-	User / docker run --restart=always --name flaresolverr -p 8191:8191 -d flaresolverr:latest
Test : {"status":"ok","message":"","startTimestamp":1606038247135,"endTimestamp":1606038260071,"version":"1.0.0","solution":{"url":"https://www.google.com/?gws_rdTYPE html><html itemscope=\"\" itemtype=\http://schema.org/WebPage\

Add API url in jakett : http://192.168.100.***:8191/
Test YggTorent : An error occurred while testing this indexer
Exception (yggcookie): Maximum timeout reached. maxTimeout=60000 (ms): Maximum timeout reached. maxTimeout=60000 (ms)
Click here to open an issue on GitHub for this indexer.

I have the same message for normal Yggtorent

**Comment by ngosang** [comment]
This project is not working. There is an alternative here in the following issue but it's not official.
 https://github.com/Jackett/Jackett/issues/9029

**Comment by ngosang** [comment]
FlareSolverr 1.2.0 is out!
It's working for all sites protected by CloudFlare.
Installation => https://github.com/FlareSolverr/FlareSolverr#docker
