### ISSUE TITLE
4chan.org : error solving the challenge 

### ISSUE THREAD

**Issue by aicynide** [FlareSolverr/FlareSolverr#903]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.2.1
- Last working FlareSolverr version:none
- Operating system:Ubuntu
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint):Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:https://4chan.org
```

### Description

{"status": "error", "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.", "startTimestamp": 1694777952296, "endTimestamp": 1694778014525, "version": "3.2.1"}

### Logged Error Messages

```text
{"status": "error", "message": "Error: Error solving the challenge. Timeout after 60.0 seconds.", "startTimestamp": 1694777952296, "endTimestamp": 1694778014525, "version": "3.2.1"}
```

**Comment by ilike2burnthing** [comment]
Current release is v3.3.5, update.

**Comment by Noobslayer123** [comment]
i still got the same exact issue with v3.3.6.

**Comment by ilike2burnthing** [comment]
Open a new issue and provide the information requested.
