### ISSUE TITLE
How to use hcaptcha solver with the binaries?

### ISSUE THREAD

**Issue by truenicoco** [FlareSolverr/FlareSolverr#91]
I am not very familiar with npm, but could get hcaptcha-solver to work when building from sources. However, I am happy to use the binaries provided instead of manually building stuff, but am getting `Cloudflare Error: The solver 'hcaptcha-solver' is not a valid captcha solving method.`. I guess it's because it is not bundled in the binary. Is there an easy way to use hcaptcha-solver and the binary release of flaresolverr?

**Comment by ilike2burnthing** [comment]
> Well, after some more tries, it's seems the previous error is that the Cloudflare challenge requested cannot be resolved by the solvers included in Flaresolverr... not that Flaresolverr doesn't find a solver module

https://github.com/FlareSolverr/FlareSolverr/issues/82

> At this time none of the captcha solvers work. You can check the status in the open issues. Any help is welcome.

https://github.com/FlareSolverr/FlareSolverr#captcha-solvers

**Comment by ngosang** [comment]
Captcha solvers are included in the binaries, but none of the captcha solvers are working ATM.
If you want to help take a look at #31
