### ISSUE TITLE
Cloudflare Turnstile challenge is not recognized inside this site

### ISSUE THREAD

**Issue by unrated1** [FlareSolverr/FlareSolverr#917]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.6
- Last working FlareSolverr version:
- Operating system: 10
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue: https://dashboard.proxyscrape.com/login
```

### Description

Hello
Cloudflare Turnstile challenge is not recognized inside this site:

https://dashboard.proxyscrape.com/login

### Logged Error Messages

```text
{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://dashboard.proxyscrape.com/login",
```

**Comment by Hyperz** [comment]
Solving embedded turnstiles is not supported yet. Maybe share the link in #804 for future reference/testing.
