### ISSUE TITLE
Cannot add Flaresolver proxie to Prowlarr

### ISSUE THREAD

**Issue by MAGAtKiller** [FlareSolverr/FlareSolverr#928]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

- FlareSolverr version: 3.3.6-1
- Operating system: BigLinux - Arch based
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:

Launch Prowlarr, settings, indexers, flaresolver, create tag flare, enter http://(my ip):8191, press test and it fails.

https://controlc.com/42f96b55

### Logged Error Messages

```text
❯ sudo systemctl status flaresolverr
[sudo] password for locutus:                      
● flaresolverr.service - FlareSolverr
     Loaded: loaded (/usr/lib/systemd/system/flaresolverr.service; enabled; preset: disabled)
     Active: active (running) since Sun 2023-10-22 16:35:24 PDT; 10h ago
   Main PID: 20878 (flaresolverr)
      Tasks: 6 (limit: 28639)
     Memory: 155.6M
        CPU: 3.703s
     CGroup: /system.slice/flaresolverr.service
             ├─20878 /opt/flaresolverr/flaresolverr
             └─21135 Xvfb :749125826 -screen 0 800x680x24

Oct 23 02:22:42 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:22:42 INFO     Response in 0.003 s
Oct 23 02:22:42 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:22:42 INFO     10.0.0.219 POST http://10.0.0.219:8191/v1 500 Internal Server Error
Oct 23 02:46:13 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:13 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
Oct 23 02:46:13 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:13 ERROR    Error: Error solving the challenge. \n---------------------\nCould not determine browser executable.\n---------------------\nMake sure your browser is installed in the default location (path).\nIf you are sure about the browser>
Oct 23 02:46:13 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:13 INFO     Response in 0.003 s
Oct 23 02:46:13 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:13 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
Oct 23 02:46:25 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:25 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
Oct 23 02:46:25 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:25 ERROR    Error: Error solving the challenge. \n---------------------\nCould not determine browser executable.\n---------------------\nMake sure your browser is installed in the default location (path).\nIf you are sure about the browser>
Oct 23 02:46:25 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:25 INFO     Response in 0.002 s
Oct 23 02:46:25 Unimatrixz-Zero flaresolverr[20878]: 2023-10-23 02:46:25 INFO     10.0.0.219 POST http://10.0.0.219:8191/v1 500 Internal Server Error
lines 1-21/21 (END)
```

**Comment by ilike2burnthing** [comment]
See the latest comment here - https://aur.archlinux.org/packages/flaresolverr

**Comment by Locutus64** [comment]
```
❯ ls -lh /usr/bin/*chrom*
-rwxr-xr-x 1 root root 13M Oct 24 22:53 /usr/bin/chromedriver
-rwxr-xr-x 1 root root 14K Oct 24 22:53 /usr/bin/chromium
-rwxr-xr-x 1 root root 324 Oct 19 10:02 /usr/bin/google-chrome-unstable
-rwxr-xr-x 1 root root 35K Sep 21 14:24 /usr/bin/vppchromasitting
```

**Comment by txtsd** [comment]
It's unable to find your `/usr/bin/chromium`. Perhaps your `PATH` isn't set up correctly. Please post the output of `echo $PATH`.

**Comment by Locutus64** [comment]
`/home/locutus/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/locutus/.dotnet/tools:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/var/lib/snapd/snap/bin`

**Comment by txtsd** [comment]
`/usr/bin` is right there. idk what the problem is.

I'm stumped at this point. You could try installing `google-chrome` and see if it's able to find that browser instead.

I'll go dig deeper in [undetected_chromedriver](https://github.com/FlareSolverr/FlareSolverr/tree/master/src/undetected_chromedriver) in the meantime.

**Comment by txtsd** [comment]
Alright let's get a log so we can see what's going on

```shell
cd /opt/flaresolverr && env LOG_LEVEL=debug python flaresolverr.py &> /tmp/flaresolverr.log
```

Then Ctrl+C out of it after like 10-15 seconds. Finally, paste the log here.

---

(You might need to add your user to the `flaresolverr` group)

**Comment by Locutus64** [comment]
```
2023-10-28 08:42:56 INFO     ReqId 140048026680384 FlareSolverr 3.3.6
2023-10-28 08:42:56 DEBUG    ReqId 140048026680384 Debug log enabled
2023-10-28 08:42:56 INFO     ReqId 140048026680384 Testing web browser installation...
2023-10-28 08:42:56 INFO     ReqId 140048026680384 Platform: Linux-6.5.5-1-MANJARO-x86_64-with-glibc2.38
2023-10-28 08:42:56 INFO     ReqId 140048026680384 Chrome / Chromium path: /usr/bin/chromium
2023-10-28 08:42:56 INFO     ReqId 140048026680384 Chrome / Chromium major version: 118
2023-10-28 08:42:56 INFO     ReqId 140048026680384 Launching web browser...
2023-10-28 08:42:56 DEBUG    ReqId 140048026680384 Launching web browser...
Traceback (most recent call last):
  File "/opt/flaresolverr/utils.py", line 296, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/opt/flaresolverr/utils.py", line 177, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/flaresolverr/undetected_chromedriver/__init__.py", line 399, in __init__
    if headless or options.headless:
                   ^^^^^^^^^^^^^^^^
AttributeError: 'ChromeOptions' object has no attribute 'headless'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/flaresolverr/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/opt/flaresolverr/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/flaresolverr/utils.py", line 300, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. 'ChromeOptions' object has no attribute 'headless'
```

**Comment by txtsd** [comment]
Yea that's what I'm seeing too and it started fairly recently. Could be something about newer Chromium or other dependencies.

**Comment by txtsd** [comment]
It's caused by newer versions of selenium. Downgrade to `python-selenium 0.4.12` and you should be good until we have a better fix.

See: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1607
See: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1603
See: https://github.com/SeleniumHQ/selenium/commit/b5cfcc4f9c51dd9df9106b62971c417a0fc9a5e4

**Comment by Locutus64** [comment]
OK I'll see if I can downgrade. BigLinux, unfortunately is set up to not keep older packages. Been meaning to ask them about disabling this feature so it will keep 2 or 3 past versions in case I should need them like now. Thanks for the info I'll let you know what mileage I got out of it.

**Comment by txtsd** [comment]
If you use `yay`, `python-selenium` builds might be cached in your build cache, possibly at `~/.cache/yay/python-selenium`. If the built package exists in there, you can install it with `yay -U <file>.pkg.tar.zst"

Or you could run flaresolverr inside a venv with the working version of selenium pinned.
