### ISSUE TITLE
Windows EXE Issue

### ISSUE THREAD

**Issue by jmackxiii** [FlareSolverr/FlareSolverr#93]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### Instruction on how to enable debug and html trace

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

**FlareSolverr Version**: 1.2.3

**Docker**: [yes/no] No

**OS**: Windows 10 x64

**Last Working FlareSolverr Version**:

**Are you using a proxy or VPN?** [yes/no] VPN

**Using Captcha Solver:** [yes/no] Using the Windows exe

**If using captcha solver, which one:**

### Description
I get the below message every time a request is made, states not using a solver, but cannot seem to find where to set that variable in the prepackaged Windows exe file. 

[List steps to reproduce the error and details on what happens and what you expected to happen]
Fresh install with the latest Jackett version 

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.torlock.com/fresh.html","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-03-02T22:46:21.833Z INFO REQ-1 Cloudflare detected
2021-03-02T22:46:21.890Z INFO REQ-1 Captcha challenge detected.
2021-03-02T22:46:21.903Z INFO REQ-1 Successful response in 3.995 s
2021-03-02T22:46:21.904Z INFO REQ-1 Cloudflare Error: Captcha detected but no automatic solver is configured.

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Presumably similar to setting log level:
> Open `cmd.exe`, run set `set CAPTCHA_SOLVER=hcaptcha-solver` and then start FlareSolverr in the same shell.

However:
> At this time none of the captcha solvers work. You can check the status in the open issues. Any help is welcome.

https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by jmackxiii** [comment]
Sadly Open cmd.exe, run set set CAPTCHA_SOLVER=hcaptcha-solver and then start FlareSolverr in the same shell.didnt change the message. Perhaps it's from the fact no captcha solvers work at all. The exe has no other files or folders outside of the chrome folder that's bundled with the exe.

**Comment by ngosang** [comment]
I think your installation is fine but FlareSolverr can't resolve Captchas  => https://github.com/FlareSolverr/FlareSolverr#captcha-solvers
I recommend you to try an alternative link for the site.
![image](https://user-images.githubusercontent.com/10577978/112394531-2d539900-8cfd-11eb-83ab-fa61dc99711f.png)
