### ISSUE TITLE
Unable to process browser request

### ISSUE THREAD

**Issue by Enohriel** [FlareSolverr/FlareSolverr#94]
### Environment

**FlareSolverr Version**: 1.2.3

**Docker**: yes

**OS**: Debian 9

**Are you using a proxy or VPN?** no

**Using Captcha Solver:** hcaptcha-solver (same issue when disabled)

### Description

Flaresolverr won't work anymore at all, even with simple command like the test to google.

[flaresolver logs.txt](https://github.com/FlareSolverr/FlareSolverr/files/6079906/flaresolver.logs.txt)

### Logged Error Messages

{"status":"error","message":"Unable to process browser request. Error: TimeoutError: Navigation timeout of 30000 ms exceeded","startTimestamp":1614816178427,"endTimestamp":1614816208709,"version":"v1.2.3"}

**Comment by ngosang** [comment]
FlareSolverr is working fine for me.
* Did it ever work? 
* I see in the traces that you are setting a header. Could you test without the header?
* Could you destroy the container and start again?

**Comment by Enohriel** [comment]
I did nothing at all (not even restarting the containter, and it does work now.

Issue can be closed I guess.
