### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by paindespik** [FlareSolverr/FlareSolverr#947]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.7
- Last working FlareSolverr version: IDK
- Operating system: debian
- Are you using Docker: [yes/no] yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] no
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hello, 
My jackett and prowlarr instances tell me the cookies provided are not valid. In the logs, flaresolver completes correctly the challenge of https://yggtorrent.wtf.
If you more info, please ask
Any help would be very much appreciated.

### Logged Error Messages

```text
2023-11-06 08:59:37 INFO     192.168.0.2 POST http://192.168.0.2:8191/v1 200 OK
2023-11-06 08:59:38 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=seed&category=all'}
2023-11-06 08:59:38 INFO     Challenge detected. Title found: Just a moment...
2023-11-06 08:59:46 INFO     Challenge solved!
2023-11-06 08:59:46 INFO     Response in 8.928 s
2023-11-06 08:59:46 INFO     192.168.0.2 POST http://192.168.0.2:8191/v1 200 OK
```

### Screenshots

![image](https://github.com/FlareSolverr/FlareSolverr/assets/18008490/4cae891a-ba1d-4b46-9c56-b0fcc290b0d8)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/18008490/9ea3f6a2-cc7a-42c2-910f-5e66b05e323b)

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If you still have issues, does this also affect the indexers for iDope, TorrentQQ, and Torrent[CORE]?

**Comment by pigsyn** [comment]
I have ipv6 enabled in my docker setup. (In _/etc/docker/daemon.json_)


I had issues with iDope (timeout after 100s) and Ygg with Jackett:
``` The cookies provided provided by FlareSolverr are not valid```
and Prowlarr:
```Unable to connect to indexer, check the log above the ValidationFailure for more details. Login failed: No form found on https://www3.yggtorrent.wtf/ using form selector #user-login``` 
until I attached an ipv4 only network to flaresolverr and containers using it.

TorrentQQ, and Torrent[CORE] do work in both setups.

Relevant docker-compose v3 networking:
```yml
networks:
  ip4net:
    driver: bridge
    enable_ipv6: false
  ip64net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdaa:5223:dbb1::/48
          gateway: fdaa:5223:dbb1::1
```

https://unique-local-ipv6.com/

**Comment by ilike2burnthing** [comment]
Try with [v3.3.8](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.8). Failing that, provide the information requested above.

**Comment by Jewem** [comment]
> Try with [v3.3.9](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.9). Failing that, provide the information requested above.
how should I install v3.3.9 with docker and your github link please?

**Comment by Jewem** [comment]
ok Thank you :) 
So if I made a  "docker pull flaresolverr/flaresolverr"  1 hour ago, I must be in 3.3.9? 
I don't know how to check my version of Flaresolverr

**Comment by ilike2burnthing** [comment]
Restart the container, the start of the log will include the version number.

**Comment by Jewem** [comment]
![282602902-aece9956-5c48-46a7-b30d-7fd8f7fae5b5](https://github.com/FlareSolverr/FlareSolverr/assets/150742202/e41ed7ef-a056-4630-a6df-0a3826f71632)
