### ISSUE TITLE
Unable to request using the first cookie, each request needs to be bypassed again

### ISSUE THREAD

**Issue by aini123152011** [FlareSolverr/FlareSolverr#953]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:
- Last working FlareSolverr version:
- Operating system:
- Are you using Docker: [yes/no]
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: [yes/no]
- Are you using a Proxy: [yes/no]
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue:https://www.ozon.ru
```

### Description

https://www.ozon.ru

### Logged Error Messages

```text
https://www.ozon.ru
```

### Screenshots
![image](https://github.com/FlareSolverr/FlareSolverr/assets/26058252/ff569ad6-b361-4a9b-a81e-b7768214ec58)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/26058252/506e389d-4ae0-4c79-905c-ba9ad762961b)

**Comment by aini123152011** [comment]
![image](https://github.com/FlareSolverr/FlareSolverr/assets/26058252/88db528c-8dbf-4888-b333-051127bfb093)

**Comment by ilike2burnthing** [comment]
Working fine here, although I'm not getting any Cloudflare challenge.

From your first screenshot it looks like you're not either, but then the second screenshot shows a response of a `Just a moment...` Cloudflare page.

Please provide a debug log with HTML enabled - https://github.com/FlareSolverr/FlareSolverr#environment-variables
