### ISSUE TITLE
Requests slow down after a while, problem with creating and killing sessions

### ISSUE THREAD

**Issue by Slender357** [FlareSolverr/FlareSolverr#967]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.9
- Last working FlareSolverr version: 3.3.7
- Operating system: macOS 14.0
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

Hello! I have a problem with proxying when I try to create and delete sessions. I don't understand what error keeps appearing.

Initially, I needed to create and kill sessions, because after about 100 requests the requests began to slow down a lot. The only thing that helped solve this problem was restarting the sessions.

### Logged Error Messages

```text
Incoming request => POST /v1 body: {'cmd': 'sessions.create'}
2023-11-13 19:30:06 version_main cannot be converted to an integer
2023-11-13 19:30:06 2023-11-13 16:30:06 INFO     Incoming request => POST /v1 body: {'cmd': 'sessions.create'}
2023-11-13 19:30:06 version_main cannot be converted to an integer2023-11-13 16:30:06 INFO     Incoming request => POST /v1 body: {'cmd': 'sessions.create'}
2023-11-13 19:30:06 version_main cannot be converted to an integer
2023-11-13 19:30:06 
2023-11-13 19:30:06 2023-11-13 16:30:06 WARNING  Task queue depth is 1
2023-11-13 19:30:06 2023-11-13 16:30:06 WARNING  Task queue depth is 2
```

### Screenshots

<img width="765" alt="image" src="https://github.com/FlareSolverr/FlareSolverr/assets/114290259/b981db80-d2f6-44f2-be30-3280b7975a90">

**Comment by ilike2burnthing** [comment]
Is your Mac ARM or Intel?

If you revert to v3.3.7 is the issue resolved?

Enable debug logging, see if it gives you a better idea or the error - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by Zeks** [comment]
I can confirm that the problem still persists. After about 40 minutes docker version will hog all your threads and stop working. had to revert to 3.3.0 for it to do anything.

**Comment by ilike2burnthing** [comment]
ARM or Intel? Provide debug logs. Thanks

**Comment by Zeks** [comment]
linux mint inside a vmaware virtual machine on an intel processor and I have no idea how to inject logging into docker instance

**Comment by ilike2burnthing** [comment]
See link above
