### ISSUE TITLE
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=60000 (ms) (Test)

### ISSUE THREAD

**Issue by stathist84** [FlareSolverr/FlareSolverr#97]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### Instruction on how to enable debug and html trace

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

**FlareSolverr Version**:

**Docker**: [yes/no]

**OS**: 

**Last Working FlareSolverr Version**:

**Are you using a proxy or VPN?** [yes/no]

**Using Captcha Solver:** [yes/no]

**If using captcha solver, which one:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
You'd need to provide the requested information if you want help.

**Comment by ngosang** [comment]
Not enough information. You have to share the URL at least.
