### ISSUE TITLE
version_main cannot be converted to an integer appearing since upgrading to 3.3.10

### ISSUE THREAD

**Issue by hulleyrob** [FlareSolverr/FlareSolverr#973]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.10
- Last working FlareSolverr version: 3.3.7
- Operating system: Linux
- Are you using Docker: YES
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: NO
- Are you using a Proxy: NO
- Are you using Captcha Solver: NO
- If using captcha solver, which one: N/A
- URL to test this issue:
```

### Description

Just reporting the error as yet I cant see any issues but noticed another bug report saying it will slow down after 100s of requests.

Weirdly even with debug on there are no other errors in the log.

### Logged Error Messages

```text
2023/11/16 10:27:23 | stdout | 2023-11-16 10:27:23 DEBUG    ReqId 139713771415296 Started executable: `/app/chromedriver` in a child process with pid: 668
-- | -- | --
2023/11/16 10:27:23 | stdout | version_main cannot be converted to an integer
2023/11/16 10:27:23 | stdout | 2023-11-16 10:27:23 DEBUG    ReqId 139713771415296 Launching web browser...
2023/11/16 10:27:23 | stdout | 2023-11-16 10:27:23 DEBUG    ReqId 139713771415296 Creating new session...
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/pull/963#issuecomment-1808973444

**Comment by jjtronics** [comment]
Hello, i have a same problem, do you have any news ?
Thank you in advance

**Comment by ilike2burnthing** [comment]
See the link above.
