### ISSUE TITLE
Issue with YGGTorrent and Prowlarr

### ISSUE THREAD

**Issue by MacBim** [FlareSolverr/FlareSolverr#976]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.10
- Prowlarr version : 1.9.4.4039
- Last working FlareSolverr version:
- Operating system: Linux
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date
```

### Description

I just started using FlareSolverr with Prowlarr, and i'm facing an issue when configuring an indexer for YGGTorrent (I'm using the YGGCookie tracker).

It is correctly configured to use FlareSolverr as you can see on the attached screenshots.

The issue is : during the indexer setup, when testing I can see the three tests requests beeing sent to FlareSolverr in the logs, all of them succeeding, always redirecting to YGG (unless there's a captcha).

Yet, on the prowlarr side, I always get this error : **Unable to access www3.yggtorrent.wtf, blocked by CloudFlare Protection.**

The logs are attached to this issue (in a .txt file since they are too long to fit here), in which you will find the HTML

[log.txt](https://github.com/FlareSolverr/FlareSolverr/files/13401303/log.txt)

Thank you

### Logged Error Messages

```text
See the attached file
```

### Screenshots

Config :
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/8e4411ae-3390-43e9-acc3-583bc2299549)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/450e1ec7-ae59-4ec0-9707-3ffe59200bbe)

Error :
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/71b5fa8a-585a-4db8-b08b-e72b4c18868c)

**Comment by jscoys** [comment]
Did you update to the last flaresolverr version?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/951#issuecomment-1809524306

**Comment by MacBim** [comment]
My issue here is not a timeout : you can see that in the logs FlareSolverr actually did bypass Cloudflare

Forcing the LANG=fr_FR did not changed anything

I'm using docker btw
docker run -d --network=host --env LANG=fr_FR flaresolverr/flaresolverr:latest

**Comment by ilike2burnthing** [comment]
Apologies, was replying to several YGG issues, must have lumped yours in with them without looking at the logs.

1) use yggtorrent, not yggcookie
2) if yggtorrent has already been added and isn't working, remove it, restart the Prowlarr and FlareSolverr containers, try adding it again
3) `LANG=fr_FR` will just cause a different problem, you'd need to use an English language code, e.g. `en_US`, or if your system is already English then just ignore it

**Comment by MacBim** [comment]
Switched to YGGTorrent and not YGGCookie, restarted both Flaresolverr and Prowarr, I get another error : 
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/860054b2-2ddf-4ac0-8979-39d1f9830fa6)

FlareSolverr still manages to bypass CloudFlare
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/b6053177-51f4-43d4-a11f-8136c4661ea4)

And the test in Prowlarr always succeed

Could it be because Prowlarr dosen't run on docker like FlareSolverr does (despite de --network=host) ?

**Comment by ilike2burnthing** [comment]
Have you added the FlareSolverr tag to the YGGtorrent indexer?

Either run both in Docker or both installed natively, not a mix.

**Comment by MacBim** [comment]
Tried both in docker, sadly still the same issue

Could this be related to https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1594#discussion-5691410 ?

In Prowlarr, both Flaresolverr and YGGTorrent indexer have the correct tag 
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/c45ff9f6-6995-47aa-9ae2-5e6fd935868c)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/8f7417c6-2772-4cb2-b5f2-df4efa8f36e4)
![image](https://github.com/FlareSolverr/FlareSolverr/assets/11718596/8663821f-ce3e-4be2-95f0-0837d07f5a45)

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If you still have issues, delete the YGGtorrent indexer, restart Prowlarr and FlareSolverr, re-add YGGtorrent with FlareSolverr configured, and test again.

Failing all that, add a Jackett container, configure FlareSolverr, and see if you have the same issue with it.

**Comment by MacBim** [comment]
Unbelivable... i'm runing the whole Servarr stack on a Synology NAS
I had disabled IPV6 on ONE of the TWO interfaces...

Disabling IPV6 on both solved the issue...

Thank you for the time and for the help !
