### ISSUE TITLE
Error: Error solving the challenge. Message: invalid cookie domain

### ISSUE THREAD

**Issue by t101804** [FlareSolverr/FlareSolverr#978]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [x] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version:3.3.10
- Last working FlareSolverr version:
- Operating system: WSL Ubuntu 20.04
- Are you using Docker: [yes]
- FlareSolverr User-Agent (see log traces or / endpoint): already
- Are you using a VPN: [no]
- Are you using a Proxy: [no]
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue:
```

### Description

{'status': 'error', 'message': 'Error: Error solving the challenge. Message: invalid cookie domain\\n  (Session info: chrome=119.0.6045.123)\\nStacktrace:\\n#0 0x561090b03d23 <unknown>\\n#1 0x5610907d17ae <unknown>\\n#2 0x56109086ed8b <unknown>\\n#3 0x561090843c92 <unknown>\\n#4 0x56109085c288 <unknown>\\n#5 0x561090843a43 <unknown>\\n#6 0x56109080dbc6 <unknown>\\n#7 0x56109080efb2 <unknown>\\n#8 0x561090ad8da7 <unknown>\\n#9 0x561090adbe8d <unknown>\\n#10 0x561090adb938 <unknown>\\n#11 0x561090adc3a5 <unknown>\\n#12 0x561090acb1df <unknown>\\n#13 0x561090adc732 <unknown>\\n#14 0x561090ab5666 <unknown>\\n#15 0x561090af4e95 <unknown>\\n#16 0x561090af507b <unknown>\\n#17 0x561090b032af <unknown>\\n#18 0x7fbdb1604ea7 start_thread\\n', 'startTimestamp': 1700407524840, 'endTimestamp': 1700407526056, 'version': '3.3.10'}
{'status': 'ok', 'message': 'The session has been removed.', 'startTimestamp': 1700407526058, 'endTimestamp': 1700407526166, 'version': '3.3.10'}

when i try send requests
data = {
            "cmd": "request.post",
            "cookies": [{'domain': '.emailhippo.com', 'expiry': 1734103526, 'httpOnly': False, 'name': '__gpi', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'UID=00000c8edda4e1b1:T=1700407526:RT=1700407526:S=ALNI_Mamm-BwydsIqeI563UacZkKeUih9A'}, {'domain': '.emailhippo.com', 'expiry': 1734103526, 'httpOnly': False, 'name': '__gads', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'ID=c9afd37bf4358774:T=1700407526:RT=1700407526:S=ALNI_MYgNx63S6Ss11R12twQ8CodA04bMg'}, {'domain': '.emailhippo.com', 'expiry': 1734967522, 'httpOnly': False, 'name': '_ga', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'GA1.1.479435977.1700407523'}, {'domain': '.emailhippo.com', 'expiry': 1734967522, 'httpOnly': False, 'name': '_ga_NS6FVYCC8M', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'GS1.1.1700407522.1.0.1700407522.60.0.0'}, {'domain': 'tools.emailhippo.com', 'httpOnly': True, 'name': '.EmailHippo.Session', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': 'CfDJ8NMGhkF%2FQXxKryh%2BbbLO8EjHOYJ4tsUYTvnUO%2ByaFkzE1K5zSQ%2FdLkFkya4h2zVysmFpESyQEI4eXph9XnJaUmVdSQBOxJAGTRy%2F%2FJsM9mIzaon2VYaPMYyssboLyCjIG3Wh%2B4AfxIzfaoY6oBdD%2FdNqzY5DoA%2BG79%2FNXrNpd5fd'}, {'domain': '.emailhippo.com', 'expiry': 1731943524, 'httpOnly': True, 'name': 'cf_clearance', 'path': '/', 'sameSite': 'None', 'secure': True, 'value': 'vkIPpf19uSgpOmAAaRDHXae1IxRo.uPgG74ydxydzsg-1700407527-0-1-f5e7338d.88f2d7a5.a9c5deaf-0.2.1700407527'}, {'domain': '.emailhippo.com', 'expiry': 1708183522, 'httpOnly': False, 'name': '_gcl_au', 'path': '/', 'sameSite': 'Lax', 'secure': False, 'value': '1.1.1458275693.1700407523'}, {'domain': 'tools.emailhippo.com', 'httpOnly': True, 'name': '.AspNetCore.Antiforgery.38G8fUVOpE4', 'path': '/', 'sameSite': 'Strict', 'secure': False, 'value': 'CfDJ8NMGhkF_QXxKryh-bbLO8Egg-l8wl05nzGfuhkbAwn3HYmXPG0yuuEDgPdIBN1DvZucihrNRuQS4CPLX6-HoCmlGaoFmGO0nmrT_wqWeiWYj8h1cVowbs4NTiLKNzflVaft0jpTGpKQi4dDLUkG6WFA'}],
            "url": self.api,
            "maxTimeout": 6000,
        } 

### Logged Error Messages

```text
{'status': 'error', 'message': 'Error: Error solving the challenge. Message: invalid cookie domain\\n  (Session info: chrome=119.0.6045.123)\\nStacktrace:\\n#0 0x561090b03d23 <unknown>\\n#1 0x5610907d17ae <unknown>\\n#2 0x56109086ed8b <unknown>\\n#3 0x561090843c92 <unknown>\\n#4 0x56109085c288 <unknown>\\n#5 0x561090843a43 <unknown>\\n#6 0x56109080dbc6 <unknown>\\n#7 0x56109080efb2 <unknown>\\n#8 0x561090ad8da7 <unknown>\\n#9 0x561090adbe8d <unknown>\\n#10 0x561090adb938 <unknown>\\n#11 0x561090adc3a5 <unknown>\\n#12 0x561090acb1df <unknown>\\n#13 0x561090adc732 <unknown>\\n#14 0x561090ab5666 <unknown>\\n#15 0x561090af4e95 <unknown>\\n#16 0x561090af507b <unknown>\\n#17 0x561090b032af <unknown>\\n#18 0x7fbdb1604ea7 start_thread\\n', 'startTimestamp': 1700407524840, 'endTimestamp': 1700407526056, 'version': '3.3.10'}
```

### Screenshots
LOG CONTAINER :
![image](https://github.com/FlareSolverr/FlareSolverr/assets/113588203/a0c3d7ea-841b-49cd-b6b3-2ce8b9b64c19)

LOG REQUESTS PYTHON :
![image](https://github.com/FlareSolverr/FlareSolverr/assets/113588203/c6b5cf28-a151-4250-aa35-41dc6142cdaa)

**Comment by ilike2burnthing** [comment]
This doesn't appear to be a FlareSolverr issue - https://developer.mozilla.org/en-US/docs/Web/WebDriver/Errors/InvalidCookieDomain
