### ISSUE TITLE
Not bypass CF access denied 1020

### ISSUE THREAD

**Issue by CyberMan571** [FlareSolverr/FlareSolverr#98]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

### Instruction on how to enable debug and html trace

[Follow the instructions from this wiki page](https://github.com/FlareSolverr/FlareSolverr/wiki/How-to-enable-debug-and-html-trace)

### Environment

**FlareSolverr Version**:
v1.2.3
**Docker**: [yes/no]
no
**OS**: 
windows 10
**Last Working FlareSolverr Version**:
first trying
**Are you using a proxy or VPN?** [yes/no]
yes
**Using Captcha Solver:** [yes/no]
no was tried
**If using captcha solver, which one:**

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
[10256:4220:0316/170017.742:ERROR:test_root_certs.cc(27)] Can't load certificate C:\net/data\ssl/certificates\root_ca_cert.pem
[10256:4220:0316/170017.743:ERROR:test_root_certs.cc(27)] Can't load certificate C:\net/data\ssl/certificates\ocsp-test-root.pem
[10256:4220:0316/170017.743:ERROR:test_root_certs.cc(27)] Can't load certificate C:\net/data\ssl/certificates\quic-root.pem
[1080:10244:0316/170019.293:WARNING:load_error_reporter.cc(78)] Extension error: C:\chrome\test\data\extensions\platform_apps\web_view\focus. Manifest dosyas─▒ eksik veya okunam─▒yor

which is folder inside empty. (C:\chrome\test\)
has not been maked C:\net/  it is no found

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

![resim](https://user-images.githubusercontent.com/30759335/111322378-eb31b400-8679-11eb-86a0-b62fe1dc6fe0.png)

please fix it

**Comment by ilike2burnthing** [comment]
Why are you running `interactive_ui_tests.exe`?

Does running `flaresolverr.exe` and then configuring it in Jackett not work?

**Comment by CyberMan571** [comment]
I have running  if it has been any error for testing. That's what I thought.
 then configuring it in Jackett not work? How can do this?  can you explain? Please?
 flaresolver, my first trying

**Comment by ilike2burnthing** [comment]
Assuming you're running Jackett on Windows as well, run flaresolverr.exe, open Jackett, scroll to the bottom, add `http://127.0.0.1:8191` for the `FlareSolverr API URL`, click `Apply server settings`, and it should work.

**Comment by CyberMan571** [comment]
![resim](https://user-images.githubusercontent.com/30759335/111531774-084bad00-8776-11eb-92c0-50ac3e6220a1.png)

that's what on me

**Comment by ilike2burnthing** [comment]
Ok, that's normal. Are you using FlareSolverr with Jackett?

**Comment by CyberMan571** [comment]
yes, portable jackett is downloaded,  it(http://0.0.0.0:819) was configured in jackett server page.
Will I do anything other than that in jackett?
I start jackett service
when you use VPN it's blocked by CF this example https://dizibox.vip

**Comment by CyberMan571** [comment]
http://127.0.0.1:8191 nothing changed

**Comment by ilike2burnthing** [comment]
Can you access that site in your web browser when using the same VPN server? If not, then the IP address has been blocked, and FlareSolverr is not going to help with that. Change your VPN server.

**Comment by CyberMan571** [comment]
I know this error was happening on other sites they set to visiting for a certain country ip! That's one reason for error 1020! If cf can be overcome, that problem will be eliminated!

this found https://www.youtube.com/watch?v=voWU97bH2zM

are there any tutorial for portable?

**Comment by CyberMan571** [comment]
![resim](https://user-images.githubusercontent.com/30759335/111544554-b0b53d80-8785-11eb-8d3f-ef27aa5689eb.png)

**Comment by ilike2burnthing** [comment]
If the issue is the site blocking certain IP addresses or using region blocking, and it's caused by you using a VPN, then you'll need to change your VPN server. This isn't related to FlareSolverr or Jackett.

**Comment by CyberMan571** [comment]
When I said bypass, I understood completely CF bypass.

**Comment by ngosang** [comment]
Your IP is banned by CloudFlare and you need to get a new IP or use a VPN. We can't fix that.
