### ISSUE TITLE
[yggtorrent] (updating) The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by frisk038** [FlareSolverr/FlareSolverr#980]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.10
- Operating system: raspbian
- Are you using Docker: yes
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: no
- If using captcha solver, which one:
- URL to test this issue: https://yggtorrent.wtf/
```

### Description

I have this `The cookies provided by FlareSolverr are not valid` on yggtorrent.wtf

### Logged Error Messages

```text
`The cookies provided by FlareSolverr are not valid`
```

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/951#issuecomment-1809524306

https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting
