### ISSUE TITLE
YGG 500 Internal Server Error - Timeout after 60.0 seconds

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [FlareSolverr/FlareSolverr#989]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.3.10
- Last working FlareSolverr version: unknown
- Operating system: Windows 10 22H2 x64
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date
```

### Description

Attempting to run a search on YGG returns a 500 error.

### Logged Error Messages

```text
PS C:\Software\flaresolverr> set LANG=en_EN
PS C:\Software\flaresolverr> .\flaresolverr.exe
2023-12-01 02:23:22 INFO     FlareSolverr 3.3.10
2023-12-01 02:23:22 INFO     Testing web browser installation...
2023-12-01 02:23:22 INFO     Platform: Windows-10-10.0.19045-SP0
2023-12-01 02:23:22 INFO     Chrome / Chromium path: C:\Software\flaresolverr\chrome\chrome.exe
2023-12-01 02:23:22 INFO     Chrome / Chromium major version: 115
2023-12-01 02:23:22 INFO     Launching web browser...
2023-12-01 02:23:27 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
2023-12-01 02:23:27 INFO     Test successful!
2023-12-01 02:23:27 INFO     Serving on http://0.0.0.0:8191
2023-12-01 02:23:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2023-12-01 02:23:43 INFO     Challenge detected. Selector found: #challenge-spinner
2023-12-01 02:24:43 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-12-01 02:24:43 INFO     Response in 62.259 s
2023-12-01 02:24:43 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
```

**Comment by ilike2burnthing** [comment]
Double the timeout, see if that resolves your issue.

If you still have issues, follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

**Comment by tifo71** [comment]
> ### Have you checked our README?
> * [x]  I have checked the README
> 
> ### Have you followed our Troubleshooting?
> * [x]  I have followed your Troubleshooting
> 
> ### Is there already an issue for your problem?
> * [x]  I have checked older issues, open and closed
> 
> ### Have you checked the discussions?
> * [x]  I have read the Discussions
> 
> ### Environment
> ```
> - FlareSolverr version: 3.3.10
> - Last working FlareSolverr version: unknown
> - Operating system: Windows 10 22H2 x64
> - Are you using Docker: no
> - FlareSolverr User-Agent (see log traces or / endpoint):
> - Are you using a VPN: no
> - Are you using a Proxy: no
> - Are you using Captcha Solver: [yes/no]
> - If using captcha solver, which one:
> - URL to test this issue: https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date
> ```
> 
> ### Description
> Attempting to run a search on YGG returns a 500 error.
> 
> ### Logged Error Messages
> ```
> PS C:\Software\flaresolverr> set LANG=en_EN
> PS C:\Software\flaresolverr> .\flaresolverr.exe
> 2023-12-01 02:23:22 INFO     FlareSolverr 3.3.10
> 2023-12-01 02:23:22 INFO     Testing web browser installation...
> 2023-12-01 02:23:22 INFO     Platform: Windows-10-10.0.19045-SP0
> 2023-12-01 02:23:22 INFO     Chrome / Chromium path: C:\Software\flaresolverr\chrome\chrome.exe
> 2023-12-01 02:23:22 INFO     Chrome / Chromium major version: 115
> 2023-12-01 02:23:22 INFO     Launching web browser...
> 2023-12-01 02:23:27 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
> 2023-12-01 02:23:27 INFO     Test successful!
> 2023-12-01 02:23:27 INFO     Serving on http://0.0.0.0:8191
> 2023-12-01 02:23:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
> 2023-12-01 02:23:43 INFO     Challenge detected. Selector found: #challenge-spinner
> 2023-12-01 02:24:43 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
> 2023-12-01 02:24:43 INFO     Response in 62.259 s
> 2023-12-01 02:24:43 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
> ```
> 
> ### Screenshots
> _No response_

Hello change your DNS, I had the same problem with the container on OMV it came from DNS. Put the DNS: 1.1.1.1 and 1.0.0.1 in the settings of your network card or WIFI on Windows and it will work.

**Comment by SuBGh0s7** [comment]
> Double the timeout, see if that resolves your issue.
already done ... still not working :(

**Comment by SuBGh0s7** [comment]
> > ### Have you checked our README?
> > 
> > * [x]   I have checked the README
> > 
> > ### Have you followed our Troubleshooting?
> > 
> > * [x]   I have followed your Troubleshooting
> > 
> > ### Is there already an issue for your problem?
> > 
> > * [x]   I have checked older issues, open and closed
> > 
> > ### Have you checked the discussions?
> > 
> > * [x]   I have read the Discussions
> > 
> > ### Environment
> > ```
> > - FlareSolverr version: 3.3.10
> > - Last working FlareSolverr version: unknown
> > - Operating system: Windows 10 22H2 x64
> > - Are you using Docker: no
> > - FlareSolverr User-Agent (see log traces or / endpoint):
> > - Are you using a VPN: no
> > - Are you using a Proxy: no
> > - Are you using Captcha Solver: [yes/no]
> > - If using captcha solver, which one:
> > - URL to test this issue: https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Description
> > Attempting to run a search on YGG returns a 500 error.
> > ### Logged Error Messages
> > ```
> > PS C:\Software\flaresolverr> set LANG=en_EN
> > PS C:\Software\flaresolverr> .\flaresolverr.exe
> > 2023-12-01 02:23:22 INFO     FlareSolverr 3.3.10
> > 2023-12-01 02:23:22 INFO     Testing web browser installation...
> > 2023-12-01 02:23:22 INFO     Platform: Windows-10-10.0.19045-SP0
> > 2023-12-01 02:23:22 INFO     Chrome / Chromium path: C:\Software\flaresolverr\chrome\chrome.exe
> > 2023-12-01 02:23:22 INFO     Chrome / Chromium major version: 115
> > 2023-12-01 02:23:22 INFO     Launching web browser...
> > 2023-12-01 02:23:27 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
> > 2023-12-01 02:23:27 INFO     Test successful!
> > 2023-12-01 02:23:27 INFO     Serving on http://0.0.0.0:8191
> > 2023-12-01 02:23:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
> > 2023-12-01 02:23:43 INFO     Challenge detected. Selector found: #challenge-spinner
> > 2023-12-01 02:24:43 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
> > 2023-12-01 02:24:43 INFO     Response in 62.259 s
> > 2023-12-01 02:24:43 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Screenshots
> > _No response_
> 
> Hello change your DNS, I had the same problem with the container on OMV it came from DNS. Put the DNS: 1.1.1.1 and 1.0.0.1 in the settings of your network card or WIFI on Windows and it will work.

Also not working...

**Comment by SuBGh0s7** [comment]
Test Search working perfectly on iDope, TorrentQQ and Torrent[CORE]

**Comment by ilike2burnthing** [comment]
As instructed, provide the information requested in your original post rather than commenting on others'.

**Comment by SuBGh0s7** [comment]
> As instructed, provide the information requested in your original post rather than commenting on others'.

What infomation ?

**Comment by ilike2burnthing** [comment]
You provided no environment information and only a single error line.

**Comment by SuBGh0s7** [comment]
- FlareSolverr version: 3.3.10
- Last working FlareSolverr version: unknown
- Operating system: Windows 10 22H2 x64
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date

**Comment by ilike2burnthing** [comment]
On your own post!

**Comment by SuBGh0s7** [comment]
> ### Have you checked our README?
> * [x]  I have checked the README
> 
> ### Have you followed our Troubleshooting?
> * [x]  I have followed your Troubleshooting
> 
> ### Is there already an issue for your problem?
> * [x]  I have checked older issues, open and closed
> 
> ### Have you checked the discussions?
> * [x]  I have read the Discussions
> 
> ### Environment
> ```
> - FlareSolverr version: 3.3.10
> - Last working FlareSolverr version: unknown
> - Operating system: Windows 10 22H2 x64
> - Are you using Docker: no
> - FlareSolverr User-Agent (see log traces or / endpoint):
> - Are you using a VPN: no
> - Are you using a Proxy: no
> - Are you using Captcha Solver: [yes/no]
> - If using captcha solver, which one:
> - URL to test this issue: https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date
> ```
> 
> ### Description
> Attempting to run a search on YGG returns a 500 error.
> 
> ### Logged Error Messages
> ```
> PS C:\Software\flaresolverr> set LANG=en_EN
> PS C:\Software\flaresolverr> .\flaresolverr.exe
> 2023-12-01 02:23:22 INFO     FlareSolverr 3.3.10
> 2023-12-01 02:23:22 INFO     Testing web browser installation...
> 2023-12-01 02:23:22 INFO     Platform: Windows-10-10.0.19045-SP0
> 2023-12-01 02:23:22 INFO     Chrome / Chromium path: C:\Software\flaresolverr\chrome\chrome.exe
> 2023-12-01 02:23:22 INFO     Chrome / Chromium major version: 115
> 2023-12-01 02:23:22 INFO     Launching web browser...
> 2023-12-01 02:23:27 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
> 2023-12-01 02:23:27 INFO     Test successful!
> 2023-12-01 02:23:27 INFO     Serving on http://0.0.0.0:8191
> 2023-12-01 02:23:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
> 2023-12-01 02:23:43 INFO     Challenge detected. Selector found: #challenge-spinner
> 2023-12-01 02:24:43 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
> 2023-12-01 02:24:43 INFO     Response in 62.259 s
> 2023-12-01 02:24:43 INFO     127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
> ```
> 
> ### Screenshots
> _No response_

- FlareSolverr version: 3.3.10
- Last working FlareSolverr version: unknown
- Operating system: Windows 10 22H2 x64
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint):
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: [no]
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.wtf/engine/search?category=all&do=search&order=desc&sort=publish_date

**Comment by SuBGh0s7** [comment]
im sorry im new to github...

**Comment by Nomuas62** [comment]
I have exactly the same error on Windows as well, and neither of the two solutions worked for me.

**Comment by ilike2burnthing** [comment]
If your system language isn't already English, use the environment variable `LANG` with and English language code, e.g. `en_GB` - https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by ilike2burnthing** [comment]
What is 'it'? There were 3 different solutions and a page of troubleshooting steps.

**Comment by UjCbFwtBayFM** [comment]
Yes I tried the different solutions and none worked.

**Comment by ilike2burnthing** [comment]
The solutions were provided after you made the post, so that doesn't really make sense.

You've tried with v3.3.12 now?
