### ISSUE TITLE
[yggtorrent] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

### ISSUE THREAD

**Issue by SuBGh0s7** [FlareSolverr/FlareSolverr#993]
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: FlareSolverr 3.3.10
- Last working FlareSolverr version: unknown
- Operating system: Windows 10 22H2
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&name="for"+"all"+"mankind"&category=all
```

### Description

An error occurred while updating this indexer

### Logged Error Messages

```text
FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
```

**Comment by ilike2burnthing** [comment]
Provide the information requested and reopen.

**Comment by SuBGh0s7** [comment]
- FlareSolverr version: FlareSolverr 3.3.10
- Last working FlareSolverr version: unknown
- Operating system: Windows 10 22H2
- Are you using Docker: no
- FlareSolverr User-Agent (see log traces or / endpoint): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
- Are you using a VPN: no
- Are you using a Proxy: no
- Are you using Captcha Solver: [yes/no]
- If using captcha solver, which one:
- URL to test this issue: https://www3.yggtorrent.wtf/engine/search?do=search&order=desc&sort=publish_date&name="for"+"all"+"mankind"&category=all

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

What is the system language of the computer FlareSolverr is running on? If not English, use the `LANG` ENV - https://github.com/FlareSolverr/FlareSolverr#environment-variables

If that doesn't work, provide a debug FlareSolverr log of the issue.

**Comment by SuBGh0s7** [comment]
troubleshooting steps followed.

Public indexers iDope, TorrentQQ and Torrent[CORE] test search good !

The system language is not english

**Comment by ilike2burnthing** [comment]
Use `LANG` as per the linked example.

**Comment by SuBGh0s7** [comment]
> Use `LANG` as per the linked example.

How i can do that ? trying all the night...

**Comment by ZePandawan** [comment]
> > Use `LANG` as per the linked example.
> 
> 
> 
> How i can do that ? trying all the night...

Just use this command : 

´export LANG=en_US ´

**Comment by SuBGh0s7** [comment]
Where i need to use this command? cmd?

**Comment by ZePandawan** [comment]
> Where i need to use this command? cmd?
> 
> 

You can follow this link I thinked you were on Linux : 

https://www.alphr.com/set-environment-variables-windows-11/

**Comment by SuBGh0s7** [comment]
New User Variable
Name: LANG
Value: ?

**Comment by SuBGh0s7** [comment]
And how to to assign the variable the desired location?

**Comment by ilike2burnthing** [comment]
See the bottom of the instructions I previously linked to - https://github.com/FlareSolverr/FlareSolverr#environment-variables

> Windows: Open `cmd.exe`, run `set LOG_LEVEL=debug` and then start FlareSolverr in the same shell.

In this case replacing `LOG_LEVEL=debug` with `LANG=en_GB` as per the example above it.

**Comment by opvexe** [comment]
```
version_main cannot be converted to an integer
2023-12-31 06:30:55 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2023-12-31 06:30:55 INFO     Response in 60.703 s
2023-12-31 06:30:55 INFO     172.17.0.1 POST http://localhost:8191/v1 500 Internal Server Error

```  

how to slove it ?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/993#issuecomment-1839685517
